### ISSUE TITLE
not master and slaveOk=false

### ISSUE THREAD

**Issue by elbuo8** [Automattic/mongoose#3928] opened 2016-03-01 20:56 UTC
I've been getting the following error every so often in my logs:

```js
Error: { [MongoError: not master and slaveOk=false]
  name: 'MongoError',
  message: 'not master and slaveOk=false',
  ok: 0,
  errmsg: 'not master and slaveOk=false',
  code: 13435 }
```

Based on this, the driver is trying to connect to a `replSet`(?). My connection should be going towards `mongos` actually. Here is my connection setup:

```js
var opts = { 
  db: { 
    native_parser: true 
  }, 
  mongos: { 
    socketOptions: { 
      keepAlive: 120, 
      connectTimeoutMS: 30000, 
      sslCA: fs.readFileSync('./cert.pem');
    } 
  } 
}; 

mongoose.connect(MONGO_URI, opts); 
```

My `MONGO_URI` composes of two `mongos`. Any suggestions on what I might be doing incorrectly?

**Comment by vkarpov15** [comment] 2016-03-03 18:50
@elbuo8 what version of mongoose are you using? And what's the general form of your connection string? Please X out your actual urls / credentials.

**Comment by elbuo8** [comment] 2016-03-03 20:29
@vkarpov15 

Version: `4.2.7`

Connection string: `mongodb://<username>:<password>@host:port,host2:port/dbname?ssl=true`

**Comment by vkarpov15** [comment] 2016-03-12 20:26
Are those your actual connection options? Looks like there's a syntax error.

Also, is there a replica set election going on when these errors occur? The most likely explanation is that one server in your replica set went down and there's an election going on.

**Comment by elbuo8** [comment] 2016-03-23 16:29
What is the syntax error? :confused: 

I'm connecting to a `mongos` instance, should it even know that there is an election going on?

**Comment by vkarpov15** [comment] 2016-03-26 17:18
Missing } in your options. And mongos is just a router - if the underlying replica set doesn't have a primary, all long is can do is just report the error back to you

**Comment by elbuo8** [comment] 2016-03-27 19:34
Ah yeah, must have messed it up when I was cleaning the sensible stuff before posting it. Modified the original post to reflect it.

**Comment by vkarpov15** [comment] 2016-04-02 20:10
I'm gonna close this issue - looks like this is expected behavior. If you want to be able to execute reads when there's an election going on, set your read preference to "primaryPreferred"

```javascript
var opts = { 
  db: { 
    native_parser: true,
    readPreference: 'primaryPreferred'
  }, 
  mongos: { 
    socketOptions: { 
      keepAlive: 120, 
      connectTimeoutMS: 30000, 
      sslCA: fs.readFileSync('./cert.pem');
    } 
  } 
}; 
```

Write operations (update, insert, save, etc.) will still fail though.

**Closed by vkarpov15** 2016-04-02 20:10 UTC
Labels: needs clarification

**Comment by manashreea** [comment] 2018-09-04 06:14
Unable to connect Atlas mongodb using in NodeJs API, MongoDB Version "3.0.1"  
Error as {"name":"MongoError","message":"not master and slaveOk=false","operationTime":"6597247092970749953","ok":0,"errmsg":"not master and slaveOk=false","code":13435,"codeName":"NotMasterNoSlaveOk"

any recommendation ..

**Comment by vkarpov15** [comment] 2018-09-08 14:01
@manashreea what does your connection string look like? Please omit any credentials, I just want to see what your connection code looks like.

This erroressage usually pops up when one of 2 things happens:

1) You're connecting to a secondary member of a replica set as a standalone connection
2) You're connected to a replica set and the majority of the replica set is down

**Comment by mete89** [comment] 2020-03-24 09:15
Hi @vkarpov15 ,

I just noticed two consecutive errors on the logs similar to this one. 

1- ```"NotMaster",
  "$clusterTime": 
{
    "clusterTime": "6807419853016662017",
    "signature": {
        "hash": "vAsddfEddysNY1YMIVGDo/wBGD43Y=",
        "keyId": "3452338724555953026"
    }
}
,
  "name": "MongoError"
}```

2- ```{
  "operationTime": "6807419844426727425",
  "ok": 0,
  "errmsg": "not master",
  "code": 10107,
  "codeName": "NotMaster",
  "$clusterTime": {
    "clusterTime": "6807419853016662017",
    "signature": {
      "hash": "vAsddfEddysNY1YMIVGDo/wBGD43Y=",
      "keyId": "3452338724555953026"
    }
  },
  "name": "MongoError"
}```

I saw replica selection activity on atlas after 10 minutes later I have seen the logs above. 

Mongodb version: 4.2.3
`mongoose.connect(mongoUri, {useFindAndModify: false, useCreateIndex: true, keepAlive: 1, useNewUrlParser: true, useUnifiedTopology: true, poolSize: 30});`

`MONGO_URI=mongodb+srv://username:password@cluster0-xxxxx.mongodb.net/dbname?retryWrites=true&w=majority
`

**Comment by vkarpov15** [comment] 2020-03-27 22:29
This error can happen during a replica set election - if the replica set hasn't decided on a primary and you're trying to write to the replica set, you may see this error pop up @mete89 .

**Comment by mete89** [comment] 2020-04-06 19:40
Hi @vkarpov15,

I'm trying to reproduce the issue using atlas failover test which brings primary node down. If I use native driver, it works fine without throwing error. But in mongoose sometimes it stucks in a state where READYSTATE is 0. Sharing a simple script which reads and writes periodically. What do you suggest? 

```
const mongoose = require('mongoose');
const mongoUri = 'mongodb+srv://username:password@hostname/failover?retryWrites=true&w=majority&readPreference=primaryPreferred';
const Test = require('./test');
mongoose.connect(mongoUri, {keepAlive: 1, useNewUrlParser: true,
    useUnifiedTopology: true, poolSize: 5});
mongoose.connection.on('error', (err) => {
    console.error('Mongoose connection error: ' + JSON.stringify(err));
});
mongoose.connection.on('reconnected', () => {
    console.log('Mongoose default connection reconnected: ' + new Date());
});
mongoose.connection.on('reconnectFailed', () => {
    console.log('Mongoose default connection reconnect failed: ' + new Date());
});
mongoose.connection.on('disconnected', function () {
    console.log('Mongoose default connection disconnected: ' + new Date());
});
mongoose.connection.on('connected', function () {
    console.log('Mongoose default connection connected: ' + new Date());
});
async function finder() {
    try  {
        // console.log('READYSTATE', mongoose.connection.readyState);
        await Test.find({});
    } catch(err) {
        console.error('error inside finder: ' + JSON.stringify(err));
    }
}
(async () => {
    try {
        await Test.deleteMany({});
        console.log('numbers are removed');
        setInterval(finder, 200);
        const numbers = Array.from(Array(10000).keys());
        for(const number of numbers) {
            console.log(number);
            const test = new Test({num: number});
            await test.save();
        }
    } catch (err) {
        console.error('error inside main: ' + JSON.stringify(err));
    }
})();
```

test.js
```
const mongoose = require('mongoose');
const testSchema = new mongoose.Schema({
    num: Number
},{
    typeKey: '$type', timestamps: {createdAt: 'created_at', updatedAt: 'updated_at'}
});
module.exports = mongoose.model('test', testSchema);
```

Here is the last part of the logs: 
```
1801
1802
1803
Mongoose default connection disconnected: Mon Apr 06 2020 20:55:09 GMT+0300 (GMT+03:00)
error inside main: {"message":"not master","name":"MongooseServerSelectionError","reason":{"type":"ReplicaSetNoPrimary","setName":"Cluster0-shard-0","maxSetVersion":2,"maxElectionId":"7fffffff0000000000000033","servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":30,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":8}}
error inside finder: {"message":"not master","name":"MongooseServerSelectionError","reason":{"type":"ReplicaSetNoPrimary","setName":"Cluster0-shard-0","maxSetVersion":2,"maxElectionId":"7fffffff0000000000000033","servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":30,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":8}}
error inside finder: {"message":"not master","name":"MongooseServerSelectionError","reason":{"type":"ReplicaSetNoPrimary","setName":"Cluster0-shard-0","maxSetVersion":2,"maxElectionId":"7fffffff0000000000000033","servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":30,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":8}}
```

It keeps giving errors.
