### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by techinfo6789** [Automattic/mongoose#12572] opened 2022-10-20 01:52 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

All Versions

### Node.js version

16.14.2

### MongoDB server version

All Versions

### Description

<img width="1021" alt="Screenshot 2022-10-20 at 7 17 28 AM" src="https://user-images.githubusercontent.com/25953806/196837057-671ad533-6b64-4c58-abc0-efb611bf7b3f.png">

### Steps to Reproduce

I'm Using Mongoose in Next Js project 
Just install Mongoose and import 
Here are my dependencies list

"dependencies": {
    "@headlessui/react": "^1.7.3",
    "autoprefixer": "^10.1.0",
    "axios": "^1.1.3",
    "bcryptjs": "^2.4.3",
    "js-cookie": "^3.0.1",
    "mongoose": "^6.6.5",
    "next": "12.1.5",
    "next-auth": "^4.3.4",
    "postcss": "^8.2.2",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-hook-form": "^7.36.0",
    "react-icons": "^4.1.0",
    "react-responsive-carousel": "^3.2.23",
    "react-slick": "^0.29.0",
    "react-toastify": "^6.2.0",
    "slick-carousel": "^1.8.1",
    "tailwindcss": "^2.0.2",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@types/react": "^18.0.8"
  }

### Expected Behavior

I expect it to work properly that's it

**Comment by vkarpov15** [comment] 2022-10-24 23:54
Try upgrading to Mongoose 6.6.7 or higher. I believe this is a duplicate of #12576

**Closed by vkarpov15** 2022-10-24 23:54 UTC
Labels: needs repro script
