### ISSUE TITLE
DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.

### ISSUE THREAD

**Issue by MrPeker** [Automattic/mongoose#6882] opened 2018-08-17 19:16 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
(node:35956) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**
Node v9.11.2
MongoDB: v3.6.1
Mongoose: v5.2.7

**Comment by lineus** [comment] 2018-08-17 19:44
thanks for opening this @MrPeker 👍 . I'm closing it because it's a duplicate of #6880

**Closed** 2018-08-17 19:44 UTC
Labels: duplicate
