### ISSUE TITLE
Add Model name to DocumentNotFoundError

### ISSUE THREAD

**Issue by prasad47** [Automattic/mongoose#6215] opened 2018-03-07 18:34 UTC
Hi ,
i have been updated mongoose node package to version :- 5.0.0

.save method is creating issues which should save the object to db ..

Issue related Code :- 

function _save(obj,callback){

    var result;
    obj.save(function(err) {
        if (err) {
            callback(err);
        } else {
            result=obj;
            callback();
        }
    });
}

Error Facing :- 

{ Error 
  at MongooseError (/app/node_modules/mongoose/lib/error/index.js:12:11) 
  at model.Model.save (/app/node_modules/mongoose/lib/model.js:322:25) 
  at _save (/app/app/controllers/orders.server.controller.js:84:9) 
  at /app/app/controllers/orders.server.controller.js:173:13 
  at /app/app/models/sequence.server.model.js:32:13 
  at model.Query.<anonymous> (/app/node_modules/mongoose/lib/model.js:3907:16) 
   at /app/node_modules/kareem/index.js:297:21 
  at /app/node_modules/kareem/index.js:135:16 
  at _combinedTickCallback (internal/process/next_tick.js:73:7) 
 at process._tickCallback (internal/process/next_tick.js:104:9) 
 message: 'No matching document found for id "5aa029057c3bbe0013f8d0d6"', 
 name: 'VersionError' }

Note :-  i can able to fetch the document from DB with Id  "xxxxxxxxxxxxxxxxxxxxxxx"

Can you guys suggest something to successful save . My Project depoyments and functionalities are halted due to this functionality distrubence 

    "node": "7.10.1",
    "npm": "3.10.1"
    "mongoose": "5.0.0"

Hope some one gives me helping advice .. Thanks

Thanks,
Prasad.
 

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by lineus** [comment] 2018-03-07 21:14
please share your schema and other relevant code. it will help us come to a solution faster. If you can't share your code for whatever reason, please create a complete but minimal example that will help us replicate what you are seeing. 

### here is an example that is both minimal and complete:
```
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/test')

const Schema = mongoose.Schema

const testSchema = new Schema({
  name: String
})

const Test = mongoose.model('test', testSchema)

const test = new Test({ name: 'George' })

test.save(function (err, doc) {
  if (err) { return console.error(err) }
  return console.log(doc)
})
```
### here is it's output:
```
$ ./example.js 
{ name: 'George', _id: 5aa0558c6fb6d2163e5f0037, __v: 0 }
^C
$ 
```

@prasad47 Also, when you have time, go to [mongoose on gitter](https://gitter.im/Automattic/mongoose) or [mongoose on slack](https://mongoosejsteam.slack.com). Folks are online there and happy to help.

**Comment by prasad47** [comment] 2018-03-08 18:14
My Code :- 
Schema Declaration :- 
```
var mongoose = require('mongoose');
var schema = new mongoose.Schema();
```
```

exports.xyzSchema= new Schema({ ... },{ versionKey: false });
mongoose.model('xyz', exports.xyzSchema); 

```
Saving the Dynamic Object (obj)
 ```
var order = new xyz(_.extend({obj:obj});
  
    order .save(function(err) {
        if (err) {
            callback(err);
        } else {
            result=order;
       }
```
 Error With Versioning False  :- 
```

{ DocumentNotFoundError: No document found for query "{ _id: 5aa178baa53c440013ada1dc }"
    at new DocumentNotFoundError (C:\F-A Workspace\marketplace-api\node_modules\mongoose\lib\error\notFound.js:31:11)
    at $__handleSave (C:\F-A Workspace\marketplace-api\node_modules\mongoose\lib\model.js:266:15)
    at C:\F-A Workspace\marketplace-api\node_modules\mongoose\lib\model.js:206:9
    at args.push (C:\F-A Workspace\marketplace-api\node_modules\mongoose\node_modules\mongodb\lib\utils.js:404:72)
    at handleCallback (C:\F-A Workspace\marketplace-api\node_modules\mongoose\node_modules\mongodb\lib\utils.js:128:55)
    at C:\F-A Workspace\marketplace-api\node_modules\mongoose\node_modules\mongodb\lib\collection.js:1028:5
    at C:\F-A Workspace\marketplace-api\node_modules\mongodb-core\lib\connection\pool.js:541:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'No document found for query "{ _id: 5aa178baa53c440013ada1dc }"',
  name: 'DocumentNotFoundError',
  query: { _id: 5aa178baa53c440013ada1dc } }
```

With Versioning True :- 
```

{ Error
at MongooseError (/app/node_modules/mongoose/lib/error/index.js:12:11)
at model.Model.save (/app/node_modules/mongoose/lib/model.js:322:25)
at _save (/app/app/controllers/orders.server.controller.js:84:9)
at /app/app/controllers/orders.server.controller.js:173:13
at /app/app/models/sequence.server.model.js:32:13
at model.Query. (/app/node_modules/mongoose/lib/model.js:3907:16)
at /app/node_modules/kareem/index.js:297:21
at /app/node_modules/kareem/index.js:135:16
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)
message: 'No matching document found for id "5aa029057c3bbe0013f8d0d6"',
name: 'VersionError' }
```
********* FYI These schemas are created with mongoose with version 3.8.8 ** Actually the errors getting started when we Upgraded to 5.0.0 .. Please suggest the problem ..  Thing is same code version Upgrade

**Comment by prasad47** [comment] 2018-03-09 07:57
FYI 
 Error when updated to New Version  5.0.9

```
{ Error 
  at MongooseError (/app/node_modules/mongoose/lib/error/index.js:12:11) 
  at model.Model.save (/app/node_modules/mongoose/lib/model.js:330:25) 
  at _saveCreatedOrder (/app/app/controllers/orders.server.controller.js:84:9) 
  at /app/app/controllers/orders.server.controller.js:185:13 
  at /app/app/models/sequence.server.model.js:37:13 
   at /app/node_modules/mongoose/lib/model.js:3930:16 
   at _init (/app/node_modules/mongoose/lib/query.js:2007:5) 
   at model.Document.init (/app/node_modules/mongoose/lib/document.js:370:5) 
   at completeOne (/app/node_modules/mongoose/lib/query.js:1993:12) 
   at cb (/app/node_modules/mongoose/lib/query.js:2365:14) 
   at /app/node_modules/mongoose/lib/query.js:2465:14 
   at /app/node_modules/mongoose/lib/utils.js:418:16 
   at result (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:413:17) 
   at executeCallback (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:405:9) 
   at handleCallback (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55) 
   at /app/node_modules/mongoose/node_modules/mongodb/lib/collection.js:2302:12 
   at result (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:413:17) 
   at executeCallback (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:405:9) 
   at handleCallback (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55) 
   at /app/node_modules/mongoose/node_modules/mongodb/lib/db.js:340:5 
   at /app/node_modules/mongodb-core/lib/connection/pool.js:541:18 
   at _combinedTickCallback (internal/process/next_tick.js:73:7) 
   at process._tickCallback (internal/process/next_tick.js:104:9) 
 message: 'No matching document found for id "5aa178baa53c440013ada1dc"', 
 name: 'VersionError' } 
```

**Comment by prasad47** [comment] 2018-03-09 10:37
Here i am updating the schema to give more clarity 

```
exports.myCartSchema = new Schema({
	schemaName:{type: String,default: 'MyCart',required: 'Schema Name cannot be blank'},	
	displayName : String,
  	payment:{
		method:String, 
		status:String, //paid or due
	},	
	customer:{
		userId:String,
		firstName:String,
		lastName:String,
		email:String,
		phone:Number
 	},
	analytics:{
		ipAddress:String,
		userAgent:String,
		referer:String,
		cookieId:String
	},
  	referralServer:{
		name:''
	},

	system: {
		createdBy: {type: Schema.ObjectId},
	 	dateCreated:{type: Date,default: Date.now},
		dateUpdated:{type: Date, default: Date.now},
		isEnabled:{type: Boolean,default:true},
		isDeleted:{type: Boolean,default:false},
		_id:false,
		id:false
	},

	 

});
var myCart=mongoose.model('myCart', exports.myCartSchema );
```

**Comment by lineus** [comment] 2018-03-09 14:24
## Summary:
@prasad47 was using mongoose@3.8.8. He upgraded to mongoose@5.0.* and gets the error: 'No matching document found for id "5aa253cf91cff8001387748b"',
name: 'VersionError' } now when he tries to save. 

## Details discussed in chat:
   1. prasad mentioned that he is accessing a mongodb server with version 3.4.6 (and that this hasn't changed. Only mongoose was updated)
      - this doesn't seem possible based on the requirements of the native driver, in order to connect to 3.4.6 he would need a higher version of mongoose/mongdb or a version of mongodb server lower than 3.x. I tried to connect to a couple of *even older* versions of mongodb server (3.4.4 and 3.0.2) from mongoose@3.8.8 and the native driver throws a server version error as expected [compatibility chart here](http://mongoosejs.com/docs/compatibility.html). 

## Where I'm at now:
it seems to me like there are a few possibilities:
   1. **the previously installed version of mongoose was higher than @3.8.8**
      - If so, then something in prasad's code that worked with this unknown previous version of mongoose is not compatible with 5.x
   1. **the previously installed version of mongoose was @3.8.8 and no server upgrade took place**
      - Then this is probably an issue. This would mean that despite the current version of the native driver ( from mongoose@5.0.9 ) being incompatible with the current server version, it is still connecting when it should be throwing an Error.
   1. **the previously installed version of mongoose was @3.8.8 and a server upgrade took place**
      - same as 1 


@prasad47, can you add a comment here with the output from db.version() in the mongo shell on the mongodb Server that you are connecting to?

**Comment by prasad47** [comment] 2018-03-09 15:45
sure
![titled](https://user-images.githubusercontent.com/6585745/37215761-e539514e-23de-11e8-8a41-0f09658b4aa6.jpg)

**Comment by prasad47** [comment] 2018-03-09 15:46
My app connects to the above console with mongo url .. plz take a loook

**Comment by lineus** [comment] 2018-03-10 11:48
I spent some more time chatting on this with @prasad47 yesterday. There is a mistake in the above example in the call to save. the lodash extend call is different from his actual code.

@prasad47 can you please update this with an example that matches your real code as closely as possible, or create a standalone example that mirrors the code you wish to remain private minus any details that are sensitive. Feel free to use my example above or one of the gists I shared yesterday and derive as complete a working example as possible.

**Comment by prasad47** [comment] 2018-03-10 17:26
Hi Guys

>  Actually there is only small Change from above code bits apart from that i can assure everything is Consistent and it has been Stable in production from 2 years FYI but the version upgrade is the thing which is creating Chaos .. here i am re-posting .. but please don't consider naming conventions stuff because they are properly Maintained .. in the project in model,controller pattern 

**Server.js File** 
 
```
var mongoose = require('mongoose');
 
var db = mongoose.connect(url, options , function(err) {
	if (err) {
		console.error(chalk.red('Could not connect to MongoDB!'));
		console.log(chalk.red(err));
	}
});
```
 
 **model.js  // Start** 
 
```
 var Schema = mongoose.Schema,
exports.CartSchema = new Schema({
	schemaName:{type: String,default: 'MyCart',required: 'Schema Name cannot be blank'},	
	displayName : String,
  	payment:{
		method:String, 
		status:String, //paid or due
	},	
	customer:{
		userId:String,
		firstName:String,
		lastName:String,
		email:String,
		phone:Number
 	},
	analytics:{
		ipAddress:String,
		userAgent:String,
		referer:String,
		cookieId:String
	},
  	referralServer:{
		name:''
	},

	system: {
		createdBy: {type: Schema.ObjectId},
	 	dateCreated:{type: Date,default: Date.now},
		dateUpdated:{type: Date, default: Date.now},
		isEnabled:{type: Boolean,default:true},
		isDeleted:{type: Boolean,default:false},
		_id:false,
		id:false
	},
});
var Cart=mongoose.model('Cart', exports.CartSchema );
``` 
**// End of Model.js** 

**controller.js  //Start** 

```
var dynamicCart= {
  "displayName": "Desktop Cart",
  "payment": {
    "method": "Cash",
    "status": "Paid"
  },
  "referralServer": {
    "name": "none"
  },
  "analytics": {
    "referer": "self",
    "userAgent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
  },
  "customer": {
    "userId": "58d5d5dssd4d55d4d5d5d45d5",
    "email": "nvprasad@gmail.com",
    "firstName": "Prasad",
    "lastName": "NV",
    "phone": 99999999999
  },
  "system": {
    "isDeleted": false,
    "isEnabled": true,
    "dateUpdated": "2017-03-07T17:54:02.294Z",
    "dateCreated": "2017-03-07T17:54:02.294Z"
  }
}

var cart= new Cart(_.extend(dynamicCart);
 
   cart.save(function(err) {
       if (err) {
           callback(err);
       } else {
           result=cart;
       callback(result);
      }
```
 **controller.js  //End 

When End Point (route) called the following error happening  
 Please refer Above Errors**  

Thanks,
Prasad

**Comment by varunjayaraman** [comment] 2018-03-11 23:22
what is `_saveCreatedOrder` doing? can we see that code

**Comment by prasad47** [comment] 2018-03-12 07:20
@varunjayaraman   I think you will get more clarity When i just deleted the other Errors which are kind of creating more chaos.

Actually _saveCreatedOrder  is nothing but  a reusable global function which performs save every time ..
_saveCreatedOrder  // what ever the method name it is 
 Code follows : - 
```
function _saveCreatedOrder(obj,callback){ // obj == cart 
    var result;
    obj.save(function(err) {
        if (err) {
            callback(err);
        } else {
            result=obj;
            callback();
        }
    });
}
```
The Filtered Error from the above scenarios is **.save** method from **Mongoose npm** is creating Problem ..  

```
{ Error
at MongooseError (/app/node_modules/mongoose/lib/error/index.js:12:11)
at model.Model.save (/app/node_modules/mongoose/lib/model.js:322:25)
at _save (/app/app/controllers/orders.server.controller.js:84:9)
at /app/app/controllers/orders.server.controller.js:173:13
at /app/app/models/sequence.server.model.js:32:13
at model.Query. (/app/node_modules/mongoose/lib/model.js:3907:16)
at /app/node_modules/kareem/index.js:297:21
at /app/node_modules/kareem/index.js:135:16
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)
message: 'No matching document found for id "5aa029057c3bbe0013f8d0d6"',
name: 'VersionError' }
```


I repeat you guys .. The Problem is **.save** method from **Mongoose npm** is creating Problem ..  If

**Comment by lineus** [comment] 2018-03-12 16:20
I have provided @prasad47 with the following test code to try and isolate the issue to mongoose, mongodb native, and the server. I have redacted the sensitive userID from the code here.
```
'use strict'

const uri = 'mongodb://localhost/test'
const collectionName = 'testing123'
const mongoose = require('mongoose')
const Schema = mongoose.Schema

const cartSchema = new Schema({
  schemaName: { type: String, default: 'MyCart', required: 'Schema Name cannot be blank' },
  displayName: String,
  payment: {
    method: String,
    status: String
  },
  customer: {
    userId: String,
    firstName: String,
    lastName: String,
    email: String,
    phone: Number
  },
  analytics: {
    ipAddress: String,
    userAgent: String,
    referer: String,
    cookieId: String
  },
  referralServer: {
    name: ''
  },

  system: {
    createdBy: { type: Schema.ObjectId },
    dateCreated: { type: Date, default: Date.now },
    dateUpdated: { type: Date, default: Date.now },
    isEnabled: { type: Boolean, default: true },
    isDeleted: { type: Boolean, default: false },
    _id: false,
    id: false
  }
})

const Test = mongoose.model(collectionName, cartSchema)

mongoose.connect(uri)
mongoose.connection.on('open', () => {
  Test.findOne({ _id: XXXX }, (err, doc) => {
    if (err) {
      return console.error(err)
    }
    if (!doc) {
      return console.error('no doc found')
    }
    console.log(doc)
    doc.save((err, saved) => {
      if (err) {
        return console.error(err)
      }
      if (!saved) {
        return console.error('not saved')
      }
      mongoose.connection.close()
      return console.log(saved)
    })
  })
})
```

**Comment by lineus** [comment] 2018-03-13 20:39
@prasad47 has verified that the above example works but his actual codebase is still failing. We're working to sort it out over IM, but since it isn't an issue with mongoose we can close this. If we come up with reproducible issue, we can open a new one.

**Comment by lineus** [comment] 2018-03-15 10:59
@prasad47 are you connecting to replicaSet?

**Comment by prasad47** [comment] 2018-03-15 11:10
No I am not to replica set

**Comment by prasad47** [comment] 2018-03-15 11:29
FYI ,

```
var Tank = mongoose.model('Tank', yourSchema);


var small = new Tank({ size: 'small' });
small.save(function (err) {
if (err) return handleError(err);
// saved!
})
```
This is what the code i used and to save docs  it is raising the issue .
you know this is the syntax you guys suggested in documentation .

**Comment by lineus** [comment] 2018-03-15 12:32
@prasad47, During our conversation on gitter you tried the test script I provided above and reported that it worked without error. The error messages in your last comment are clearly coming from your app and not an isolated test case like the one I provided or the one in the documentation. **The syntax from the documentation is correct.**

I'm going to step back and allow someone with more experience to take over. I'm always available to answer questions regarding this issue or help in any reasonable way.

# Current State of this issue
   1. the testcase I provided [above](https://github.com/Automattic/mongoose/issues/6215#issuecomment-372369765) works in their environment
   1. their codebase's save call fails with a "no document found" err when calling save
   1. their codebase is private. According to prasad access is only available over skype.

**Comment by vkarpov15** [comment] 2018-03-21 17:23
Thanks @lineus for the debugging you've done thus far. @prasad47 can you email me at val@karpov.io so we can set up a time to debug over skype?

**Comment by prasad47** [comment] 2018-03-26 15:18
I mailed you@ vkarpov15   @ val@karpov.io a day ago .. pls take a look thanks !!

**Comment by prasad47** [comment] 2018-03-27 11:54
Hi vkarpov15  could you confirm your availability  .. i work in IST timings i am avaialbe from 9 to 9 IST .. Please confirm your availability . i can adjust my time as per your availability

**Comment by prasad47** [comment] 2018-03-31 13:43
Hi Guys,

My Issue has been troubleshooted by Mr.Valeri karpov . Valeri Described it as Strange Issue when i screen shared  my problem in detail . He suggested me a simple fix.. 

While i am trying to create new Object mongoose is not recognizing the object as New  .. it is supposing the object as already exists which is Really Strange . So Valeri suggested a Fix 
OBJ.isNew = true before executing the .save method .. which is worked like a Charm .. 
That is really helped me a Lot Mr. Valri !! 
Thanks for trying to Help Mr.Lineus . Hope this Answer May help ........+1 it when The solution worked ..  

Thanks,
Prasad.

**Comment by neeraj24** [comment] 2018-04-26 19:19
Thanks. Got the same issue and the fix suggested worked for me. Is this fix going to be included in the newer version?

**Comment by lineus** [comment] 2018-04-26 20:14
@neeraj24 if you can create a reproducible example that shows the error please open a new issue and include it there. Thanks!

**Comment by adamreisnz** [comment] 2019-05-27 08:10
I am also occasionally seeing `No document found for query "{ _id: xxxxxx }"` errors in our error reporting. Is there some documentation somewhere as to the cause of this error? This issue doesn't provide much details other than a hack for how to solve it in a particular case.

However, for us this happens very infrequently, and probably not always for the same query, so I'd like to know more about why this error happens in the first place.

**Comment by vkarpov15** [comment] 2019-05-29 15:49
@adamreisnz this error happens when you `save()` a document that was deleted from the db. Here's an example:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh6215`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const schema = new Schema({ name: String });
  const Model = mongoose.model('Test', schema);

  const doc = await Model.create({ name: 'foo' });

  await Model.deleteMany({});

  doc.name = 'bar';
  await doc.save();
}
```

Would it be helpful if we added the original stack trace of the `save()` call and the name of the model to the error message? That might help you at least figure out what `save()` is causing this error.

**Closed** 2019-06-06 17:56 UTC
Labels: developer-experience

**Comment by adamreisnz** [comment] 2019-06-06 22:35
@vkarpov15 did you figure out what was happening?

**Comment by vkarpov15** [comment] 2019-06-08 17:41
@adamreisnz I didn't figure out why this was happening for your application. Additional logging may help, we'll continue our discussion in #7844

**Comment by meSmashsta** [comment] 2021-08-08 15:11
This typically happens when you insert a JSON without using proper data type (at least in my experience), here's an example of a problematic JSON:
```JSON
{
 "_id": "610feed7f9c11a4c1f957853",
 "date": "2021-08-08T14:48:55.467Z"
}
```
when it should be:
```JSON
{
 "_id": { "$oid": "610feed7f9c11a4c1f957853" },
 "date": { "$date": "2021-08-08T14:48:55.467Z" }
}
```
Maybe someone manually inserted a raw JSON in your database?
