### ISSUE TITLE
mongoose function create and insertMany auto convert array to object

### ISSUE THREAD

**Issue by ngankt2** [Automattic/mongoose#7727] opened 2019-04-22 10:27 UTC
DataFakeTest.create({
        'tags':["tech","php","sql"]
});

data after insert

`/* 13 */
{
    "_id" : ObjectId("5cbd96e102c912558673dc26"),
    "tags" : {
        "0" : "tech",
        "1" : "php",
        "2" : "sql"
    },
    "__v" : 0
}`

Please help me
my data is array object (not object)

**Comment by vkarpov15** [comment] 2019-04-23 00:21
@ngankt2 what does your schema look like?

**Comment by ngankt2** [comment] 2019-04-23 01:22
@ValYouW  My code
`
```javascript
import mongoose from 'mongoose';

/**
 *
 */
const DataFakeTestSchema = new mongoose.Schema({}, {strict: false}
);
DataFakeTestSchema.options.strict = false;
DataFakeTestSchema.options.toJSON = {
    transform: function (doc, ret) {
        ret.id = ret._id;
        delete ret._id;
        delete ret.__v;
        return ret;
    },
};

const DataFakeTest = mongoose.model('data_fake_test', DataFakeTestSchema, 'data_fake_test');
export default DataFakeTest
````

**Comment by ngankt2** [comment] 2019-04-23 06:24
@ValYouW 
Can you help me!
Please

**Comment by snakierten96** [comment] 2019-04-23 13:20
This appears to reproduce from version 5.5.1 and onwards. Earlier versions do not show the same behavior

**Comment by vkarpov15** [comment] 2019-05-07 13:31
This is a duplicate of #7733, please upgrade to 5.5.6 for the fix :+1:

**Closed by vkarpov15** 2019-05-07 13:31 UTC
Labels: has repro script

**Comment by jomgapuz** [comment] 2021-09-02 01:42
Can we reopen this? The bug is apparent on `"^6.0.4"`.

**Comment by vkarpov15** [comment] 2021-09-02 22:04
@jomgapuz no. Please open a new issue and follow the issue template, including detailed code samples. Also, please stop spamming.
