### ISSUE TITLE
(node:15576) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.

### ISSUE THREAD

**Issue by talaikis** [Automattic/mongoose#10007] opened 2021-03-09 17:45 UTC
**Do you want to request a *feature* or report a *bug*?**

Warning that pollutes logs.

**What is the current behavior?**

getting warning: `(node:15576) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.`

On mongoose >= 5.11.15

**What is the expected behavior?**

No warning.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
> 5.11.15

Downgrading to 5.11.15 solves the problem.

**Comment by vkarpov15** [comment] 2021-03-11 23:13
Please provide a code sample that demonstrates your issue.

**Comment by talaikis** [comment] 2021-03-12 08:31
> Please provide a code sample that demonstrates your issue.

```js
const mongoose = require('mongoose')

const createConnection = promisify(async (done) => {
  if (mongoose.connection.readyState === 1) {
    done()
  } else {
    const uri = `mongodb+srv://<uri>`

    mongoose.connect(uri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
      useCreateIndex: false,
      autoIndex: false,
      keepAlive: true,
      useFindAndModify: false,
      bufferCommands: false,
      user: <user>,
      pass: <pass>,
      dbName: s[3],
      family: 4,
      bufferMaxEntries: 0,
      connectTimeoutMS: 60000,
      socketTimeoutMS: 60000
    })

    mongoose.connection.once('open', () => {
      done()
    })
  }
})

(async () => {
  await createConnection()
})
```

It runs on Lambda.

**Comment by IslandRhythms** [comment] 2021-03-22 19:38
```
const mongoose = require('mongoose')
const util = require('util');

const createConnection = util.promisify(async (done) => {
  if (mongoose.connection.readyState === 1) {
    done()
  } else {
    const uri = `mongodb://localhost:27017/test`

    mongoose.connect(uri, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    mongoose.connection.once('open', () => {
      done();
    })
  }
});

(async () => {
  await createConnection()
})
```
doesn't pop up

**Comment by tukusejssirs** [comment] 2021-04-08 12:19
Possible duplicate of #9930.

**Closed** 2021-04-15 18:42 UTC
Labels: can't reproduce
