### ISSUE TITLE
Post Save Hooks Get Flow Control - how to replicate the old functionality?

### ISSUE THREAD

**Issue by domharrington** [Automattic/mongoose#12929] opened 2023-01-20 11:29 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

5.x.x and 6.x.x

### Node.js version

14.19.3

### MongoDB server version

4.2.12

### Description

We recently upgraded to mongoose v5.x.x and I just discovered this breaking change in the changelog to do with post save hooks getting flow control: https://github.com/Automattic/mongoose/blob/9d7bf10606e567990969aabe130f16b896e2d29b/docs/migrating_to_5.md#post-save-flow-control

We use post('save') hooks extensively for operations that we want to run _after_ the document has been saved to the database; operations that we do not want to wait for before responding to the request. Some examples include: sending a welcome email and syncing data to a 3rd party service.

Now from mongoose 5.x and onward, these operations happen _before_ the document is saved, and therefore our requests are taking longer to return to the user. 

### Steps to Reproduce

Consider the following code:

```js
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017');

function sleep(n) { return new Promise(resolve=>setTimeout(resolve,n)); }

const Schema = new mongoose.Schema({ text: String });
Schema.post('save', async () => {
  await sleep(2000);
  console.log('Post save callback');
});

const Model = mongoose.model('Model', Schema);
const m = new Model({ text: 'lorem ipsum' });
m.save(function() {
  console.log('Save callback');
});
```

In mongoose v4.x, this would print the following:
```
Save callback
Post save callback
```

But in mongoose v5.x and v6.x, it prints the following and waits for the async post('save') hook to complete:
```
Post save callback
Save callback
```

### Expected Behavior

Is there any way to get the old behaviour back? Of the hooks running after the call to document.save() has been returned to the caller? Have I missed something obvious here? It seems like there's no longer any difference between the pre() and post() hooks if they're both running before the save is happening?

Thanks so much in advance. I hope this is clear!

**Comment by IslandRhythms** [comment] 2023-01-23 16:04
I believe this is what you're looking for https://mongoosejs.com/docs/middleware.html#post

**Comment by domharrington** [comment] 2023-01-23 16:47
So is it only executed _after_ save if it is an async function, or it returns a Promise?

**Comment by domharrington** [comment] 2023-01-25 11:41
How is what we're doing any different? Why does the post('save') function get called now _after_ the save callback is called. 

We do stuff like this:

```js
const m = new Model({ text: 'lorem ipsum' });
m.save(function() {
  res.json(m);
});
```

When we want to return something from an API, but now the post save is called before that happens, and if it does anything async, then it blocks our return to the API. Do we have to refactor to this now?

```js
const m = new Model({ text: 'lorem ipsum' });
await m.save();
res.json(m);
```

Would you mind sharing the commits where this change happened, so I can dig into understanding the change a little more?

**Comment by IslandRhythms** [comment] 2023-01-25 15:54
The post save hook is not being called after the `save` callback but rather before. Here's an example using your syntax
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

testSchema.post('save', () => {
  console.log('post save hook')
});

const Test = mongoose.model('Test', testSchema);


async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  const doc = new Test({ name: 'Test Testerson' });
  doc.save(function() {
    console.log('save callback');
  })
}

run();
```

1. the save function executes
2. the post hook executes
3. the callback executes.

**Comment by domharrington** [comment] 2023-01-25 18:37
To use your example from earlier, but with an async operation happening in the post('save') hook:

```js
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

function sleep(n) { return new Promise(resolve=>setTimeout(resolve,n)); }

testSchema.post('save', async () => {
  await sleep(5000)
  console.log('post save hook')
});

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = new Test({ name: 'Test Testerson' });
  await doc.save();
  console.log('doc saved');
}

run();
```

It does not output "doc saved" until the post save hook has completed. So the .save() operation is blocked waiting until the post save has completed. Sorry to keep going back and forth on this, but this seems like a massive change and completely breaks my understanding of what I thought mongoose was doing here. I know it was done in a major release, so it's completely permissible of course. None of this is documented particularly well either (https://mongoosejs.com/docs/middleware.html#post). 

This seems like the only way to get the old functionality back:

```js
testSchema.post('save', () => {
  process.nextTick(async () => {
    await sleep(5000)
    console.log('post save hook')
  });
});
```

**Comment by IslandRhythms** [comment] 2023-01-25 18:55
Can you clarify what you mean by `.save() operation`? The document is updated in mongodb before the post hook runs. So the script you've modified is behaving as expected because `doc.save()`, not the actual updating of the document in the db, needs to complete before it can print the console log.

**Comment by domharrington** [comment] 2023-01-25 19:02
Say if I had an express route that created something in the database and returned it to the user:

```js
app.post('/users', async () => {
  const doc = new Test({ name: 'Test Testerson' });
  await doc.save();
  console.log('doc saved');
  res.json(doc);
})
```

If I want to do something async in the post('save'), like sending a welcome email, or tracking something in an external system. How would I do that without that blocking me from responding as soon as possible to the HTTP request? This is how it used to work, but now an async post save blocks the caller from returning until they're all complete.

**Comment by IslandRhythms** [comment] 2023-01-25 19:05
Ah, the hooks allow the passing of the document that was saved. So you can just fire that inside the post hook.
https://mongoosejs.com/docs/middleware.html#post

**Comment by IslandRhythms** [comment] 2023-01-25 19:14
Your proposed solution would be the way to do it.

**Comment by domharrington** [comment] 2023-01-25 19:17
With the process.nextTick()? That seems like such a massive change from 4.x and I can't wrap my head around why it has been done like this. Do you have any context on that decision or some PRs I can read through? It's so surprising to me that no one else is seemingly coming up against this issue. It was always obvious in my mind... need something async and blocking, use a pre('save'), need something to happen completely _after_ the save, use a post('save').

**Comment by IslandRhythms** [comment] 2023-01-25 19:19
I do not have the context, but I'll assign the person that does.

**Comment by domharrington** [comment] 2023-01-25 19:20
Thanks again! Really appreciate it. It's probably time for us to move towards a non-blocking/queue system for these types of things anyway, was just a bit of a shock to realize the shift.

**Comment by vkarpov15** [comment] 2023-02-06 21:16
@domharrington yes, `process.nextTick()` is the way to go for making a `post('save')` hook that doesn't block resolving the `save()` promise.

```javascript
testSchema.post('save', async () => {
  process.nextTick(async () => {
    try {
      await sleep(5000)
      console.log('post save hook')
    } catch (err) { /* do something with error */
  })
})
```

There are several reasons why we made this change in Mongoose 5:

1. Consistent error handling. You see in the above example that, if the post save hook throws an error, you need to handle that error separately. With our current approach, a `post('save')` hook throwing an error means `save()` rejects.
2. Allow post save hooks to modify the result. Not as important for `post('save')` hooks, but more important for `post('find')`, etc.
3. Easy to replicate the old behavior with `process.nextTick()` or `setImmediate()`. Harder to go the other way.

**Closed by vkarpov15** 2023-02-06 21:16 UTC
Labels: help

**Comment by domharrington** [comment] 2023-02-07 11:59
Hey! Thanks for the response. I can understand the rationale for consistent error handling, though the types of things we normally do in a post save are by definition things that are not crucial to succeed, and we have to be aware of things like retrying and error handling by posting those errors to external services. 

Regarding post('find') operations and modifying the results, I can see that. Though I'd probably just achieve that with a function like so: `Model.find({}).then(processResults)` rather than adding that complexity to mongoose. 

I agree it is easy to replicate the old behaviour, but was definitely a massive gotcha when I realized that this was occurring and it went against all of my old assumptions of what post('save') did - I'm surprised there aren't more people complaining about this. Maybe the docs could be updated to provide some more examples like the ones above, to explain the order of execution and order in which the promises resolve? Would you accept a PR for this?

Thanks again,
Dom

**Comment by vkarpov15** [comment] 2023-02-10 18:11
We'd accept a PR. Perhaps put this info in our [middleware docs](https://github.com/Automattic/mongoose/blob/master/docs/middleware.md) ?

**Comment by msavastio** [comment] 2023-11-02 12:36
I have a question on this as well @vkarpov15. I ran into the same unexpected behavior as @domharrington on this one, and this post was super helpful in explaining what was going on, so thank you all for that. However, what I am finding is `process.nextTick()` doesn't seem to really do anything for me, nor does using `setImmediate()`.

If I wrap my code in my post save middleware in either `setImmediate()` or `process.nextTick()`, my API request from the front end takes ~6 seconds to get a response.

If I comment out the wrapped code entirely, I get a response in ~2.3 seconds, so I know that particular middleware is what's delaying my front end responses.

What I find strange is that if I use a `setTimeout()` with a delay of >1.5 seconds, I get a front end response in about 2.5 seconds total, and I can see that my code continues to run on the back end after that point in time. This does more or less result in the desired behavior, but it feels crappy and implies to me that there could be some kind of timeout threshold that I need to exceed in order to result in this behavior. Note that this is entirely my speculation, and I am frequently accused of being a "classic overthinker".

I have also tried doing things like calling `next()` on the first line of my post schema, arrow vs. traditional functions, async vs sync, all sorts of fun stuff. I'm not sure if this has to do with my admittedly amateur understanding of the node event loop or what, but it would be great if someone a bit wiser could shed some light on this for me!

Thanks,
Matt

**Comment by msavastio** [comment] 2023-11-03 16:28
I actually did some more digging on this after posting that - the latency was actually caused by middleware being triggered off of that section of code. After a good refactor and updating via query instead of document, my total API call is now at a much more desirable <500ms.

Thanks for the response and sorry to waste your time!

**Comment by vkarpov15** [comment] 2023-11-03 18:05
No worries, I'm glad you figured out the issue :+1:
