### ISSUE TITLE
Support node v7

### ISSUE THREAD

**Issue by letranloc** [Automattic/mongoose#4675] opened 2016-11-03 03:40 UTC
I got error when trying to run on node v7 (v6.9.1 working normally)
```bash
[piping] error given was: TypeError: Cannot convert undefined or null to object
[2]     at Function.keys (<anonymous>)
[2]     at ValidationError.toString (/Users/letranloc/Working/message-me/node_modules/mongoose/lib/error/validation.js:49:10)
[2]     at Function.prepareStackTrace (/Users/letranloc/Working/message-me/node_modules/source-map-support/source-map-support.js:365:16)
[2]     at Function.captureStackTrace (<anonymous>)
[2]     at new MongooseError (/Users/letranloc/Working/message-me/node_modules/mongoose/lib/error.js:12:11)
[2]     at ValidationError (/Users/letranloc/Working/message-me/node_modules/mongoose/lib/error/validation.js:17:19)
[2]     at model.Document.invalidate (/Users/letranloc/Working/message-me/node_modules/mongoose/lib/document.js:1458:32)
[2]     at /Users/letranloc/Working/message-me/node_modules/mongoose/lib/document.js:1334:17
[2]     at validate (/Users/letranloc/Working/message-me/node_modules/mongoose/lib/schematype.js:705:7)
[2]     at /Users/letranloc/Working/message-me/node_modules/mongoose/lib/schematype.js:742:9
[2]     at Array.forEach (native)
[2]     at SchemaString.SchemaType.doValidate (/Users/letranloc/Working/message-me/node_modules/mongoose/lib/schematype.js:710:19)
[2]     at /Users/letranloc/Working/message-me/node_modules/mongoose/lib/document.js:1332:9
[2]     at _combinedTickCallback (internal/process/next_tick.js:67:7)
[2]     at process._tickCallback (internal/process/next_tick.js:98:9)
```

I found this error occurred when validate this path
```js
const userSchema = new Schema({
...
password: {
    type: String, set: v => {
      if (isEmpty(v) || v.length < 8) {
        return v;
      }
      return generateHash(v);
    }, minlength: 8
  },
});
```

**Comment by ehog90** [comment] 2016-11-06 18:09
I have similar issues, but with PM2 only.

**Comment by karthikiyengar** [comment] 2016-11-11 21:42
Can reproduce this myself.

**Comment by paton** [comment] 2016-11-13 03:21
Node 7 is beta and unstable, so it's possible this is a Node bug rather than a mongoose bug.

I'm not sure what mongoose's policy is on version support, but I wouldn't expect them to support non-LTS (even-numbered) versions of Node.

https://github.com/nodejs/LTS#lts-schedule

**Comment by derEremit** [comment] 2016-11-15 23:27
@paton 
I never once read anywhere that non-lts versions of node should be considered beta or even unstable.
I also does not mention anything about that in your provided link.
AFAIK most node modules already support v7
(like newrelic monitoring for weeks, which is really only useful for production usecases)

**Comment by paton** [comment] 2016-11-15 23:48
LTS version of node (even numbers) guarantee no semver-major changes. Odd-numbered versions are subject to semver-major API / breaking changes during the course of development toward Node 8 LTS.

But I'm sure @vkarpov15 would merge in a PR if someone here can pinpoint the cause and propose a fix.

Has anyone debugged this or pinpointed the issue?

**Comment by derEremit** [comment] 2016-11-16 00:08
@paton it's already been merged

**Comment by paton** [comment] 2016-11-16 00:34
Thanks @patrickd- for the fix 👍

**Comment by vkarpov15** [comment] 2016-11-17 14:35
Just fair warning, I would recommend you do **not** use newrelic, or at least use newrelic in dev, test, and prod, rather than just in prod. Newrelic does some really dirty monkey-patching of the mongodb driver, so you're actually running completely different mongodb connection logic in dev and in prod, and that's a recipe for disaster.

**Comment by varunjayaraman** [comment] 2017-01-07 22:35
Closing this since it was resolved through https://github.com/Automattic/mongoose/pull/4719

**Closed by varunjayaraman** 2017-01-07 22:35 UTC

**Comment by galenandrew** [comment] 2017-03-03 19:24
@vkarpov15 regarding your recommendation to **not** use newrelic, is this still an issue? Any additional insight/resources on what they are doing to the mongodb driver?

**Comment by paton** [comment] 2017-03-03 19:29
We use NewRelic + Mongoose on ~20 servers and haven't run into major issues (anecdotally, as far as I know). From what I understand, Newrelic monkey patches a lot of code (tries to re-write parts of the driver to record metrics). Automatically monkey patching anything always introduces possibility of unexpected / hard to identify errors. @vkarpov15 might have more insight.

**Comment by paton** [comment] 2017-03-03 19:31
+1 for @vkarpov15 suggestion for using NewRelic in dev (and not just prod) so at least your dev environment + test suite + staging is running on the "monkey patched" code as well.

**Comment by vkarpov15** [comment] 2017-03-10 21:41
I haven't used new relic in a few years, so maybe they've gotten better, take my recommendations with a grain of salt. I just don't find the risk of them making a monkeypatching mistake worth the infinitesimal value their product provides. If you're having an issue in prod only but not in local I'd try shutting off new relic and see what happens.
