### ISSUE TITLE
[Typescript] replaceOne returns type `any`

### ISSUE THREAD

**Issue by guy-wal** [Automattic/mongoose#12347] opened 2022-08-29 09:58 UTC
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

6.4.0

### Node.js version

16.13.1

### MongoDB version

4.4.11

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.5.1

### Issue

When using mongoose with typescript the return value of `await Model.replaceOne(...)` is `any` instead of a specific result type like `updateWriteOpResult`.

I can see the [replaceOne `QueryWithHelpers` is given `any`](https://github.com/Automattic/mongoose/blob/6cb1284821405c71a4d75e9857ef45d95c367972/types/models.d.ts#L405) instead of [`UpdateWriteOpResult` as done in `updateOne`](https://github.com/Automattic/mongoose/blob/6cb1284821405c71a4d75e9857ef45d95c367972/types/models.d.ts#L435).

<img width="369" alt="image" src="https://user-images.githubusercontent.com/95572228/187175987-9dbe41f2-56b0-4f1a-9937-e82435109f89.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/95572228/187176039-b43fbf4e-2453-4aac-b4f4-4e173d699a9c.png">

during runtime I can see the `replaceOne` result does have the expected fields:
<img width="670" alt="image" src="https://user-images.githubusercontent.com/95572228/187175418-2aea724d-aa9a-4e6a-86b8-a3324d1d025c.png">

for now I can just tell typescript what type it is: 
<img width="551" alt="image" src="https://user-images.githubusercontent.com/95572228/187193524-a7fdd0f8-24cb-4d65-a246-8fb66467d5ef.png">

not sure if this is the expected behavior. if not I can open a PR to fix it

**Comment by IslandRhythms** [comment] 2022-08-29 14:46
possible duplicate of #12342

**Comment by hasezoey** [comment] 2022-08-29 15:10
> possible duplicate of #12342

i dont think it is a duplicate, because the mentioned issue is about documentation being outdated and this issue is about a type not being set correctly (in the types, not in the documentation)

**Comment by florianwalther-private** [comment] 2022-08-29 15:18
I don't know if it's the same problem, but the reference (my) issue is not about the documentation, it's about the `any` return type.

**Closed** 2022-08-30 15:29 UTC
Labels: typescript
