### ISSUE TITLE
Post-save hooks on subdocs are firing before the document has finished saving.

### ISSUE THREAD

**Issue by jrthib** [Automattic/mongoose#5101] opened 2017-03-22 23:33 UTC
I'm reporting a bug with mongoose document hooks. I have tested with Mongoose 4.8.1 and 4.9.1, NodeJS 4.7.0, and MongoDB 3.4.

Currently it appears that the post-save hooks on sub documents are firing before the actual document is finished saving to the database. However, the parent document's post-save hooks fire after the document is saved, as expected.

**Steps to reproduce**

To fully reproduce my console output, you will need to add `console.log('driver-save-callback')` to line 157 of `mongoose/lib/models.js` where the insert at the driver occurs.

````javascript
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Set internal promise object to be the native Promise object
mongoose.Promise = global.Promise;

// Bootstrap db connection
mongoose.connect('mongodb://localhost:27017/testing', {
    server: {
        auto_reconnect: true,
        socketOptions: {
            keepAlive: 1
        },
    }
});

const conn = mongoose.connection;

// When the connection is disconnected
conn.on('disconnected', function() {
    console.log('Mongoose default connection disconnected');
});

new Promise((resolve, reject) => {
    // When successfully connected
    conn.on('connected', function() {
        console.log('Mongoose default connection open');
        resolve(conn);
    });

    // If the connection throws an error
    conn.on('error', function(err) {
        console.log('Mongoose default connection error: ', err);
        reject(err);
    });
}).then(function(conn) {
    const subDocSchema = new Schema({
        name: { type: String },
    });

    subDocSchema.post('save', function() {
        console.log('subdoc-post-save');
    });

    const parentSchema = new Schema({
        name: { type: String },
        sub: [subDocSchema]
    });

    parentSchema.post('save', function() {
        console.log('parent-post-save');
    });

    const Parent = conn.model('Parent', parentSchema);

    let test = new Parent({
        name: 'parent',
        sub: [{
            name: 'subdoc',
        }]
    });

    test.save().then(function() {
        console.log('mongoose-save-callback');
    });

});
````

ACTUAL OUTPUT:
````
subdoc-post-save
driver-save-callback
parent-post-save
mongoose-save-callback
````

EXPECTED OUTPUT:
````
driver-save-callback
subdoc-post-save
parent-post-save
mongoose-save-callback
````

**Comment by jrthib** [comment] 2017-03-22 23:37
Seems like https://github.com/Automattic/mongoose/issues/5085 is the same issue I reported here.

**Comment by jrthib** [comment] 2017-03-23 15:17
I also just tested on 4.8.0, since #5085 said it was a bug introduced in 4.8.1. 4.8.0 has the same issue.

**Comment by varunjayaraman** [comment] 2017-03-24 03:10
@jrthib yeah this is a duplicate of #5085. I'm gonna close this and track the issue there if that's cool with you

**Closed by varunjayaraman** 2017-03-24 03:10 UTC
