### ISSUE TITLE
findOne not doing anything (v4.7.3)

### ISSUE THREAD

**Issue by joetidee** [Automattic/mongoose#4857] opened 2017-01-02 18:24 UTC
I am using the following within a static model method, but neither the err or doc is printing to the console. any ideas why? (the _id is set as a String in the schema.)

```
this.findOne({_id: templateId},function(err, doc){
        console.log("err:",err);
        console.log("doc:",doc);
    });
```

**Comment by apeguero24** [comment] 2017-01-04 00:31
Happens with findById too, it says CastError: Cast to ObjectId failed for value...

I had to go back to a older version 4.6.8

**Comment by joetidee** [comment] 2017-01-04 02:35
I discoverd that the templateId, despite having a type of 'string', needed to be wrapped in JSON.parse()

**Comment by apeguero24** [comment] 2017-01-04 02:37
Is that part of the update? Because it seems more like a bug to me.

**Comment by apeguero24** [comment] 2017-01-04 02:39
For me it wouldn't accept a string as the ID and if used mongoose.SchemaType.ObjectId() it would give me a null document back in the callback.

**Comment by joetidee** [comment] 2017-01-04 15:10
What are you wanting Mongoose to do, 1) generate the _id for you upon inserting a document, 2) supply your own _id when inserting a document?

**Comment by apeguero24** [comment] 2017-01-04 15:45
retrieve a document based on a given _id. It would cast an ObjectId error in the latest version, however since downgrading it works fine. I was wondering is bug.

**Comment by joetidee** [comment] 2017-01-04 22:52
But how are you creaitng the _id when inserting the documents using Mongoose?

**Comment by iambrian7** [comment] 2017-01-05 23:27
Ya, reinstalled 4.7.2 and everything works again!

**Comment by apeguero24** [comment] 2017-01-06 00:02
So it's back to normal? Because that was really frustrating. Added several hours to my project of work.

**Comment by varunjayaraman** [comment] 2017-01-06 04:45
It seems like @joetidee 's problem isn't related to the js-bson error from https://github.com/Automattic/mongoose/issues/4867https://github.com/Automattic/mongoose/issues/4867 but is related to more to his _id as a string. In any  case, I'm going to close this since it's a duplicate of https://github.com/Automattic/mongoose/issues/4859

Feel free to discuss there.

**Closed** 2017-01-06 04:46 UTC

**Comment by apeguero24** [comment] 2017-01-06 04:49
Honestly, I would use the older version until this is clarified further. It worked for me.
