### ISSUE TITLE
Throw error if doing `import { model } from mongoose;` or `const { model } = require('mongoose')`

### ISSUE THREAD

**Issue by Elergy** [Automattic/mongoose#3768] opened 2016-01-16 14:04 UTC
It's common when user wants to import variables from module without saving module into a variable, e.g.

```
let {Schema} = require('mongoose');
```

or 

```
var Schema = require('mongoose').Schema;
```

but when I do this with model 

```
var model = require('mongoose').model;
```

and try to create a model with imported function, I have an error

```
TypeError: Cannot read property 'modelSchemas' of undefined
```

Yes, model is a property of Mongoose.prototype, but Schema also is.
If documentation contains an instruction like 

```
var Schema = mongoose.Schema,
...
```

it's possible to assume that 'model' will have similar behavior

**Comment by vkarpov15** [comment] 2016-01-16 19:53
Supporting this behavior would involve a massive refactor of mongoose connections. Long story short, `require('mongoose').model();` is different than `var model = require('mongoose').model; model();` because the value of `this` in the former function call is the `require('mongoose');` singleton, whereas it is the global object in the latter call. If you want a workaround, `model.call(require('mongoose'), 'MyModelName', schema);` should work fine. I'm not a huge fan of the fact that mongoose's top level functions are laden with side effects, but to get rid of that we'd also have to get rid of the `mongoose.model()` getter syntax, which would break a lot of people's code.

**Comment by Elergy** [comment] 2016-01-16 21:19
@vkarpov15 thanks for your answer!

There are 2 different cases:
1. We know it's a bug, but fixing it takes a time for refactoring. Then we should keep the issue open
2. We assert it is not a bug. Then we should close the issue

When we have the issue open, it can be fixed with breaking change (in new major release) or without breaking change (you know, everything can be refactored with backward compatibility, it just depends on effort). Someone (e.g. me) probably has time for it. 

But when we mark the issue closed, we give contributors to know that pull requests with fixing this bug will be rejected, and someone doesn't even start to fix it. 

What do you think about it?

**Comment by vkarpov15** [comment] 2016-01-18 14:17
Fair point, I'll keep this issue open. The workaround is easy, just ensure the functions have proper context. The eventual solution is no side-effects.

**Comment by SummerWish** [comment] 2016-02-02 02:10
+1

Currently this doesn't work:
```js
import { model } from 'mongoose'
```

**Comment by vkarpov15** [comment] 2016-02-02 21:01
Not expected to work in the immediate future because of side-effects in mongoose. No really good way to make `mongoose.model()` work as a getter/setter if you're using `import { model }` unless you use global state, which I'm loathe to do. Why don't you just use `import 'mongoose';` ? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by jacob-israel-turner** [comment] 2016-03-04 01:38
I'll +1 this.

```
import { model } from 'mongoose'
```
^ is a handy/attractive syntax.

**Comment by jacob-israel-turner** [comment] 2016-03-04 01:56
I created #3943 as a quick fix for this.  If it's acceptable (until a better solution can be created), then I can write a test to go with the PR.  If it needs revised at all, I'm more than willing to.

**Comment by vkarpov15** [comment] 2016-03-06 00:45
I like the general idea, but tests fail in that pr, which is a deal breaker unfortunately

**Comment by jacob-israel-turner** [comment] 2016-03-06 19:41
Yup, I did see that. I'll be playing with it tomorrow to see what's going
on.

**Comment by chrisbruford** [comment] 2017-07-19 18:52
Came across this today after trying `const { model } = require('mongoose');`

needless to say it didn't work so back to `let foo = mongoose.model('foo',fooSchema);`

Be nice if someone has time for a fix but I can see why it's not high priority!

**Comment by cr05s19xx** [comment] 2018-10-09 09:30
So, to try and clarify, running

**Comment by cr05s19xx** [comment] 2018-10-09 09:32
So, to try and clarify, running
```javascript
import { model } from 'mongoose';
//...
model('testModel', testModelSchema);
```
...exposes the `model` object to the global namespace, whereas
```javascript
import mongoose from 'mongoose';
//...
mongoose.model('testModel', testModelSchema);
```
places the model in the scope of the already connected mongoose singleton object. Can some confirm this for me please.
Thanks

**Comment by vkarpov15** [comment] 2018-10-13 21:32
@cr05s19xx that is generally correct. In the former, `this` is the global namespace, but in the latter `this` in `model()` refers to the mongoose singleton

**Comment by silverlight513** [comment] 2018-11-17 10:18
If this error only occurs when we have this problem, it would be beneficial to print out the cause and fix so people don't end up having to google and coming to this issue like I did.

**Closed** 2018-11-21 16:11 UTC
Labels: developer-experience

**Comment by vkarpov15** [comment] 2018-11-21 16:14
In 5.3.14, you'll be able to do `import {model} from 'mongoose'` and it will work properly. That is just for this one function though, we still need more work to support that for the rest of the [Mongoose global API](https://mongoosejs.com/docs/api.html#mongoose_Mongoose). We'll still warn against doing this and keep the [section in the FAQ](https://mongoosejs.com/docs/faq.html#destructured-imports), but the model case is so frequent that we can fix it as a one-off.
