### ISSUE TITLE
4.2 breaks pluralization

### ISSUE THREAD

**Issue by jthomerson** [Automattic/mongoose#3490] opened 2015-10-22 18:01 UTC
When 4.2 was released a couple hours ago, it broke anyone who relied on NPM's "^4.y.z" syntax for installing "compatible" versions because pluralization rules changed.

Previously, a model named "category" would have been pluralized **categories**, but in 4.2.0 is pluralized **categorys**.

This indicates that #3415 was actually not a non-breaking version of #3398

**Comment by ElliotCampbell** [comment] 2015-10-22 18:10
:+1:

**Comment by nemo** [comment] 2015-10-22 18:10
:+1: 

All our servers got very mad today because of this. We've downgraded until we fix this issue.

**Comment by Jokero** [comment] 2015-10-22 18:39
Why do you not use strict versions in `package.json`? This is a more safely

**Comment by nemo** [comment] 2015-10-22 18:41
That's what we did now, suprised we didn't have it before.

But anyway, we'd love to upgrade – but the issue still stands.

**Comment by jthomerson** [comment] 2015-10-22 18:42
@Jokero you're correct, that's safer, but it doesn't invalidate that 4.2.0 should be a compatible change as specified by semver and discussed by @ChristianMurphy and @vkarpov15 in the referenced issues.

**Comment by ChristianMurphy** [comment] 2015-10-22 19:01
Investigating this now

**Comment by brozeph** [comment] 2015-10-22 19:12
:+1: 

Seeing already pluralized collections being pluralized a second time (for example, stations is now stationss)

**Comment by vkarpov15** [comment] 2015-10-22 19:56
Merged @ChristianMurphy's fixes and released 4.2.1, sorry for the snafu. 4.2.0 was not meant to be backwards breaking, but sometimes mistakes happen. Feel free to report any other issues you might find.

**Comment by jthomerson** [comment] 2015-10-22 20:46
@vkarpov15 and @ChristianMurphy Thanks for the quick fix!

That said, I have concerns about the "fix" @ChristianMurphy did on this issue. Looking at [the commit](https://github.com/ChristianMurphy/pluralize-mongoose/commit/e5ac0c54f63a7bff7b2d38db3cce5f80eb4327fd) done in `pluralize-mongoose` to fix the issue shows several warning signs:

 1. it removed all of the code that was actually forked from `pluralize` in the first place
 2. with that, it removed all tests in the `pluralize-mongoose` repo
 3. it looks hasty and sloppy since it also adds `npm-debug.log`, which usually indicates someone just did `git commit -a` rather than reviewing what they were committing

This is not meant to be a dig against @ChristianMurphy ... the idea he had in #3398 to remove custom code and use an established library is a good idea. I just worry that the implementation of that idea was not done in a professional manner on the first attempt nor on this quick cleanup attempt.

**In the first attempt:**

A fork was made of `blakeembrey/pluralize` into the custom `ChristianMurphy/pluralize-mongoose` repo, adding a custom commit on top of `blakeembrey/pluralize`. But that commit drastically changed the functionality of the upstream repo, making me wonder if the fork is really worthwhile. Additionally, it broke the many tests that the upstream repo had, not replacing them with any new tests.

Then on the `mongoose` side, #3415 was implemented in a sloppy (I know, "sloppy" is a subjective term, but I'll stick with it here) manner: it incorporated the original two commits from #3398 (which was known to be a breaking change), and then overrides them by adding a third commit that override the functionality added by the first two.

Also, despite you saying in #3398 the following, no tests were actually added.

>  Should be ok to merge this if we can ensure that all the pluralization rules stay the same. Can we add some tests to make sure that all the old pluralization rules still work? Right now the tests (utils.test.js) don't really cover the end results.

**In the hurried fix today**

Some of the issues from today's hurried fix were mentioned at the outset. But the real problem is that this entire exercise, ending with today's "fix" has simply made the mongoose codebase messier than it needs to be. It has literally taken the code that used to exist in `lib/utils.js` and moved it into a separate repo owned by someone else. That separate repo is now a fork of an upstream repo that actually has no code left from the upstream, being entirely replaced by the code that was removed from Mongoose.

The proper fix for today's issue (IMHO) would have been to simply revert the mongoose commits that made it use pluralize (or the mongoose-pluralize fork) in the first place.

**My suggestion**

Based on all of the observations above, I make the following suggestion: revert to using the `lib/utils.js` pluralization code, completely reverting the effects of d7d677c0, 4cdaf757, ae075771, and bfacc094.

If, in a future ***major*** update (5.0), you want to accept the change of pluralization rules, then make the changes originally proposed by @ChristianMurphy in #3398 to make mongoose use `blakeembrey/pluralize`. But don't use a fork of that repo, and especially not a fork that is just a copy of the rules that were removed from mongoose in the first place - which invalidates the reason any of this work was even proposed.

The reality is that many important projects now rely on mongoose. That's a great hat-tip to you @vkarpov15, but it also comes with the responsibility of really vetting contributions and upstream libraries, which doesn't look like it was done here.

Thanks for considering.

**Comment by jedireza** [comment] 2015-10-22 21:12
This broke a site I help manage. In my case I had the model `ProductCategory` which used to be pluralized into `producecategories` and with 4.2 it gets pluralized into `productcategorys`. This should have been a major version bump.

This is a critical change. If not already, tests should be added to prevent a regression like this in the future.

**Comment by ChristianMurphy** [comment] 2015-10-22 21:21
@jthomerson 

> But don't use a fork of that repo, and especially not a fork that is just a copy of the rules that were removed from mongoose in the first place - which invalidates the reason any of this work was even proposed.

This the replacement of `utils.js` pluralize with `pluralize-mongoose` is meant as a transition before moving over to `pluralize` proper. See [comments in 3398](https://github.com/Automattic/mongoose/pull/3398#issuecomment-142714110).

**Comment by r-tanner-f** [comment] 2015-10-22 21:29
+1 Also seeing extra `s`'s in our queries.

**Comment by vkarpov15** [comment] 2015-10-22 22:10
Admittedly I didn't do as well as I should have in terms of vetting the pluralization changes. I apologize for the issue, we'll make sure to be more careful with the pluralization code in the future. 4.2.2 uses the old pluralization code.

@ChristianMurphy thanks for your work in trying to get this improvement in, but we're gonna have to hold off on further pluralization changes until 5.0 because they're just too risky.

**Closed by vkarpov15** 2015-10-22 22:10 UTC
