### ISSUE TITLE
Mongoose Error with mongoose-i18n-localize

### ISSUE THREAD

**Issue by Youmna30** [Automattic/mongoose#8297] opened 2019-11-03 11:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
i have been working with mongoose and mongoose-i18n-localize modules after the last release from mongoose i got this error.

i removed mongoose from node_modules and add one from old version it works but i want to know why this error happened.

this error also happened when i user mongoose localize in my project otherwise it works

![problem](https://user-images.githubusercontent.com/24256815/68084214-630f8d80-fe3b-11e9-8c7a-59f8ea656e32.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To run without error 

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js 10.14.1
Mongoose 5.7.1

**Comment by vkarpov15** [comment] 2019-11-06 17:18
This looks like a duplicate of #8292 . We fix will be in 5.7.9 :+1:

**Closed by vkarpov15** 2019-11-06 17:18 UTC
