### ISSUE TITLE
Schema validate failed for number enum with Object.values()

### ISSUE THREAD

**Issue by BsLeeha** [Automattic/mongoose#13750] opened 2023-08-18 09:12 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.11.5

### Node.js version

18.13.0

### MongoDB server version

4.16.0

### Typescript version (if applicable)

4.9.5

### Description

schema:
```ts
enum Status {
    ON = 1,
    OFF = 2
}
const authorSchema = new mongoose.Schema({
    name: String,
    age: Number,
    status: {
        type: Number,
        enum: Object.values(Status)   // here
    }
});
const Author = mongoose.model('author', authorSchema);
```
insert value:
```ts
await Author.insertMany([{
    name: 'test',
    age: 1,
    status: Status.ON
}]);
```
error stack:
```
~/node_modules/mongoose/lib/document.js:3174
    this.$__.validationError = new ValidationError(this);
                               ^
ValidationError: author validation failed: status: OFF
    at model.Document.invalidate (~/node_modules/mongoose/lib/document.js:3174:32)
    at ~/node_modules/mongoose/lib/document.js:2962:17
    at ~/node_modules/mongoose/lib/schematype.js:1349:9
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errors: {
    status: ValidatorError: OFF
        at validate (~/node_modules/mongoose/lib/schematype.js:1346:13)
        at SchemaNumber.SchemaType.doValidate (~/node_modules/mongoose/lib/schematype.js:1330:7)
        at ~/node_modules/mongoose/lib/document.js:2954:18
        at processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'enum',
      path: 'status',
      value: 1,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'author validation failed'
}

```

### Steps to Reproduce

info: fail on mongoose >= v6.0.5, and
insert author fail:
```ts
const authorSchema = new mongoose.Schema({
    name: String,
    age: Number,
    status: {
        type: Number,
        enum: ['ON', 'OFF', 1, 2]
    }
});
```
insert author ok:
```ts
const authorSchema = new mongoose.Schema({
    name: String,
    age: Number,
    status: {
        type: Number,
        enum: [3, 'ON', 'OFF', 1, 2]
    }
});
```

### Expected Behavior

Insert data success with `enum: Object.values(Status)`

**Comment by DipeshAggarwal** [comment] 2023-08-18 10:03
I had `sanitiseFilter` set to True. Please close this as this is not a bug,

**Comment by IslandRhythms** [comment] 2023-08-29 18:47
```typescript
import * as mongoose from 'mongoose';

enum Status {
  ON = 1,
  Off = 2
}

const authorSchema = new mongoose.Schema({
  name: String,
  age: Number,
  status: {
      type: Number,
      enum: Object.values(Status)   // here
  }
});
const Author = mongoose.model('author', authorSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  await Author.insertMany([{
    name: 'test',
    age: 1,
    status: Status.ON
}]);
}

run();
```

**Comment by vkarpov15** [comment] 2023-09-04 15:57
Unfortunately this is expected behavior and not something we can support by default. You're setting `enum` on a number path to an array of values that contains non-numbers. But there is a workarounds: remove non-numeric values from your `enum`: `enum: Object.values(Status).filter(v => /^\d+$/.test(v))`

**Closed by vkarpov15** 2023-09-04 15:57 UTC
Labels: confirmed-bug
