### ISSUE TITLE
Cannot read property of undefined Mongoose@4.2.6

### ISSUE THREAD

**Issue by makenova** [Automattic/mongoose#3598] opened 2015-11-19 22:00 UTC
Running the following code errors out in mongoose@4.2.6 but in mongoose@4.2.5
there is no issue. Is this intentional and if so, is there another way I should
be doing this?

```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var petSchema = new Schema({
  name: String
});

var personSchema = new Schema({
  name: String,
  friends:[{
    type: Schema.Types.ObjectId,
    ref:'pets'
  }]
});

var petModel = mongoose.model('pets', petSchema);
var personModel = mongoose.model('people', personSchema);

var dudMuffin = new petModel({name:'dudMuffin'});
var generalMeow = new petModel({name:'generalMeow'});

var mike = new personModel({name:'mike', friends:[dudMuffin]});

mike.friends.push(generalMeow);
```

```sh
➜  testMongooseArray  node app.js
/Users/mnovaMBP/work/test/testMongooseArray/node_modules/mongoose/lib/types/array.js:105
      Model = populated.options.model;
                               ^

TypeError: Cannot read property 'model' of undefined
    at Array.MongooseArray.mixin._cast (/Users/mnovaMBP/work/test/testMongooseArray/node_modules/mongoose/lib/types/array.js:105:32)
    at Array.MongooseArray.mixin._mapCast (/Users/mnovaMBP/work/test/testMongooseArray/node_modules/mongoose/lib/types/array.js:295:17)
    at Object.map (native)
    at Array.MongooseArray.mixin.push (/Users/mnovaMBP/work/test/testMongooseArray/node_modules/mongoose/lib/types/array.js:308:25)
    at Object.<anonymous> (/Users/mnovaMBP/work/test/testMongooseArray/app.js:24:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by vkarpov15** [comment] 2015-11-20 15:29
Duplicate of #3579, fix will be out later today.

**Closed by vkarpov15** 2015-11-20 15:29 UTC
