### ISSUE TITLE
upsert make new field id only ObjectId

### ISSUE THREAD

**Issue by divinzer** [Automattic/mongoose#5899] opened 2017-12-12 17:43 UTC
'upsert' option make id value to only ObjectId not String
 { setDefaultsOnInsert: true } is not work too.

so  below is not work
new Schema({
  _id                   : { type: String }
});

Thank you.

**Comment by srsandy** [comment] 2017-12-12 21:29
Use this 
```
import mongoose from 'mongoose';

let Schema = mongoose.Schema({
    _id :  mongoose.Schema.Types.ObjectId
});
```

**Comment by JasonCust** [comment] 2017-12-14 14:12
Quoting from the referenced [contributing](https://github.com/Automattic/mongoose/blob/master/CONTRIBUTING.md) guidelines when creating a new issue:
> If you have a question about Mongoose (not a bug report) please post it to either [StackOverflow](http://stackoverflow.com/questions/tagged/mongoose), or on [Gitter](https://gitter.im/Automattic/mongoose?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

You are more likely to get a response much sooner on either of those while not adding to a backlog of bugs/features that the maintainers need to sift through here.

For future reference, you do not need to specify the `_id` field as Mongoose automatically adds that to every schema (including subdocument arrays) unless you turn off the [option](http://mongoosejs.com/docs/guide.html#_id) in the schema.

**Comment by vkarpov15** [comment] 2017-12-19 20:47
Duplicate of #4069 , will be fixed in 5.0.0. Not supported in 4.x because of backwards compatibility with mongodb 2.4.

**Closed by vkarpov15** 2017-12-19 20:47 UTC

**Comment by cobola** [comment] 2018-04-17 15:40
i use mongoose 5.0.15 
it still save objectID when use ```findOneAndUpdate```
```
let GroupSchema = new Schema({
  id: {
    type: String,
    trim: true,
    required: true,
    default: shortid.generate()
  },
...
```

**Comment by vkarpov15** [comment] 2018-04-23 17:10
@cobola please open a new issue and provide more detailed code samples and description of the issue you're experiencing
