### ISSUE TITLE
To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

### ISSUE THREAD

**Issue by felegure** [Automattic/mongoose#8369] opened 2019-11-21 19:26 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Comment by felegure** [comment] 2019-11-21 19:31
request a feature

Version of nodejs:  v12.13.0
mongoose:   "mongoose": "^5.7.12"

mongodb:  1.19.12
  }

**Comment by AbdelrahmanHafez** [comment] 2019-11-25 16:06
duplicate of #8362

**Closed** 2019-12-06 15:45 UTC
