### ISSUE TITLE
Embedded Documents in Embedded Arrays call hooks a weird # of times

### ISSUE THREAD

**Issue by wlingke** [Automattic/mongoose#5757] opened 2017-10-26 19:10 UTC
There’s a slightly weird issue where, for an embedded array, the spies are called an odd number of times. (related to #5706)

In the case where I try to push in one doc it calls each hook `1` time which is expected.
```
var doc = new TrackModel({
          events: [
            {
              message: 'Test',
              kind: 'Purchased'
            }
          ]
        });
```

However, when there are two, it calls each hook `4` times.
```
var doc = new TrackModel({
          events: [
            {
              message: 'Test',
              kind: 'Purchased'
            },
            {
              message: 'TestAgain',
              kind: 'Purchased'
            }
          ]
        });
```

When there’s 3 docs, each hook is called 6 times.

Test Script: `https://github.com/wlingke/mongoose`
`npm test -- -g "(gh-5706)"`

**Comment by vkarpov15** [comment] 2017-10-29 02:16
This is a duplicate of https://github.com/Automattic/mongoose/issues/4983. You need to do `purchasedSchema.clone()` when calling `discriminator()`.

**Closed** 2017-10-29 02:16 UTC
