### ISSUE TITLE
SCRAM-SHA-1 authentication failed on MongoDB Arbiter Setup

### ISSUE THREAD

**Issue by swathianni** [Automattic/mongoose#7241] opened 2018-11-13 16:37 UTC
Do you want to request a feature or report a bug?
Bug.

What is the current behavior?
We got lot´s of logs on a arbiter instance.
I ACCESS [conn5918755] SCRAM-SHA-1 authentication failed for xxx on xxx from client 10.0.0.126:32804 ; UserNotFound: Could not find user xxx@xxx

If the current behavior is a bug, please provide the steps to reproduce.

We have a replicaSet (MongoDB 3.4.16) with 3 members and 2 arbiter. An all arbiter we got a lot log message of failed connections errors (see message above).

The connections itself seems working correctly.

Our Connection looks like:

uri = "mongodb://xxxxxxxxxxx.com:27101,xxxxxxxxxxxx.com:27101,arbiternode.com:27101/admin?authSource=admin";

const dbPath = config.get('database.Connection.uri');
const dbOptions = config.get('database.Connection.options');
mongoose.connect(dbPath, dbOptions);
  db = mongoose.connection;

What is the expected behavior?
No logs on the arbiter.

Please mention your node.js, mongoose and MongoDB version.
nodeJS: 8.11.3
mongoose: 5.2.0 (tried 5.3.7 as well, seeing same issue)
MongoDB Driver: 3.4.16

Did anyone have any idea how to fix this problem?

**Comment by NewEraCracker** [comment] 2018-11-13 17:43
mongoose 5.2.0 LOL that is the must bugged version ever. Please try with the latest. Also why are you connecting to the arbiters in the first place? they are supposed to be management nodes and not hold data as far as I know.

**Comment by vkarpov15** [comment] 2018-11-16 23:45
Thanks for reporting, will investigate ASAP. Just to confirm, do you have auth enabled?

**Comment by swathianni** [comment] 2018-11-26 16:35
@vkarpov15  we are using mongodb 3.4 
 
I am authenticating as Admin. Below is my connection uri and options I am using.
uri = "mongodb://xxxxxxxxxxx.com:27101,xxxxxxxxxxxx.com:27101,arbiternode.com:27101/admin?authSource=admin",
     "options": {
        "dbName": "xxxxdb01",
        "replicaSet": "xxxx01",
        "autoIndex": false,
        "useNewUrlParser": true,
        "useCreateIndex": true,
        "native_parser": true,
        "poolSize": 20,
        "reconnectTries": 10,
        "reconnectInterval": 1000,
        "autoReconnect": true,
        "noDelay": true,
        "keepAlive": 120,
        "connectTimeoutMS": 0,
        "user": "USER_NAME",
        "pass": "PASSWORD"
      }

**Comment by vkarpov15** [comment] 2019-01-02 23:30
I'm unable to repro this locally:

Script to start repl set:

```javascript
'use strict';

const co = require('co');

co(function*() {
  var ReplSet = require('mongodb-topology-manager').ReplSet;

  // Create new instance
  var topology = new ReplSet('mongod', [{
    // mongod process options
    options: {
      bind_ip: 'localhost',
      port: 31000,
      dbpath: `/data/db/31000`,
      auth: null,
      keyFile: './key'
    }
  }, {
    // mongod process options
    options: {
      bind_ip: 'localhost',
      port: 31001,
      dbpath: `/data/db/31001`,
      auth: null,
      keyFile: './key'
    }
  }, {
    // Type of node
    arbiter: true,
    // mongod process options
    options: {
      bind_ip: 'localhost',
      port: 31002,
      dbpath: `/data/db/31002`,
      auth: null,
      keyFile: './key'
    }
  }], {
    replSet: 'rs'
  });

  yield topology.start();

  topology.managers[2].process.stdout.on('data', str => {
    console.log(str.toString('utf8'))
  })

  console.log('done');
}).catch(error => {
  console.error(error);
  process.exit(-1);
});
```

Script that connects to the replica set:

```
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7241`;
const connectionString = `mongodb://localhost:31000,localhost:31001,localhost:31002/${ GITHUB_ISSUE }?replicaSet=rs`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  while (true) {
    await new Promise(resolve => setTimeout(resolve, 5000));
    console.log('spinning');
  }
}
```

Output from the script that runs the replica set doesn't show any errors.

[MongoDB arbiters do **not** store any authentication data](https://docs.mongodb.com/manual/core/replica-set-arbiter/#security) so all logins against them fail. The [MongoDB node driver fixed a bug related to this in v2.2.23](https://github.com/mongodb/node-mongodb-native/blob/master/HISTORY.md#2223-2017-02-13), so I suspect you have another dependency (maybe connect-mongo, agenda, etc.) that's running an older version of the MongoDB driver. Can you run `npm list | grep "mongo"` and see if you have a version of the MongoDB driver that's `<= 2.2.22`?

**Comment by vishalgakhare** [comment] 2019-01-03 17:59
─┬ mongoose@5.2.0
│ ├── mongodb@3.1.0
│ ├─┬ mongodb-core@3.1.0
│ │ ├─┬ require_optional@1.0.1
│ │ │ ├── resolve-from@2.0.0
│ │ │ └── semver@5.5.0
│ │ └── saslprep@1.0.0
│ ├── mongoose-legacy-pluralize@1.0.2


**npm list | grep "mongo"**
├─┬ mongoose@5.2.0
│ ├── mongodb@3.1.0
│ ├─┬ mongodb-core@3.1.0
│ ├── mongoose-legacy-pluralize@1.0.2

**Comment by swathianni** [comment] 2019-01-03 18:11
npm list | grep "mongo"
├─┬ mongoose@5.3.7
│ ├─┬ mongodb@3.1.6
│ │ ├── mongodb-core@3.1.5 deduped
│ ├─┬ mongodb-core@3.1.5
│ ├── mongoose-legacy-pluralize@1.0.2

**Comment by vkarpov15** [comment] 2019-01-04 19:07
That's strange. In which case, I'm unable to repro this. Can you also double check that these connection failures are coming from your Mongoose app? Also, can you print out your [`rs.status()`](https://docs.mongodb.com/manual/reference/method/rs.status/) with hostnames and ports omitted?

**Comment by vishalgakhare** [comment] 2019-01-18 17:07
I am verifying this issue for original submitter. To give more context, there is dedicated relica set set up for our app and it is managed by different group. Here's the `rs.status()` from test region

```json
MongoDB Enterprise qrsiris01:PRIMARY> rs.status()
{
        "set" : "qrsiris01",
        "date" : ISODate("2019-01-18T16:23:31.660Z"),
        "myState" : 1,
        "term" : NumberLong(876),
        "syncingTo" : "",
        "syncSourceHost" : "",
        "syncSourceId" : -1,
        "heartbeatIntervalMillis" : NumberLong(2000),
        "optimes" : {
                "lastCommittedOpTime" : {
                        "ts" : Timestamp(1547828601, 7),
                        "t" : NumberLong(876)
                },
                "readConcernMajorityOpTime" : {
                        "ts" : Timestamp(1547828601, 7),
                        "t" : NumberLong(876)
                },
                "appliedOpTime" : {
                        "ts" : Timestamp(1547828601, 7),
                        "t" : NumberLong(876)
                },
                "durableOpTime" : {
                        "ts" : Timestamp(1547828601, 7),
                        "t" : NumberLong(876)
                }
        },
        "members" : [
                {
                        "_id" : 0,
                        "name" : "node01:27101",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 14553,
                        "optime" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDate" : ISODate("2019-01-18T16:23:21Z"),
                        "syncingTo" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "electionTime" : Timestamp(1547814079, 1),
                        "electionDate" : ISODate("2019-01-18T12:21:19Z"),
                        "configVersion" : 451860,
                        "self" : true,
                        "lastHeartbeatMessage" : ""
                },
                {
                        "_id" : 1,
                        "name" : "amdbqiris0102.kdc.capitalone.com:27101",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 14544,
                        "optime" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDate" : ISODate("2019-01-18T16:23:21Z"),
                        "optimeDurableDate" : ISODate("2019-01-18T16:23:21Z"),
                        "lastHeartbeat" : ISODate("2019-01-18T16:23:31.398Z"),
                        "lastHeartbeatRecv" : ISODate("2019-01-18T16:23:30.614Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "node05:27101",
                        "syncSourceHost" : "node05:27101",
                        "syncSourceId" : 6,
                        "infoMessage" : "",
                        "configVersion" : 451860
                },
                {
                        "_id" : 2,
                        "name" : "node03:25101",
                        "health" : 1,
                        "state" : 7,
                        "stateStr" : "ARBITER",
                        "uptime" : 14544,
                        "lastHeartbeat" : ISODate("2019-01-18T16:23:31.448Z"),
                        "lastHeartbeatRecv" : ISODate("2019-01-18T16:23:30.167Z"),
                        "pingMs" : NumberLong(0),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "configVersion" : 451860
                },
                {
                        "_id" : 3,
                        "name" : "node04:27101",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 14543,
                        "optime" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDate" : ISODate("2019-01-18T16:23:21Z"),
                        "optimeDurableDate" : ISODate("2019-01-18T16:23:21Z"),
                        "lastHeartbeat" : ISODate("2019-01-18T16:23:30.840Z"),
                        "lastHeartbeatRecv" : ISODate("2019-01-18T16:23:31.478Z"),
                        "pingMs" : NumberLong(81),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "node05:27101",
                        "syncSourceHost" : "node05:27101",
                        "syncSourceId" : 6,
                        "infoMessage" : "",
                        "configVersion" : 451860
                },
                {
                        "_id" : 5,
                        "name" : "node06:25101",
                        "health" : 1,
                        "state" : 7,
                        "stateStr" : "ARBITER",
                        "uptime" : 14543,
                        "lastHeartbeat" : ISODate("2019-01-18T16:23:31.481Z"),
                        "lastHeartbeatRecv" : ISODate("2019-01-18T16:23:30.360Z"),
                        "pingMs" : NumberLong(72),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "",
                        "syncSourceHost" : "",
                        "syncSourceId" : -1,
                        "infoMessage" : "",
                        "configVersion" : 451860
                },
                {
                        "_id" : 6,
                        "name" : "node05:27101",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 14543,
                        "optime" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDurable" : {
                                "ts" : Timestamp(1547828601, 7),
                                "t" : NumberLong(876)
                        },
                        "optimeDate" : ISODate("2019-01-18T16:23:21Z"),
                        "optimeDurableDate" : ISODate("2019-01-18T16:23:21Z"),
                        "lastHeartbeat" : ISODate("2019-01-18T16:23:30.192Z"),
                        "lastHeartbeatRecv" : ISODate("2019-01-18T16:23:30.819Z"),
                        "pingMs" : NumberLong(73),
                        "lastHeartbeatMessage" : "",
                        "syncingTo" : "node01:27101",
                        "syncSourceHost" : "node01:27101",
                        "syncSourceId" : 0,
                        "infoMessage" : "",
                        "configVersion" : 451860
                }
        ],
        "ok" : 1
}

```

**Comment by vkarpov15** [comment] 2019-01-23 21:08
@vishalgakhare what does your connection string look like? Please omit any sensitive details like passwords and hostnames. Also, can you post the error message you're seeing?

One more detail: is it intentional that one host in the replica set has a different hostname than the others?

**Comment by vishalgakhare** [comment] 2019-02-01 17:48
Update on tests done on AWS dev stack:
1. app using mongoose 5.3.7 - arbiter node gets auth failed error logs
2. app using mongodb 3.1.13 and no mongoose package - Arbiter has no err log

However, from local:
1. app using mongoose 5.3.7 - Arbiter has no err log
2. app using mongodb 3.1.13 and no mongoose package - Arbiter has no err log

strange!

**Comment by vkarpov15** [comment] 2019-02-05 22:55
@vishalgakhare do you have any other modules that connect to mongodb like connect-mongo, agenda, etc.?

**Comment by vishalgakhare** [comment] 2019-02-06 17:02
@vkarpov15 I did grep on possible npm packages that may connect to mongodb..

```sh
$ npm ls | grep mon
├─┬ mongodb@3.1.13
│ ├─┬ mongodb-core@3.1.11
├─┬ nodemon@1.18.9
│ ├─┬ @sinonjs/commons@1.3.0
│ │ │   ├── @sinonjs/commons@1.3.0 deduped

npm ls | grep con
├─┬ config@1.31.0
│ │ │ └─┬ color-convert@1.9.3
│ ├─┬ concat-stream@1.6.2
│ │ │ ├── iconv-lite@0.4.19 deduped
│ │   └── concat-map@0.0.1
│ │ │   │ ├─┬ iconv-lite@0.4.24
│ │ │   │ │     └── concat-map@0.0.1
│ │ │   │ ├── console-control-strings@1.1.0
│ │ │   │ │ ├── console-control-strings@1.1.0 deduped
│   ├─┬ configstore@3.1.2
│ │ └── precond@0.2.3
│ │ ├── content-type@1.0.4
│ │ ├── iconv-lite@0.4.19
│ │ │ ├── iconv-lite@0.4.19 deduped
│ │ ├── concat-stream@1.6.2 deduped
│ ├─┬ swagger-converter@0.1.7
```
and also glanced through the npm ls. I didn't find any other npm package.
Since, all tests are inconclusive to identify the root cause, we have put a workaround script that cleans the arbiter log daily. 
The issue can be closed as we haven't made any promising progress.

**Closed** 2019-02-08 15:40 UTC
Labels: can't reproduce
