### ISSUE TITLE
Setters don't run on findOneAndUpdate

### ISSUE THREAD

**Issue by buunguyen** [Automattic/mongoose#2946] opened 2015-04-30 18:47 UTC
I'm not sure if this is intended or a bug, but schema setters don't seem to run in atomic find-and-modify operations. If it's intended, it's quite a big limitation because I use these almost exclusively throughout the app to perform updates.  Is there a page that documents behaviors of find-and-modify when coming to validation, setters etc.

Mongoose version: 4.0.1.

**Comment by vkarpov15** [comment] 2015-05-01 16:16
That's by design right now, but definitely a feature worth considering for the future

**Comment by buunguyen** [comment] 2015-05-01 16:26
@vkarpov15 thanks for your response. I've been using Mongoose for a number of projects and I've found myself use atomic operations more and more, to almost exclusively in the current project. Without these, I will have to manually execute setters and validations although they are already declared in the schema, which is kind of defeating the purpose of using Mongoose in the first place. On top of that, with all the new hooks available, I would say it's counter-intuitive that setters and validations aren't automatically executed on atomic operations.

I really hope this will be implemented.

**Comment by zhura** [comment] 2015-05-14 07:16
+1

**Comment by akalinovski** [comment] 2015-05-14 12:52
+1

**Comment by cylwin** [comment] 2015-05-20 13:26
+1

**Comment by welkinwong** [comment] 2015-05-22 04:48
+1

**Comment by skotchio** [comment] 2015-05-23 14:26
+1

**Comment by newmanw** [comment] 2015-11-04 16:38
runValidators and/or setDefaultsOnInsert don't apply setters???

+1 for this as well.

**Comment by xavdid** [comment] 2016-05-27 01:19
Dunno if this is still in the works, but I got around it by only ever writing to mongo in one place and just using my setter manually. I passed this as the second argument to `findOneAndUpdate`

```
{
  $set: {
    access_token: encrypt(access_token),
    name: name
  }
}
```

**Comment by kholiavko-roman** [comment] 2017-10-24 22:50
+1

**Comment by vkarpov15** [comment] 2017-10-30 18:13
Use the `runSettersOnQuery` to opt in to this behavior, we'll have it on by default for 5.0 :+1:

**Comment by vkarpov15** [comment] 2017-12-06 17:22
Going to close this in favor of #5340. Please follow that issue for more updates, but the plan is to turn this behavior on by default for 5.0.

**Closed by vkarpov15** 2017-12-06 17:22 UTC
Labels: discussion, new feature
