### ISSUE TITLE
mongoose somtimes  populate failed ! 

### ISSUE THREAD

**Issue by rianran1993** [Automattic/mongoose#5095] opened 2017-03-22 04:00 UTC
`mId: {type: ObjectId, ref: require("../mat/mat").modelName},`

`currentModel.findById(params._id)
        .populate("mId", "mName logo sizeType")
        .exec(function(err, data) {
            if(err) {
                return callback(err);
            }
           .....
        });`
this is my code , sometimes it work successfully but sometimes failed and it return just ObjectId not a object

**Comment by varunjayaraman** [comment] 2017-03-24 02:15
@rianran1993 this isn't really a reproducible script. Do you have more context?

**Comment by varunjayaraman** [comment] 2017-03-30 03:13
hey @rianran1993 i'm going to close this unless you have more context. It's pretty hard to work with an issue like this without more info.

**Closed by varunjayaraman** 2017-03-30 03:13 UTC
Labels: needs clarification

**Comment by chrisschaub** [comment] 2017-04-07 19:26
I am also seeing this happen. I can run a query with a populate, sometimes it will fail to populate. I'm wondering if mongodb is running out of resources on my local box occassionally? It does not throw an error, the referenced collection field is just empty.

**Comment by chrisschaub** [comment] 2017-04-07 20:55
Ok, more details. This happens when you try to use populate to go a few levels deep. It sometimes works, sometimes does not. Moving the populate to a schema pre find seems to be much more stable. But there is definitely a populate bug in 4.x with nesting more than a level deep. And it happens on my linux dev laptop and on a production mongodb atlas server.

**Comment by akankshach29** [comment] 2018-03-07 17:29
I'm seeing this issue as well. When populating a few level deep on Atlas server sometimes it returns the query with all details but sometimes it skips the last level populate.

**Comment by akshaykumar12527** [comment] 2019-04-18 10:07
I am also facing the same issue @chrisschaub, how did you fix that issue, can you suggest something

**Comment by vkarpov15** [comment] 2019-04-22 19:22
@akshaykumar12527 please open up a separate issue with code samples. I'm closing this issue as spam.
