### ISSUE TITLE
Mongoose 4.6.2 produces error "MongoError: no primary found in replicaset" while 4.4.19 works just fine

### ISSUE THREAD

**Issue by adeelzaman** [Automattic/mongoose#4596] opened 2016-10-04 14:04 UTC
Simple connection to a MongoDB replica set. Works great in Mongoose 4.4.19 but not in 4.6.2

mongoURI = "mongodb://IP:27017,IP:27017/" + dbName + "?replicaSet=my_replica_set";

Using 4.6.2, I have tried the following:
- defining replset in connection options
- connectWithNoPrimary: true
- tried both mongoose.createConnection vs mongoose.connect
- included and excluded arbiter node in the connection string

If connection string only uses one database, it works fine. I am really curious as to why this error occurs. Any thoughts?

Full Error:

/Users/adeel/dev/navi/euler/node_modules/mongodb/lib/replset.js:360
          process.nextTick(function() { throw err; })
                                        ^
MongoError: no primary found in replicaset
    at /Users/adeel/dev/navi/euler/node_modules/mongodb-core/lib/topologies/replset.js:631:32
    at .<anonymous> (/Users/adeel/dev/navi/euler/node_modules/mongodb-core/lib/topologies/replset.js:421:24)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/adeel/dev/navi/euler/node_modules/mongodb-core/lib/topologies/server.js:313:21)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/adeel/dev/navi/euler/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/Users/adeel/dev/navi/euler/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by ashishtilara** [comment] 2016-10-06 23:11
+1

**Comment by vkarpov15** [comment] 2016-10-08 20:03
Can you connect with the mongo shell?

**Comment by adeelzaman** [comment] 2016-10-08 20:23
Can connect with mongo shell. The DB is working fine. We are in production and many microservices are connected to the DB using the replica set string.

However, for new projects, connecting using the replica set string doesn't seem to work. And we have to use just the IP of the master node. I first thought this was a version issue (4.6.2 vs 4.4.19).

However, recently I wasn't able to connect using the replica string on 4.6.2 either on the new project. As a tempoary solution, I decided to just the IP for the master node.

**Comment by adeelzaman** [comment] 2016-10-17 00:29
@zoellner If you are able to post a shortlist of some of the packages you updated right before this issue started for you, I can check it against my own list and we can try to pinpoint where the incompatibility lies.

**Comment by zoellner** [comment] 2016-10-17 01:27
@adeelzaman I've created a diff of my project's npm-shrinkwrap.json for the commit that started to cause the issues. It's a bit long, so I've put it here:
https://gist.github.com/zoellner/eddd3d40291e150919bb025f452f9054

**Comment by zoellner** [comment] 2016-10-17 20:29
@adeelzaman ignore that last comment. I just discovered that my Dockerfile ignored the npm-shrinkwrap.json - those updates actually work fine.

**Comment by dan-perron** [comment] 2016-10-19 17:55
@zoellner I can't tell from that gist which one is the cause, can you enlighten us?

**Comment by adeelzaman** [comment] 2016-10-19 18:39
I found out that for us the issue does not occur for Mongoose 4.5.8. Temporarily we have locked our repos into 4.5.8 of Mongoose to solve the problem.

Also I should mention that when attempting to isolate the problem, I created a brand new project with only one node module (mongoose) and attempted to connect to the replica set using 4.6.0 and got the same error.

So maybe it isn't an incompatibility error but an error with 4.6.0? I couldn't pinpoint any further as per what was causing the error. I plan to look into it more when I get some free time.

**Comment by zakpatterson** [comment] 2016-10-19 20:21
I just ran into what I'm pretty sure is the same issue on 4.6.2 and 4.6.4, I get this output for my replicaset connection, same config uri setup as above

```
Error: Uncaught, unspecified "error" event. ([object Object])
    at NativeConnection.emit (events.js:163:17)
    at /home/projects/xxx/xxx/node_modules/mongoose/lib/connection.js:466:17
    at NativeConnection.Connection.error (/home/projects/xxx/xxx/node_modules/mongoose/lib/connection.js:489:12)
    at /home/projects/xxx/xxx/node_modules/mongoose/lib/connection.js:520:15
    at /home/projects/xxx/xxx/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:216:21
    at /home/projects/xxx/xxx/node_modules/mongodb/lib/db.js:229:14
    at .<anonymous> (/home/projects/xxx/xxx/node_modules/mongodb/lib/replset.js:357:9)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Timeout.<anonymous> (/home/projects/xxx/xxx/node_modules/mongodb-core/lib/topologies/replset.js:507:14)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by vkarpov15** [comment] 2016-10-22 01:52
Hmm strange. This is almost certainly an issue with the underlying mongodb driver, because mongoose doesn't do anything with replica sets on its own. There were some issues with replica sets that [were fixed in mongodb driver 2.2.11](https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#2211-2016-10-21), will upgrade for mongoose 4.6.5 and see if that fixes it.

**Comment by mo4islona** [comment] 2016-10-25 05:37
+1

**Comment by vkarpov15** [comment] 2016-10-26 17:14
@mo4islona still happening in 4.6.5?

**Comment by alexanderMykhailenko** [comment] 2016-10-27 09:32
+1 the same problem (in 4.6.5 also).
Latest working version 4.5.9 after this version 4.6.0 and more i receive error "no primary found in replicaset"

**Comment by mo4islona** [comment] 2016-10-27 09:38
@vkarpov15 Yes 4.6.5 doesn't work. Didn't try 4.5.9 but 4.4.19 works.

**Comment by dottodot** [comment] 2016-11-09 16:58
same problem here using a uri such as 

```
mongodb://user:password@server1,server2,server3/database?replicaSet=repname
```

works on 4.5.9 but latest version gives errors

**Comment by stampsrule** [comment] 2016-11-11 03:26
today I did an install on ubuntu 14 with mongoose 4.5.9 and got the same error
`/node_modules/mongodb/lib/mongo_client.js:225
          throw err
          ^
MongoError: no primary found in replicaset
    at /node_modules/mongodb-core/lib/topologies/replset.js:628:32
    at Server.<anonymous> (test/node_modules/mongodb-core/lib/topologies/replset.js:420:24)`

the same code was working no problem on mac OSX

my uri is same as dottodot

**Comment by vkarpov15** [comment] 2016-11-14 00:49
Weird. Can you confirm whether you can connect using the mongodb shell using that URI from the same machine?

**Comment by stampsrule** [comment] 2016-11-14 06:54
@vkarpov15 I can connect using the mongodb shell and I can connect using the standard URI way

**Comment by vkarpov15** [comment] 2016-11-16 19:23
@stampsrule what's the standard URI way?

**Comment by stampsrule** [comment] 2016-11-16 23:16
@vkarpov15 

`mongodb://user:password@server:port/database`

**Comment by vkarpov15** [comment] 2016-11-17 22:55
Ok so what's the connection code that's failing?

**Comment by asabhaney** [comment] 2016-11-23 02:49
I am having the same issue as well. Reverting to `4.5.10` works. My connection string looks like:

```
mongodb://username:password@ip1:port1,ip2:port2/database?authSource=blah&replicaSet=rs0&ssl=true
```

- Using mongoose `4.6.8`, but the issue seems to apply to `4.6.2` and up
- `mongoose.connection.readyState` is `2` while it tries to connect, then `0` when the connection fails
-  Although I've turned debugging on, there is no output
- Using node 6.7.0

**Comment by saguila** [comment] 2016-12-06 23:25
use mongoose@4.4.12,the last version don't work.i had the same problem(repset).

**Comment by dustywusty** [comment] 2016-12-06 23:41
@adeelzaman is your replica set hosted in an environment where you may have more than one address to access each of the replica set members e.g. internal and external?

**Comment by adeelzaman** [comment] 2016-12-09 12:39
@dustywusty Not it doesn't. One IP address per replica set member.

**Comment by wparsons-360insights** [comment] 2016-12-09 19:51
I have this issue happening with 4.6.0 and newer, 4.5.10 is the last working version for me.

**Comment by flipflopapp** [comment] 2016-12-23 19:53
Kindly review if this issue is similar to - https://github.com/Automattic/mongoose/issues/4834

**Comment by stampsrule** [comment] 2016-12-31 01:48
I am using the latest version and logged `self.s.replicaSetState` at the time of the error and found this:
`topologyType: 'ReplicaSetNoPrimary',
  setName: 'rs0',
  set: 
   { 'mongo1:27017': 
      { type: 'Unknown',
        electionId: null,
        setName: null,
        setVersion: null },
     'mongo2:27017': 
      { type: 'PossiblePrimary',
        setVersion: null,
        electionId: null,
        setName: null },
     'mongo3:27017': 
      { type: 'Unknown',
        electionId: null,
        setName: null,
        setVersion: null },
     'database4ca:27017': 
      { type: 'RSSecondary',
        electionId: undefined,
        setName: 'rs0',
        setVersion: 5 },
     'mongoarb:27017': 
      { type: 'Unknown',
        electionId: null,
        setName: null,
        setVersion: null } },`

are the null values causing the error?

**Comment by stampsrule** [comment] 2016-12-31 08:07
that was 100% the problem, when I put in mongo1.example.com:27017 it would not connect even though the IP worked. when I resolved the URL issue and replaced my mongodb:// URI with URLs all worked.

**Comment by mengfoobar** [comment] 2017-01-09 01:40
saw @wparsons-360insights  's comment and tried it out. Confirming that the exact db connection for replica set works in 4.5.10 but **not in 4.7.1**

**Comment by tapankumar** [comment] 2017-01-09 12:31
Hi,

I am facing the same issue.

mongoose": "^4.7.6"

config:
config.mongoose = {
    uri: "mongodb://Appinv-db:27017,Appinv-db1:27017,Appinv-db2:27017,Appinv-db3:27017/nexgtv_16?replicaSet=rs0",
    //uri: "mongodb://localhost/nexgtv_16",
    options: {
        db: { native_parser: true },
        replset: {
            //auto_reconnect: false,
            poolSize: 10,
            socketOptions: {
                keepAlive: 1000,
                connectTimeoutMS: 30000
            },
            reconnectInterval: 2000, //Default is 1000 ms
            reconnectTries: 60 //Default is 30
        },
        server: {
            poolSize: 5,
            socketOptions: {
                keepAlive: 1000,
                connectTimeoutMS: 30000
            },
            reconnectInterval: 2000, //Default is 1000 ms
            reconnectTries: 60 //Default is 30
        }
    }
}

Connection:
mongoose.connect(config.mongoose.uri, config.mongoose.options);

Error:
MongoError: connection 3 to Appinv-db3:27017 closed
    at Function.MongoError.create (/etc/scripts/push-notifications/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/etc/scripts/push-notifications/node_modules/mongodb-core/lib/connection/connection.js:198:22)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
connection error: { MongoError: no primary found in replicaset
    at /etc/scripts/push-notifications/node_modules/mongodb-core/lib/topologies/replset.js:659:32
    at Server.<anonymous> (/etc/scripts/push-notifications/node_modules/mongodb-core/lib/topologies/replset.js:442:24)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Object.cb (/etc/scripts/push-notifications/node_modules/mongodb-core/lib/topologies/server.js:259:55)
    at Connection.<anonymous> (/etc/scripts/push-notifications/node_modules/mongodb-core/lib/connection/pool.js:243:32)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/etc/scripts/push-notifications/node_modules/mongodb-core/lib/connection/connection.js:197:12)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
  name: 'MongoError',
  message: 'no primary found in replicaset' }

Please suggest any solution

**Comment by aks0020** [comment] 2017-01-27 17:08
Having similar issue with mLab on heroku with replica in uri fixed by using ` 4.5.10` version

**Comment by dan-perron** [comment] 2017-01-27 17:10
We are encountering this issue as well, but a recent upgrade from MongoDB 3.0 -> 3.4 seems to allow the most recent version of mongoose to run stably.

**Comment by dazwiafl** [comment] 2017-01-31 12:04
I've had the same problem.
Adding the replicasets members hostnames (like they are on the replset hostsfile) to the webservers hostsfile fixed the issue for me.

```
rs.conf();
{
	"_id" : "cwreplset0",
	"version" : 348189,
	"protocolVersion" : NumberLong(1),
	"members" : [
		{
			"_id" : 0,
			"host" : "cwmongo1:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 2,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 1,
			"host" : "cwmongoArbiter:27017",
			"arbiterOnly" : true,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "cwmongo2:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
...
```

```
cwmongo1 /etc/hosts:
127.0.0.1	cwmongo1
XXX	cwmongo2
XXX cwmongoArbiter

cwmongo2 /etc/hosts:
127.0.0.1	cwmongo2
XXX	cwmongo1
XXX cwmongoArbiter

cwmongoArbiter /etc/hosts:
127.0.0.1	cwmongoArbiter
XXX	cwmongo2
XXX cwmongo1
```

```
webservers /etc/hosts:

XXX cwmongo1
XXX cwmongo2
```

**Comment by aks0020** [comment] 2017-02-02 05:28
Surprisingly issue fixed for me with `replicaSet` param in mLab `MONGODB_URI` after updating to latest version `4.8.1`.

**Comment by zoellner** [comment] 2017-02-03 23:14
given @dazwiafl's comment, is it possible that the error occurs when the "host" in the replicaset configuration on the mongodb server doesn't match the server names in the connection string? E.g. when custom (internal) dns names or IP addresses are used?
Looking through the previous comments it seems to be the case for everyone who mentioned their hostnames. 
In that case #4834 would actually be the same issue as suggested by @flipflopapp

**Comment by zoellner** [comment] 2017-02-06 21:57
Confirming that mongoose 4.8.1 works for us (with mongodb 3.4.2) if and only if we use the full (external) dns names in the connection string. 

We previously used an internal dns name (that resolved to a private EC2 IP address within our VPC). This doesn't work when the host names in the rs.conf() is set to the external dns names.
I haven't tested all configurations, but my intuition at this point tells me that the mongoose/mongodb version doesn't really matter.
This problem should be solved when using the full dns names.

**Comment by dottodot** [comment] 2017-02-07 11:49
@zoellner I have a similar setup where I'm connecting to mongo via private network so there is no external access, so how do you get round that? Before I could just connect using the private ip addresses. I've been trying to find an answer but without much luck.

**Comment by zoellner** [comment] 2017-02-07 18:45
I made some infrastructure changes to allow "external access" (limited to the servers who need it). Not an ideal solution but will work for a while until there's a better way. I think it's really an issue to raise with the folks at mongodb to better handle this rather common scenario

**Comment by phutchins** [comment] 2017-02-08 14:03
@dottodot You should be able to set sslAllowInvalidCertificates and sslAllowInvalidHostnames on the client side, and set the self signed cert up to use localhost or 127.0.0.1 for the FQDN. This is working for me with IP's as the host field in the replicaset and still am accessing the hosts via a hostname that doesn't match the hosts's hostname or FQDN set in the cert. I haven't tested using IP's in the mongo uri to access the cluster however. If it would be beneficial to you, I could test this...

**Comment by edgarmarkosov** [comment] 2017-02-22 14:25
Is there any fix of this issue for mongoose v4.8.4?

**Comment by wayofthefuture** [comment] 2017-02-27 21:49
4.5.10 and 4.4.12 doesn't solve the problem for me. Running a google compute replica set with replica set name rs0.

**Comment by luismendozamx** [comment] 2017-02-28 03:45
I had the same issue using v4.6.5 upgrading to v4.8.5 solved the issue without changing any config.

**Comment by wayofthefuture** [comment] 2017-02-28 05:34
Just tried 4.8.5 no luck :(

**Comment by edgarmarkosov** [comment] 2017-02-28 06:08
How do you connect to replica set?

**Comment by wayofthefuture** [comment] 2017-02-28 12:20
We are using:

```javascript
mongodb://root:password@mongo0.dev.domain.com:27017,mongo1.dev.domain.com:27017,mongo2.dev.domain.com:27017/main?replicaSet=rs0&authSource=admin
```

I've read somewhere it is only required to pass the primary address and the 2 secondaries are not necessary. Is this true? Thanks.

**Comment by edgarmarkosov** [comment] 2017-02-28 13:16
Try this. NOTE that there is no need to connect to arbiter mongo, only 2 replicas:

mongoose.connect("mongodb://mongo1.dev.domain.com,mongo2.dev.domain.com/main?replicaSet=rs0&authSource=admin", {
            user: 'MONGO_USERNAME',
            pass: 'MONGO_PASSWORD'
        });

**Comment by abeven** [comment] 2017-03-01 03:16
Just to chime in - ran into this issue connecting to a mongo RS in a Kubernetes StatefulSet. Didn't qualify the DNS names in the connection string with the SS name and got the "no primary error".

So for a SS named mongo, "mongo-0" should've been "mongo-0.mongo". Error went away.

**Comment by wayofthefuture** [comment] 2017-03-01 15:37
@edgarmarkosov We are not using an arbiter. We are using 3 full instances. It was recommended in the Mongo docs that having 3 full instances was better than 2 with an arbiter. We are using the standard Google Cloud bitnami replica deployment. Pretty much just a few clicks and it is up and running.

I tried connection using your method above but it did not work. I am sure it's some kind of weird problem. I read somewhere that the primary will send the addresses of the other 2 secondaries. I hope that is so, then we can just use the address of the primary in the connection string.

**Comment by Trenrod** [comment] 2017-03-06 08:42
@wayofthefuture "I read somewhere that the primary will send the addresses of the other 2 secondaries."
Do you have a source. Bcos this didnt work for me eigther nor any workaround suggested here. Im stucked in the same situation like op. :/

**Comment by wayofthefuture** [comment] 2017-03-06 15:08
Sometimes I wonder if it would just be better to use straight up Mongo API? Is it really more beneficial to get stuck with problems like these because we wanted something that was easier to work with? Sometimes it feels like an unnecessary abstraction layer.

**Comment by vkarpov15** [comment] 2017-03-10 22:30
@wayofthefuture agreed, we're planning on that but haven't done so yet.

**Comment by rushabhnagda11** [comment] 2017-03-21 13:41
Can confirm this issue on 4.9.0.

Running mongo in Kubernetes with 3 nodes in a Replication Controller. My node server using mongooose is connecting to my mongo cluster in a different namespace.

If my nodeserver and mongo cluster is in the same namespace (no dns resolution required) it works.

**Comment by asabhaney** [comment] 2017-03-28 10:06
Was able to figure out the issue, thanks to more specific error messages with the latest driver upgrades (now using mongoose 4.9.2). The issue was that mongoose was trying to connect to each host specified in the mongo replica set configuration, rather than using the hosts I specified in my mongoose connection string. And since my node server and mongo cluster are running in separate namespaces, my node server was unable resolve the DNS for these hosts.

**Comment by wayofthefuture** [comment] 2017-03-28 12:52
Can you please explain what you did to solve the problem? My Mongo Cluster is running in a separate namespace as well. Thanks.

**Comment by asabhaney** [comment] 2017-03-28 20:53
@wayofthefuture I'm not sure if I did it in the best way, but I just edited the `/etc/hosts` file on my host where the node server is running. 

So for example, let's say the hosts specified in your replica set configuration are `db1.example.com` and `db2.example.com`. But then for some reason (like firewall configuration), the host where your node server is running can't resolve these two hostnames. So in your mongoose connection configuration string you are using different hostnames or IP addresses (for example `10.0.0.1` and `10.0.0.2`). If this is the case, then you could edit the `/etc/hosts` file (on the same host as the node server is running) to include the lines:

```
10.0.0.1 db1.example.com
10.0.0.2 db2.example.com
```

At least that's what my issue was - I'm not sure that this applies to this will apply to your situation as well. Bizarre that a different version of the mongo driver could cause an issue like this. Anyway, hope that helps.

**Comment by JonathanYates** [comment] 2017-04-08 20:55
Confirm same error:
Mongoose default connection error: MongoError: no primary found in replicaset.

Using mongoose 4.9.3. and docker compose. Not sure if docker is anything to do with it, but reverting to 4.5.10 resolved the issue.

Please can someone take a serious look into this issue as it was raised 7 months ago with no solution other than to revert to 4.5.10.

**Comment by wayofthefuture** [comment] 2017-04-10 20:54
@asabhaney I think you are on the right track. I have changed the Mongoose connection string to use all static IPs, instead of domain names. It would appear it is successfully connecting now. I also recreated the cluster using google compute bitnami image, and made sure the firewall port was open for all nodes. Currently working :)

So it would appear the problem is that it doesn't resolve the DNS names when you put domain names in the connection string. When you give static IP's, it uses them. When you give domain names, it asks the servers for their IP, which in turn gives a local IP and not the public IP.

**Comment by wayofthefuture** [comment] 2017-04-10 21:22
@asabhaney You are right... now it is trying to connect to the internal IP addresses of each cluster node. This seems like a bug still to me though, because if I specify a domain name with a static IP, it should use that static IP and not try to use the internal IP in another subnet. The /etc/hosts fix is a solution but seems like a fix for a bigger problem, right? Thanks.

**Comment by ekryski** [comment] 2017-05-06 06:59
I'm wondering if this an underlying issue with the native mongodb driver? I'm also seeing issues connecting to replica sets through Heroku. It's just bombing not being able to find a primary.

**Comment by wparsons-360insights** [comment] 2017-05-08 13:05
I haven't looked, but unless the native mongodb driver being used between the known working and known not working versions of mongoose was changed, it can't be just the native driver at fault.

**Comment by liquidscorpio** [comment] 2017-05-15 14:05
+1 Reverting to v4.5.10 works.

#### Node versions tested against
v7.7.3
v7.10.0
lts/boron

#### Mongoose versions tested and failed with "No primary found"
5.6.2
5.7.0
5.8.5

#### Mongo versions
3.2
2.6

#### Reproducibility
Consistent


Any leads where to even start looking to get underneath this bug?

**Comment by liquidscorpio** [comment] 2017-05-15 14:20
Is this issue related to https://github.com/Automattic/mongoose/issues/4517? While that issue is marked closed I am not sure if the issue was resolved. Newer versions still have this problem.

**Comment by dtzar** [comment] 2017-05-20 15:28
I've verified this error exists against Azure CosmosDB using the 4.9.10 version of the driver.  It also exists against the 4.5.10 driver with CosmosDB too unless you specify `&readPreference=secondary` at the end of the connection string - then it works fine.

**Comment by vkarpov15** [comment] 2017-05-23 23:50
@dtzar fair warning, supporting CosmosDB/DocumentDB is currently a non-goal for mongoose. If you choose to use mongoose with those dbs you're on your own.

**Comment by ronenteva** [comment] 2017-05-24 10:14
Issue still exists on  Mongoose 4.10.2

**Comment by wayofthefuture** [comment] 2017-05-24 14:21
I connected using the mongo native driver and the issue still occurred. It's not mongoose it's the hard coded IP addresses on each one of the computers in the cluster. You have to change the IP address to the public external IP address and not the internal IP. When I used Mongo Atlas official service it was already setup ready to go no modification required as far as IPs are concerned.

**Comment by dtzar** [comment] 2017-05-25 22:12
@wayofthefuture are you referring to CosmosDB?  I also realized connecting to CosmosDB worked via Mongoose 4.5.10 if you drop the &replicaset=globaldb at the end.

**Comment by cula** [comment] 2017-06-19 10:06
Issue still exists on Mongoose 4.10.2
Any update?

**Comment by dtzar** [comment] 2017-06-19 17:23
This issue is no longer present with the latest Mongoose version as far as I can see connecting to CosmosDB using MongoDB API as long as you specify the connection string in the following format:
```
mongodb://myservername:mypassword@myservername.documents.azure.com:10255/mydbname?ssl=true&replicaSet=globaldb
```
It's important to call out the fact that the `mydbname` is *not* present by default in the Azure portal and must be inserted or else the connection WILL fail with the mentioned issue above.  It doesn't matter what value you provide for mydbname, but it must be there.

**Comment by vunb** [comment] 2017-07-29 09:22
Try to fix hostname of mongodb server in `/etc/hosts`, for example:

```
1.2.3.4 mdb01 mdb01.example.com
1.2.3.5 mdb02 mdb02.example.com
1.2.3.6 mdb03 mdb03.example.com
```
Hope this help !

**Comment by aichholzer** [comment] 2017-08-31 02:04
Using `V. 4.11.5` on Heroku. -At first I had the same issues, I fixed it by just adding `replicaSet` to the connection string:

```
mongodb://user:pass@mongolayer.com,mongolayer.com/database?replicaSet=database
```

I hope this helps.

**Comment by thetaris-slack** [comment] 2017-09-27 15:24
Hi I am also hitting this issue with a StatefulSet (Mongo DB self-awareness is ReplicaSet) on Kubernetes with CoreOS and AWS.

Can we have a summary of a good solution for this, even though it might (totally unsure tbh??) not be a mongoose problem.

**Comment by nottinhill** [comment] 2017-09-27 15:24
Hi I am also hitting this issue with a StatefulSet (Mongo DB self-awareness is ReplicaSet) on Kubernetes with CoreOS and AWS.

Can we have a summary of a good solution for this, even though it might (totally unsure tbh??) not be a mongoose problem.

**Comment by nottinhill** [comment] 2017-10-06 02:02
Solution:

```
    options.replset = {
      socketOptions: {
        connectTimeoutMS: 60000, 
        keepAlive: 120
      }
    };
```

**Comment by ChrisBarriere** [comment] 2017-11-21 11:41
setting /etc/hosts works for me

**Comment by alexratiu** [comment] 2017-12-06 10:10
I think you can open compass and cluster connection in web tab and choose connect to compass and compass app automatically detect the connection :)

**Comment by sravzpublic** [comment] 2018-03-23 14:27
I get the same error in Node 8. Node 6 works fine. Any ideas?

Error: Cannot determine state of server
    at canCheckoutReader (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:779:12)
    at Server.checkoutReader (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:793:16)
    at Cursor.nextObject (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
    at Collection.findOne (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:162:10)
    at /home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/lib/connect-mongo.js:223:18
    at MongoStore._get_collection (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/lib/connect-mongo.js:156:21)
    at MongoStore.get (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
    at session (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express-session/index.js:367:11)
    at Layer.handle [as handle_request] (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:269:13)
    at /home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:311:12)
    at /home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:294:3)
    at next (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:188:10)
    at cookieParser (/home/vagrant/SravzNew/Sravz.Rest/node_modules/cookie-parser/index.js:48:5)
Error: Cannot determine state of server
    at canCheckoutReader (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:779:12)
    at Server.checkoutReader (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:793:16)
    at Cursor.nextObject (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:748:48)
    at Collection.findOne (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/collection/query.js:162:10)
    at /home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/lib/connect-mongo.js:223:18
    at MongoStore._get_collection (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/lib/connect-mongo.js:156:21)
    at MongoStore.get (/home/vagrant/SravzNew/Sravz.Rest/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
    at session (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express-session/index.js:367:11)
    at Layer.handle [as handle_request] (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:269:13)
    at /home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:236:9
    at Function.proto.process_params (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:311:12)
    at /home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:227:12
    at Function.match_layer (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:294:3)
    at next (/home/vagrant/SravzNew/Sravz.Rest/node_modules/express/lib/router/index.js:188:10)
    at cookieParser (/home/vagrant/SravzNew/Sravz.Rest/node_modules/cookie-parser/index.js:48:5)


Node Version
v6.13.0 -> WORKS
 v8.10.0 -> Throws that error. Does mongoose support Node8?

npm list | grep mongoose
├─┬ mongoose@5.0.11
│ ├── mongoose-legacy-pluralize@1.0.2

npm list | grep mongodb
│ └── mongodb@1.4.40 extraneous
├─┬ mongodb@3.0.3 invalid
│ └── mongodb-core@3.0.3 extraneous
│ ├─┬ mongodb@3.0.4
│ │ └─┬ mongodb-core@3.0.4

**Comment by vkarpov15** [comment] 2018-04-03 21:16
@sravzpublic please look closely at your stack trace, it shows that the error is in connect-mongo and has nothing to do with mongoose. FWIW, mongoose does support node 8.

**Comment by prologic** [comment] 2019-03-25 04:02
We experience this too on Mongoose 5.2.12 (*much newer than reported here*) on NodeJS 6.x -- Haven't had too much time to dig into it yet :/

**Comment by patientplatypus** [comment] 2019-04-11 21:53
I am getting this issue on "mongoose": "^5.4.19", and have provided examples an open stackoverflow here: https://stackoverflow.com/questions/55637808/mongoerror-no-mongos-proxy-available-when-connecting-to-replica-set. It's concerning that this seems to be an open issue for so long and through a version upgrade even. Hmm....

**Comment by fd98279** [comment] 2019-04-12 12:13
I faced this issue in node 8 I upgrade to node 10 and have these packages and restructured my mongodb connection logic to below. It worked. 

cat package.json | grep mongo
    "connect-mongo": "^2.0.1",
    "mongodb": ">=3.0.4",
    "mongoose": ">=5.0.11",

node -v
v10.4.1

db.version()
3.4.15

config.db = mongodb://user:pass@host:26000/dbname?ssl=true

// Get Mongoose to use the global promise library
mongoose.Promise = global.Promise;
var db = mongoose.connect(config.db, {
    auto_reconnect: true,
    socketTimeoutMS: 0,
    connectTimeoutMS: 0
  },
  function (err) {
    if (err) {
      console.error(chalk.red('Could not connect to MongoDB!' + err));
      console.log(chalk.red(err));
    }
  });

// When successfully connected
mongoose.connection.on('connected', function () {
 };

// If the connection throws an error
mongoose.connection.on('error', function (err) {
  console.log('Mongoose default connection error: ' + err);
});

// When the connection is disconnected
mongoose.connection.on('disconnected', function () {
  console.log('Mongoose default connection disconnected');
});

**Comment by GuruKarmakar** [comment] 2019-07-27 16:42
i think the problem is on host: (cluster0-shard-00-00-vmyny.mongodb.net) use the primary one.

**Comment by vkarpov15** [comment] 2019-07-29 17:46
I'm going to close this, it looks like the issue is with connect-mongo, not mongoose.

**Closed by vkarpov15** 2019-07-29 17:46 UTC
Labels: needs clarification
