### ISSUE TITLE
Error when trying to make database connection

### ISSUE THREAD

**Issue by Cesarcs7** [Automattic/mongoose#6649] opened 2018-07-03 10:35 UTC
**What is the current behavior?**
Im tryng to set a pre save hook for Auth.

`userSchema.pre('save', async function preSave(next) {
  try {
    if (!this.isModified('password')) {
      return next();
    }
    const hashedPassword = await bcrypt.hash(this.password, 10);
    this.password = hashedPassword;
    return next();
  } catch (err) {
    return next(err);
  }
});

userSchema.methods.comparePassword = async function comparePassword(candidatePassword, next) {
  try {
    const isMatch = await bcrypt.compare(candidatePassword, this.password);
    return isMatch;
  } catch (err) {
    return next(err);
  }
};`
**What is the expected behavior?**
Connection with database should be established normally

**Please mention your Node.js, mongoose and MongoDB version.**
Node 9.9.0
Mongoose 5.2.0
MongoDB 3.4.9

I tried to create a new app with mongoose  and node.js, anytime when i wanted to start the connection with the database i have got this error
`(node:3904) UnhandledPromiseRejectionWarning: MongoError: port must be specified
    at Function.MongoError.create (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb-core\lib\error.js:49:10)
    at new Server (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\topologies\server.js:136:24)
    at options.servers.map.serverObj (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\operations\mongo_client_ops.js:570:9)
    at Array.map (<anonymous>)
    at translateOptions (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\operations\mongo_client_ops.js:567:26)
    at createServer (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\operations\mongo_client_ops.js:332:19)
    at parseFn (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\operations\mongo_client_ops.js:221:14)
    at parseConnectionString (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb-core\lib\uri_parser.js:307:3)
    at connect (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\operations\mongo_client_ops.js:179:3)
    at connectOp (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\operations\mongo_client_ops.js:283:3)
    at executeOperation (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\utils.js:420:24)
    at MongoClient.connect (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongodb\lib\mongo_client.js:168:10)
    at Promise (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongoose\lib\connection.js:455:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongoose\lib\connection.js:452:19)
    at Mongoose.connect (C:\Users\Cesar\Desktop\Code\bodyscan\node_modules\mongoose\lib\index.js:229:15)
(node:3904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I have made a similar app couple of weeks before and it was running normally. I noticed that the version from mongoose in my dependecies package.json was different, i used version 5.1.4 for the oldest project and this one has version 5.2.0, so i installed version 5.1.4 again and it runs normally.

Please let me know if im probably doing something wrong or this is a known new issue from mongoose. Thank you.

**Comment by alexisab** [comment] 2018-07-03 12:23
I got the exact same error. Here is my mongoose connection : 
```
mongoose.Promise = Promise;
mongoose.connect('mongodb://localhost/tned-prototype', {
    keepAlive: 600 * 1000,
    connectTimeoutMS: 60 * 1000
});
```

`"mongoose": "^5.1.7"`

**Comment by lineus** [comment] 2018-07-03 13:35
this is a duplicate of #6647. The comments there have more info.

**Closed by lineus** 2018-07-03 13:35 UTC
