### ISSUE TITLE
populate times out when schema hasn't been registered for model indicated in options - mongoose v4.0

### ISSUE THREAD

**Issue by Andrewpk** [Automattic/mongoose#2798] opened 2015-03-26 14:28 UTC
Calling `.populate()` with options that include a model, which no schema has been registered for, times out instead of prompting with a `MissingSchemaError: Schema hasn't been registered for model` message.

It can be a difficult issue to debug so I figured I'd submit the issue in hopes that people looking for help could find this.

**Comment by vkarpov15** [comment] 2015-03-26 14:42
Hmm that's an odd one. I'll look into it, thanks for pointing this out.

**Comment by vkarpov15** [comment] 2015-03-27 14:03
Hmm can you provide me an example that reproduces the behavior you're seeing? My translation of english to code looks like this:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var util = require('util');
var assert = require('assert');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh2798');

var ConversionEvent = new Schema({
  owner: { type: Schema.Types.ObjectId, ref: 'User', required: true }
});

var Conversion = mongoose.model('Conversion', ConversionEvent);

var userSchema = new Schema();
var User = mongoose.model('User', userSchema);

clear(function() {
  User.create({ _id: '000000000000000000000001', name: 'val' }, function(err) {
    Conversion.create({
      name: 'test',
      owner: '000000000000000000000001'
    }, function (err, conversion) {
      Conversion.find().populate({ path: 'owner', model: 'Not Exist' }).exec(function (err, bases) {
        console.log('done!');
        process.exit(0);
      });

    });
  });
});

function clear(callback) {
  Conversion.remove({}, function() {
    User.remove({}, function() {
      callback();
    });
  });
}
```

Which errors out as expected:

```
Mongoose: conversions.remove({}) {}  
Mongoose: users.remove({}) {}  
Mongoose: users.insert({ _id: ObjectId("000000000000000000000001"), __v: 0 })   
Mongoose: conversions.insert({ owner: ObjectId("000000000000000000000001"), _id: ObjectId("551562aac143269623481c86"), __v: 0 })   
Mongoose: conversions.find({}) { fields: undefined }  

/home/val/Workspace/10gen/mongoose/lib/connection.js:660
    throw new MongooseError.MissingSchemaError(name);
          ^
MissingSchemaError: Schema hasn't been registered for model "Not Exist".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (/home/val/Workspace/10gen/mongoose/lib/connection.js:660:11)
    at getModelsMapForPopulate (/home/val/Workspace/10gen/mongoose/lib/model.js:2354:26)
    at populate (/home/val/Workspace/10gen/mongoose/lib/model.js:2196:15)
    at Function.Model.populate (/home/val/Workspace/10gen/mongoose/lib/model.js:2166:5)
    at Immediate.cb (/home/val/Workspace/10gen/mongoose/lib/query.js:1043:16)
    at Immediate._onImmediate (/home/val/Workspace/10gen/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by vkarpov15** [comment] 2015-03-27 14:03
Hmm can you provide me an example that reproduces the behavior you're seeing? My translation of english to code looks like this:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var util = require('util');
var assert = require('assert');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh2798');

var ConversionEvent = new Schema({
  owner: { type: Schema.Types.ObjectId, ref: 'User', required: true }
});

var Conversion = mongoose.model('Conversion', ConversionEvent);

var userSchema = new Schema();
var User = mongoose.model('User', userSchema);

clear(function() {
  User.create({ _id: '000000000000000000000001', name: 'val' }, function(err) {
    Conversion.create({
      name: 'test',
      owner: '000000000000000000000001'
    }, function (err, conversion) {
      Conversion.find().populate({ path: 'owner', model: 'Not Exist' }).exec(function (err, bases) {
        console.log('done!');
        process.exit(0);
      });

    });
  });
});

function clear(callback) {
  Conversion.remove({}, function() {
    User.remove({}, function() {
      callback();
    });
  });
}
```

Which errors out as expected:

```
Mongoose: conversions.remove({}) {}  
Mongoose: users.remove({}) {}  
Mongoose: users.insert({ _id: ObjectId("000000000000000000000001"), __v: 0 })   
Mongoose: conversions.insert({ owner: ObjectId("000000000000000000000001"), _id: ObjectId("551562aac143269623481c86"), __v: 0 })   
Mongoose: conversions.find({}) { fields: undefined }  

/home/val/Workspace/10gen/mongoose/lib/connection.js:660
    throw new MongooseError.MissingSchemaError(name);
          ^
MissingSchemaError: Schema hasn't been registered for model "Not Exist".
Use mongoose.model(name, schema)
    at NativeConnection.Connection.model (/home/val/Workspace/10gen/mongoose/lib/connection.js:660:11)
    at getModelsMapForPopulate (/home/val/Workspace/10gen/mongoose/lib/model.js:2354:26)
    at populate (/home/val/Workspace/10gen/mongoose/lib/model.js:2196:15)
    at Function.Model.populate (/home/val/Workspace/10gen/mongoose/lib/model.js:2166:5)
    at Immediate.cb (/home/val/Workspace/10gen/mongoose/lib/query.js:1043:16)
    at Immediate._onImmediate (/home/val/Workspace/10gen/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by Andrewpk** [comment] 2015-03-30 16:31
Hello,

Sorry I haven't gotten back to you sooner. I can replicate this in our code, but cannot with your example. Upon further research into our code - we need to change a lot of things, so I'm going to assume the problem is with a combination of our schema design and model methods that are causing the issues.

I'll reopen once I can reliably reproduce without using our schemas and methods.

**Comment by vkarpov15** [comment] 2015-03-30 16:56
Ok, I'll close it for now. Re-open if you can reliably repro.

**Closed by vkarpov15** 2015-03-30 16:56 UTC
Labels: can't reproduce
