### ISSUE TITLE
MongoDB error when adding the async cursor option to aggregate query

### ISSUE THREAD

**Issue by raoulwissink** [Automattic/mongoose#4101] opened 2016-04-27 14:55 UTC
When adding the `async` cursor option I get the following error:

```
MongoError: cursor object can't contain fields other than batchSize
```

The (simplified) query:

``` Javascript
var pipeline = [
    { $lookup: {
        from: "interactions",
        localField: "_id",
        foreignField: "message_id",
        as: "interactions"
    }},
    { $project: {
        id: "$_id",
        numberOfInteractions: { $size: "$interactions" }
    }},
    { $match: {
        numberOfInteractions: { $eq: 0 }
    }}
];

var promise = Message
    .aggregate(pipeline)
    .allowDiskUse(true)
    .cursor({ batchSize: 2500, async: true })
    .exec();
```

If I make this modification the error goes away:

``` diff
diff --git a/lib/aggregate.js b/lib/aggregate.js
index fd2c2fc..ad76bd6 100644
--- a/lib/aggregate.js
+++ b/lib/aggregate.js
@@ -499,6 +499,7 @@ Aggregate.prototype.exec = function(callback) {

   if (this.options && this.options.cursor) {
     if (this.options.cursor.async) {
+      delete this.options.cursor.async;
       return new Promise.ES6(function(resolve) {
         if (!_this._model.collection.buffer) {
           process.nextTick(function() {
```

My setup:

```
NodeJS 4.2.4
MongoDB version 3.2.5
Mongoose 4.4.13
```

**Comment by bestphoneappsdev** [comment] 2017-12-15 02:59
This issue is still coming while using MongoDB 3.6 on server. 

I get the following error when asking questions : 

**"Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server 169.48.160.4:28001. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }"**

**Comment by bestphoneappsdev** [comment] 2017-12-15 02:59
This issue is still coming while using MongoDB 3.6 on server.

I get the following error when asking questions :

"Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server 127.0.0.1:28001. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }"

**Comment by rturk** [comment] 2017-12-19 17:05
This issue re-surfaced when we've migrated to MongoDB 3.6

**Comment by vkarpov15** [comment] 2017-12-27 16:29
@rturk @bestphoneappsdev  code samples please?

**Comment by nuwanarti** [comment] 2017-12-27 22:29
same problem here.. when i update to mongo v 3.6

**Comment by kumangxxx** [comment] 2017-12-28 04:33
same here, my code:

```
App.aggregate([
    {
        $match: {
            .. 
        }
    },
    {
        $unwind: '$team'
    },
    ....
], ( err, result ) => {
    console.log( err, result );
})
```

using mongodb 3.6
mongoose 4.11

**Comment by web-master777** [comment] 2017-12-29 16:06
I get alike error on PHP after upgrading to mongodb 3.6 (from 3.4)

**Comment by rturk** [comment] 2017-12-29 16:55
@vkarpov15 fixed after I've upgraded to the latest Mongoose version

**Comment by rturk** [comment] 2017-12-29 16:55
@raoulwissink looks like its fixed in the newer versions of Mongoose

**Comment by vkarpov15** [comment] 2017-12-30 20:11
@rturk what version of mongoose did you upgrade to? 4.13.8 or 5.0.0-rc0?

**Comment by rturk** [comment] 2017-12-31 18:36
@vkarpov15 4.13.7

**Comment by varunjayaraman** [comment] 2018-01-06 19:24
@rturk can we close this one out then?

**Comment by rturk** [comment] 2018-01-06 22:07
@varunjayaraman for my case yes.

**Closed** 2018-01-09 02:33 UTC
Labels: fixed?, needs repro script

**Comment by sjohnson540** [comment] 2018-04-04 18:05
Hello! I know this issue is closed, but I was wondering what the root cause was. I have run into the same problem, and upgrading fixed it, but I was hoping to know what the underlying issue was. I did not see a relevant commit attached to this issue.

**Comment by vkarpov15** [comment] 2018-04-11 17:01
@sjohnson540 can you show the code that's causing this issue? This issue shouldn't show up in newer versions of mongoose, the issue was that the `async` flag that mongoose used internally was getting down to the mongodb server.

**Comment by harshad-shirsat** [comment] 2018-04-25 11:03
@sjohnson540 MongoDB 3.6 version has made cursor option mandatory as opposed to version 3.4. Hence you get the warning while running aggregate queries. Refer this link for more information: [https://docs.mongodb.com/manual/reference/command/aggregate/#dbcmd.aggregate]()

**Comment by jasleen19** [comment] 2018-06-15 06:10
We have upgraded mongodb to 3.6.3 and one of the aggregations return this error when called from UI. It was working fine with 3.4.1. I don't know how to resolve it. Please help.

**Comment by jasleen19** [comment] 2018-06-15 06:44
Please find the code:

{  
         "type":"pipeline",
         "uri":"fetchpreloadedData",
         "stages":[  
            {  
               "_$facet":{  
                  "riskProfiles":[  
                     {  
                        "_$unwind":"$service-enrichment.risk-assess-service.enrich-data.risk_details.riskProfiles"
                     },
                     {  
                        "_$group":{  
                           "_id":"riskProfiles",
                           "profileNames":{  
                              "_$addToSet":"$service-enrichment.risk-assess-service.enrich-data.risk_details.riskProfiles"
                           }
                        }
                     }
                  ],
                  "arrivalPorts":[  
                     {  
                        "_$match":{  
                           "travelType":"DEP"
                        }
                     },
                     {  
                        "_$group":{  
                           "_id":"arrivalPorts",
                           "portNames":{  
                              "_$addToSet":"$flight.destination"
                           }
                        }
                     }
                  ],
                  "departurePorts":[  
                     {  
                        "_$match":{  
                           "travelType":"ARR"
                        }
                     },
                     {  
                        "_$group":{  
                           "_id":"departurePorts",
                           "portNames":{  
                              "_$addToSet":"$flight.origin"
                           }
                        }
                     }
                  ],
                  "carrierNames":[  
                     {  
                        "_$match":{  
                           "flight.carrier":{  
                              "_$exists":true,
                              "_$ne":null
                           }
                        }
                     },
                     {  
                        "_$group":{  
                           "_id":"carrierNames",
                           "carrierNames":{  
                              "_$addToSet":"$flight.carrier"
                           }
                        }
                     }
                  ],
                  "flightNumbers":[  
                     {  
                        "_$match":{  
                           "flight.flightNumber":{  
                              "_$exists":true,
                              "_$ne":null
                           }
                        }
                     },
                     {  
                        "_$group":{  
                           "_id":"flightNumbers",
                           "flightNumbers":{  
                              "_$addToSet":"$flight.flightNumber"
                           }
                        }
                     }
                  ],
                  "citizenshipCountriesList":[  
                     {  
                        "_$match":{  
                           "citizenshipCountry":{  
                              "_$exists":true
                           }
                        }
                     },
                     {  
                        "_$group":{  
                           "_id":"citizenshipCountries",
                           "CountriesList":{  
                              "_$addToSet":"$citizenshipCountry"
                           }
                        }
                     }
                  ]
               }
            },
            {  
               "_$out":"preloadData"
            }
         ]
      }
