### ISSUE TITLE
readPreference with secondaryPreferred not working with read command

### ISSUE THREAD

**Issue by conglq** [Automattic/mongoose#4670] opened 2016-11-02 06:34 UTC
I set readPreference: secondaryPreferred, only write command working and read does not with mongoose@4.6.4.

I try mongoose 3.8.40 it works well.
Please help me to fix it. Thanks

This is my config
mongoose.connect("mongodb://mongodb1.com:27017,mongodb2:27017/db", options);

options config:

"db": {
            "readPreference": "secondaryPreferred"
        },
"replset": {
            "rs_name": "rs_dev",
            "socketOptions": {
                "keepAlive": 300000,
                "connectTimeoutMS": 30000
            }
        }

**Comment by paton** [comment] 2016-11-03 01:39
+1 - none of our queries using `read('sp')` are being sent to secondaries anymore. This used to work in older versions.

mongoose: 4.6.5
node: 6.9.1

**Comment by vkarpov15** [comment] 2016-11-07 04:54
Below script works fine for me with 4.6.6:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27000,localhost:27001,localhost:27002/test', {
  "db": {
"readPreference": "secondaryPreferred"
},
"replset": {
"rs_name": "mongoose26",
debug: true
}
});
mongoose.set('debug', true);

var schema = new Schema({ name: String });

var M = mongoose.model('Test', schema);

mongoose.connection.db.s.topology.s.replset.on('pickedServer', (readPref, server) => {
  console.log('Picked', server.s.serverDescription);
});

M.create({ name: 'test' }).
  then(doc => M.findById(doc._id)).
  then(doc => {
    console.log('doc', doc);
  }).
  catch(error => {
    console.error(error);
    process.exit(-1);
  });
```

```
$ node gh-4670.js 
(node:13669) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose: tests.insert({ name: 'test', _id: ObjectId("582008ccd9ac13356591e38a"), __v: 0 })
Mongoose: tests.findOne({ _id: ObjectId("582008ccd9ac13356591e38a") }, { fields: undefined })
Picked { address: 'localhost:27001',
  arbiters: [],
  hosts: [],
  passives: [],
  type: 'RSSecondary' }
doc { _id: 582008ccd9ac13356591e38a, name: 'test', __v: 0 }
^C
$ 
```

Can you make sure your secondaries are actually reachable from your server? Also, how are you determining that these queries aren't hitting your secondary?

**Comment by paton** [comment] 2016-11-07 10:16
![image](https://cloud.githubusercontent.com/assets/609881/20053469/88adfbc2-a48d-11e6-96cf-ee165f36beb1.png)

Screenshot of Cloud Manager, the right is the primary. The secondaries are idle (aside from replication).

Our connection app code:

```
var connectionString = 'mongodb://user:pass@db.host1.com:27000,db.host2.com:27000,db.host3.com:27000,db.host4.com:27000/localize?replicaSet=localizedb&poolSize=30';
  
  mongoose.set('debug', false);

  // Connect
  mongoose.connect(connectionString, {
    replset: {
      loggerLevel: 'error',
      replicaSet: 'localizedb',
      socketOptions: {
        socketTimeoutMS: 300 * 60 * 1000,
        keepAlive: 1,
      },
    },
  });

  mongoose.connection.on('error', (error) => console.error('Mongo connection error:', error));

  mongoose.connection.once('open', () => {
    console.log('Connected to MongoDB');
  });
```

And app code:

```
User.findOne({ email: 'example@email.com' }).select('name').read('sp').exec(console.log);
```

I tried changing "sp" to "secondary" and still no luck. I also tried adding the `replicaSet` option to the connection object, along with the query param, but didn't have an affect.

The opcounters on our secondaries are always near 0 despite very heavy workload on the primary.

I noticed mongodb native driver had a minimum latency setting for secondaries @ 15ms - that's my only guess at this point, although these are big r3.4xlarge and r3.2xlarge servers in AWS within the same availability zone as our application.

Not sure if it's helpful for debugging, but connections to the primary (right most graph) are always much higher than secondaries.

![image](https://cloud.githubusercontent.com/assets/609881/20053734/ca32c342-a48e-11e6-82ee-2b9eea58e8d7.png)

We'll try the `pickedServer` code you used above as we continue debugging.

Lmk if anything comes to mind.

**Comment by ChrisZieba** [comment] 2016-11-07 19:09
> Also, how are you determining that these queries aren't hitting your secondary?

They are appearing in the `mongodb.log` on the primary instance.

**Comment by ChrisZieba** [comment] 2016-11-07 19:47
Without adding `readPreference: "secondaryPreferred",` to our connection object, output is always the primary 

```
Picked { address: 'db.host4.localize.0600.mongodbdns.com:27000',
  arbiters: [],
  hosts: [],
  passives: [],
  type: 'RSPrimary' }
Picked { address: 'db.host4.localize.0600.mongodbdns.com:27000',
  arbiters: [],
  hosts: [],
  passives: [],
  type: 'RSPrimary' }
Picked { address: 'db.host4.localize.0600.mongodbdns.com:27000',
  arbiters: [],
  hosts: [],
  passives: [],
  type: 'RSPrimary' }
```

When we set ` readPreference: "secondaryPreferred"` we start to get hits from the secondaries

```
Picked { address: 'db.host2.localize.0600.mongodbdns.com:27000',
  arbiters: [],
  hosts: [],
  passives: [],
  type: 'RSSecondary' }
```

```js
var connectionString = 'mongodb://user:pass@db.host1.com:27000,db.host2.com:27000,db.host3.com:27000,db.host4.com:27000/localize?replicaSet=localizedb&poolSize=30';

  mongoose.set('debug', false);

  mongoose.connect(connectionString, {
    db: {
      readPreference: "secondaryPreferred",
    },
    replset: {
      loggerLevel: 'error',
      replicaSet: 'localizedb',
      socketOptions: {
        socketTimeoutMS: 300 * 60 * 1000,
        keepAlive: 1,
      },
    },
  });

  mongoose.connection.db.s.topology.s.replset.on('pickedServer', (readPref, server) => {
    console.log('Picked', server.s.serverDescription);
  });
```

Using `read('sp')` in the query does not seem to have any effect (always get primary).

```js
      Collection.find({}).read('sp').exec((err, collection) => {
           // ...
      });
```

**Comment by ChrisZieba** [comment] 2016-11-07 19:57
From what I gather, the only way to read from the secondary is by setting the preference on the initial connection object, like this:

```js
  mongoose.connect(connectionString, {
    db: {
      readPreference: "secondaryPreferred",
    },
    replset: {
      loggerLevel: 'error',
      replicaSet: 'localizedb',
      socketOptions: {
        socketTimeoutMS: 300 * 60 * 1000,
        keepAlive: 1,
      },
    },
  });
```

**Comment by paton** [comment] 2016-11-08 03:02
@vkarpov15 To reproduce, try the test script you posted above but set read('sp') in the query and remove the global readPreference from the connection option.

We tried debugging this more with some help from enterprise MongoDB support guys and no luck. They suggested creating 2 mongoose connection pools (one directly to secondaries) since the per-query read preference doesn't seem to be recognized.

**Comment by paton** [comment] 2016-11-08 03:17
The original poster is setting the readPreference in the connection options (which works for us) - let us know if we should open a new issue for the per-query `read('sp')` option when readPreference isn't set in the connection options.

**Comment by conglq** [comment] 2016-11-08 03:36
@vkarpov15  I set db.setProfilingLevel(2) and see log file of mongo. If I set readPreference: "primary" it works fine and see log on primary server . But when set secondaryPreferred the read query was handle and timeout no any log on server.
I try with mongoose@3.8.40 that work fine with secondary server so I think the network connection don't have any problem.

**Comment by conglq** [comment] 2016-11-08 09:39
@vkarpov15  I try debug mode and  found my problem is difference between host name of rs.config on mongodb server and host name in mongo connection string on client. Mongo driver compare make an error. Thanks a lot!

**Comment by paton** [comment] 2016-11-08 19:28
We changed all of our `read('sp')` commands to `read('s')` and queries are now reading from secondaries. Not sure what was causing `sp` to prefer primary.

These are our 3 secondaries (4th primary not showing). The spike in activity is when we deployed the `read('s')` change.

![image](https://cloud.githubusercontent.com/assets/609881/20113698/56304f00-a5a6-11e6-8162-40eae7ae420a.png)

**Comment by vkarpov15** [comment] 2016-11-13 01:48
Funny, still works fine for me using `.read()`:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://conan:27000,conan:27001,conan:27002/test', {
"replset": {
"rs_name": "mongoose26",
debug: true
}
});
mongoose.set('debug', true);

var schema = new Schema({ name: String });

var M = mongoose.model('Test', schema);

mongoose.connection.db.s.topology.s.replset.on('pickedServer', (readPref, server) => {
  console.log('Picked', server.s.serverDescription);
});

M.create({ name: 'test' }).
  then(doc => M.findById(doc._id).read('sp').exec()).
  then(doc => {
    console.log('doc', doc);
  }).
  catch(error => {
    console.error(error);
    process.exit(-1);
  });
```

```
$ node gh-4670.js 
(node:14669) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose: tests.insert({ name: 'test', _id: ObjectId("5827c40a811bd0394d89879e"), __v: 0 })
Mongoose: tests.findOne({ _id: ObjectId("5827c40a811bd0394d89879e") }, { readPreference: ReadPreference { _type: 'ReadPreference', mode: 'secondaryPreferred', tags: undefined, options: undefined }, fields: undefined })
Picked { address: 'localhost:27002',
  arbiters: [],
  hosts: [],
  passives: [],
  type: 'RSSecondary' }
doc null
^C
$ 
```

@paton the 15ms acceptable latency only applies if you're [using readPreference 'NEAREST'](http://mongodb.github.io/node-mongodb-native/2.2/api/ReplSet.html) so that's a dead end unfortunately.  Can you enable mongoose debug mode with `require('mongoose').set('debug', true)` so we can see if mongoose is sending the right read preference to the driver? That would help bisect if this is an issue with mongoose or the mongodb driver.

**Comment by paton** [comment] 2016-11-13 02:13
Thanks for giving this a second shot.

I connected to our production replica set on my local machine and ran `read('sp')` queries with the "pickedServer" event + mongoose debug.

The queries printed with `secondaryPreferred` as expected (albeit the test environment was running a different version of node / npm compared to production where we were seeing no secondary reads).

In the local test conntected to remote production replica set, about 50% of the queries returned `RSPrimary` and the other 50% returned `RSSecondary` -- seemingly randomly for the same queries.

I'm no longer able to reproduce the issue of 100% queries routing to the primary with `read('sp')`, but still not sure what's causing the 50/50 split between primary and secondaries with `secondaryPreferred`.

@ChrisZieba might be able to clarify if he was able to reproduce the case where 100% of queries were routed to Primary to make sure the output of readPreference is with mongoose debug enabled.

Does `.set('debug', true)` output the raw queries that are sent to the Mongodb driver? If that's the case and we're seeing the correct readPreference, would that confirm it's not a mongoose issue?

**Comment by vkarpov15** [comment] 2016-11-15 02:50
@paton yeah that would mean mongoose is sending the correct read preference to the driver, which would mean it's likely a driver issue. You mentioned something about having a 4-node replica set? Why 4 and not 3?

**Comment by paton** [comment] 2016-11-15 04:40
Gotcha. Feel free to close this. I'll post again if we see the readPreference isn't being passed to the driver.

4-nodes was just temporary while upgrading the primary due to maxed out CPU.

Side note (maybe totally unrelated):  connection count on the secondaries is always ~50% the connection count of the primary, the middle server below.

Stranger, when we add a new secondary, the far right server, connection count is about the same as the primary... right until we update the connection string. Once it's in the connection string, connection count drops back down.

Haven't researched this much, but strange that connection count for the Primary and any unlisted secondaries is about equal to `app servers * poolSize (30)`, which secondaries are about half that. Maybe totally irrelevant but throwing it out there just in case :)

![image](https://cloud.githubusercontent.com/assets/609881/20292658/45afca7c-aaa4-11e6-982d-6ed0bee12132.png)

**Comment by Jeff-Lewis** [comment] 2016-11-15 15:39
BTW @paton, what are you using to monitor MongoDB on AWS?

**Comment by paton** [comment] 2016-11-15 18:39
Cloud Manager.

**Comment by vkarpov15** [comment] 2016-11-16 19:10
Yeah that's very strange, might explain why you're not always getting secondaries - if the mongodb driver can't maintain a steady connection to the secondaries that might explain your issues. What does your DNS setup look like - are these servers provisioned by cloud manager? Do the server's hostnames match their FQDN and their name in `rs.status()`?

**Comment by ChrisZieba** [comment] 2016-11-16 20:39
@vkarpov15 

> What does your DNS setup look like - are these servers provisioned by cloud manager? Do the server's hostnames match their FQDN and their name in `rs.status()`?

The servers are provisioned by cloud manager, and the hostnames do match. For example this is the output of `rs.status()`.

```
{
  "members" : [
    {
      "_id" : 6,
      "name" : "conan-2xl-0.company.0600.mongodbdns.com:27000",
    },
    {
      "_id" : 7,
      "name" : "conan-2xl-1.company.0600.mongodbdns.com:27000",
    },
    {
      "_id" : 8,
      "name" : "conan-xl-0.company.0600.mongodbdns.com:27000",
    },
    {
      "_id" : 9,
      "name" : "conan-xl-1.company.0600.mongodbdns.com:27000",
    },
    {
      "_id" : 10,
      "name" : "conan-arbiter-0.company.0600.mongodbdns.com:27000",
    }
  ],
}
```

The `hostname --fqdn` of the servers are

```
conan-2xl-0.company.0600.mongodbdns.com
conan-2xl-1.company.0600.mongodbdns.com
conan-xl-0.company.0600.mongodbdns.com
conan-xl-1.company.0600.mongodbdns.com
conan-arbiter-0.company.0600.mongodbdns.com
```

**Comment by paton** [comment] 2016-11-16 20:49
Perhaps we should try defining poolSize in the replSet or db connection object instead of just in the connection string.

**Comment by vkarpov15** [comment] 2016-11-17 22:52
@paton why would poolSize help?

@ChrisZieba I love the DNS names :) Can you try turning on mongoose debug mode, `require('mongoose').set('debug', true)` and capture the output? Would help figure out whether this is a mongoose bug or something wrong with the underlying driver.

**Comment by paton** [comment] 2016-11-18 02:26
> why would poolSize help?

Just thinking setting it on the db or replSet connection object might fix the low connection counts rather than setting it on the connection string. Just a shot in the dark, I'm not too familiar with how connection pool works internally, or if there's supposed to be 30 connections to each individual host, or only to the primary.

**Comment by vkarpov15** [comment] 2016-12-17 22:49
Closing as per email convo with @paton . Re-open if you have a similar issue.

**Closed by vkarpov15** 2016-12-17 22:49 UTC
Labels: needs clarification
