### ISSUE TITLE
Bug: mongoose.Types.ObjectId doesn't extend mongodb.ObjectId properly (TypeScript)

### ISSUE THREAD

**Issue by meness** [Automattic/mongoose#11654] opened 2022-04-10 06:42 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

```typescript
user: mongoose.Types.ObjectId;

user._id._id._id._id._id._id //...
user._id.toHexString() // error: toHexString() doesn't exist on _id
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Version 2.6.10 changed `ObjectId` and `Schema.index()` behavior.

```typescript
// before (worked)
MySchema.index({ key: 1, star: 1 }, { unique: true });

// today (not sure if it works)
MySchema.index({ key: 1, star: 1 }, { weights: { unique: true } });
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

**Mongoose:** 6.2.10

**Comment by meness** [comment] 2022-04-10 06:57
I temporarily rolled back to version 6.2.9 which everything works fine

**Comment by taxilian** [comment] 2022-04-11 18:46
I am unable to reproduce this; I used the following code:

```
  const oid = new Types.ObjectId();

  oid._id._id._id._id._id._id.toHexString();
  oid._id.toHexString();
```

This works just fine. Can you clarify? Possibly paste the exact mongoose string? What version of typescript are you using?

**Comment by meness** [comment] 2022-04-12 07:57
@taxilian I'm using TypeScript 4.6.3. Surprisingly, I tested the latest version once again today, and it worked! `_id._id._id._id._id._id` is still the same.

**Comment by Uzlopak** [comment] 2022-04-12 08:52
Nice. Closing

**Closed by Uzlopak** 2022-04-12 08:52 UTC
Labels: typescript

**Comment by taxilian** [comment] 2022-04-12 15:36
I have occasionally seen typescript do things like that, where things fail but then later (after some kind of cache expires?) it works. glad that was an easy fix ;-)

the _id recursion thing is from what I can tell expected.
