### ISSUE TITLE
[bug] Is mongoose populate object share the same object reference?

### ISSUE THREAD

**Issue by sj82516** [Automattic/mongoose#6334] opened 2018-04-12 04:19 UTC
**What is the current behavior?**
Here is my pseudo code
```
let p = await Person.find (
    pre_query, ....
  )
    .lean ()
    .populate ({
      path: 'event',
      select: 'uid name status startAt endAt -_id',
    })

console.log(p[0].event == p[1].event) would be true if the event is the same.
```

I want to make sure why populated object would share the same object reference ? 

**What is the expected behavior?**
It would be nice if very single populated object does not share the same object reference.

**Please mention your node.js, mongoose and MongoDB version.**
nodejs v 6.10 / mongoose v 4.12 / mongodb v 3.2.4

**Comment by sj82516** [comment] 2018-04-13 02:44
Thanks for your comments!   
It's my fault that I forget to add test code.  
However, in my case the populate item is the same. 
They are not two individual objects. 
Here is my test code modified from yours(thanks for helping out again). 
```
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const nameSchema = new Schema({
  name: String
});

const personSchema = new Schema({
  name: {
    type: Schema.Types.ObjectId,
    ref: 'Name'
  }
});

const Name = mongoose.model('Name', nameSchema);
const Person = mongoose.model('Person', personSchema);

const names = [];
const people = [];

let n = new Name({ name: 'Bill' });
names.push(n);
for(let i =0; i<2; i++)people.push(new Person({ name: n._id }));



async function run () {
  await conn.dropDatabase();
  await Name.create(names);
  await Person.create(people);
  let f = await Person.find({}).populate('name');
  console.log(f);
  console.log(f[0].name == f[1].name); // true
  return conn.close();
}

run();
```

**Comment by lineus** [comment] 2018-04-13 08:53
@sj82516 

In your version of the example, you are only storing one name document in the names collection.
The name properties of the different people have the same object reference because there is only one object to refer to.

Here is what get's stored in the db when you run your example:
```
issues: mongo --quiet test
> db.people.find().pretty()
{
        "_id" : ObjectId("5ad06cbf6230101a94afe0ee"),
        "name" : ObjectId("5ad06cbf6230101a94afe0ed"),
        "__v" : 0
}
{
        "_id" : ObjectId("5ad06cbf6230101a94afe0ef"),
        "name" : ObjectId("5ad06cbf6230101a94afe0ed"),
        "__v" : 0
}
> db.names.find().pretty()
{ "_id" : ObjectId("5ad06cbf6230101a94afe0ed"), "name" : "Bill", "__v" : 0 }
>
```

Can you elaborate on what effect this is having on your code?

**Comment by sj82516** [comment] 2018-04-13 09:00
Because I would loop through people and modify the event object, it would bother me if the same event share the same object reference.  
I thought db.people.find() would return pure json object.  

Thanks for your help! It save my days.  
If mongoose design in this way , I would change my code.  
Thanks a lot.
please mark solved.

**Comment by vkarpov15** [comment] 2018-04-19 16:35
This is a duplicate of #3258, see [my comments here](https://github.com/Automattic/mongoose/issues/3258#issuecomment-130314827)

**Closed by vkarpov15** 2018-04-19 16:35 UTC
