### ISSUE TITLE
Bug in applying defaults to missing properties when using projection.

### ISSUE THREAD

**Issue by PaulMaas** [Automattic/mongoose#3256] opened 2015-08-11 16:08 UTC
When using a projection on a find query, depending on how you specify the projection, defaults may or may not be set. It seems to be tied to how you specify exclusions. If your projection excludes properties using false:

    var projection = {property: false};

Then any property that isn't set in the database will not get its default value.
But if you specify the projection using 0, or as a string:

    var projection = {property: 0};
or

    var projection = '-property';

Default values _are_ populated.

It's worth noting that the projection is applied correctly either way you do it.

Steps to reproduce:

1. Create a schema with one or more properties.
2. Add some objects to the collection.
3. Now modify the schema and add a new property with a default.
4. Query the collection for an existing object that doesn't have a value for the new property. Exclude an existing property in the various ways described above.
5. Notice the default value for the new property is not set depending on how you specify your projection.

Btw: If you have multiple exclusions and even one of those exclusions uses 0 instead of false it 'magically' starts working...

Thanks,

Paul

**Comment by PaulMaas** [comment] 2015-08-11 16:46
These problems also occur if you use en 'empty' object or if you do something like use $slice in your projection:

    var projection =  {};

or

    var projection = {arrayProperty: {$slice: 40}}

Does not work (default values on undefined properties are not set), whereas

    var projection = '';

Does work (default values on undefined properties are set).

**Comment by vkarpov15** [comment] 2015-08-11 22:22
Please provide more thorough code examples, translating prose to code is an error prone process. Also, this looks like a duplicate of #3214 - does you think this is a different issue?

**Comment by PaulMaas** [comment] 2015-08-12 00:47
This is not a duplicate of #3214. They may be somewhat related though.

To reproduce, run this script:

    var mongoose = require('mongoose');
    var Schema = mongoose.Schema;
    
    // Create the schema.
    var PersonSchema = new Schema({
        name: String,
        lastName: String,
        dependents: [String]
    });
    
    var Person = mongoose.model('Person', PersonSchema, 'Person');
    
    // Create a person.
    var person = new Person({name: 'John', lastName: 'Doe', dependents: ['Jake', 'Jill', 'Jane']});
    
    person.save(function() {
        // Person John saved.
    });

Then run this script:

    var mongoose = require('mongoose');
    var Schema = mongoose.Schema;
    
    // Update the schema with a new property that has a default.
    var PersonSchema = new Schema({
        name: String,
        lastName: String,
        salary: {type: Number, default: 25000}
    });
    
    var Person = mongoose.model('Person', PersonSchema, 'Person');
    
    // Various ways of defining a projection to exclude lastName and/or dependents.
    var projections = [
        // These work as expected:
        '-lastName',
        {lastName: 0},
        null,
        '',
        // The rest doesn't work as expected:
        {lastName: false},
        {},
        // These two are really interesting:
        {dependents: 0, lastName: false},
        {dependents: false, lastName: 0},
        // For this one it doesn't matter if you slice like this or if you use Mongoose's slice() function.
        {dependents: {$slice: 1}}
    ];
    
    // The results of using the various ways of defining a projection. Sometimes salary has a value, sometimes it doesn't.
    // I would expect it to always have a value since it is not excluded in the projection. Note that the projection is always applied correctly.
    for (var i = 0; i < projections.length; i++) {
    
        (function(projection) {
            Person.findOne({name: 'John'}, projection, function(err, person) {
                console.log('Projection:', JSON.stringify(projection));
                console.log('Result:', person);
                console.log('Salary\'s value:', person.salary);
                console.log('');
            });
        })(projections[i]);
    
    }

Thanks for taking the time to look into this.

**Closed** 2015-08-24 16:33 UTC
