### ISSUE TITLE
Weird unpredictable behaviour

### ISSUE THREAD

**Issue by mindrunner** [Automattic/mongoose#8942] opened 2020-05-06 16:18 UTC
Not sure if this is the right place to post. I am a little bit out of ideas where this issue can origin from. I developed a Node/Express/Mongoose backend, with a quite small and straight forward Database part. There is only one model which looks more or less like this:
```
const mySchema = mongoose.Schema({
  url: { type: String, required: true },
  timestamp: { type: Date, default: null },
  o1: { type: Object, required: false },
  o2: { type: Object, required: false },
  o3: { type: Object, required: false },
  o4: { type: String, required: false },
  o5: { type: Object, required: false },
  o6: { type: Object, required: false },
  o7: { type: Object, required: false },
  o8: { type: Object, required: false },
  o9: { type: Object, required: false },
  o10: { type: Object, required: false },
  o11: { type: Object, required: false },
  o12:  {type: Object, required: false },
  o13: { type: Object, required: false },
});
```
The `create` endpoint gathers a quite big amount of different data and stores it in the `Object` properties:
```
  async insert (data) {
    let result = new mySchema(data);
    let options = {
      setDefaultsOnInsert: true,
      checkKeys: false,
    };
    await result.save(options);
    return result;
  }
}
```
To query one of this entries, I am using the mondodb internal `_id` property:
```
  async byId (id) {
    return await mySchema.findOne({ _id: id }).exec();
  }
```

I am developing the whole thing with webstorm, have a build pipeline which creates a docker container and on production, this is pretty much the setup:
```
version: '3.7'
services:
  backend:
    restart: always
    image: backend:latest
    volumes:
      - ./log:/app/log
    env_file:
      - .env-backend
    expose:
      - 3000
    depends_on:
      - mongodb

  frontend:
    restart: always
    image: frontend:latest
    expose:
      - 8080

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongodb:/data/db
```

Now comes the problem. It seems that mongodb is not reliably serving me the existing data. I have the following observations:

- Directly after inserting a document, a query `byId` returns null. Trying a second time it normally succeeds.
- There is another endpoint to return an array based on the `url` property:
```
  async byHostName (hostName) {
    return await mySchema.find({ url: hostName }).exec();
  }
```
Calling this multiple times in a row, sometimes returns different results. As far as my observations went, I usually have two alternating result arrays which are always the same if I repeat the procedure of calling the endpoint. If in this state, some of the `byId` requests return null, even though the id is 100% sure existing in the database.

I already refactored a lot of the code to make it more robust, stable, integrated proper logging, but I have no clue where the issue might be.

This only happens on the deployed production system. It never occurs locally and I could never reproduce it by connecting with my local dev-environment to the production database.

Also, I could not reproduce this behavior by spinning up the whole thing with docker-compose on my local system.

I previously assumed, there are some issues with indexed. I already wiped the whole database and cleanly imported the data into a fresh new one. No luck

I am lost. Calling out for help. Maybe someone has an idea.

**Comment by andreialecu** [comment] 2020-05-06 18:43
It's possible mongo isn't done writing before you run the query.

Maybe give these docs a read: https://docs.mongodb.com/manual/reference/write-concern/

**Comment by mindrunner** [comment] 2020-05-06 19:02
> Directly after inserting a document, a query `byId` returns null. Trying a second time it normally succeeds.

Yes, I assumes something like that, however this probably does not apply to:

> Calling this multiple times in a row, sometimes returns different results. As far as my observations went, I usually have two alternating result arrays which are always the same if I repeat the procedure of calling the endpoint. If in this state, some of the `byId` requests return null, even though the id is 100% sure existing in the database.

This definitely happens to old entries as well

**Comment by andreialecu** [comment] 2020-05-06 19:12
Usually in such instances the problem is in the app's logic somewhere. Make sure you disable [all http caching in express](https://www.npmjs.com/package/nocache).

What do you mean by directly after inserting? What's the time frame? Is it always the first query, or is it time based?

Do you run your production db in a docker container as well? Maybe try MongoDB Atlas, as it comes with replica set support and various tools to inspect the server for issues.

**Comment by mindrunner** [comment] 2020-05-06 19:21
> Usually in such instances the problem is in the app's logic somewhere. Make sure you disable all http caching in express.

cool, will try that

> Do you run your production db in a docker container as well?

Yes, it is running on the same host in docker as well (see my compose fille)

> Maybe try MongoDB Atlas, as it comes with replica set support and various tools to inspect the server for issues.

Checking with the customer if that is an option


> What do you mean by directly after inserting? What's the time frame? Is it always the first query, or is it time based?

Yeah, it is seconds more or less. Also not really an issue. The other problem is the big one.

**Comment by andreialecu** [comment] 2020-05-06 19:25
> > Maybe try MongoDB Atlas, as it comes with replica set support and various tools to inspect the server for issues.

> Checking with the customer if that is an option

They have a free tier, and if not, an M10 cluster is about $70-80 per month including point in time backups. I have nothing but good words for it. :)

**Comment by mindrunner** [comment] 2020-05-06 19:51
That is unfortunately exeeding the budget at the moment. I think my problem is with cursors:

> mongodb_1   | 2020-05-06T19:47:50.005+0000 I  COMMAND  [conn23] command xxx.xxx command: find { find: "xxx", filter: { _id: ObjectId('5e8ced53380e1c001cd4660d') }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, lsid: { id: UUID("cb36dc01-660c-4db5-8349-830cb553f5ac") }, $db: "xxx" } planSummary: IDHACK keysExamined:0 docsExamined:0 cursorExhausted:1 numYields:0 nreturned:0 reslen:119 locks:{ ReplicationStateTransition: { acquireCount: { w: 1 } }, Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } }, Mutex: { acquireCount: { r: 1 } } } storage:{} protocol:op_msg 146ms


This is one of the queries by id, which returns `null`.

**Comment by vkarpov15** [comment] 2020-05-13 22:09
How are you defining your models and how are you connecting to MongoDB? One possibility is that you have some mixup where you have multiple models with the same name pointing to different collections.

**Comment by mindrunner** [comment] 2020-05-17 20:18
> How are you defining your models?

There is only one model:
```
import mongoose from 'mongoose';

const mySchema = mongoose.Schema({
  url: { type: String, required: true },
  timestamp: { type: Date, default: null },
  o1: { type: Object, required: false },
  o2: { type: Object, required: false },
  o3: { type: Object, required: false },
  o4: { type: String, required: false },
  o5: { type: Object, required: false },
  o6: { type: Object, required: false },
  o7: { type: Object, required: false },
  o8: { type: Object, required: false },
  o9: { type: Object, required: false },
  o10: { type: Object, required: false },
  o11: { type: Object, required: false },
  o12:  {type: Object, required: false },
  o13: { type: Object, required: false },
});

const my = mongoose.model('my', mySchemaSchema);

module.exports = my;
```

> how are you connecting to MongoDB?

```
import mongoose from 'mongoose';

async function connect() {
  const connectionString = process.env.MONGO_URI;
  if(true === process.env.MONGO_DEBUG) mongoose.set('debug', true);
  mongoose.set('useUnifiedTopology', true);
  mongoose.set('useNewUrlParser', true);
  mongoose.set('useFindAndModify', false);
  mongoose.set('useCreateIndex', true)
  await mongoose.connect(connectionString);
  return connectionString;
}
module.exports.connect = connect;
```

> One possibility is that you have some mixup where you have multiple models with the same name pointing to different collections.

I doubt that this is the case here, but I am still quite sure I am overlooking something super obvious here...

**Comment by vkarpov15** [comment] 2020-05-25 23:29
It's highly unlikely this issue has anything to do with cursors, and also unlikely to be a Mongoose issue. Realistically we won't be able to debug this without a reproducible code sample, so I'm going to close this for now.

**Closed by vkarpov15** 2020-05-25 23:29 UTC
Labels: needs clarification
