### ISSUE TITLE
"Plug-ins" links go to http://plugins.mongoosejs.io/  (dead)

### ISSUE THREAD

**Issue by lexishanson** [Automattic/mongoose#6111] opened 2018-02-08 19:11 UTC
When clicking links to the plug-in site, it directs to http://plugins.mongoosejs.io/ instead of http://plugins.mongoosejs.com/.

Should the latter URL replace the current one, or should there be a re-route?

I've found the dead link in the following places:
* "Discover plug-ins" button of mongoosejs.com homepage.
* Readme.MD
* Contributing.MD

**Comment by varunjayaraman** [comment] 2018-02-11 21:41
thanks for reporting

**Comment by vkarpov15** [comment] 2018-02-12 20:53
Duplicate of a bunch of issues, we're working on bringing plugins.mongoosejs.io back

**Closed by vkarpov15** 2018-02-12 20:53 UTC
Labels: docs
