### ISSUE TITLE
[TypeError: Cannot assign to read only property 'checkKeys' of true]

### ISSUE THREAD

**Issue by BrandonCopley** [Automattic/mongoose#3293] opened 2015-08-21 22:38 UTC
I am trying to save new objects to the database and regularly receiving this error: [TypeError: Cannot assign to read only property 'checkKeys' of true]

This appears to be related to mongoose?

**Comment by BrandonCopley** [comment] 2015-08-21 22:51
I've narrowed this down to something with strict:true turned on causing issues, turning this off fixes some issues, but not all.

**Comment by vkarpov15** [comment] 2015-08-24 18:15
Can you provide some code samples, preferably one that reproduces this issue?

**Comment by gregthegeek** [comment] 2015-08-24 20:59
We're getting that too. It started with mongoose 4.1.2, but I'm not exactly sure where or how yet.

**Comment by BrandonCopley** [comment] 2015-08-24 21:45
What version works for you? I'm dropping out version down and trying to
find the one we could use and have it still work.

On Monday, August 24, 2015, Greg Carlin <notifications@github.com> wrote:

> We're getting that too. It started with mongoose 4.1.2, but I'm not
> exactly sure where or how yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3293#issuecomment-134378756>
> .
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by gregthegeek** [comment] 2015-08-24 21:46
I found version 4.1.1 to work but versions 4.1.2 and 4.1.3 to fail.

**Comment by gregthegeek** [comment] 2015-08-24 22:01
I think this is the same as #3286.

**Comment by vkarpov15** [comment] 2015-08-28 18:10
Hmm I'm having trouble reproducing this with any version of mongoose. Can you confirm which bluebird version you're using?

```javascript
var mongoose  = require('mongoose');
var Promise   = require('bluebird');
var Schema    = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh3286');

var schema = new Schema({ name: String });

schema.statics.createAsync = function() {
  return Promise.promisify(this.create).apply(this, arguments);
};

var MyModel = mongoose.model('test', schema);

MyModel.createAsync({ name: 'abc' }).then(function(v) {
  console.log('done');
  process.exit(0);
});
```

Seems to work fine, no exceptions

**Comment by napa3um** [comment] 2015-08-29 10:09
```javascript
require('es6-promise').polyfill();
var mongoose = require('mongoose');

var PlaceSchema = new mongoose.Schema({
	title: { type: String, required: true },
	geo: { type: [Number], required: true, index: '2dsphere', unique: true }
}, { safe: true });

var PlaceModel = mongoose.model('Place', PlaceSchema, 'Place');

mongoose.connect(MONGO_URI, function(err){
	if(err)
		return console.log(err);

	var data = [{title: 'title1', geo: [50,50]}, {title: 'title2', geo: [51,51]}];
	var i = 0;
	(function rowIter(){
		if(i >= data.length)
			return;
		
		(function(i, row){
			new Promise(function(resolve, reject){
				PlaceModel.create({
					title: row.title,
					geo: row.geo
				}, function(err, doc){
					if(err)
						return reject(err);
					return resolve();
				});
			})
			.then(rowIter)
			.catch(function(err){
				console.log(err); // [TypeError: Cannot assign to read only property 'checkKeys' of true]
			});
		})(i, data[i]);
		
		i++;
	})();
});
```

**Comment by vkarpov15** [comment] 2015-08-31 13:15
See discussion on #3286, it looks like this is already fixed in master. Re-open if this is still an issue when 4.1.4 is released today.

**Closed by vkarpov15** 2015-08-31 13:15 UTC
Labels: can't reproduce
