### ISSUE TITLE
modifiedpaths are not returning as expected when we use .set() with nested paths as an object in v5.12.5 vs v6.x.x

### ISSUE THREAD

**Issue by sakethyerra** [Automattic/mongoose#14024] opened 2023-11-01 09:31 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.1

### Node.js version

14.18.1

### MongoDB server version

4.4

### Description

Hi, the following code behaves differently in both versions v5.12.5 and v6.x.x.
Note: modified paths are not returning as expected when we use .set() with nested paths as an object.

```
var mongoose = require('mongoose')
let Schema = mongoose.Schema
var eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    field1: { type: String },
    field2: { type: String },
    jsonField: {
        name: { type: String }
    }
  }
})
var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { field1: 'test', jsonField: { name: 'test3' }} })
  eventObj.save(function (err, eventObj) {
    var newObject = eventObj.toObject()
    newObject.__stateBeforeSuspension = { field1: '12', jsonField: { name: 'test4' }}
    eventObj.set(newObject)
    var modifiedPaths = eventObj.modifiedPaths()
    console.log(modifiedPaths)
   
  })
}
run();
```
Output with v5.12.5 :
```
[
  '__stateBeforeSuspension',
  '__stateBeforeSuspension.field1',
  '__stateBeforeSuspension.jsonField',
  '__stateBeforeSuspension.jsonField.name'
]
```

Output with v6.12.1 :
```
[ '__stateBeforeSuspension', '__stateBeforeSuspension.jsonField' ]
```

The modified paths are returning differently in both versions.
Note: We have raised a different issue similar to .set() one. for more info please refer to https://github.com/Automattic/mongoose/issues/14022

### Steps to Reproduce

Added the full-fledged details on how to reproduce the issue in the description with a code snippet.

**Comment by sakethyerra** [comment] 2023-11-01 10:00
We observed another thing non-modified paths are showing as modified paths for more info please refer to the below code.

```
var mongoose = require('mongoose')
let Schema = mongoose.Schema
var eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    test: { type: String },
    test2: { type: String },
    test3: {
        name: { type: String }
    }
  }
})
var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { test: 'test', test3: { name: 'test3' }} })
  eventObj.save(function (err, eventObj) {
    var newObject =  { test: 'test', test3: { name: 'test4' }}
    eventObj.set('__stateBeforeSuspension', newObject)
    var modifiedPaths = eventObj.modifiedPaths()
    console.log(modifiedPaths)
  })
}
run();
```
Output with v5.12.5 :
```
[ '__stateBeforeSuspension' ]
```

Output with v6.12.1 :
```
[
  '__stateBeforeSuspension',
  '__stateBeforeSuspension.test3',
  '__stateBeforeSuspension.test3.name'
]
```

**Comment by sakethyerra** [comment] 2023-11-03 06:46
@vkarpov15 Can you please update the status of this tracker

**Comment by IslandRhythms** [comment] 2023-11-03 15:40
confirmed for both

```javascript
const mongoose = require('mongoose');
const { Schema } = mongoose;

// for function run()
/*
const eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    field1: { type: String },
    field2: { type: String },
    jsonField: {
        name: { type: String }
    }
  }
});*/


// for function test
const eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    field1: { type: String },
    field2: { type: String },
    jsonField: {
        name: { type: String },
        name1: { type: String }
    }
  }
})
const  Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();
  const  eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { field1: 'test', jsonField: { name: 'test3' }} })
  eventObj.save(function (err, eventObj) {
    var newObject = eventObj.toObject()
    newObject.__stateBeforeSuspension = { field1: '12', jsonField: { name: 'test4' }}
    eventObj.set(newObject)
    var modifiedPaths = eventObj.modifiedPaths()
    console.log(modifiedPaths)
   
  })
}
// run();

async function test() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const eventObj = new Event({ name: "event object", __stateBeforeSuspension: { field1: "test", jsonField: { name: "test3" }} })
  eventObj.save(function (err, eventObj) {
    var newObject =  { field1: "test", jsonField: { name: "test3", name1: "test4"} }
    eventObj.set('__stateBeforeSuspension', newObject)
    var modifiedPaths = eventObj.modifiedPaths()
    console.log(modifiedPaths)
  })
}

test();
```

**Comment by vkarpov15** [comment] 2023-11-05 20:40
For your first post (the following code snippet), this is expected behavior. In Mongoose 6, `modifiedPaths()` doesn't include children of already modified paths by default. Use `modifiedPaths({ includeChildren: true })` to get the Mongoose 5 behavior in Mongoose 6.

```
var mongoose = require('mongoose')
let Schema = mongoose.Schema
var eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    field1: { type: String },
    field2: { type: String },
    jsonField: {
        name: { type: String }
    }
  }
})
var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { field1: 'test', jsonField: { name: 'test3' }} })
  eventObj.save(function (err, eventObj) {
    var newObject = eventObj.toObject()
    newObject.__stateBeforeSuspension = { field1: '12', jsonField: { name: 'test4' }}
    eventObj.set(newObject)
    var modifiedPaths = eventObj.modifiedPaths()
    console.log(modifiedPaths)
   
  })
}
run();
```

Re: your 2nd post, the fact that `name` and `name1` were showing up in `modifiedPaths()` is a bug. I fixed in #14053 with https://github.com/Automattic/mongoose/pull/14053/commits/4bd592703f9f4930fff5f3270ea36a998cbc2690.

**Comment by sakethyerra** [comment] 2023-11-07 06:26
For the first use case, it's working as expected but we found that we are using ```isDirectModified()``` and it's not returning the child-modified paths. please find the below code snippet for more information.
Note: In our case, we are mostly relying on ```isDirectModified()``` to check in the database docs which will impact us a lot.

```
var mongoose = require('mongoose')
let Schema = mongoose.Schema
var eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    field1: { type: String },
    field2: { type: String },
    jsonField: {
        name: { type: String }
    }
  }
})
var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { field1: 'test', jsonField: { name: 'test3' }} })
  eventObj.save(function (err, eventObj) {
    var newObject = eventObj.toObject()
    newObject.__stateBeforeSuspension = { field1: '12', jsonField: { name: 'test4' }}
    eventObj.set(newObject)
    var modifiedPaths = eventObj.modifiedPaths({ includeChildren: true })
    console.log(modifiedPaths)
    modifiedPaths.forEach(function (modifiedPath) {
      console.log('modifiedPath: ', modifiedPath)
      if (eventObj.isDirectModified(modifiedPath)) {
        console.log('direct modified path: ', modifiedPath)
      }})
  })
}
run();
```

Output with v5.12.5 :

```
[
  '__stateBeforeSuspension',
  '__stateBeforeSuspension.field1',
  '__stateBeforeSuspension.jsonField',
  '__stateBeforeSuspension.jsonField.name'
]
modifiedPath:  __stateBeforeSuspension
modifiedPath:  __stateBeforeSuspension.field1
direct modified path:  __stateBeforeSuspension.field1
modifiedPath:  __stateBeforeSuspension.jsonField
modifiedPath:  __stateBeforeSuspension.jsonField.name
direct modified path:  __stateBeforeSuspension.jsonField.name
```

Output with v6.12.1 :
```
[
  '__stateBeforeSuspension',
  '__stateBeforeSuspension.jsonField',
  '__stateBeforeSuspension.jsonField.name',
  '__stateBeforeSuspension.field1'
]
modifiedPath:  __stateBeforeSuspension
direct modified path:  __stateBeforeSuspension
modifiedPath:  __stateBeforeSuspension.jsonField
direct modified path:  __stateBeforeSuspension.jsonField
modifiedPath:  __stateBeforeSuspension.jsonField.name
modifiedPath:  __stateBeforeSuspension.field1
```

If we see the above outputs we are not getting the as-expected values for the "direct modified path" log
Note: Let me know if we need to raise a new issue for it. Can you please add it to the 6.12.3

**Comment by vkarpov15** [comment] 2023-11-07 17:43
I think the `isDirectModified()` bit is expected behavior. The spirit of `isDirectModified()` is that it should return `true` for fields that you have explicitly set (not 100% true in 6.x, we've made some improvements on that front in subsequent versions). So given that you're calling `eventObj.set(newObject)`, the only direct modified path should be `__stateBeforeSuspension`, because `eventObj.set(newObject)` becomes `eventObj.set('name', 'event object'); eventObj.set('__stateBeforeSuspension', ...)` and `__stateBeforeSuspension` is the only path that is set to a different value. If you want `__stateBeforeSuspension.jsonField.name` to show up as the direct modified path, you should do `eventObj.set('__stateBeforeSuspension.jsonField.name', 'test 4')` or something similar.

**Comment by sakethyerra** [comment] 2023-11-08 10:11
We are using ```.set()``` in many places of our code and it is hard for us to modify it in all the paces. We are using ```isDirectModified()``` for auditing(To get the specific modified field) the docs to show those details to the end users. Is there any way to achieve the older behaviour?

**Comment by vkarpov15** [comment] 2023-11-08 22:12
Does using `isModified()` instead of `isDirectModified()` work for you?

**Comment by sakethyerra** [comment] 2023-11-09 08:47
@vkarpov15, No it doesn't work as  ```isModified()``` will come true for all the values coming in ```modifiedPaths()```. To avoid this issue we are using the ```isDirectModified()``` to get the exact fields that were modified but in 6.x.x we are not getting the exact child fields that are modified. Is there a way to achieve the same behaviour of the 5.12.5v?

**Comment by vkarpov15** [comment] 2023-11-11 00:29
What is your definition of the exact fields that were modified? Do you have a more exact definition or just the 5.x behavior?

**Comment by sakethyerra** [comment] 2023-11-11 07:02
As mentioned in this comment https://github.com/Automattic/mongoose/issues/14024#issuecomment-1797892862 we are updating the '__stateBeforeSuspension.jsonField.name' and '__stateBeforeSuspension.field1' fields those fields are not coming as the ```isDirectModified()``` in 6.X

**Comment by vbharath2809** [comment] 2023-11-11 15:09
Just adding to what @sakethyerra  mentioned, 

@vkarpov15
 5.X behavior will be enough i.e we want  isDirectModified to return true for   `__stateBeforeSuspension.jsonField.name` and `__stateBeforeSuspension.field1 ` but not for `__stateBeforeSuspension` and `__stateBeforeSuspension.jsonField`

**Comment by akhilkcg** [comment] 2023-11-15 06:43
Hi @vkarpov15 post fix (6.12.3), it seems that .set() behaviour is still undesirable if the nested object has more than 1 field.
behaviour is different in 5.12.5 vs 6.12.3

code
```
const superheroSchema = new Schema({
  name: { type: String },
  meta: {
    nickname: { type: String },
    car: { type: String }
  }
})
const Superhero = mongoose.model('Superhero', superheroSchema)

  async function test4() {
    await connectToDB();
    let superhero = new Superhero({ name: 'Bruce', meta: { nickname: 'Batman', car: 'Batmobile' } });
    const doc1 = await superhero.save()
    console.log('Superhero first val', doc1)
    const newDocObj = {
      name: 'Bruce',
      meta: {
        nickname: 'Dark Knight'
      }
    }
    doc1.set(newDocObj)
    const doc2 = await doc1.save()
    console.log('Superhero second val', doc2)
    await mongoose.disconnect();
  }

```

6.12.3 output 
```
Superhero first val {
  name: 'Bruce',
  meta: { nickname: 'Batman', car: 'Batmobile' },
  _id: new ObjectId("65546208efed9e98ba3e09a7"),
  atr: 2023-11-15T06:15:36.918Z,
  __v: 0
}
Superhero second val {
  name: 'Bruce',
  meta: { nickname: 'Dark Knight' }, // <-- car field is not there anymore
  _id: new ObjectId("65546208efed9e98ba3e09a7"),
  atr: 2023-11-15T06:15:36.951Z,
  __v: 0
}
```

5.12.5 output (desired output)
```
Superhero first val {
  _id: 65546187632cc03364a08dbc,
  name: 'Bruce',
  meta: { nickname: 'Batman', car: 'Batmobile' },
  atr: 2023-11-15T06:13:27.784Z,
  __v: 0
}
Superhero second val {
  _id: 65546187632cc03364a08dbc,
  name: 'Bruce',
  meta: { nickname: 'Dark Knight', car: 'Batmobile' },
  atr: 2023-11-15T06:13:27.817Z,
  __v: 0
}
```
Workaround in 6.12.3
```
    // doc1.set() works as expected if :-
    // 1. I send doc1.set(newDocObj, undefined, { merge: true)
    // 2. also works if I send empty object in 2nd parameter doc1.set(newDocObj, {})
```

there have been code changes in `mongoose/lib/document.js` which I think might be cause of the change in behavior

5.12.5
```
const someCondition = typeof path[key] === 'object' &&
                            !utils.isNativeObject(path[key]) &&
                            !utils.isMongooseType(path[key]) &&
                            path[key] != null &&
                            pathtype !== 'virtual' &&
                            pathtype !== 'real' &&
                            pathtype !== 'adhocOrUndefined' &&
                            !(this.$__path(pathName) instanceof MixedSchema) &&
                            !(this.$__schema.paths[pathName] &&
                            this.$__schema.paths[pathName].options &&
                            this.$__schema.paths[pathName].options.ref);

// this condition is true if pathtype is 'nested'
      if (someCondition) {
        this.$__.$setCalled.add(prefix + key);
        this.$set(path[key], prefix + key, constructing, options); <-- path[key] is first, followed by prefix + key
      } else if (strict) {
...
```
6.12.3
```
const pathName = prefix ? prefix + key : key;
const valForKey = path[key];
...
if (utils.isNonBuiltinObject(valForKey) && pathtype === 'nested') {
        this.$set(pathName, valForKey, constructing, Object.assign({}, options, { _skipMarkModified: true })); <-- prefix + key is first, followed by path[key]
        $applyDefaultsToNested(this.$get(pathName), pathName, this);
        continue;
      } else if (strict) {
...
```


Requesting you to please help investigate this issue, thanks!

**Comment by sakethyerra** [comment] 2023-11-16 12:18
@vkarpov15, Any update on this

**Comment by heyfirst** [comment] 2023-11-29 14:04
Hi, I'm confirming that the `isModified` is difference for 5.x and 6.x and it's really hard to make a migration.

**Comment by heyfirst** [comment] 2023-12-16 01:14
Hi @vkarpov15, our problem is that when we push the item to the array of subdocuments, it's marked as modified the whole array. in v5, it will marked modified only the one that has been added.

you can see the code below which's from `test/document.modified.test.js` and I modified to match with our case,

<img width="1188" alt="Screenshot 2566-12-16 at 03 09 42" src="https://github.com/Automattic/mongoose/assets/4945174/f319e10a-9a99-47f1-bcce-6a5a2921e6c2">

We have 2 schema, let's say `Post` and `Comment` and then you can see in the line 192, I pushed the new comments to array, Turns out the first one (index:0) has been marked as modified and our whole validators and middlewares which rely on `isModified` integration test are failed. 

This issue made us really difficult to move to Mongoose v6. I have checked the code on isModified itself and seems like it has a slightly changes from v5 and v6 as v6 seems checking the parents modified path as well. I might be wrong and hope you could also guide me to implement the proper way to use isModified here.

**Comment by heyfirst** [comment] 2023-12-28 09:52
@vkarpov15 I will create the reproduce script for you in first week of January 🫡 hope it will help you easily reproduce the issue.

**Comment by vkarpov15** [comment] 2024-01-01 15:59
@heyfirst thanks for the repro, we will look into it and see if we can fix

**Comment by vkarpov15** [comment] 2024-01-01 21:03
@heyfirst are you able to try out the code in #14213 and see if that helps?

**Comment by heyfirst** [comment] 2024-01-02 07:44
Sure! let me try them by this evening! Thanks so much for promptly act on it 🙇🏻

**Closed** 2024-01-12 14:32 UTC
Labels: confirmed-bug
