### ISSUE TITLE
mongoose ver 6 deleteMany() removes ALL documents when search options contains field not from schema

### ISSUE THREAD

**Issue by Vadim725** [Automattic/mongoose#12389] opened 2022-09-03 11:16 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.5.4

### Node.js version

12.22.12

### MongoDB server version

4.4

### Description

There is a collection with documents, there is it schema.
At the same time, not all fields of documents are described in the schema, 
i.e. some documents have fields not described in the schema.
We call model.deleteMany({x:<some_value>})  where "x" not in schema.
This call **removes all documents in the collection.**

This behavior was not in version 5

### Steps to Reproduce

Simple nodejs program, file _index.js_
```
const mongoose = require('mongoose');

mongoose.connect('mongodb://127.0.0.1:27017/mongoose_test', {});

// User model
const User = mongoose.model('User', {
	name: { type: String },
	age: { type: Number }
	// type: { type: Number }
});

User.deleteMany({}, function (err, result) { // clear collection
  if (err) return console.log(err)
  User.collection.insertMany([  // with .collection - through mongo driver, without mongoose validation
    { name: 'Vadim', age: 30 },
    { name: 'Dmitry', age: 27 },
    { name: 'Nikita', age: 20, type: 2 },
    { name: 'Mark', age: 45 },
    { name: 'Serge', age: 40, type: 2 }],
    function (err, result) {
      if (err) return console.log(err)
      console.log(result)
      // now want to delete documents with type==2
      User.deleteMany({ type: 2 }, function (err, result) {
        if (err) return console.log(err)
        console.log(result)
      })
    }
  )
}
)
```
file _package.js_:
```
{
  "name": "mongoose-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "mongoose": "^6.5.4"
  }
}
```
result:
```
C:\Bin\node-v12.22.12-win-x64\node.exe .\index.js
{acknowledged: true, insertedCount: 5, insertedIds: {…}}
{acknowledged: true, deletedCount: 5}

```
same program in mongoose 5.13.15 produce
```
C:\Bin\node-v12.22.12-win-x64\node.exe .\index.js
(node:17288) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:17288) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
{result: {…}, ops: Array(5), insertedCount: 5, insertedIds: {…}}
insertedCount: 5
insertedIds: {0: ObjectID, 1: ObjectID, 2: ObjectID, 3: ObjectID, 4: ObjectID}
ops: (5) [{…}, {…}, {…}, {…}, {…}]
result: {ok: 1, n: 5}
__proto__: Object
{n: 2, ok: 1, deletedCount: 2}
deletedCount: 2
n: 2
ok: 1
__proto__: Object
```

### Expected Behavior

Expected behavior - exactly as in version 5 - only documents with {x:<some_value>} should be deleted.

**Comment by Uzlopak** [comment] 2022-09-03 12:30
i guess strictQuery striked again

**Comment by Vadim725** [comment] 2022-09-04 10:19
@Uzlopak Thanks for strictQuery, I'm not that familiar with mongoose.
but two things
1st - only _strict=false_ gives me the correct result, _strictQuery=true/false_ does not affect
2nd - this must be specified in [Migrating from 5.x to 6.x](https://mongoosejs.com/docs/migrating_to_6.html)

**Comment by hasezoey** [comment] 2022-09-05 10:29
Looks like a Duplicate of #4251

**Comment by Vadim725** [comment] 2022-09-05 11:03
@hasezoey thanks, after more careful study of the problems, I also found other issue - [#10946](https://github.com/Automattic/mongoose/issues/10946)
BTW - despite of _strictQuery_ - it is very dangerous default in v6

**Comment by IslandRhythms** [comment] 2022-09-07 19:28
https://github.com/Automattic/mongoose/issues/11861

**Comment by chris-gaona** [comment] 2022-09-26 22:15
Is there any fix for this issue in the works? We've ran into a similar issue, but with discriminators. Our discriminators have a few different fields and attempting to use `deleteMany` filtering for a field that only exists on a few, but not all, of the discriminators deletes all the docs in the collection. This seems like a pretty critical issue.

**Comment by hasezoey** [comment] 2022-09-26 22:36
> Is there any fix for this issue in the works? We've ran into a similar issue

because this would be a breaking change, it has been put off to the next major version, see #11861

the manual fix would be to use [`strictQuery: false`](https://mongoosejs.com/docs/guide.html#strictQuery) as either a schema-option, or on a per-query level

**Comment by vkarpov15** [comment] 2022-10-05 15:52
We're planning on changing this behavior back in 7.0.0 with #11861. We agree that this change was a mistake on Mongoose's part, and we're very sorry for any trouble this issue caused you. I'm going to close this issue, follow #11861 for updates.

**Closed by vkarpov15** 2022-10-05 15:52 UTC
Labels: acknowledged
