### ISSUE TITLE
useFindAndModify: true - wrong error message

### ISSUE THREAD

**Issue by TrejGun** [Automattic/mongoose#7644] opened 2019-03-26 08:48 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
node test.js
(node:36160) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
All Assertions Pass.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
#!/usr/bin/env node
"use strict";

const assert = require("assert");
const mongoose = require("mongoose");
mongoose.set("useFindAndModify", true);
const {Schema, connection} = mongoose;
const DB = "6880";
const URI = `mongodb://localhost:27017/${DB}`;
const OPTS = {family: 4, useNewUrlParser: true};

const schema = new Schema({
  name: String,
});

const Test = mongoose.model("test", schema);

const test = new Test({name: "test1"});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc);
  const cond = {};
  const update = {name: "test2"};
  const options = {new: true};
  const updated = await Test.findOneAndUpdate(cond, update, options); // <- here
  assert.strictEqual(updated.name, "test2");
  console.log("All Assertions Pass.");
  await connection.close();
}

run();
```

**What is the expected behavior?**
should print nothing I guess

because it offers to replace `findOneAndUpdate` with `findOneAndUpdate` which makes no sense to me

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 8.15.1
mongodb 4.0.6
mongoose: 5.4.16 / 5.4.20

**Comment by 720degreeLotus** [comment] 2019-03-26 14:47
You are setting "useFindAndModify" to true.
As the message tells you, this is deprecated.
Set it to false and the message should disappear i guess?

**Comment by TrejGun** [comment] 2019-03-27 07:02
@720degreeLotus 
man, this message is broken. it says `replace X by X`.

**Comment by 720degreeLotus** [comment] 2019-03-27 07:17
@TrejGun The message says:
`findAndModify` is deprecated, use `findOneAndUpdate, findOneAndReplace or findOneAndDelete` instead.

The word `findAndModify` is different from `findOneAndUpdate`, `findOneAndReplace` or `findOneAndDelete`

**Comment by TrejGun** [comment] 2019-03-28 07:37
look at the code example, i did it special for you

```js
const updated = await Test.findOneAndUpdate(cond, update, options); // <- here
```

i'm using `findOneAndUpdate` from `findAndModify` group which also includes methods like `findByIdAndUpdate` which is actually deprecated.

so `findByIdAndUpdate` should print deprecation warning and `findOneAndUpdate` should not. 

is it clear now?

**Comment by TrejGun** [comment] 2019-03-28 07:43
@720 
ok i see now you are sugessting to user `findOneAndUpdate` from native driver instead of mongose polyfill but this error message is missleading because i have no idea about actual implementations and thus I read it like `replace X by X`

**Comment by 720degreeLotus** [comment] 2019-03-28 10:02
I don't know what to say anymore.
If you have a message that tells you `Don't use A, instead use B, C or D` and you read/understand it as `Don't use A, use A, A or A instead` then this is really bad, no offense here.

Also, deprecation-warnings are no alerts, that something is not working properly.
If you read a deprecation-warning, regardless of the coding language or library, you should read the documentation about why it is deprecated and how to use the new preferred way. Then you should try to rewrite your code, so that, when the deprecated feature is removed from the library at some point in time, your project still works fine.
The only thing that "could" be done is to, within the deprecation-warning, link to the documentation about it. But would just be for the lazy people that cannot search for the documentatio or more information on google, imho.

**Comment by TrejGun** [comment] 2019-03-28 11:02
@720degreeLotus open your eyes, man. I have created that repro scripts special for you.
read it line by line until you see
```js
const updated = await Test.findOneAndUpdate(cond, update, options); // <- here
```
`findOneAndUpdate` you see?! it not `findAndModify`

Not compare to error message
```
DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
```
can you see my point now?

**Comment by 720degreeLotus** [comment] 2019-03-28 13:15
So... what think you are talking about now is, that you are writing Test.**findOneAndUpdate** but since the warning mentions not **findOneAndUpdate** but instead **findAndModify** you get confused... Can you tell us if fthat's what you mean?
This still doesn't explain why you assume `replace x by x` but it would explain what you are talking about and why you are confused.
See, you are setting `mongoose.set("useFindAndModify", true);` in your code.
So you are telling mongoose to **use FindAndModify**.
And since `FindAndModify` is deprecated and should no longer be used (or better "set to true"), you see this deprecation-message.

If this is not what you are talking about, i'm really sorry but then i think you need to explain more in detail, like i did in this post here, what exactly confuses you. We may not talk about the same "source of confusion", so you then need to describe it in more detail (not about the code but about the core of your confusion).
I hope we can talk about this mannered so we can clear all confusion on both side :)

**Comment by TrejGun** [comment] 2019-03-29 08:58
i dont have time to explain so obvious things. let @vkarpov15 take a look at this issue.

**Comment by 720degreeLotus** [comment] 2019-03-29 11:03
@TrejGun Calm down. You are here because you are confused by something you don't fully understand, so we should help you and see, if this is a bug or a misunderstanding on user-side.
If you `don't have time to explain`, then please close this issue and move forward with your project.

To summarize:

> What is the expected behavior?
should print nothing I guess

The expected behaviour in this case is to print a deprecation-warning **if** mongoose is set to use `findAndModify` under the hood.
Which you do:
```js
mongoose.set("useFindAndModify", true);
```

> because it offers to replace findOneAndUpdate with findOneAndUpdate

As mentioned multiple times now, this is plain incorrect.
The deprecation-message exactly states, that `findAndModify` is deprecated and you should use `findOneAndUpdate` or one of the other 2 methods mentioned.

> man, this message is broken. it says replace X by X

Same as above, the message is not stating this anywhere.

>const updated = await Test.findOneAndUpdate(cond, update, options); // <- here
findOneAndUpdate you see?! it is not findAndModify

Also, as already mentioned, what methods you are using in your code does not matter.
You are using `findOneAndUpdate`, i get that, but this has **nothing** to do with the error-message.

I cannot state this more clear:
You are **FORCING** mongoose to use a old/deprecated way of handling things under the hood by setting
```js
mongoose.set("useFindAndModify", true);
```
. Mongoose let's you do this but warns you that this method is deprecated and should be avoided in the future.
If you are talking about something completely different, you must explain yourself. If you don't have time for this, then i don't know what we are talking about here.

**Comment by TrejGun** [comment] 2019-03-29 12:25
i have explicitly set
```js
mongoose.set("useFindAndModify", true);
```
just for you to ask no questions) but this is default behaviour, DEFAULT
so when I updated mongoose to lates version first I saw was this deprecation warning.

as a user I dont know (and dont want to know) how it works under the hood. 
so it looks broken to me when message says `replace X by X` especiall it makes me confused when i cant find `findAndModify`  in my code. because as I said dont know how it works under the hood.

so you might refer to new flag in the error message or better give a link to https://mongoosejs.com/docs/deprecations.html#-findandmodify- in the error message and not make user to dig into the problem.

**Comment by 720degreeLotus** [comment] 2019-03-29 12:52
Ok i now think we are talking about the same thing.
And partly i agree with you, that it's slightly irritating that this is "default" behaviour.
But i am 99% sure that the reason for this beeing "default" is, that it doesn't break backwards-compatibility.
If your project does exist for some time and you update mongoose, you don't want to get unexpected crashed and non-working code, just because now the internal "findAndModify" breaks some things your project relies on (or your mongodb-version).
So to not break those projects, the internal flag is, by default, set to use the "old mechanism".
But to push coders to use the "new mechanic" at some point, a deprecation-warning is given.
I also agree that putting a url into that warning, that points to the documentation, would be better maybe. But then i again, personally, would argue that coders should somewhat read changelogs when/before updating things and so they would stumple upon this change.
Also, it really (REALLY) only takes a few couples of seconds to find the documentation... And this should be no problem for a coder.
YES, you don't need to understand what's happening under the hood but also YES, you should read some rough details about those changes (and how they may affect your project) if such a deprecation-warning is given.
Many times such a deprecation-warning does not exist because a coder just felt like deleting some function, it's more likely that something in a core-technology has changed (like the mongodb itself) which might also affekt your project in different locations.
So... a little bit reading into changelogs and documentation must be accepted by coders, in my personal opinion.

Also, i can understand that `findAndModify` and `findOneAndUpdate` may sound similar and can be mixed up so that they are interpreted as "replace X by X". But in the end, those 2 method-names are just not the same, even when similar.

I now feel like we're on the same page, which is great :)
Please tell me if you understand my guess for this setting beeing defaulted to "true" and if there is anything else we should discuss :)

**Comment by TrejGun** [comment] 2019-03-29 13:39
it was good time when I was working closely with mongoose 3 years ago. I have created lots of issues about `populate` functinality and even made some PR's. things has changed since that time. whoever hired you to read and answer issues, has made this project looks like corporate shit, where the end user can do nothing because he meets a wall of text, which basically says "fuck off". fuck off you too.

**Comment by 720degreeLotus** [comment] 2019-03-29 14:27
? i am in no way associated to mongoose, i am just a user with some experience.
I think, based on your last sentence, you constantly misinterpret what i am writing but there is no point in discussion if you end a sentence like this.

**Comment by vkarpov15** [comment] 2019-04-06 18:36
I'm really not liking where this issue has gone. @720degreeLotus  I appreciate your help but please be more concise and empathetic with your future responses. This issue should have just been resolved with `.set('useFindAndModify', false)`, not a wall of text. If you continue to post non-committal non-answers that implicitly blame the end user, you will do more harm than good for this project.

And @TrejGun you know I appreciate your numerous contributions to Mongoose over the years and I apologize that this issue has been such a bad experience, but do not ever say "fuck you" on this GitHub repo again. This is an intellectual forum, please conduct yourself accordingly.

For posterity, the solution is `.set('useFindAndModify', false)` instead of `true`

**Comment by TrejGun** [comment] 2019-04-07 09:32
@vkarpov15 sorry for being rude.

as i said i have explicitly set
```
.set('useFindAndModify', true)
```
to indicate i'm using default behavior
https://mongoosejs.com/docs/deprecations.html#-findandmodify-

as for me deprecation message should explain 
```
you are using mongoose wrapper over `findAndModify` engine, you can make your code faster by using native implementation by setting useFindAndModify to `true`, you can read more [here].
```

**Comment by 720degreeLotus** [comment] 2019-04-07 10:47
@TrejGun i'm also sorry. I asked a friend of mine, who is native english (i'm not) to read our discussion and she told me that there were misunderstandings on both sides, most likely caused by language barrier.

It was **never** my intent to be condescending or anything like that.

> you are using mongoose wrapper over `findAndModify` engine, you can make your code faster by using native implementation by setting useFindAndModify to `true`, you can read more [here]

I fully agree that such a deprecation message is more way understandable :)

**Comment by vkarpov15** [comment] 2019-04-07 12:45
@720degreeLotus it's ok, thanks for clarifying.

Unfortunately I can't change that deprecation warning because it comes from the underlying mongodb driver. I'll see if there's a good way to suppress this warning for Mongoose so we can print a better warning

**Comment by vkarpov15** [comment] 2019-04-22 14:28
Going to close this for now. I added an additional deprecation warning that should help clarify this, but I can't suppress the `findAndModify` deprecation warning reliably without this PR: https://github.com/mongodb/node-mongodb-native/pull/1980

**Closed by vkarpov15** 2019-04-22 14:28 UTC
Labels: developer-experience
