### ISSUE TITLE
Discriminated model with custom collection

### ISSUE THREAD

**Issue by justrudd** [Automattic/mongoose#7547] opened 2019-02-20 21:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug I believe.
**What is the current behavior?**
I have a base model that I want to store in multiple collections. And that base model has several discriminated models. But the discriminated model uses the collection of the FIRST model registered (since collection name isn't part of the cache key).

**If the current behavior is a bug, please provide the steps to reproduce.**
```JavaScript
  const options = { discriminatorKey: "kind" };

  // the base event...
  const eventSchema = new mongoose.Schema({ time: Date }, options);
  const eventModelUser1 = mongoose.model("Event", eventSchema, "user1_events");
  const eventModelUser2 = mongoose.model("Event", eventSchema, "user2_events");

  // outputs user1_events
  console.log(eventModelUser1.collection.name);

  // outputs user2_events
  console.log(eventModelUser2.collection.name);

  // Our ClickEvent for user1
  const clickEventUser1 = eventModelUser1.discriminator(
    "ClickEvent",
    new mongoose.Schema({ url: String }, options),
  );

  // even though they are different model instances, the cached model
  // internally is the same because collection isn't part of the key. So
  // if we call model.discriminate again, it will throw.
  const clickEventUser2 = eventModelUser2.discriminators["ClickEvent"];

  // outputs user1_events as expected
  console.log(clickEventUser1.collection.name);

  // outputs user1_events and not user2_events
  console.log(clickEventUser2.collection.name);
```
**What is the expected behavior?**
I would expect `clickEventUser2.collection.name` to be `user2_events` not the first model that was cached internally.

**Please mention your node.js, mongoose and MongoDB version.**
NodeJS: 10.15.1
Mongoose: 5.4.13
MongoDB: 3.6 and 4.0

**Comment by justrudd** [comment] 2019-02-20 21:27
We got around this by using unique model names.

**Comment by mhombach** [comment] 2019-02-21 13:28
Hey :)
Glad you solved your problem (i think you can close this ussue here then).
Just for he record: Discriminating a model does not mean to store the same model in different collections.
It's meant for storing multiple **different models** in the **same collection**.

Example would be models called "**Tiger**, **Cat**, **Bear**", which all contain "**numberOfFeet**, **numberOfEyes**" plus each have additional attributes on their own and all should get saved into the collection "**Animals**" :)

**Comment by justrudd** [comment] 2019-02-21 15:39
Thanks for the reply @mhombach. I understand what discriminated models are for. I worked with Hibernate for a decade. I've built some very complicated model hierarchies using discriminated types all stored in different databases using the same model names.

But I think this is breaking the principle of least surprise. If I do this...
```JavaScript
  // the base event...
  const eventSchema = new mongoose.Schema({ time: Date }, options);
  const eventModelUser1 = mongoose.model("Event", eventSchema, "user1_events");
  const eventModelUser2 = mongoose.model("Event", eventSchema, "user2_events");

  const e1 = new eventModelUser1({time: new Date()});
  await e1.save();

  const e2 = new eventModelUser2({time: new Date()});
  await e2.save();
```
`e1` is stored as an `Event` in `user1_events`. `e2` is stored as an `Event` in `user2_events`. So as a user, if I call `discriminator` on `eventModelUser2` I would expect that whatever model is returned would write to `user2_events`. The fact that it is writing to a different collection is surprising.

Looking through the code, the first model with a name that hasn't been seen is cached. If a second model with the same name but a different collection comes in, it isn't cached but it doesn't throw `OverwrittenModelError`. It seems odd that discriminated models follow a different set of rules.

If you're saying that this is the expected behavior for discriminated models, OK. I'll close the issue. But this feels wrong.

**Comment by mhombach** [comment] 2019-02-21 16:01
Ok, i slightly misunderstood your intention but i think i got it now.
Can you check this script and tell me:
A: If this is what you intended to do and 
B: If this works as intended?

```js
var mongoose = require('mongoose');
const connectionString = `mongodb://localhost:27017/test_db`;

async function test() {
    await mongoose.connect(connectionString, {
        useNewUrlParser: true,
        useCreateIndex: true
    });
    await mongoose.connection.dropDatabase();
    const eventSchema = new mongoose.Schema({ time: Date });
    const eventModelUser1 = mongoose.model("Event", eventSchema, "user1_events");
    const eventModelUser2 = mongoose.model("Event", eventSchema, "user2_events");
  
    const DiscA = eventModelUser1.discriminator("DiscA", new mongoose.Schema({ url: String }));
    const DiscB = eventModelUser2.discriminator("DiscB", new mongoose.Schema({ url: String }));
  
    const e1 = new eventModelUser1({time: new Date()});
    await e1.save();
  
    const e2 = new eventModelUser2({time: new Date()});
    await e2.save();
  
    const discA = new DiscA({url: "url1"});
    await discA.save();
  
    const discB = new DiscB({url: "url2"});
    await discB.save();
    console.log("all saved");
  }
  
  test();
```

The output on my computer is:
Collection "user1_events" contains 2 documents:
```js
{ _id: "5c6ec9ee98a2eb2f800ed211",
time: "2019-02-21T15:55:26.161+00:00",
__v: 0 }
// AND
{ _id : "5c6ec9ee98a2eb2f800ed213",
__t: "DiscA",
url: "url1",
__v: 0 }
```

Collection "user2_events" contains 2 documents:
```js
{ _id: "5c6ec9ee98a2eb2f800ed212",
time: "2019-02-21T15:55:26.198+00:00",
__v: 0 }
// AND
{ _id : "5c6ec9ee98a2eb2f800ed214",
__t: "DiscB",
url: "url2",
__v: 0 }
```

Is this what you expect to happen?

**Comment by justrudd** [comment] 2019-02-27 21:28
Hey @mhombach. Sorry for the delay in getting back to you. This does work. But that's because you're giving each discriminated model a unique name `DiscA` and `DiscB`. If you were to just call it `Disc` (as I suspect most people would), it doest not work.

**Closed** 2019-03-07 18:56 UTC
Labels: has repro script
