### ISSUE TITLE
readPreference with secondaryPreferred not read only from Secondaries node while 2 secondaries still alive.

### ISSUE THREAD

**Issue by huytran0605** [Automattic/mongoose#5353] opened 2017-06-13 07:16 UTC
I have 3 mongo instance run on AWS,
1 Primary, 2 Secondary.
Currently, we want all read operator comes only from Secondaries node.
So we are using config options object when create connect mongoose
``` 
options = {
    db: {
       readPreference: 'secondaryPreferred',
       native_parser: true
    },
    replset: {
        strategy: 'ping',
        auto_reconnect: false,
    }
};
mongoose.connect(databaseUrl, options);
```
Problem: With that setting, read operator come from both `Primary` And `Secondary` while 2 Secondaries node still alive.(??!)
When we use readPreference: 'secondary', it's working as we expect. All read operator come only from Secondaries.
Please help me to explain this because with the mongo docs metion
`secondaryPreferred: In most situations, operations read from secondary members but if no secondary members are available, operations read from the primary.`
Btw, I saw some same issues  but all of them still not have a clear solution. :(

We are using:
1. mongoose: v4.9.5
2. Mongo server: v3.2
3. Node: v5.12.0

**Comment by huytran0605** [comment] 2017-06-13 10:11
One more thing, I have a test
When i increase `priority` of Primary node to higher than 2 secondaries, for e.g: 600
All read operator will come only from 2 secondaries with setting `readPreference: 'secondaryPreferred'`
But as the doc mention, `priority` only use for election secondary become primary.
https://docs.mongodb.com/manual/tutorial/adjust-replica-set-member-priority/
Could anyone who have more experience please help me explain it? 
It make me very confuse :(

**Comment by vkarpov15** [comment] 2017-06-16 20:56
Can you try upgrading to latest mongoose? Also, how are you determining that reads are happening on the primary?

**Comment by huytran0605** [comment] 2017-06-19 02:37
I try with upgrade latest mongoose.
And i'm using mongostat to check which node are using.

**Comment by kevinadi** [comment] 2017-06-22 04:57
My quick testing using the `secondaryPreferred` setting resulted in these numbers from `mongostat` (`localhost:27017` being the primary):

```
           host insert query update delete getmore command ...
localhost:27017     *0   445     *0     *0       0     3|0  ...
localhost:27018     *0   527     *0     *0       0     3|0  ...
localhost:27019     *0   914     *0     *0       0     3|0  ...
```

However doing the same test using the Python driver & the Java driver resulted in numbers more like these:

```
           host insert query update delete getmore command ...
localhost:27017     *0    *0     *0     *0       0     2|0  ...
localhost:27018     *0   870     *0     *0       0     2|0  ...
localhost:27019     *0   852     *0     *0       0     2|0  ...
```

I confirmed that this behaviour originated from the node driver, which the Python driver and the Java driver doesn't seem to exhibit.

I have submitted [NODE-1049](https://jira.mongodb.org/browse/NODE-1049) to seek clarification for this issue. Since this is not a mongoose issue, I propose to close this issue and watch the related NODE ticket in JIRA instead.

**Comment by huytran0605** [comment] 2017-06-22 05:31
@kevinadi Could you please tried to increase `priority`  of Primary node like my comment above and show the report? 
btw, I know `priority` use for voting secondary node become Primary

https://docs.mongodb.com/manual/tutorial/adjust-replica-set-member-priority/

**Comment by kevinadi** [comment] 2017-06-22 05:55
@huytran0605 I don't see any difference when changing the priority. All reads still go to all nodes. Regardless, I still believe this is an issue with the node driver and not mongoose.

**Comment by huytran0605** [comment] 2017-06-22 06:33
@kevinadi thanks for your idea. Did you test with another driver (python, java,..)?
Another guy in my team also tested with Python driver and they have the same problem... :(

**Comment by kevinadi** [comment] 2017-06-22 06:38
@huytran0605 no, as I mentioned before, I didn't see the same behaviour with the Python (pymongo 3.3.0) & Java (driver 3.4.1). Full description of what I saw are in [NODE-1049](https://jira.mongodb.org/browse/NODE-1049). I think it's best to move this discussion to the associated NODE ticket and not in this mongoose issue, where it can be properly handled by the driver engineers.

**Comment by huytran0605** [comment] 2017-06-26 06:28
@kevinadi FYI, They've already fixed that issue in here https://github.com/christkv/mongodb-core/pull/194/files

**Closed** 2017-07-03 10:39 UTC
Labels: needs repro script
