### ISSUE TITLE
Full Text Search not consistent with Mongo Shell Query Results

### ISSUE THREAD

**Issue by altninja** [Automattic/mongoose#5433] opened 2017-07-03 05:59 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Full text search returns null in Mongoose but returns document in MongoDB Shell with exact same query
example:
**Document:** 
```
{
    "inputs" : {
        "primary" : "like", 
        "exact" : [
            "do you like ", 
            "what do you think of ", 
            "are you a fan of "
        ]
    }
}
```
**Mongoose Query:**
`Collection.findOne({$text: {$search: 'do you like PHP?'}})`
Result: returns null
**MongoDB Query:**
`db.collection.findOne({$text: {$search: 'do you like PHP?'}})`
Result: returns Document
**Index:**
```
{
    'inputs.primary' : "text",
    'inputs.exact' : "text"
},
{
     weights: {
       'inputs.primary' : 20,
       'inputs.exact' : 10
    }
}
```
**If the current behavior is a bug, please provide the steps to reproduce.**

See Above ^^

**What is the expected behavior?**
That it returns the document same as in MongoDB Shell 

**Please mention your node.js, mongoose and MongoDB version.**
nodejs 8.1.0 mongodb 3.4.4 mongoose 4.11.0

**Comment by varunjayaraman** [comment] 2017-07-08 19:32
I'm not able to reproduce this, both work for me:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5433`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${error}\n${error.stack}`);
  });


function exec() {
  return co(function* () {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${GITHUB_ISSUE}`);
    const schema = new mongoose.Schema({
      inputs: {
        primary: String,
        exact: [String]
      }
    });

    schema.path('inputs.primary').index({ text: true });
    schema.path('inputs.exact').index({ text: true });
    const Model = db.model('Model', schema);

    yield Model.remove({});

    yield Model.ensureIndexes();

    yield Model.create({
      inputs: {
        primary: 'like',
        exact: [
          'do you like ',
          'what do you think of ',
          'are you a fan of '
        ]
      }
    });

    // doc found thru mongoose
    const docThruMongoose = yield Model.findOne({
      $text: { $search: 'do you like PHP?' }
    });

    console.log(docThruMongoose); // retrieves doc

    const docThruDriver = yield db.collections['models'].findOne({
      $text: { $search: 'do you like PHP?' }
    });

    console.log(docThruDriver); // retrieves doc
  });
}
```

**Comment by altninja** [comment] 2017-07-11 05:55
Thanks for looking into it, results have very been inconsistent but I guess its not to do with the ORM but something else

**Comment by varunjayaraman** [comment] 2017-07-15 16:50
thanks, i'll close this for now. Please feel free to open another issue if you think it is indeed a problem with mongoose

**Closed by varunjayaraman** 2017-07-15 16:50 UTC
Labels: can't reproduce
