### ISSUE TITLE
CastError: Cast to [undefined] failed for value "["user"]" at path "roles"

### ISSUE THREAD

**Issue by AdamBCo** [Automattic/mongoose#8058] opened 2019-08-10 00:58 UTC
I am currently receiving the following error when running a Mongoose query in a test environment utilizing supertest and jest.

    CastError: Cast to [undefined] failed for value "["user"]" at path "roles"

I am using Mongoose 5.6.9 with the code below:

### The Query

    const _id = req.params._id

	User.findOne({
		_id,
		roles: 'admin'
	})
		.exec()
		.then(user => {
			if (!user) {
				return next(boom.badRequest("No User"))
			}
			res.status(200).json(user)
		})
		.catch(err => next(boom.badRequest(err)))

### The User Model

    const mongoose = require('mongoose')

    const Roles = ['user', 'admin', 'gallery', 'artist', 'appraiser', 'beta', 'super', 'contractor', 'auction_house']

    const schema = mongoose.Schema(
	    {
    		name: {
    			type: String,
    			trim: true
    		},
    		roles: {
    	        type: [{
    	            type: String,
    	            enum: Roles
    	        }],
    	        default: ['user']
    	    }
    
	    },
    	{
    		timestamps: {
    			createdAt: 'created_at',
    			updatedAt: 'updated_at'
    		}
    	}
    )
    
    module.exports = mongoose.model('User', schema)

Can someone please help me figure out what's going on?

Thank you

**Comment by esetnik** [comment] 2019-08-10 02:36
Maybe this is related to #8053

**Comment by AdamBCo** [comment] 2019-08-10 15:35
@esetnik Thanks for pointing me to that issue. Unfortunately it showcases the creation of a User object; whereas I am simply trying to find one. I'm not sure where the case issue is occurring.

**Comment by vkarpov15** [comment] 2019-08-11 15:59
The below script executes without error for me on 5.6.9, please modify the below script to demonstrate your issue.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh8058`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();
  
  const schema = mongoose.Schema(
    { 
      name: { 
        type: String,
        trim: true
      },
      roles: {
        type: [{
          type: String,
          enum: ['admin', 'super-admin']
        }],
        default: ['user']
      }
    });

  const User = mongoose.model('User', schema);

  await User.create({ name: 'test', roles: ['admin'] });
  const doc = await User.findOne({ roles: 'admin' });
  console.log(doc);
}
```

**Comment by vkarpov15** [comment] 2019-08-18 00:34
This looks to be a duplicate of #8053. It's a bug in Jest that we'll work around.

I strongly recommend moving off of Jest. [Jest is an anti-pattern](https://mongoosejs.com/docs/jest.html) because it does so much monkeypatching that it creates a distinct JavaScript environment that isn't quite Node.js or a browser. Code that works in Jest may not work in Node.js and vice versa.

**Closed** 2019-08-18 00:34 UTC

**Comment by realeibo** [comment] 2019-08-29 09:18
I had the same problem - I updated to 5.6.11 and it fixes it.
