### ISSUE TITLE
4.7.1 => 4.7.2 : MongoError connection timed out 

### ISSUE THREAD

**Issue by dcolens** [Automattic/mongoose#4789] opened 2016-12-09 09:53 UTC
When testing mongoose@4.7.2 / mongodb@2.2.12, I get:
> MongoError: connection 2 to XXXXXX timed out
>     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:29:11)
>     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:186:20)
>     at Socket.g (events.js:286:16)
>     at emitNone (events.js:86:13)
>     at Socket.emit (events.js:185:7)
>     at Socket._onTimeout (net.js:333:8)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)' } 'connection 2 to XXXXXX timed out

this does not happen with mongoose@4.7.1 / mongodb@2.2.11.

More details:
   - query: aggregate with allowDiskUse(true).read('secondaryPreferred').cursor()
   - timing: the error happens about 35s after sending the query (before first results are received)
   - node version: v6.3.0
   - npm version: 3.10.9
   - connect options: 
```json
{
 "socketOptions": {
	"socketTimeoutMS": 240000,
	"keepAlive": 10000,
	"connectTimeoutMS" : 30000
} 
```
   - query:
```javascript
[
	{ $match: {
			_id: { $lt: oid },
			signature: { $exists: true }
		}
	},
	{ $group: { 
			_id: { myid: '$myid', signature: '$signature' },
			count: { $sum:  1 },
			myid: { $first: '$myid' },
			docs: { $push: { _id: '$_id', name: '$name' } }
		}
	},
	{ $match: {
			count: { $gt : 1 }
		}
	}
]
```

**Comment by silentjohnny** [comment] 2016-12-22 19:05
I'm experiencing the same problem, mongoose@4.7.4, mongodb@2.2.16

- setting socketTimeoutMS to higher values or 0 makes no difference
- setting connectTimeoutMS to higher values or 0 makes no difference
- no "close" or "reconnected" event is fired, only a "timeout", which results in a Mongoose error in the callback

Rolling back to mongoose@4.7.1 / mongodb@2.2.11 solves the issue, i.e., does not cause timeouts

From mongodb@2.2.11 to 2.2.12 the timeout event listener changed from "once" to "on", maybe this has something to do with it?

Or should we post this as an issue in the mongodb native driver?

**Comment by k14hatake** [comment] 2016-12-23 00:19
@silentjohnny Getting the same issue with mongoose@4.7.4

**Comment by vkarpov15** [comment] 2016-12-24 22:23
I'd post an issue in the mongodb native driver, mongoose doesn't do much in the way of initial connection.

**Comment by vkarpov15** [comment] 2016-12-24 22:24
[Here's the mongodb driver jira](https://jira.mongodb.org/browse/NODE)

**Comment by tomgrossman** [comment] 2017-01-03 08:55
Weird. I am experiencing the same issue but with mongoose@4.7.3 and higher which are using mongodb@2.2.16.
With mongoose@4.7.2 and mongodb@2.2.12 **it does work!**.
My aggregate query is without any options so I don't know, maybe that's the difference between me and the original issue @dcolens .

Anyone opened an issue to the native driver? so I can follow it...
Right now I'm staying with mongoose@4.7.3

**Comment by silentjohnny** [comment] 2017-01-03 22:48
mongodb@2.2.17 updated to mongodb-core@2.1.3 which includes a fix for monitoring operations timing out and generating a timeout event on running operations [@1284917](https://github.com/christkv/mongodb-core/commit/1284917978d54274b445d38b2ec381b5a41a1dbc)

Soon Mongoose updates to mongodb@2.2.19, I will give it a try.

**Comment by steve-p-com** [comment] 2017-01-05 11:08
Same issue for me, and I'm not even sure if it's just long running aggregates that are timing out, or if it's random and not a real timeout at all. It seems like it times out almost straight away sometimes, but other times it runs for 30 seconds or so. In this particular case, I have four aggregate.execs running at once.

Reverting to mongoose@4.7.2 and mongodb@2.2.12 fixes it so I'm doing that for now.

**Comment by varunjayaraman** [comment] 2017-01-06 04:49
This should hopefully be fixed in the next release since mongoose 4.7.7 uses mongodb@2.2.19. Either way, this isn't really a mongoose issue like @vkarpov15 said but more to do with mongodb. I'm going to close this for now, but if you still get the same issue after the next release, you should open up a ticket or a PR on mongodb's end.

**Comment by steve-p-com** [comment] 2017-01-18 12:09
I think there may be more to this issue than meets the eye. I've had to revert to 4.4.20 to completely stop these aggregate timeouts occurring under all circumstances. 4.7.x and 4.6.x both had bogus very quick timeouts under some circumstances of multiple concurrent executions. I skipped 4.5 and went straight back to a known good version (4.4.20) which we are using in production, and that has completely solved the problem, but TBH I'm still mystified by what is happening. I'm sorry I don't have any further data to add, but I'm not sure if it is solely a problem with the version of the native mongodb driver that mongoose is using, or if there's more than one contributory factor at work.

**Comment by flosky** [comment] 2017-01-28 19:13
Having the same problem with mongoose@4.7.9 and mongodb@2.2.22. Timeouts are really weird. This one is pretty short (around 5s) and very reproducible but other queries take longer than 5s and do not time out

**Comment by steve-p-com** [comment] 2017-01-30 10:36
I'm certain the timeouts are often bogus. In one scenario I was looking at I started four simultaneous aggregate.exec operations which take around 30 seconds. One timed out in 8 seconds, one timed out in 20 seconds, but the other two completed normally in 30 seconds. Repeating caused a different timeout order, but always a similar result. I suspect timeouts are incorrectly being set on the wrong connections, or are not being removed when an operation completes so that they fire unexpectedly on a subsequent exec. Something like that anyway. Unfortunately I've no time at the moment to pursue it.

**Comment by silentjohnny** [comment] 2017-01-30 11:57
mongoose@4.7.7 seems to have solved the timeouts for me. @steve-p-com like you are suggesting, the timeouts in 4.7.2 were indeed bogus and caused error events being emitted on the wrong connection, this was solved by mongodb-core@2.1.6 and so mongoose@4.7.7 should work fine in your case. Did you run a test with that version?

Haven't tested 4.7.9 or 4.8.0 yet, maybe mongodb@2.2.22 introduced a regression, which would explain the issue @flosky is experiencing. Does that timeout also happen on mongoose@4.7.7?

**Comment by steve-p-com** [comment] 2017-02-01 13:09
I have retested with 4.8.1 today, and have not had any issues with unexpected timeouts. I removed all npm caches and yarn caches first, then zapped node_modules, then reinstalled everything. So far, so good.

**Comment by thenitai** [comment] 2017-02-10 20:18
Happening for me with 4.8.1 as well. I went back many versions on Mongoose and MongoDB and get the issue all the time.

**Comment by varunjayaraman** [comment] 2017-02-10 22:06
@thenitai do you have more context / can we see how you set up your mongoDB connection?

**Comment by thenitai** [comment] 2017-02-12 15:21
@varunjayaraman I found that our domain error code is catching the error and thus restarts our app. However, the issue is still there.

Not quite sure what you need to see in the set up of our connection. Do you mean the connection options? If so, they are:

```
var dbOptions = {
			db: { native_parser: true },
			server: {
				auto_reconnect: true,
				socketOptions: {
					keepAlive: 1, 
					connectTimeoutMS: 300000,
					socketTimeoutMS: 300000
				}
			}
		};
```

**Comment by gitawego** [comment] 2017-02-21 15:15
I've same problem as well. even with latest version v4.8.4

**Comment by adrienbaron** [comment] 2017-03-01 09:00
I'm seeing this issue too on my server with Mongoose `4.7.7`, MongoDB `3.4.1` and Node `4.7.2`. When memory usage is high on my server, timeouts seems to occur randomly in series:

```
CosWebsite-27 MongoError: connection 42 to 127.0.0.1:27017 timed out
CosWebsite-27     at Function.MongoError.create (/home/cos/cos/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
CosWebsite-27     at Socket.<anonymous> (/home/cos/cos/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:186:20)
CosWebsite-27     at Socket.g (events.js:260:16)
CosWebsite-27     at emitNone (events.js:67:13)
CosWebsite-27     at Socket.emit (events.js:166:7)
CosWebsite-27     at Socket.wrapped (/home/cos/cos/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
CosWebsite-27     at Socket.wrappedEmit [as emit] (/home/cos/cos/node_modules/newrelic/lib/transaction/tracer/index.js:220:46)
CosWebsite-27     at Socket._onTimeout (net.js:333:8)
CosWebsite-27     at _runOnTimeout (timers.js:537:11)
CosWebsite-27     at _makeTimerTimeout (timers.js:528:3)
CosWebsite-27     at Timer.unrefTimeout (timers.js:597:5)
... times 6
CosWebsite-27 GET /clans/compas-c-r-98QP9J2G/members 500 10569.300 ms - 9893
CosWebsite-27 GET /players/1000-99JQVQ9VU 500 12388.484 ms - 9849
CosWebsite-27 GET /players/R0YUPPRR/profile 500 8204.622 ms - 9857
CosWebsite-27 GET /players/UG8YJUJY/profile 500 4622.819 ms - 9857
CosWebsite-27 GET /clans/next-state-P8RYGQYV 500 11526.859 ms - 9861
CosWebsite-27 GET /clans/YY2CCUVV 500 6755.380 ms - 9817
```

As you can see the requests none of the request lasted more than 12s. My mongoose connector is set up this way:
```js
const mongoDB = {
	uri: "mongodb://127.0.0.1:27017/XXX",
	options: {
		host: '127.0.0.1',
		port: '27017',
		database: "XXX",
		compression: false,
		server: {
			poolSize: 5,
			auto_reconnect: true,
			socketOptions: {
				socketTimeoutMS: 0,
				connectTimeoutMS: 0
			}
		},
		promiseLibrary: Promise
	}
};
```

Any idea what could be going wrong?

**Comment by kekedaine** [comment] 2017-03-16 19:10
@adrienbaron Me too!!!
someone please help me.

**Comment by flosky** [comment] 2017-03-19 17:19
Has someone files a bug report to the developers of the native mongo driver?

**Comment by artofspeed** [comment] 2017-03-22 11:33
does this issue still exist in 4.9.1?

**Comment by hellivan** [comment] 2017-03-29 08:03
Yes, issue still exists in 4.9.1....

**Comment by glazkoman** [comment] 2017-04-06 02:01
Had same issue today with the latest mongoose version, after downgraded back to 4.7.1 and everything is working perfect!

**Comment by flosky** [comment] 2017-04-06 10:05
The issue has been unresolved for some time now.
**What should we do to fix this?**
At some point I would like to update to the recent version but I can only do that when this has been resolved.

**Comment by centigrade-thomas-becker** [comment] 2017-04-19 07:23
I updated Mongoose from 4.4.17 to 4.7.9 about a month ago. Since then a daily cronjob has errored three times now, always with a mongo connect timeout error.

I'll switch to Mongoose 4.7.1 and see if this helps

**Comment by adrienbaron** [comment] 2017-04-19 07:36
@centigrade-thomas-becker I had the same issue for more than a month in production, I switched back to 4.7.1 yesterday, no more issues!

**Comment by zqWu** [comment] 2017-04-27 02:15
same problem occur @ 4.7.7

**Comment by centigrade-thomas-becker** [comment] 2017-05-03 08:22
With Mongo 4.7.1 there are fewer problems than with 4.7.9, but I still get the occasional error message when saving to the MongoDB:

```
2017-04-30 03:09:32: Error: connection timeout
    at .<anonymous> (/var/www/someproject/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:168:17)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at listener (/var/www/someproject/node_modules/mongodb/lib/db.js:1791:14)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/var/www/someproject/node_modules/mongodb/lib/server.js:270:14)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/var/www/someproject/node_modules/mongodb-core/lib/topologies/server.js:322:12)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/var/www/someproject/node_modules/mongodb-core/lib/connection/pool.js:271:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/var/www/someproject/node_modules/mongodb-core/lib/connection/connection.js:175:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:333:8)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

The error occurs on a Linux VM running Ubuntu 15.04

**Comment by xeroxoid** [comment] 2017-05-03 14:09
Same here with:

```
├─┬ mongoose@4.9.5
│ ├─┬ mongodb@2.2.25
│ │ ├── mongodb-core@2.1.9
```
mongo version @ 3.2.11

on AWS EC2.

Any update/workaround? Would ```keepAlive: true``` have any positive effect?

**Comment by ht2** [comment] 2017-05-10 13:54
Not sure if this helps anyone, but in our case we noticed that we were passing in our timeout params (`socketTimeoutMS` etc) in through `options.server`. This was _wrong_! We are using a replica set and as such our options should have been:

In our case the application actually needed the ability to connect to either a replica or normal server, so we did:

```
const serverOptions = {
  poolSize: 100,
  socketOptions: {
    socketTimeoutMS: 60000
  }
};

const createConnection = () => {
  return mongoose.createConnection(dbpath, {
    promiseLibrary: Promise,
    server: serverOptions,
    replSet: serverOptions
  });
};
```

Hope that helps someone!

**Comment by RemeAjayi** [comment] 2017-06-01 12:14
Hello Everyone,
I am using mlab to host my database. I get this error
Mongo DB connectionerror: {[MongoError: connection 0 to ds155841.mlab.com:xxxxx timed out'}

**Comment by cyrilchapon** [comment] 2017-06-06 07:42
@RemeAjayi I think this has nothing to do with this post.
You should try / create another one after digging into issue.

**Comment by doboy** [comment] 2017-06-14 20:58
Not sure if this helps anyone, but in my case I had to set a specific timeout on my query

So rather than, `stream = Order.find(query).stream()` I use `stream = Order.find(query, {}, {timeout: false}).stream()`

```
$ npm list | grep mongo
│ └─┬ mongoose@4.7.2
│   ├─┬ mongodb@2.2.12
│   │ ├─┬ mongodb-core@2.0.14
```

**Comment by cyrilchapon** [comment] 2017-06-15 08:28
Is there any viable solution ?

**Comment by cyrilchapon** [comment] 2017-06-19 12:41
In case it helps anyone, I experienced this issue when parallelizing 2 brutal `find()` queries (using Promise pattern).

Turning

```
Promise.all([
  col1.find({longQuery: true}),
  col2.find({longQuery: true})
])
.spread(function(result1, result2) {
  //stuff
});
```

into

```
col1.find({longQuery: true})
.then(function(result1) {
  return Promise.all([
    result1,
    col2.find({longQuery: true})
  ])
})
.spread(function(result1, result2) {
  //stuff
});
```

Made it work

**Comment by gustvao** [comment] 2017-08-01 22:58
@cyrilchapon thought it was working for me but your sequential approach did not solve my issue :/

it is intermittent.. sometimes it works, sometimes it times out..

**Comment by cyrilchapon** [comment] 2017-09-20 07:28
Why this silent close ?

**Comment by centigrade-thomas-becker** [comment] 2017-09-20 07:34
A follow-up to my previous comment https://github.com/Automattic/mongoose/issues/4789#issuecomment-298849907

I moved the offending database from a virtual machine to a docker container with brand new linux, nodeJS and mongoDB. I created a stress test that does nothing but truncate and refill the database all day. I found that about 1 in 6000 operations result in a timeout error.

**Comment by gustvao** [comment] 2017-09-20 10:42
I had I guess the same experience after my last comment, forgot to mention.

But updating node to its one of its latest versions along with all the other deps apparently did the trick.

Now with the comment above I believe it is a matter of legacy error

**Comment by mzahidriaz-tr** [comment] 2018-04-19 05:14
I was also having the same issue with mongo 3.6.2 and mongoose 4.9.2
I fixed it by passing additional connection parameters

`MONGO_URI=mongodb://user:password@127.0.0.1:27017/dbname?keepAlive=true&poolSize=30&autoReconnect=true&socketTimeoutMS=360000&connectTimeoutMS=360000`

**Comment by mzahidriaz** [comment] 2018-04-19 05:15
I was also having the same issue with `mongo 3.6.2` and `mongoose 4.9.2`
I fixed it by passing additional connection parameters

`MONGO_URI=mongodb://user:password@127.0.0.1:27017/dbname?keepAlive=true&poolSize=30&autoReconnect=true&socketTimeoutMS=360000&connectTimeoutMS=360000`

**Comment by vkarpov15** [comment] 2018-07-08 22:43
@MinhNguyen41092 right now the only docs are the MongoDB driver docs http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#connect . we'll add details about this to http://mongoosejs.com/docs/connections.html

**Closed** 2018-07-09 14:14 UTC
Labels: docs

**Comment by binki** [comment] 2018-08-03 03:02
For those experiencing the intermittent errors, I had those too on mongoose-4.13.11 with mongodb-2.2.35 mongodb-core-2.1.19 in a particular environment. Various queries at different points in our testsuite, though mostly testing one particular part of our app which has heavier queries and does do things in parallel IIRC, were all getting this error message. And the whole test suite does not even take 15s to run, so there’s no way I should have been hitting the built-in default 30s timeouts in the first place:

```
     MongoError: connection 0 to localhost:27017 timed out
      at Function.MongoError.create (node_modules/mongoose/node_modules/mongodb-core/lib/error.js:29:11)
      at Socket.<anonymous> (node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:200:20)
      at Socket._onTimeout (net.js:448:8)
```

This only happened in our CI test build server. I couldn’t reproduce it on my dev machine.

(In my own system (private repo, this is for my own reference in case ever need to dig this up again), this error shows up at least in build numbers are 358, 356, 355, 352).

After turning on `useMongoClient: true`, the tests seem to pass reliably in the CI environment so far. I have had three successful runs with just that change whereas many prior sequential runs fail due to the weird timeout error.

I think @thenitai @steve-p-com @adrienbaron were experiencing the weird bogus timeouts too. I think the error was happening to you guys before 4.11 was out which even brought `useMongoClient: true` as an option. Can you tell if that made the difference for your workloads?

**Comment by SergeyVatz** [comment] 2019-02-25 15:12
mongodb-core@2.1.10
mongodb@2.2.26
mongoose@4.9.10
Have the same problem, 1.5M errors in roll bar for a couple of days, with what it can be connected? How resolve?
<img width="925" alt="screen shot 2019-02-25 at 2 53 37 pm" src="https://user-images.githubusercontent.com/36629375/53346794-6fdcf880-3920-11e9-80b1-41bcbc213555.png">
<img width="671" alt="screen shot 2019-02-25 at 2 54 01 pm" src="https://user-images.githubusercontent.com/36629375/53346795-6fdcf880-3920-11e9-8161-1972ed9db0f5.png">
<img width="790" alt="screen shot 2019-02-25 at 2 55 27 pm" src="https://user-images.githubusercontent.com/36629375/53346796-70758f00-3920-11e9-91b4-d8c7f118dfcc.png">

**Comment by vkarpov15** [comment] 2019-02-27 23:08
@SergeyVatz see response to your question on #5376
