### ISSUE TITLE
[feature] readonly attribute

### ISSUE THREAD

**Issue by Ncifra** [Automattic/mongoose#7713] opened 2019-04-16 09:49 UTC
I see that there is already the issue #1293 but it is quite old.

**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the expected behavior?**
Declaring a schema field with an attribute readonly: true, would make it not updateable. Maybe it would make sense to also include the case where:
if the field didn't exist at the time of the document creation, we should be able to first evaluate it, and then shouldn't be able to assign a new value to it.

**Comment by vkarpov15** [comment] 2019-04-22 19:07
Duplicate of #7671, will add it for next minor release.

**Closed by vkarpov15** 2019-04-22 19:07 UTC
