### ISSUE TITLE
Mongoose not reconnect after MongoDb stop and run

### ISSUE THREAD

**Issue by kostuyn** [Automattic/mongoose#3615] opened 2015-11-25 15:57 UTC
This is simple example for reproduce:
```
var http = require('http');
var mongoose = require('mongoose');
var express = require('express');

var db = mongoose.connection;

var schema = new mongoose.Schema({
    field: String
});

var MyCollection = mongoose.model('myCollection', schema);

db.on('error', function (error) {
    console.error('Error in MongoDb connection: ' + error);
});
db.on('connected', function () {
    console.log('MongoDB connected!');
});
db.on('reconnected', function () {
    console.log('MongoDB reconnected!');
});
db.on('disconnected', function () {
    console.log('MongoDB disconnected!');
});

mongoose.connect('localhost/base');


var app = express();
http.createServer(app).listen(8080);

app.use('/a', function (req, res) {
    MyCollection.find(function(err, items){
        if(err){
            console.log(err.stack);
            res.status(500);

            return res.send(err);
        }

        res.send(items);
    });
});

app.use('/b', function (req, res) {
    res.send('b');
});
```

Steps to reproduce:
1. run app.js
2. shutdown mongodb
3. GET to /a
4. waiting for error response
5. run mongodb(should be reconnect, but nothing happens)
6. GET to /a - response hangs on forever, but GET to /b - work success

Error:
```
MongoError: no connection available for operation
    at Function.MongoError.create (g:\Node.js\mongo_error\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:31:11)
    at Store.flush (g:\Node.js\mongo_error\node_modules\mongoose\node_modules\mongodb\lib\topology_base.js:68:43)
    at destroyHandler (g:\Node.js\mongo_error\node_modules\mongoose\node_modules\mongodb\lib\server.js:257:18)
    at g (events.js:199:16)
    at emit (events.js:107:17)
    at Server.destroy (g:\Node.js\mongo_error\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:670:24)
    at reconnectServer (g:\Node.js\mongo_error\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:162:17)
    at null._onTimeout (g:\Node.js\mongo_error\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:273:7)
    at Timer.listOnTimeout (timers.js:119:15)
```

Note: if run mongodb before occur error response (4) than success.
*mongoose: v4.2.7
mongo: v3.0.6
node: v0.12.7*

**Comment by vkarpov15** [comment] 2015-11-25 18:58
Unfortunately expected behavior. Mongoose will stop trying to reconnect after a [certain interval determined by `server.reconnectTries` and `server.reconnectInterval`](http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html), and any future requests will be automatically buffered by mongoose until you explicitly reconnect. You can [shut down buffering](http://mongoosejs.com/docs/guide.html#bufferCommands) as a workaround.

This is definitely worth improving though...

**Comment by tomgrossman** [comment] 2016-01-04 15:54
I think [#3729](https://github.com/Automattic/mongoose/issues/3729) is not a duplicate of this one.
In, [#3729](https://github.com/Automattic/mongoose/issues/3729) I explicitly open the connection again like you say here, but the problem is that disconnections are not fired when the DB is down again.
If you can, please check this issue reproduce steps again.

Thanks.

**Closed** 2016-06-13 13:48 UTC
Labels: fixed?
