### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by misland** [Automattic/mongoose#7173] opened 2018-10-23 08:46 UTC
**What is the current behavior?**
I just import mongoose in a project that initialized by vue-cli 2.0,when I run the project ,an error thrown as the title said,can anyone explain why?thanks!! 
here is the detail of error:
Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (webpack-internal:///./node_modules/mongoose/lib/types/buffer.js:184)
    at Array.forEach (<anonymous>)
    at Object.eval (webpack-internal:///./node_modules/mongoose/lib/types/buffer.js:183)
    at eval (webpack-internal:///./node_modules/mongoose/lib/types/buffer.js:306)
    at Object../node_modules/mongoose/lib/types/buffer.js (app.bundle.js:2554)
    at __webpack_require__ (app.bundle.js:679)
    at fn (app.bundle.js:89)
    at Object.eval (webpack-internal:///./node_modules/mongoose/lib/schema/buffer.js:10)
    at eval (webpack-internal:///./node_modules/mongoose/lib/schema/buffer.js:225)
    at Object../node_modules/mongoose/lib/schema/buffer.js (app.bundle.js:2386)
    at __webpack_require__ (app.bundle.js:679)
    at fn (app.bundle.js:89)
    at eval (webpack-internal:///./node_modules/mongoose/lib/schema/array.js:19)
    at Object../node_modules/mongoose/lib/schema/array.js (app.bundle.js:2370)
    at __webpack_require__ (app.bundle.js:679)
    at fn (app.bundle.js:89)

**Please mention your node.js, mongoose and MongoDB version.**
Node.js 8.12
mongoose 5.3.5
MongoDB 4.0.3

**Comment by nikdunn** [comment] 2018-10-24 19:19
The fix for this issue: #7102 seems to have been what introduces this bug. There is no Buffer property on global when NodeBuffer gets created.

**Comment by nikdunn** [comment] 2018-10-25 15:20
Why did you close this Issue? It's not fixed. This should be an open issue.

**Comment by lineus** [comment] 2018-10-25 16:29
@nikdunn does 5.3.6 fix the issue for you?

**Comment by nikdunn** [comment] 2018-10-25 16:41
No, @lineus , 5.3.6 is where the issue is introduced. I was using 5.3.4 and then an npm install bumped me to 5.3.6 where I started experiencing the issue.

**Comment by lineus** [comment] 2018-10-26 00:10
i am able to replicate this using a new vue-cli@2.9.6 webpack app and just adding the mongoose import statement `import mongoose from 'mongoose/browser';`.

**Comment by misland** [comment] 2018-10-26 00:46
@nikdunn sorry that I didn't quite familar with github issues,@lineus has opened this already

**Comment by vkarpov15** [comment] 2018-10-26 13:12
Thanks for helping us find this issue. We started using the core node buffer for a couple use cases to work around a bug in safe-buffer (https://github.com/feross/safe-buffer/pull/23) .

**Closed by vkarpov15** 2018-10-26 13:12 UTC
Labels: confirmed-bug

**Comment by odelucca** [comment] 2019-01-25 14:36
I´m getting the same error on a Jest test suite:
```
    TypeError: Cannot read property 'prototype' of undefined

      at Object.<anonymous> (node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:160:28)
      at Object.<anonymous> (node_modules/mongoose/lib/drivers/node-mongodb-native/index.js:8:22)
      at Object.<anonymous> (node_modules/mongoose/lib/index.js:10:27)
```

Any toughts on how to fix it?

**Comment by vkarpov15** [comment] 2019-01-27 21:03
@odelucca can you provide code samples? The original issue had nothing to do with jest and jest has a lot of issues. If you're going to use jest, make sure you read this doc: https://mongoosejs.com/docs/jest.html

**Comment by odelucca** [comment] 2019-01-30 12:17
@vkarpov15 thanks for the reply. I found out that the issue wasnt with mongoose :)

Thanks!
