### ISSUE TITLE
Should mongoose show an error/warning if trying to delete on non-existing properties?

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#4251] opened 2016-06-18 04:37 UTC
I was deleting two models based on a given court, and noticed a discrepancy in the logs (one time ObjectId and one time string):

```
Mongoose: bookings.remove({ court: ObjectId("5764ceaed5b3e76b78c149e9") }) {}  
Mongoose: events.remove({ court: '5764ceaed5b3e76b78c149e9' }) {}  
```

After further investigation, I realised the difference between the two models is that for events the `court` properly doesn't exist (it should have been `courts`). Should mongoose not throw an error/warning if we're deleting on properties which are not defined on the model?

What is the expected behaviour if we do this?

**Comment by vkarpov15** [comment] 2016-06-18 15:21
Right now mongoose's behavior for fields that aren't defined in the schema in filters is "do nothing with them" I'd love to see a plugin that can handle this more smartly though

**Comment by adambuczynski** [comment] 2016-06-18 21:31
Ok, thanks for the clarification. However, in the case of removing documents from the database, I don't think Mongoose is "doing nothing with them", because I didn't run into a problem of Mongoose trying to delete all my documents.

My filter was only passing the invalid field in it, so if Mongoose does nothing with them, shouldn't that have resulted in a remove operation with an empty filter, e.g. `{}` and remove all documents?

**Comment by vkarpov15** [comment] 2016-06-22 15:09
By "do nothing with them" I meant they stay in the query as is and mongoose doesn't cast them away,

**Comment by hasezoey** [comment] 2022-08-26 10:29
with the current mongoose version it removes those paths from the query, which could result in unwanted (and silent) behavior:

```ts
// NodeJS: 18.7.0
// MongoDB: 5.0 (Docker)
// Typescript 4.7.4
import * as mongoose from 'mongoose'; // mongoose@6.5.2

const userSchema = new mongoose.Schema({ prop1: String });

const UserModel = mongoose.model('User', userSchema);

(async () => {
  await mongoose.connect(`mongodb://localhost:27017/`, {
    dbName: 'verifyMASTER',
  });

  mongoose.set('debug', true);

  // Mongoose: users.remove({}, {})
  // remove { acknowledged: true, deletedCount: 0 }
  console.log('remove', await UserModel.remove({ nonExistent: true }));
  // Mongoose: users.deleteOne({}, {})
  // deleteOne { acknowledged: true, deletedCount: 0 }
  console.log('deleteOne', await UserModel.deleteOne({ nonExistent: true }));
  // Mongoose: users.deleteMany({}, {})
  // deleteMany { acknowledged: true, deletedCount: 0 }
  console.log('deleteMany', await UserModel.deleteMany({ nonExistent: true }));

  await mongoose.disconnect();
})();
```

Reproduction Repository / Branch: https://github.com/typegoose/typegoose-testing/tree/mongooseGh4251

this is probably related to `strict` being default now and strict removing unknown properties (though silently)

**Comment by hasezoey** [comment] 2022-09-05 11:51
may be related to #11861

**Comment by vkarpov15** [comment] 2024-09-17 16:59
I'm going to close this issue. If you want Mongoose to throw an error on unknown properties in query filters, you can set `strictQuery: 'throw'`

```javascript
// Will throw an error if `court` isn't a property on `Event` model's schema
await Event.deleteOne({ court: 'abcd' }, { scrictQuery: 'throw' });
```

You can also set `strictQuery` on your schema's options to make all queries have `strictQuery: 'throw'`.

**Closed by vkarpov15** 2024-09-17 16:59 UTC
Labels: plugin
