### ISSUE TITLE
Multiple Issues with Typescript

### ISSUE THREAD

**Issue by mrfambo** [Automattic/mongoose#10122] opened 2021-04-09 19:42 UTC
typescript: ^4.2.4
mongoose: ^5.12.3
nodejs: 14.16.1
mongodb: 3.6.2 
@types/mongoose: ^5.10.4

*bug*

Here are the interfaces I am using:

```
interface ShadowBucket {
  _id: string
  Collaborators: Collaborator[]
}

interface Collaborator {
  id: string
  acl: ACL[]
}

interface ACL {
  permission: string
  author: AccountRef
  timestamp: Date
}

// Model creation

const ShadowBucketSchema = new mongoose.Schema(
  {
    Collaborators: {
      type: Array
    },
  }
)

const ShadowBucketModel = mongoose.model<ShadowBucket & mongoose.Document>('shadow-buckets', ShadowBucketSchema)

// This is the method having problem
public removeShadowCollaboratorACL = async (_id: string, collaboratorid: string, removedACLs: string[]): Promise<ShadowBucket | null> => {
    return ShadowBucketModel.findOneAndUpdate(
      {
        _id: Mongoose.Types.ObjectId(_id),
        Collaborators: { $elemMatch: { id: collaboratorid, acl: { $elemMatch: { permission: { $in: removedACLs } } } } }
      },
      {
        'Collaborators.$.lastUpdated': new Date(),
        $pull: {
          'Collaborators.$.acl': {
            permission: {
              $in: removedACLs
            }
          }
        }
      },
      {
        new: true
      }
    )
  }
```

Error Message: 

```
No overload matches this call.
  Overload 1 of 3, '(filter: FilterQuery<ShadowBucket & Document<any, {}>>, update: UpdateQuery<ShadowBucket & Document<any, {}>>, options: QueryOptions & { ...; }, callback?: ((err: any, doc: FindAndModifyWriteOpResultObject<...>, res: any) => void) | undefined): Query<...>', gave the following error.
    Type '{ 'Collaborators.$.acl': { permission: { $in: string[]; }; }; }' is not assignable to type 'PullOperator<_AllowStringsForIds<LeanDocument<ShadowBucket & Document<any, {}>>>>'.
      Object literal may only specify known properties, and ''Collaborators.$.acl'' does not exist in type 'PullOperator<_AllowStringsForIds<LeanDocument<ShadowBucket & Document<any, {}>>>>'.
  Overload 2 of 3, '(filter: FilterQuery<ShadowBucket & Document<any, {}>>, update: UpdateQuery<ShadowBucket & Document<any, {}>>, options: QueryOptions & ... 1 more ... & ReturnsNewDoc, callback?: ((err: any, doc: ShadowBucket & Document<...>, res: any) => void) | undefined): Query<...>', gave the following error.
    Type '{ 'Collaborators.$.acl': { permission: { $in: string[]; }; }; }' is not assignable to type 'PullOperator<_AllowStringsForIds<LeanDocument<ShadowBucket & Document<any, {}>>>>'.
      Object literal may only specify known properties, and ''Collaborators.$.acl'' does not exist in type 'PullOperator<_AllowStringsForIds<LeanDocument<ShadowBucket & Document<any, {}>>>>'.
  Overload 3 of 3, '(filter?: FilterQuery<ShadowBucket & Document<any, {}>> | undefined, update?: UpdateQuery<ShadowBucket & Document<any, {}>> | undefined, options?: QueryOptions | ... 1 more ... | undefined, callback?: ((err: any, doc: (ShadowBucket & Document<...>) | null, res: any) => void) | undefined): Query<...>', gave the following error.
    Type '{ 'Collaborators.$.acl': { permission: { $in: string[]; }; }; }' is not assignable to type 'PullOperator<_AllowStringsForIds<LeanDocument<ShadowBucket & Document<any, {}>>>>'.
      Object literal may only specify known properties, and ''Collaborators.$.acl'' does not exist in type 'PullOperator<_AllowStringsForIds<LeanDocument<ShadowBucket & Document<any, {}>>>>'.ts(2769)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have provided the interfaces and method to reproduce this!

```
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "allowJs": true,
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true, 
    "noImplicitAny": false,
    "strictPropertyInitialization": false,
    "alwaysStrict": true,
    "moduleResolution": "node",
    "baseUrl": "./src",
    "typeRoots": ["./node_modules/@types"],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": false
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "newschema", "__tests__/**/*", "jest.config.js", "migration-scripts", "migration-scripts/**"]
}
```

**What is the expected behavior?**
There shouldn't be any TS bug in it

**Comment by mrfambo** [comment] 2021-04-09 19:53
Marking `pull:{...} as any` worked for now.

**Comment by mrfambo** [comment] 2021-04-09 19:58
Now over 20 services have 90+ occurrences of `any` with every $pull and $push. Seems something is very wrong. At the moment, I am functional but we need to resolve it please.

**Comment by mrfambo** [comment] 2021-04-09 19:59
Issue is not with $ only.
`{ $push: { seenBy: seenBy } as any }`

**Comment by mrfambo** [comment] 2021-04-09 20:07
Every `deleteMany` needs to have a second argument of `undefined` to satisfy the needs of Typescript.

```
GoLiveSessionFeedModel.deleteMany({ poll, feedType: 'POLL_REQUEST' }, (err) => {
        if (err) resolve(false)
        resolve(true)
      })
```

It needs to be updated with

```
GoLiveSessionFeedModel.deleteMany({ poll, feedType: 'POLL_REQUEST' }, undefined, (err) => {
        if (err) resolve(false)
        resolve(true)
      })
```

**Comment by IslandRhythms** [comment] 2021-04-14 17:51
```
import mongoose from "mongoose";

interface ShadowBucket {
    _id: string
    Collaborators: Collaborator[]
  }
  
  interface Collaborator {
    id: string
    acl: ACL[]
  }
  
  interface ACL {
    permission: string
    author: AccountRef
    timestamp: Date
  }
  
  // Model creation
  
  const ShadowBucketSchema = new mongoose.Schema(
    {
      Collaborators: {
        type: Array
      },
    }
  )
  
  const ShadowBucketModel = mongoose.model<ShadowBucket & mongoose.Document>('shadow-buckets', ShadowBucketSchema)
  
  // This is the method having problem
   const removeShadowCollaboratorACL = async (_id: string, collaboratorid: string, removedACLs: string[]): Promise<ShadowBucket | null> => {
      return ShadowBucketModel.findOneAndUpdate(
        {
          _id: mongoose.Types.ObjectId(_id),
          Collaborators: { $elemMatch: { id: collaboratorid, acl: { $elemMatch: { permission: { $in: removedACLs } } } } }
        },
        {
          'Collaborators.$.lastUpdated': new Date(),
          $pull: {
            'Collaborators.$.acl': {
              permission: {
                $in: removedACLs
              }
            }
          }
        },
        {
          new: true
        }
      )
    }
    ```

**Comment by vkarpov15** [comment] 2021-04-16 18:30
The `$pull` issue is a duplicate of #10075, please upgrade to 5.12.4 for the fix.

**Comment by vkarpov15** [comment] 2021-04-16 18:42
Also, it looks like you're using callbacks to resolve/reject a promise. That's silly and unnecessary. Just do:

```javascript
GoLiveSessionFeedModel.deleteMany({ poll, feedType: 'POLL_REQUEST' }).exec()
```

**Closed** 2021-04-16 18:42 UTC
Labels: confirmed-bug, typescript
