### ISSUE TITLE
4.6.7 Not Backwards-Compatibile

### ISSUE THREAD

**Issue by peterkrieg** [Automattic/mongoose#4710] opened 2016-11-14 23:32 UTC
Breaking changes between 4.6.6 and 4.6.7 for me, and apparently others.  

Before, I had some code running `.populate('')` (an empty string) which I know is probably dumb, but simply did nothing on 4.6.6.  With 4.6.7, an error is thrown:

`Error: If you are populating a virtual, you must set the localField and foreignField options`.

I just wanted to bring this up mostly because of backwards-breaking changes just from updating the patch.  Thanks!

**Comment by maximilianschmid** [comment] 2016-11-16 17:16
Also experience populate() breaking change between 4.6.6 and 4.6.7

.populate('participants.user ', 'email profile.firstName profile.lastName lastlogindate alreadyloggedin')

throws this error: 
`Error: If you are populating a virtual, you must set the localField and foreignField options
`

**Comment by vkarpov15** [comment] 2016-11-17 14:50
Duplicate of #4702, fixed in master, will be fixed with next release.

@maximilianschmid you're having a different issue, please show your schema. OP's issue was about populate with an empty string, yours is not empty.

**Closed by vkarpov15** 2016-11-17 14:50 UTC

**Comment by behalka** [comment] 2016-11-18 13:22
I've received the same error using populate like this after updating to 4.6.8 (note the extra space after path name):

`    
return Account.findOne({ identifier: identifier }).lean()
        .populate({ path: 'topic ', options: { lean: true }})
`

The same code worked as expected in versions prior to the 4.6.7. I know it's just a typo and it shouldn't be there, but the error message is misleading and it can maybe point at other problems with the new .populate method.

**Comment by vkarpov15** [comment] 2016-11-22 01:51
Hmm how do you defined "worked as expected"? I'd be surprised if it actually populated the results

**Comment by behalka** [comment] 2016-11-22 08:22
It populated the results :) nevermind.. I'm glad the update helped me to discover this typo and that's it.
