### ISSUE TITLE
Mongodb-mongoose-replicaset - MongoError: database names cannot contain the character '.'

### ISSUE THREAD

**Issue by Divine1** [Automattic/mongoose#8900] opened 2020-04-30 11:38 UTC
iam using mongoose 5.9.0. i have setup mongodb with replicaSets with 2 replica's.

i checked the mongoose docs on how to connect to replicaset
![image](https://user-images.githubusercontent.com/10482177/80705743-9427fc80-8b04-11ea-98cd-93c4e6e75b80.png)

i updated my source code as per the docs
![image](https://user-images.githubusercontent.com/10482177/80705845-d4877a80-8b04-11ea-8c33-82faca1dc2b9.png)

![image](https://user-images.githubusercontent.com/10482177/80705885-e79a4a80-8b04-11ea-8a4d-4f45277957e7.png)

i get below error when i use multiple hosts as mentioned in the docs.
Please let me know what would be the proper configuration for mongoose?
![image](https://user-images.githubusercontent.com/10482177/80705930-03055580-8b05-11ea-81f6-2627d8b2750d.png)

**Comment by lineus** [comment] 2020-04-30 15:33
@Divine1 You have missed a small detail in the connection string example from the docs. The database does **not** go on the end of each host:port combo in the list. The database should only appear once at the end of the string. 

### you have
`mongodb://111.99.22.33:27017/dbz,111.99.22.33:27019/dbz`
### it should be 
`mongodb://111.99.22.33:27017,111.99.22.33:27019/dbz`

**Comment by Divine1** [comment] 2020-04-30 16:45
its not working

![image](https://user-images.githubusercontent.com/10482177/80736537-ea5e6500-8b2f-11ea-8de8-f08e975a6fd9.png)

but i'm able to connect via mongo client via this same machine.

**Comment by lineus** [comment] 2020-04-30 17:03
There isn't enough information provided for me to answer that question. I can only assume that there is a plugin or some other part of the code that is attempting to connect to localhost instead of the host you provided.

Here's a complete script that reproduces your original issue

### 8900.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8900';
const URI = `mongodb://127.0.0.1:27017${DB},127.0.0.1:27018/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  name: String,
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test',
});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc && doc.name === 'test');
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```

if you remove the first instance of '${DB}' from the URI template literal, the connection works just fine ( I have a replica set running locally ). 

Are you using any plugins? What does the output of `npm ls | grep mongo` look like when run from your repository's root folder?

**Comment by Divine1** [comment] 2020-04-30 17:31
@lineus  Your program works perfectly as per your instruction when i run within the replicaset instance that is `mongodb://127.0.0.1:27017,127.0.0.1:27018/${DB}`

but when i change localhost to my elastic ipaddress and connect from my machine via nodejs program, it doesnot work. i get below error message
![image](https://user-images.githubusercontent.com/10482177/80740982-87bc9780-8b36-11ea-96f5-ab1d71718eba.png)



 iam able to login via mongoclient via  my machine. so elasticip is not the problem,

**Comment by Divine1** [comment] 2020-04-30 18:08
@lineus  i think mongoose is always looking for the ip `127.0.0.1` disregarding the elasticip incase of uri's with multiple ip address

**Comment by lineus** [comment] 2020-04-30 18:37
I can't speak as to why your setup is trying to connect to localhost. 

**When I run my code from above with the IP addresses from your original report it does not attempt to connect to localhost**

### 8900.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8900';
const URI = `mongodb://111.99.234.9:27017,111.99.234.9:27018/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  name: String,
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test',
});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc && doc.name === 'test');
  console.log('All Assertions Pass.');
  await connection.close();
}

run();
```

### Output:
```
$ ./8900.js 
(node:68974) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connection timed out
    at new MongooseServerSelectionError (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/error/serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/index.js:333:15)
    at run (/home/lineus/old_dev/node/BE/mongoose/issues/8900.js:22:18)
    at Object.<anonymous> (/home/lineus/old_dev/node/BE/mongoose/issues/8900.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:68974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:68974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
$: 
```

**Comment by Divine1** [comment] 2020-04-30 20:00
i have jumbled that ip. please use this ip 167.99.21.9

**Comment by lineus** [comment] 2020-04-30 20:09
note the ` type: 'ReplicaSetNoPrimary',` below. Once again, unable to reproduce the localhost connection. It looks like there is a configuration issue with your replica set.

### 8900.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8900';
const URI = `mongodb://167.99.21.9:27017,167.99.21.9:27018/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  name: String,
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test',
});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc && doc.name === 'test');
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(console.error);
```
### Output
```
$: ./8900.js 
MongooseError [MongooseServerSelectionError]: Server selection timed out after 30000 ms
    at new MongooseServerSelectionError (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/error/serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/index.js:333:15)
    at run (/home/lineus/old_dev/node/BE/mongoose/issues/8900.js:22:18)
    at Object.<anonymous> (/home/lineus/old_dev/node/BE/mongoose/issues/8900.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'testReplicaDB',
    maxSetVersion: 11,
    maxElectionId: 7fffffff000000000000001e,
    servers: Map {},
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 7
  },
  [Symbol(mongoErrorContextSymbol)]: {}
}
$: 
```

**Comment by Divine1** [comment] 2020-04-30 22:13
if there is something wrong with replica why it would connect successfully with nodejs program running on the same instance and mongo clients from external systems ?

![image](https://user-images.githubusercontent.com/10482177/80764176-bc901500-8b5d-11ea-8c2e-a9d18fdb3631.png)

![image](https://user-images.githubusercontent.com/10482177/80764199-c9ad0400-8b5d-11ea-8709-552626d6abdc.png)

**Comment by lineus** [comment] 2020-04-30 23:05
in your latest comment, the ports are different from your original report. When trying to connect to the correct host:port combination I **do** now get the localhost error you are seeing ( as shown below ). 

### 8900.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
const { Schema, connection} = mongoose;
const DB = '8900';
const URI = `mongodb://167.99.21.9:12017,167.99.21.9:12019/${DB}`;
const OPTS = { useNewUrlParser: true, useUnifiedTopology: true };

const schema = new Schema({
  name: String,
});

const Test = mongoose.model('test', schema);

const test = new Test({
  name: 'test',
});

async function run() {
  await mongoose.connect(URI, OPTS);
  await connection.dropDatabase();
  const doc = await Test.create(test);
  assert.ok(doc && doc.name === 'test');
  console.log('All Assertions Pass.');
  await connection.close();
}

run().catch(console.error);
```
### Output:
```
$: ./8900.js 
MongooseError [MongooseServerSelectionError]: connect ECONNREFUSED 127.0.0.1:12017
    at new MongooseServerSelectionError (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/error/serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/connection.js:823:32)
    at Mongoose.connect (/home/lineus/old_dev/node/BE/mongoose/issues/node_modules/mongoose/lib/index.js:333:15)
    at run (/home/lineus/old_dev/node/BE/mongoose/issues/8900.js:22:18)
    at Object.<anonymous> (/home/lineus/old_dev/node/BE/mongoose/issues/8900.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'testReplicaDB',
    maxSetVersion: 1,
    maxElectionId: 7fffffff0000000000000001,
    servers: Map {
      'localhost:12017' => [ServerDescription],
      'localhost:12019' => [ServerDescription],
      'localhost:12018' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 8
  },
  [Symbol(mongoErrorContextSymbol)]: {}
}
$:
```
`localhost` in this context is being reported from the perspective of the replica set, not your local node process. This can be seen by running `tcpdump` locally while running the script above. (output below). 

Your replica set is trying to connect to localhost and for some reason it isn't working when connecting from the mongodb nodejs driver.  Are there any relevant logs on the mongodb server that might show more details?

### localhost tcpdump output ( while running above code )
```
$ sudo tcpdump -n port 12017 or port 12019
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp5s0, link-type EN10MB (Ethernet), capture size 262144 bytes
18:53:48.932734 IP 192.168.1.25.37278 > 167.99.21.9.12017: Flags [S], seq 3010290995, win 64240, options [mss 1460,sackOK,TS val 2829357102 ecr 0,nop,wscale 7], length 0
18:53:48.932777 IP 192.168.1.25.37066 > 167.99.21.9.12019: Flags [S], seq 2034282473, win 64240, options [mss 1460,sackOK,TS val 2829357102 ecr 0,nop,wscale 7], length 0
18:53:48.968332 IP 167.99.21.9.12019 > 192.168.1.25.37066: Flags [S.], seq 2680676233, ack 2034282474, win 28960, options [mss 1460,sackOK,TS val 2506035234 ecr 2829357102,nop,wscale 7], length 0
18:53:48.968375 IP 192.168.1.25.37066 > 167.99.21.9.12019: Flags [.], ack 1, win 502, options [nop,nop,TS val 2829357138 ecr 2506035234], length 0
18:53:48.968547 IP 167.99.21.9.12017 > 192.168.1.25.37278: Flags [S.], seq 932920304, ack 3010290996, win 28960, options [mss 1460,sackOK,TS val 2506035234 ecr 2829357102,nop,wscale 7], length 0
18:53:48.968569 IP 192.168.1.25.37278 > 167.99.21.9.12017: Flags [.], ack 1, win 502, options [nop,nop,TS val 2829357138 ecr 2506035234], length 0
18:53:48.974420 IP 192.168.1.25.37066 > 167.99.21.9.12019: Flags [P.], seq 1:314, ack 1, win 502, options [nop,nop,TS val 2829357144 ecr 2506035234], length 313
18:53:48.975356 IP 192.168.1.25.37278 > 167.99.21.9.12017: Flags [P.], seq 1:314, ack 1, win 502, options [nop,nop,TS val 2829357145 ecr 2506035234], length 313
18:53:49.016553 IP 167.99.21.9.12019 > 192.168.1.25.37066: Flags [.], ack 314, win 235, options [nop,nop,TS val 2506035282 ecr 2829357144], length 0
18:53:49.016878 IP 167.99.21.9.12017 > 192.168.1.25.37278: Flags [.], ack 314, win 235, options [nop,nop,TS val 2506035282 ecr 2829357145], length 0
18:53:49.025415 IP 167.99.21.9.12017 > 192.168.1.25.37278: Flags [P.], seq 1:733, ack 314, win 235, options [nop,nop,TS val 2506035290 ecr 2829357145], length 732
18:53:49.025433 IP 192.168.1.25.37278 > 167.99.21.9.12017: Flags [.], ack 733, win 501, options [nop,nop,TS val 2829357195 ecr 2506035290], length 0
18:53:49.026288 IP 167.99.21.9.12019 > 192.168.1.25.37066: Flags [P.], seq 1:757, ack 314, win 235, options [nop,nop,TS val 2506035290 ecr 2829357144], length 756
18:53:49.026302 IP 192.168.1.25.37066 > 167.99.21.9.12019: Flags [.], ack 757, win 501, options [nop,nop,TS val 2829357195 ecr 2506035290], length 0
18:53:49.031283 IP 192.168.1.25.37278 > 167.99.21.9.12017: Flags [F.], seq 314, ack 733, win 501, options [nop,nop,TS val 2829357200 ecr 2506035290], length 0
18:53:49.032802 IP 192.168.1.25.37066 > 167.99.21.9.12019: Flags [F.], seq 314, ack 757, win 501, options [nop,nop,TS val 2829357202 ecr 2506035290], length 0
18:53:49.065539 IP 167.99.21.9.12017 > 192.168.1.25.37278: Flags [F.], seq 733, ack 315, win 235, options [nop,nop,TS val 2506035330 ecr 2829357200], length 0
18:53:49.065559 IP 192.168.1.25.37278 > 167.99.21.9.12017: Flags [.], ack 734, win 501, options [nop,nop,TS val 2829357235 ecr 2506035330], length 0
18:53:49.066850 IP 167.99.21.9.12019 > 192.168.1.25.37066: Flags [F.], seq 757, ack 315, win 235, options [nop,nop,TS val 2506035332 ecr 2829357202], length 0
18:53:49.066869 IP 192.168.1.25.37066 > 167.99.21.9.12019: Flags [.], ack 758, win 501, options [nop,nop,TS val 2829357236 ecr 2506035332], length 0
^C
20 packets captured
20 packets received by filter
0 packets dropped by kernel
```
I remember seeing something like this in the past, I'll try to find the previous issue that it was addressed in. If I recall correctly it was a configuration issue on the replica set.

**Comment by Divine1** [comment] 2020-04-30 23:19
@lineus 
i changed the port to check if my port is causing problem.

this is my current configuration of replica set. do you think i have to provide my elasticip in place of host in below configuration? 

```
var configuration = {
    _id : "testReplicaDB",
    members:[
        {_id:0,host:"localhost:12017"},
        {_id:1,host:"localhost:12018",arbiterOnly:true,buildIndexes:false},
        {_id:2,host:"localhost:12019"}
    ]
}

```

**Comment by Divine1** [comment] 2020-05-01 18:39
@lineus if you found any detail , kindly share. i'm stuck on this.

**Comment by lineus** [comment] 2020-05-02 00:18
[this was the issue where I had seen this before](https://github.com/Automattic/mongoose/issues/7165) the last comment there points [to these docs](https://mongoosejs.com/docs/connections.html#replicaset-hostnames) which seems very relevant to your current situation.

**Comment by vkarpov15** [comment] 2020-05-02 20:36
Read up on [replica set hostnames](https://mongoosejs.com/docs/connections.html#replicaset-hostnames) @Divine1 . It looks like your replica set members are self-reporting their host as 'localhost' rather than '167.99.21.9', etc.

**Closed by vkarpov15** 2020-05-02 20:36 UTC

**Comment by Divine1** [comment] 2020-05-04 03:52
@lineus i added a valid ip address to the replicaSet config. now it works. thank you

@vkarpov15 thank you.
