### ISSUE TITLE
Cyclic Dependency error on Schema.Types.Mixed

### ISSUE THREAD

**Issue by arushgupta2007** [Automattic/mongoose#8974] opened 2020-05-11 06:25 UTC
**Do you want to request a *feature* or report a *bug*?**
I having a bug.

**What is the current behavior?**
Having Cyclic dependency on using Schema.Types.Mixed
Error:
```
(node:3629) UnhandledPromiseRejectionWarning: Error: cyclic dependency detected
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:333:34)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:941:17)
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:941:17)
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:941:17)
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:727:17)
    at serializeObject (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:347:18)
    at serializeInto (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/parser/serializer.js:941:17)
    at BSON.serialize (/home/user/Desktop/project/website_node_js/node_modules/bson/lib/bson/bson.js:64:28)
    at Msg.serializeBson (/home/user/Desktop/project/website_node_js/node_modules/mongodb/lib/core/connection/msg.js:126:22)
(node:3629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**If the current behavior is a bug, please provide the steps to reproduce.**
When defining a shema, using Schema.Types.Mixed, gives error

```js
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const userSchema = new Schema({
    meetingID:Number,
    meetingName:String,
    meetingSession: Schema.Types.Mixed,
    tokens:[{type: String}],
    code: String,
    next_id: Number,
})

const Meeting = mongoose.model("meeting", userSchema);
module.exports = Meeting;
```
The above code gives an cyclic dependency error
```js
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const userSchema = new Schema({
    meetingID:Number,
    meetingName:String,
    //meetingSession: Schema.Types.Mixed,
    tokens:[{type: String}],
    code: String,
    next_id: Number,
})

const Meeting = mongoose.model("meeting", userSchema);
module.exports = Meeting;
```
While this code ran without an error

**What is the expected behavior?**
No cylic dependency errors
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Mongoose: 5.9.13
Nodejs: 14.1.0
MongoDB: I wish that this is what you would like to know: `MongoDB shell version v4.2.6`

Thank You

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 06:54
Welcome @arushgupta2007 

I can't reproduce this, please try the following and see if this works.

1. Remove node_modules folder
2. Remove package-lock.json
3. Remove yarn.lock
4. Run npm cache clean --force
5. Run yarn cache clean
6. Run npm install

### 8974.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const userSchema = new Schema({
  meetingID: Number,
  meetingName: String,
  meetingSession: Schema.Types.Mixed,
  tokens: [{ type: String }],
  code: String,
  next_id: Number
});

const Meeting = mongoose.model('meeting', userSchema);

assert.ok(Meeting);
console.log('All assertions passed.');
console.log(mongoose.version);
```
### Output
```
All assertions passed.
5.9.13
```

**Comment by arushgupta2007** [comment] 2020-05-11 06:57
Thanks for the quick response.
Sorry, The above reproducing steps were wrong.
When I create a new meetings Model with some data and save it to my database, then I get the error.
By the way, I am storing like a class in my meetingSession , which looks like this when logged:
```
<ref *1> Session {
  ov: OpenVidu {
    urlOpenViduServer: 'https://localhost:4443',
    Buffer: [Function: Buffer] {
      TYPED_ARRAY_SUPPORT: true,
      poolSize: 8192,
      from: [Function (anonymous)],
      alloc: [Function (anonymous)],
      allocUnsafe: [Function (anonymous)],
      allocUnsafeSlow: [Function (anonymous)],
      isBuffer: [Function: isBuffer],
      compare: [Function: compare],
      isEncoding: [Function: isEncoding],
      concat: [Function: concat],
      byteLength: [Function: byteLength]
    },
    activeSessions: [ [Circular *1] ],
    hostname: 'localhost',
    port: 4443,
    basicAuth: 'Basic T1BFTlZJRFVBUFA6TVlfU0VDUkVU'
  },
  activeConnections: [],
  recording: false,
  properties: {
    mediaMode: 'ROUTED',
    recordingMode: 'MANUAL',
    defaultOutputMode: 'COMPOSED',
    defaultRecordingLayout: 'BEST_FIT'
  },
  sessionId: 'ses_Le4UPER13e',
  createdAt: 1589178643074
}
```
I was able to store it in an array and use it later to run some functions. I am trying to do the same, but store it in the database and use it later.

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 07:02
Happy to help, please provide a reproduction script like the one in https://github.com/Automattic/mongoose/issues/8974#issuecomment-626508916

**Comment by arushgupta2007** [comment] 2020-05-11 07:11
Here is the code where the error lies in: 
```js
OV.createSession()
    .then((session) => {
        mapSessions[session_id] = session;
        mapSessionNamesTokens[session_id] = [];
        name_codes[session_id] = {
            name: name_meeting,
            code: session_code,
        };
        
        session
            .generateToken(tokenOptions)
            .then((token) => {
                mapSessionNamesTokens[session_id].push(token);
                // console.log("error would be here if at all!!!");
                
                meetingsModel({
                    meetingID:session_id,
                    meetingName:name_meeting,
                    meetingSession: [session],
                    tokens:[token],
                    code: session_code,
                    next_id: 1,
                }).save().then((newMeeting) => {
                    res.render(__dirname + "/public/session/session.ejs", {
                        sessionName: session_id,
                        token: token,
                        nickName: name_client,
                        userName: 0,
                        meetingName: name_meeting,
                    });
                })                           
            })
            .catch((err) => console.log(err));
    })
    .catch((err) => console.log(err));
```
I am using Openvidu: [https://openvidu.io](https://openvidu.io) to create my session

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 09:03
Can you modify the script below to reproduce the issue?
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const meetingSchema = new Schema({
    meetingID: Number,
    meetingName: String,
    meetingSession: Schema.Types.Mixed,
    tokens: [{ type: String }],
    code: String,
    next_id: Number
  });
  const Meeting = mongoose.model('Meeting', meetingSchema);


  const meeting = await Meeting.create({
    meetingID: 1,
    meetingName: 'important meeting',
    meetingSession: { nested: ['no', 'rules'] },
    tokens: ['a', 'b', 'c'],
    code: '123',
    next_id: 1
  });


  assert.deepEqual(meeting.meetingSession, { nested: ['no', 'rules'] });

  console.log('All assertions passed.');
}
```

**Comment by arushgupta2007** [comment] 2020-05-11 10:02
I am not able to reproduce the error but can you try this script: 
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);


class Car {
  constructor(brand) {
    this.carname = brand;
  }
  static hello() {
    return "Hello!!";
  }
}


async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const meetingSchema = new Schema({
    meetingID: Number,
    meetingName: String,
    meetingSession: Schema.Types.Mixed,
    tokens: [{ type: String }],
    code: String,
    next_id: Number
  });
  const Meeting = mongoose.model('Meeting', meetingSchema);


  const meeting = await Meeting.create({
    meetingID: 1,
    meetingName: 'important meeting',
    meetingSession: Schema,
    tokens: ['a', 'b', 'c'],
    code: '123',
    next_id: 1
  });


  assert.deepEqual(meeting.meetingSession, Schema);

  console.log('All assertions passed.');
}
```

Does the Schema object be stored?

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 10:10
Why are you trying to save `mongoose.Schema` in your database?

[Model.create(...)](https://mongoosejs.com/docs/api/model.html#model_Model.create) takes a document as a parameter. You can not save functions in the database.

**Comment by arushgupta2007** [comment] 2020-05-11 10:14
Just like Schema I am trying to store an instance of a class. Weirdly enough, I can store a instance of this class: 
```js
class Car {
  constructor(brand) {
    this.carname = brand;
  }
  static hello() {
    return "Hello!!";
  }
}
```

**Comment by arushgupta2007** [comment] 2020-05-11 10:38
Using this script I am able to store a class which uses a function? :
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

class Car {
  constructor(brand) {
    this.carname = brand;
  }
  hello() {
    return this.carname;
  }
}

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const meetingSchema = new Schema({
    meetingID: Number,
    meetingName: String,
    meetingSession: Schema.Types.Mixed,
    tokens: [{ type: String }],
    code: String,
    next_id: Number
  });
  const Meeting = mongoose.model('Meeting', meetingSchema);


  const meeting = Meeting({
    meetingID: 1,
    meetingName: 'important meeting',
    meetingSession: new Car("Hello"),
    tokens: ['a', 'b', 'c'],
    code: '123',
    next_id: 1
  }).save().then((meeting) => {
      console.log(meeting.meetingSession.hello())
});

  console.log(typeof new Car("Hello"));
  assert.deepEqual(meeting.meetingSession, new Car("Hello"));

  console.log('All assertions passed.');
}
```

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 10:59
That's because mongoose doesn't do any casting to `Schema.Types.Mixed` and you still have the object in memory, doesn't mean that it's actually stored in memory. When you try to fetch the document from the database, the function will not be there.

Anyway, why try to store `mongoose.Schema` on the database? Why not just access it from mongoose when you need it?

```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');

run().catch(console.error);

class Car {
  constructor(brand) {
    this.carname = brand;
  }
  hello() {
    return this.carname;
  }
}

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const meetingSchema = new Schema({
    meetingID: Number,
    meetingName: String,
    meetingSession: Schema.Types.Mixed,
    tokens: [{ type: String }],
    code: String,
    next_id: Number
  });
  const Meeting = mongoose.model('Meeting', meetingSchema);


  await Meeting.create({
    meetingID: 1,
    meetingName: 'important meeting',
    meetingSession: new Car('Hello'),
    tokens: ['a', 'b', 'c'],
    code: '123',
    next_id: 1
  });


  const meeting = await Meeting.findOne();

  // TypeError: meeting.meetingSession.hello is not a function
  const value = meeting.meetingSession.hello();
  assert.equal(value, 'Hello');

  console.log('All assertions passed.');
}
```

**Comment by arushgupta2007** [comment] 2020-05-11 11:09
I am running a web server for video meetings. I initiate a object when one person starts a meeting. Then when somebody else tries to join the meeting, the I need the object I initialized before to join the meeting. Storing object in RAM makes my computer hang.

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 11:19
You might find [instance methods](https://mongoosejs.com/docs/guide.html#methods) helpful in that case. You can define methods for documents and call them when you need to.

Storing logic on the database is not the solution to that problem.

**Comment by arushgupta2007** [comment] 2020-05-11 11:41
Thanks, I will give it a try!

**Comment by AbdelrahmanHafez** [comment] 2020-05-11 11:43
Happy to help 👍

I'll close this issue for now, please reopen if you need any further assistance.

**Closed by AbdelrahmanHafez** 2020-05-11 11:43 UTC
Labels: needs repro script
