### ISSUE TITLE
Save does not correctly $set subdocuments for timestamp updates

### ISSUE THREAD

**Issue by Vogel612** [Automattic/mongoose#11603] opened 2022-03-31 12:05 UTC
**What is the current behavior?**

When updating a subdocument with javascript and `save()`, the behaviour is different from dispatching an equivalent `$set` operation.
Notably this is relevant for timestamps on subdocuments.

**If the current behavior is a bug, please provide the steps to reproduce.**

The following test case demonstrates the issue observed.

```
import mongoose from "mongoose";
import assert from "assert";

describe("Test Repro for $set vs. save issues", () => {
    const childSchema = new mongoose.Schema({
        name: String
    }, { timestamps: { createdAt: "created", updatedAt: false }, _id: false });
    const testSchema = new mongoose.Schema({ child: childSchema, age: Number});
    before(async () => {
        await mongoose.connect('mongodb://localhost:27017/test');
    })
    beforeEach(async () => {
        await mongoose.connection.dropDatabase();
    });
    after(async () => {
        await mongoose.disconnect();
    });
    it("Mongoose $set behaves as expected", async () => {
        const Test = mongoose.model('Test', testSchema);

        await Test.create({ age: 10 });
        await Test.findOneAndUpdate({ child: { $exists: false } }, { $set: { child: { name: "Update Creation" }}});

        const updatedParent: any = await Test.findOne({ age: 10 });
        assert(typeof updatedParent.child.created !== "undefined");
    });
    it("Mongoose save behaves as expected", async () => {
        const Test = mongoose.model('Test', testSchema);
        await Test.create({ age: 10 });

        const parentToChange: any = await Test.findOne({ child: { $exists: false }});
        parentToChange.child = { name: "Update Creation" };
        await parentToChange.save();
        
        const updatedParent: any = await Test.findOne({ age: 10 });
        assert(typeof updatedParent.child.created !== "undefined");
    });
});
```

**What is the expected behavior?**

Both test cases should pass, yet only the explicit `$set` behaves as expected.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

I observed the behaviour after updating to version 6.2.9 from previously 5.11.2. In the 5.x version, this worked as expected.

**Comment by vkarpov15** [comment] 2022-04-18 21:29
Confirmed. It looks like the cause of this issue is that, because subdocument `isNew` is the same as parent `isNew` after #7048, schema timestamps aren't working correctly for subdocuments. We're working on a fix and should have a fix released within the next couple of days.

**Closed** 2022-04-19 02:02 UTC
Labels: confirmed-bug
