### ISSUE TITLE
Wrong typescript definitions for the string version of the document´s _id

### ISSUE THREAD

**Issue by OmarOmeiri** [Automattic/mongoose#11050] opened 2021-12-06 13:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Wrong type definitions for typescript "id"

**What is the current behavior?**

The string version of the document `_id` is typed as `any`.
Even the comment says it should be the string version of the document´s id.

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
602:   /** The string version of this documents _id. */
603:    id?: any;
```
**What is the expected behavior?**

If it is the string version of the document´s `id`, it should be typed as `string`
type `any` makes any type checking imposssible .

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node: 16.13.0
mongoose: 6.0.14
mongodb: 4.2.1

**Comment by vkarpov15** [comment] 2021-12-07 17:18
Duplicate of https://github.com/Automattic/mongoose/pull/10248 . TLDR; as long as we support `extends Document`, we need `id: any`, otherwise devs won't be able to define a custom `id` property in their schema. Because `id: string` means you can't do `id: number` in a class that `extends Document` in TypeScript.

**Closed by vkarpov15** 2021-12-07 17:18 UTC
Labels: typescript
