### ISSUE TITLE
Can't save nested sub docs

### ISSUE THREAD

**Issue by rcleroux** [Automattic/mongoose#3444] opened 2015-10-08 08:01 UTC
Hi,

I have this setup where a Book has a sub document Transaction that has a sub document TransactionLine.

```
'use strict';

var mongoose          = require('mongoose'),
    Schema            = mongoose.Schema,
    AccountSchema     = require('./../account/account.model').schema,
    TransactionSchema = require('./../transaction/transaction.model').schema,
    modelConfig       = require('./../../config/models'),
    modelName         = modelConfig.Book.name,
    userModelName     = modelConfig.User.name,
    BookSchema        = new Schema({
        name: String,
        accounts: [AccountSchema],
        transactions: [TransactionSchema],
        _user: {
            type: Schema.ObjectId,
            ref: userModelName
        }
    }),
    BookModel         = mongoose.model(modelName, BookSchema);

module.exports = BookModel;
```

```
'use strict';

var mongoose              = require('mongoose'),
    Schema                = mongoose.Schema,
    TransactionLineSchema = require('./../transactionLine/transactionLine.model').schema,
    modelConfig           = require('./../../config/models'),
    modelName             = modelConfig.Transaction.name,
    TransactionSchema     = new Schema({
        description: String,
        comment: String,
        date: Date,
        transactionLines: [TransactionLineSchema]
    }),
    TransactionModel      = mongoose.model(modelName, TransactionSchema);

module.exports = TransactionModel;
```
```
'use strict';

var mongoose              = require('mongoose'),
    Schema                = mongoose.Schema,
    modelConfig           = require('./../../config/models'),
    modelName             = modelConfig.TransactionLine.name,
    accountModelName      = modelConfig.Account.name,
    TransactionLineSchema = new Schema({
        amount: Number,
        _account: {
            type: Schema.ObjectId,
            ref: accountModelName
         }
    }),
    transactionLineModel = mongoose.model(modelName, TransactionLineSchema);

module.exports = transactionLineModel;
```

I can successfully add transactions to a book, and persist them. But, when I push transactionGroups into transactions, doesn't matter if I call book.save() or transaction.save(), it's not persisted. Any idea why?

**Comment by ludydoo** [comment] 2015-10-08 18:02
Sorry I'm the author of this issue.

I've got it working now with a hack.

If I add transactionLines to one of the book's transactions, I have to set book.markedModified('transactions') for mongoose to actually understand that it was modified when doing book.save(). 

I did not investigate the issue further, but I'm guessing that when pushing a sub-document into a document's subdocument, it does not notify the root document that his subdocument's path must be marked as changed. It only works when the pushed subdocuments are a direct child of the root document. In other words, modify notifications only get bubbled up one level.

**Comment by vkarpov15** [comment] 2015-10-08 18:42
How are you actually adding transaction lines to transactions?

**Comment by ludydoo** [comment] 2015-10-08 20:23
transaction.transactionLines.push(transactionLine)

**Comment by vkarpov15** [comment] 2015-10-12 12:58
The below script executes without error for me. Can you modify the below script and see if you can make it reproduce your issue?

```javascript
var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
mongoose.set('debug', true);

mongoose.connect('mongodb://localhost:27017/gh3444');

var TransactionLineSchema = new Schema({
  amount: Number,
  _account: {
    type: Schema.ObjectId
   }
});

var TransactionSchema = new Schema({
  description: String,
  comment: String,
  date: Date, 
  transactionLines: [TransactionLineSchema]
});

var BookSchema = new Schema({
  name: String,
  transactions: [TransactionSchema],
  _user: {
    type: Schema.ObjectId
  }     
});

var Book = mongoose.model('book', BookSchema);

Book.create({ name: 'test', transactions: [{ transactionLines: { amount: 25 } }] }, function(error, doc) {
  assert.ifError(error);
  Book.findOne({ _id: doc._id }, function(error, doc) {
    doc.transactions.id(doc.transactions[0]._id).transactionLines.push({ amount: 50 });
    doc.save(function(error) {
      assert.ifError(error);
      Book.findOne({ _id: doc._id }, function(error, doc) {
        assert.equal(doc.transactions[0].transactionLines.length, 2);
        process.exit(0);
      });
    });
  });
});
```

**Comment by vkarpov15** [comment] 2015-10-27 00:41
Issue is stale and can't reproduce. Re-open if this is still an issue.

**Closed by vkarpov15** 2015-10-27 00:41 UTC
Labels: can't reproduce
