### ISSUE TITLE
mongoose with mongodb 5

### ISSUE THREAD

**Issue by armaccs** [Automattic/mongoose#10467] opened 2021-07-17 20:48 UTC
Is there compatibility of mongoose with the new version of mongodb 5?
"mongoose": "^5.13.3"
node: 14.17.3
mongoDB: 5.0.0
"npm": "7.20.0"

my app does not work with mongodb5 and I interact only with with mongoose.

Thanks!

**Comment by andalike** [comment] 2021-07-18 08:16
Duplicate of [10454](https://github.com/Automattic/mongoose/issues/10454)

**Comment by vkarpov15** [comment] 2021-07-19 21:16
We're finishing up Mongoose 6.0 and expect to have a release candidate out in the next week or two. Mongoose 5.13.x is unfortunately not fully compatible with MongoDB 5.0.

**Closed by vkarpov15** 2021-07-19 21:16 UTC
Labels: duplicate
