### ISSUE TITLE
Extract Schema??

### ISSUE THREAD

**Issue by vixalien** [Automattic/mongoose#11797] opened 2022-05-11 22:43 UTC
Is it possible to extract and isolate all `schema` related files (such as schematypes, types etc) to own files (or maybe module) because Mongoose has one of the best validation/schema thingy and it would be nice if it was isolated so as to be used independently of mongoose.

**Comment by vixalien** [comment] 2022-05-29 07:33
people??

**Comment by vkarpov15** [comment] 2022-06-10 21:28
Duplicate of #4282. This is something we'd like to do, but just haven't gotten around to yet.

**Closed by vkarpov15** 2022-06-10 21:28 UTC
Labels: help
