### ISSUE TITLE
Use MongoClient.connect() instead of authenticate() if user provides URI to avoid Db.prototype.authenticate deprecated

### ISSUE THREAD

**Issue by glecoz** [Automattic/mongoose#5304] opened 2017-05-28 15:21 UTC
I'm using a connection method like :

```
var Mongoose = require('mongoose');
connectionUrl = mongodb://some_login:some_pwd@some_host:27017/some_db?authSource=admin
Mongoose.connect(connectionUrl); 
```
... as indicated in the [docs](http://mongoosejs.com/docs/connections.html), but receiving the following **warning** on NodeJS console :

```
Db.prototype.authenticate method will no longer be available 
in the next major release 3.x as MongoDB 3.6 will only allow auth 
against users in the admin db and will no longer allow multiple credentials on a socket. 
Please authenticate using MongoClient.connect with auth credentials.

Connection with database succeeded.
```

(I get an authentication failure if I omit `?authSource=admin`)

**Is this normal at this stage (do we need to wait for a next mongoose release ?), 
or what should I  change from now ?**

Versions :

Node : 7.10.0
Mongoose : 4.10.3
MongoDB : 3.4

Thank you.

**Comment by wellcaffeinated** [comment] 2017-05-28 22:38
+1

**Comment by monkeymon** [comment] 2017-05-29 08:54
+1

**Comment by AussieFlem** [comment] 2017-05-29 11:11
+1
Mac OS X 10.12.5
Node: v7.10.0
Mongoose: 4.10.3
MongoDB v3.4.4

**Comment by cbratschi** [comment] 2017-05-29 15:13
+1

**Comment by varunjayaraman** [comment] 2017-05-29 16:01
yup looks like it only happens once you actually touch the db to do some operation (like a write):

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5304`;


exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.connect(`mongodb://gh_5304:gh_5304@localhost:27017/${ GITHUB_ISSUE }?authSource=admin`);

    const schema = new mongoose.Schema({ name: String });

    const Model = db.model('Model', schema);

    const doc = yield Model.create({ name: 'Test' });
  });
}
```

Log output:

```
Db.prototype.authenticate method will no longer be available in the next major release 3.x
as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow
multiple credentials on a socket. Please authenticate using MongoClient.connect with auth c
redentials.
successfully ran program
```

I'll mark this as a "bug", although tbh I'm not sure what I would describe this as. It's definitely a warning that should be heeded...

**Comment by vkarpov15** [comment] 2017-05-29 18:32
The `authSource` issue is expected behavior atm, if you're connecting to `some_db` and your user is not defined on the `some_db` database, you need to specify `authSource`.

Re: the warning, this is something mongoose will have to carefully work around because that is the only way mongoose auth works right now. Even if you specify credentials in MongoClient.connect(), mongoose will still call `authenticate()` under the hood. The plan right now is to make 4.11 use `MongoClient.connect()` if you just provide a URI, or fall back to mongoose's internal connection logic if you use host, user, etc.

**Comment by vkarpov15** [comment] 2017-05-29 18:37
Until 4.11, I wouldn't worry about this warning. To the best of my knowledge, MongoDB 3.6 and MongoDB driver 3.0 are unlikely to be released until much later this year and these changes will not require any end user changes.

**Comment by glecoz** [comment] 2017-05-29 19:23
Thanks @varunjayaraman @vkarpov15 for your detailed answers ;)

**Comment by JonathanBristow** [comment] 2017-05-29 19:29
Does anyone know of a way to disable/hide this message? I keep seeing it come up when I spawn a process and it's getting on my nerves! 😅

**Comment by pumano** [comment] 2017-05-30 15:55
I have same issue.

**Comment by vipinshar** [comment] 2017-05-30 16:58
I have also same issue. I don't know should i use mongoose or not.

**Comment by GuidoNebiolo** [comment] 2017-05-30 21:02
+1

**Comment by omidmaldar** [comment] 2017-05-31 06:15
the same issue here

**Comment by jeanmw** [comment] 2017-05-31 12:15
+1

**Comment by marodriguez-llbean** [comment] 2017-05-31 19:19
+1 
Mongoose: 4.10.3
MongoDB v3.4

**Comment by varunjayaraman** [comment] 2017-05-31 19:58
if you want to turn off warnings from the mongodb driver until 4.11, you can try using the steps here and use the underlying client from mongoose to set the logger:

http://mongodb.github.io/node-mongodb-native/2.2/reference/management/logging/

otherwise you will be fine and the problem should be resolved in `4.11`

**Comment by guimafx** [comment] 2017-06-01 13:46
+1

**Comment by msaiganesh** [comment] 2017-06-02 06:25
const mongoose = require('mongoose');
var db = mongoose.connect("mongodb://saiganesh:saiganesh6997@ds161121.mlab.com:61121/tester");

var Scheme = mongoose.Schema({
  title:  String,
  author: String,
  body:   String,
  comments: [{ body: String, date: Date }],
  date: { type: Date, default: Date.now },
  hidden: Boolean,
  meta: {
    votes: Number,
    favs:  Number
  }
});
module.exports = db.model('mongodb', Scheme);




var BlogPost = require("./models/mongodb.js");

//create new model
var post = new BlogPost({title: "My first post", author: "saiganesh",
													body: "We want to make documentation obsolete"});

post.save(function (err) {
  if (err) {
		return err;
  }
  else {
  	console.log("Post saved");
  }
});



error:

 node .\index.js(node:2604) DeprecationWarning: Mongoose: mpromise (mongoose's de
fault promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin
 db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
 
events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: Authentication failed.
    at Function.MongoError.create (C:\Users\saiganesh\Desktop\socket.io-master\examples\chat\mongoosedb\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\saiganesh\Desktop\socket.io-master\examples\chat\mongoosedb\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\Users\saiganesh\Desktop\socket.io-master\examples\chat\mongoosedb\node_modules\mongodb-core\lib\connection\pool.js:443:
16)
    at Connection.messageHandler (C:\Users\saiganesh\Desktop\socket.io-master\examples\chat\mongoosedb\node_modules\mongodb-core\lib\connection\pool.js:4
77:5)
    at Socket.<anonymous> (C:\Users\saiganesh\Desktop\socket.io-master\examples\chat\mongoosedb\node_modules\mongodb-core\lib\connection\connection.js:32
1:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by amand1996** [comment] 2017-06-02 11:26
Which MongoDB and Mongoose version shall I use to avoid this error?

**Comment by amand1996** [comment] 2017-06-02 17:36
Which MongoDB and Mongoose version shall I use to avoid this error?

**Comment by sensugaz** [comment] 2017-06-03 21:35
this is bug right ?

**Comment by juniormayhe** [comment] 2017-06-03 22:59
I am getting the same issue. MongoDB shell version v3.4.2
dependencies in package json: "mongodb": "^2.2.28", "mongoose": "^4.10.4"

**Comment by sensugaz** [comment] 2017-06-03 23:01
"mongoose": "~4.10.2", is work!

**Comment by juniormayhe** [comment] 2017-06-03 23:10
Ok now I have removed node_module folders and changed package.json to use fixed older version "mongoose":"4.10.2". After npm install, the warning message is gone:

`├─┬ mongodb@2.2.28 
│ └── mongodb-core@2.1.12 
└─┬ mongoose@4.10.2 
  └─┬ mongodb@2.2.26 
    └── mongodb-core@2.1.10 
`
I am afraid this is not a good approach. There should be compatibility between latest mongoose and mongo softwares

**Comment by sensugaz** [comment] 2017-06-04 07:15
Yes, I'm waiting for bug fixes maybe a next version

**Comment by varunjayaraman** [comment] 2017-06-04 20:26
please do not just comment `+1` we have clearly responded to this by stating that it is not a breaking bug, marking the issue as a `confirmed-bug`, and that you should be fine until mongoose 4.11. It is simply a warning message and I even posted a way to that you could use the mongodb logger to hide the message if you want to mute it. I don't mean to be an ass about it, but the +1 messages simply flood our inboxes, which is particularly annoying when reading the thread would show that the issue has been addressed

**Comment by varunjayaraman** [comment] 2017-06-04 20:27
as for your issue @msaiganesh that seams to be a separate issue related to your db authentication. Can you please open up a separate issue?

**Comment by ggwc82** [comment] 2017-06-07 08:30
"mongoose": "^4.10.4"

I'm getting this error also - I take it it's just a warning message as opposed to a bug, and doesn't prevent me from continuing?

**Comment by DennisEnt** [comment] 2017-06-07 22:50
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

I keep getting this error when I run npm start on my MEAN app. I can't start the app. Can anyone help?

**Comment by JonathanBristow** [comment] 2017-06-08 08:29
Please read the issue in full before sending asking an already answered question and inadvertently sending an email to everyone who has subscribed to updates on this issue.

**Comment by wangkangmao** [comment] 2017-06-13 13:27
I wonder how you solved it  @JonathanBristow

**Comment by Thinkdiff** [comment] 2017-06-17 23:51
I`v read these comments in this page but I still can`t fix this problem!! could you check my code?

this is my connection code:

> mongoose.Promise = require('bluebird');
mongoose.connect("mongodb://<username>:<password>@cluster0-shard-00-00-xlnqd.mongodb.net:27017,cluster0-shard-00-01-xlnqd.mongodb.net:27017,cluster0-shard-00-02-xlnqd.mongodb.net:27017/<database>?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin", function(err){
    if(err){
        console.log(err);
    } else {
        console.log('connected to the database successfuly.');
    }
});

and I got this warning: 
"Db.prototype.authenticate method will no longer be available in the next 
major release 3.x as MongoDB 3.6 will only allow auth against users in the 
admin db and will no longer allow multiple credentials on a socket. Please 
authenticate using MongoClient.connect with auth credentials."

**Comment by JonathanBristow** [comment] 2017-06-17 23:54
I have no words.

**Comment by vikaspotluri123** [comment] 2017-06-18 00:01
@thinkdiff ... it's a `warning`, not an `error`. A warning generally indicates something that's not going to break the code. In English: there's nothing structurally wrong, don't worry about it.

**Comment by vkarpov15** [comment] 2017-06-20 20:47
I'm locking this issue temporarily to prevent continued spam. There will be an option that will shut off this warning in 4.11, which will be released this week barring any unforeseen delays. Thank you for your patience.

**Closed** 2017-06-25 09:30 UTC
Labels: confirmed-bug, underlying library issue
