### ISSUE TITLE
Exception: Cursor id xxxx not found

### ISSUE THREAD

**Issue by useo6** [Automattic/mongoose#6629] opened 2018-06-28 12:07 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] bug
- [ ] feature

**What is the current behavior?**

I'm using MongoDB Atlas with WiredTiger (MongoDB 3.6) engine that enables me to use Change Streams. Basically it works but sometimes my NodeJS app crashes with an exception "cursor id 6520755503057538559 not found". Sometimes my application is running for several hours without any error.

**If the current behavior is a bug, please provide the steps to reproduce.**
Unfortunately I don't know how to reproduce this behavior, but the error is as follows:

> uncaughtException: cursor id 9099471977467727757 not found date=Thu Jun 28 2018 14:03:39 GMT+0200 (Mitteleuropäische Sommerzeit), pid=8276, uid=null, gid=null, cwd=C:\Projects\ChangeStream, execPath=C:\Program Files\nodejs\node.exe, version=v8.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Projects\ChangeStream\index.js], rss=48721920, heapTotal=27619328, heapUsed=23470992, external=18515933, loadavg=[0, 0, 0], uptime=353566.7076712
> MongoError: cursor id 9099471977467727757 not found
>     at C:\Projects\ChangeStream\node_modules\mongodb-core\lib\connection\pool.js:593:63
>     at authenticateStragglers (C:\Projects\ChangeStream\node_modules\mongodb-core\lib\connection\pool.js:516:16)
>     at Connection.messageHandler (C:\Projects\ChangeStream\node_modules\mongodb-core\lib\connection\pool.js:552:5)
>     at emitMessageHandler (C:\Projects\ChangeStream\node_modules\mongodb-core\lib\connection\connection.js:309:10)
>     at TLSSocket.<anonymous> (C:\Projects\ChangeStream\node_modules\mongodb-core\lib\connection\connection.js:452:17)
>     at emitOne (events.js:116:13)
>     at TLSSocket.emit (events.js:211:7)
>     at addChunk (_stream_readable.js:263:12)
>     at readableAddChunk (_stream_readable.js:250:11)
>     at TLSSocket.Readable.push (_stream_readable.js:208:10)
>     at TLSWrap.onread (net.js:607:20)

Maybe someone has an idea what can cause/fix the problem?!

**Please mention your node.js, mongoose and MongoDB version.**

node.js --> 8.10.0
mongoose --> 5.1.7

**Comment by simllll** [comment] 2018-06-28 14:59
Hi @useo6 ,
is this a long runnign query? Did you try "no_cursor_timeout"? 
e.g. 
```
Model.find({
    }, {}, {
        timeout: true})
```
Otherwise I think you are also affected by the underlying mongodb issue https://jira.mongodb.org/browse/SERVER-34810
see also #6504 .

A temporary workaround is in this case sticking to mongoose@5.0.14.

Regards
Simon

**Comment by useo6** [comment] 2018-06-28 16:50
Hi simllll,
I'm not executing a find() query. I'm using change streams to track collection updates. I'm just doing something like:

```
MyModel.watch().on("change", data => {
    MyModel.hydrate(data.fullDocument)
})
```

**Comment by useo6** [comment] 2018-06-30 17:00
I'll add a comment during the upcoming business days. Thanks for your reply!

**Comment by AbdelrahmanHafez** [comment] 2018-07-07 21:13
I'd just like to mention that we've been having this exception as well for a month or so, once or twice a day.

Sadly, it seems to happen randomly, tough to reproduce.

**Comment by cosminn777** [comment] 2018-07-09 05:35
Happened to me too, but after upgrading to MongoDB 4.0 it didn't happened any more. So it might be a MongoDB related issue.

**Comment by shivpatel** [comment] 2018-07-26 17:11
Same issue here! According to SERVER-34810 the fix should be in 3.6.6, but still happens for me with Atlas MongoDB 3.6.6 (WiredTiger) and Mongoose 5.1.5. Hesitating on moving to 4.0 as we just upgraded from 3.4 to 3.6.

**Comment by SavePointSam** [comment] 2018-10-24 23:11
Hit this issue today running mongoose@5.2.3 and mongoDB@4.0.2. Not too sure what caused it and we've never hit this problem before. I'll post any other findings I have if something comes up!

**Comment by vkarpov15** [comment] 2018-10-30 21:12
So I've been trying to repro this for a while, with no results. Here's the most relevant MongoDB docs I can find on the subject: https://docs.mongodb.com/manual/reference/method/db.collection.watch/#behavior . My best guess is that there's a timeout somewhere that's causing the underlying socket to close, perhaps due to an OS-level timeout on the socket if there wasn't any activity for a while. But honestly, I don't think we'll be able to make any progress with this issue without being able to consistently reproduce it. The best recommendation I have would be to restart the change stream when an error occurs:

```
  let stream = Model.watch();
  stream.on('change', handleChange);
  stream.on('error', handleError);

  function handleError(err) {
    console.log('Got error', err);
    stream = Model.watch();
    stream.on('change', handleChange);
    stream.on('error', handleError);
  }

  function handleChange(change) {
    console.log('Got', change);
  }
```

**Closed by vkarpov15** 2018-10-30 21:12 UTC
Labels: needs repro script
