### ISSUE TITLE
Revive NamedScope

### ISSUE THREAD

**Issue by bakorer** [Automattic/mongoose#3737] opened 2016-01-06 10:05 UTC
I want to revive *NamedScope*.

- refs: https://github.com/Automattic/mongoose/issues/679, https://github.com/Automattic/mongoose/commit/26ed874ebf7bbdb368c5d052dac783727d7537f1

Please wait for my pull request.
If I implements NamedScope, can I add one?

**Comment by vkarpov15** [comment] 2016-01-06 17:17
At first glance, I don't quite understand what NamedScope is meant to do. Can you clarify?

**Comment by bakorer** [comment] 2016-01-07 06:31
@vkarpov15 Thank you for your quick reply.

NamedScope is meant to prepare the named query like below.

- ref: http://stackoverflow.com/questions/11863635/chaining-static-constructor-in-mongoose-like-scope-in-rails/11869563#11869563

```js
var UserNSSchema = new Schema({
    age: Number
  , gender: String
  , lastLogin: Date
});

UserNSSchema.namedScope('olderThan', function (age) {
  return this.where('age').gt(age);
});

UserNSSchema.namedScope('youngerThan', function (age) {
  return this.where('age').lt(age);
});

UserNSSchema.namedScope('twenties').olderThan(19).youngerThan(30);

UserNSSchema.namedScope('male').where('gender', 'male');

UserNSSchema.namedScope('female').where('gender', 'female');

UserNSSchema.namedScope('active', function () {
  return this.where('lastLogin').gte(+new Date - _24hours)
});

mongoose.model('UserNS', UserNSSchema);

UserNS.olderThan(20).find(function (err, found) { ... });
UserNS.olderThan(40).active.male.find(function (err, found) { ... });
```

**Comment by bakorer** [comment] 2016-01-07 08:59
refs: #679 #642 #455 #379

**Comment by vkarpov15** [comment] 2016-01-07 15:14
Seems related to #3740, etc. I'd love to see an implementation of this for 4.4 or 4.5 if you'd be willing to do one. Just one minor suggestion: 'NamedScope' is a confusing name IMO, doesn't really indicate what the feature does. I haven't been able to think of a better name yet though - any suggestions?

**Comment by eloytoro** [comment] 2016-01-07 20:32
:+1: for this idea, I agree with @vkarpov15 the name's a bit confusing.
If this were to be implemented then the order in which they are piled up shouldn't matter right?
```javascript
UserNS.olderThan(20).find()
// should be the same as
UserNS.find().olderThan(20)
```
I see that the fuctions are passed the Schema as the context, wouldnt it be better to take [Laravel's query builder's](https://laravel.com/docs/5.1/queries#advanced-where-clauses) implementation and use the query as a context?

**Comment by vkarpov15** [comment] 2016-01-07 21:28
@eloytoro it looks like the functions get the model (or query?) as the context, not the schema, at least based on @bakorer's examples

**Comment by eloytoro** [comment] 2016-01-07 21:37
Looks like it did take the query as the context before it got removed
See https://github.com/Automattic/mongoose/blob/9bdd71deccebd02cd0bf050b8c34ccc299ebb90c/lib/schema.js#L842-L862

**Comment by onbjerg** [comment] 2016-01-15 15:50
This is like a similar concept in Ruby on Rails and the PHP framework Laravel, called query scopes (or just scopes for RoR).

Here is an example snippet from the Laravel framework (implemented in the respective model class):

```php
/**
 * Scope a query to only include active users.
 *
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeActive($query)
{
    return $query->where('active', 1);
}
```

In essence it modifies the query before executing it, allowing to have a shorthand for common queries (i.e. scoping the queries). Global query scopes shared between all models are also available in Laravel. This is useful for e.g. pagination queries.

**Comment by onbjerg** [comment] 2016-01-16 03:04
Okay, so, the reason for named scopes not working previously is (at least partially) due to the fact that the named scope cumulative query is only merged with the model query when a model method is called, e.g. ``find``.

When one calls e.g. ``find``, the method ``Model._applyNamedScope`` is called, which is the function merging the two queries. Before this is called, no query is returned as a result of calling a named scope, as the current named scope is returned for method chaining.

Observe the following examples demonstrating:

```js
// Not possible as olderThan returns the named scope for method chaining,
// and skip is defined in the package mquery, which Query inherits from.
Person.olderThan(15).skip(1).find(...)

// Possible because .find is defined on the model object, which is what
// the named scopes are decorating.
Person.olderThan(15).find(...)

// Will not result in an error, but skip is ignored
Person.olderThan(15).find(...).skip(1)
```

A possible solution would be to merge the named scope with the cumulative query and return that instead of the current named scope. An obvious caveat of this would be that one cannot give your named scope the same name as methods in the ``Query`` class without breaking mongoose. All of the available query methods can be found in the package ``mquery``.

Thoughts? @vkarpov15 @bakorer

**Comment by eloytoro** [comment] 2016-01-16 03:14
Maybe it would be best if the "named scopes" acted as `where` queries.
Take this example extracted from the docs
```javascript
// instead of writing:
User.find({age: {$gte: 21, $lte: 65}}, callback);

// we can instead write:
User.where('age').gte(21).lte(65);
```
So it would be
```javascript
// The find operation is implied here
Person.olderThan(15).exec();

Person.find({/*...*/}).olderThan(15);
// would be the same as
Person.find({/*...*/}).where({age: {$gt: 15}});
```
But the named scope would allow you to define the query logic somewhere else

**Comment by onbjerg** [comment] 2016-01-16 03:21
@eloytoro This is not the issue. The issue is that specific instructions do not work before calling e.g. ``find`` or similar methods in the ``Model`` class, as the named scopes are not returning a query but rather the model for method chaining. See #379.

If we wanted to call ``find`` (or similar) every time we "apply" a named scope we would end up with something extremely inefficient (and maybe even yet again broken).

**Comment by onbjerg** [comment] 2016-01-16 03:34
I found out my "solution" wouldn't work. We somehow need to expose query methods on the return value of an invoked named scope while retaining the model methods (and therefore also retaining the defined named scopes, allowing for method chaining).

**Comment by eloytoro** [comment] 2016-01-16 07:38
I didn't mean to execute a `find` operation every time a named scope is used, but rather to allow using _only_ named scopes to create executable queries without the need to call `find` at the end of it, just like `where` works
To allow model query chaining I suggest subclassing `Query` for every model created, that way we can extend this `ModelQuery` prototype for each of the models registered onto the app and allowing users to extend it using some kind of API to define them, similar to the one used for methods or statics

**Comment by onbjerg** [comment] 2016-01-16 13:48
@eloytoro Oh, ok. Got you.

It seems that @bakorer is inactive both in the discussion and no code was pushed to his fork. Maybe someone else should pick it up? It would definitely be nice to have.

**Comment by onbjerg** [comment] 2016-01-16 15:17
There's an implementation of the Active Record thingy used in Ruby on Rails written in Node.js. It supports scopes. Maybe we could get some ideas from the source?

Link: https://github.com/PhilWaldmann/openrecord

**Comment by vkarpov15** [comment] 2016-01-16 19:58
My thought would be to just implement these as "query methods" sorta like [what monogram has](https://github.com/vkarpov15/monogram#it-custom-query-methods). It fits much more nicely with the mongoose paradigm.

As a side note, if only JS had a pipeline operator, this would be so much easier...

**Comment by onbjerg** [comment] 2016-01-16 20:23
@vkarpov15 So instead of scopes on the model itself, it would be "scopes" on queries? This would still require you to call e.g. ``Model.find`` to get a query to perform the scopes on.

**Comment by vkarpov15** [comment] 2016-01-18 14:14
"scopes" is a odd choice of name IMO. Imagine how you create methods on documents in mongoose:

```javascript
schema.methods.populateUserField = function(field) {
  this.populate(`user.${field}`);
  return this;
};
```

And you can then do `doc.populateUserField('friends').populateUserField('favorites');`. I'd imagine a similar API for queries. Yes you would need to call `Model.find();` to get a query to perform methods on, but we already have the ability to add methods to a model using [statics](http://mongoosejs.com/docs/guide.html#statics)

**Comment by onbjerg** [comment] 2016-01-18 23:38
@vkarpov15 This makes me wonder why the functionality was removed in the first place. It was removed partially due to issues such as https://github.com/Automattic/mongoose/issues/379.

**Closed** 2016-06-09 15:01 UTC

**Comment by gberger** [comment] 2016-06-24 03:45
Hi everyone. I have implemented named scopes as a plugin.

https://github.com/gberger/mongoose-named-scopes

@bakorer let me know if it fits your needs!
