### ISSUE TITLE
Problems updating documents with a 'status' field

### ISSUE THREAD

**Issue by fsanzv** [Automattic/mongoose#4076] opened 2016-04-14 16:54 UTC
Hi,

I'm using mongoose v.4.1.6 in a project and there is a script that runs this update:

```javascript
MyCollection.update({status: 'paid'}, {$set: {status: 'finished', 'payment.status': 'paid'}}, {multi: true}, (error, mongoResponse) => {
    if (error) {
        return next(error);
    }

    response += 'Paid documents updated: ' + JSON.stringify(mongoResponse) + '.';
        return next();
    });
});
```

This query finds the correct number of records, and update the records **but only updates 'payment.status' field, status field remains unmodified**.

We have added .collection to the model to perform the same update against mongo native driver and it works fine so we think there is a conflict with the status word in the mongoose layer.

This is the schema:
```javascript
let schema = new mongoose.Schema({
    userId: String,
    date: Date,
    status: String,
    payment: { // Payment info (only present when the booking has been paid)
        status: String,
        amount: Number,
        currency: String
    },
    createdAt: Date, // Created at (datetime)
    updatedAt: Date // Updated at (datetime)
}, {collection: 'myCollection'});
```
I'm using Mongoose 4.1.6 and nodejs 4.3.1. I have tried to use last version of mongoose but I'm getting this error:
```
(node) warning: possible EventEmitter memory leak detected. 11 reconnect listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:239:17)
    at connectDB [as _onTimeout] (/Users/fer/develop/SmartNode/ITTServer/app/loader.js:350:32)
    at Timer.listOnTimeout (timers.js:92:15)
```

I have tried to set `mongoose.Promise = global.Promise;` but the problem remains so I'm sticked to 4.1.6 version that works well with node 4.3.1.

Please, can you help me with the problem with the status field, I'm afraid this field can cause any other unexpected behaviors in any other part of the application.

And also, am I missing something to use last mongoose version with a nodejs 4.3.x?.

Thanks in advanced.

**Comment by dciccale** [comment] 2016-04-16 11:10
when you update a model and wants to get back the updated value, i think you should pass `{new: true}` as an option. something like this:

```js
MyCollection.update({status: 'paid'}, {$set: {status: 'finished', 'payment.status': 'paid'}}, {multi: true, new: true}, (error, mongoResponse) => {
    if (error) {
        return next(error);
    }

    response += 'Paid documents updated: ' + JSON.stringify(mongoResponse) + '.';
        return next();
    });
});
```

(haven't tried it)

**Comment by vkarpov15** [comment] 2016-04-16 15:16
The new option only works for findOneAndUpdate, not update.

Try setting debug mode, 'require('mongoose').set('debug', true)` and see what the actual update getting sent to mongodb is, so we can verify if this is a mongoose issue or not

**Comment by vkarpov15** [comment] 2016-04-16 20:39
Re: the event emitter issue, are you calling `useDb()` at all or opening multiple mongoose connections? Should be no issue using more recent versions of mongoose with node 4.

Re: your update info, you're going to have to provide me some additional context, the below script works fine for me with mongoose 4.1.6. Can you try modifying the below script to reproduce your issue?

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4076');
mongoose.set('debug', true);

let schema = new mongoose.Schema({
    userId: String,
    date: Date,
    status: String,
    payment: { // Payment info (only present when the booking has been paid)
        status: String,
        amount: Number,
        currency: String
    },
    createdAt: Date, // Created at (datetime)
    updatedAt: Date // Updated at (datetime)
}, {collection: 'myCollection'});

const Model = mongoose.model('test', schema);

Model.create({ status: 'paid' }, function(error, doc) {
  assert.ifError(error);
  Model.update({status: 'paid'}, {$set: {status: 'finished', 'payment.status': 'paid'}}, {multi: true}, function(error) {
    assert.ifError(error);
    Model.findById(doc._id, function(error, doc) {
      assert.ifError(error);
      assert.equal(doc.status, 'finished');
      assert.equal(doc.payment.status, 'paid');
      console.log('done');
      process.exit(0);
    });
  });
});
```

Output:

```
$ node gh-4076.js 
Mongoose: myCollection.insert({ status: 'paid', _id: ObjectId("5712a22f2a9335225a45482b"), __v: 0 })   
Mongoose: myCollection.update({ status: 'paid' }) { '$set': { status: 'finished', 'payment.status': 'paid' } } { multi: true } 
Mongoose: myCollection.findOne({ _id: ObjectId("5712a22f2a9335225a45482b") }) { fields: undefined }  
done
$ cat node_modules/mongoose/package.json | grep "version"
    "type": "version"
  "version": "4.1.6"
$
```

**Comment by fsanzv** [comment] 2016-04-16 23:29
Thank you for the response and for taking the time to write a test for this issue.

We are running in development with debug enabled and the output is:
`Mongoose: bookings.update({ status: 'paid' }) { '$set': { status: 'finished', 'payment.status': 'paid' } } { multi: true }`

When I wrote the issue, I could reproduce it consistently in my own development environment and in our live environment, but not now.

I have dropped the collection and created it again, so I suspect this issue could have some data related problem.

I have shared the issue with the project team so, if any one can still reproduce it, we will add more info to this issue.

About the event emitter issue, we are not using `useDb()` neither opening multiple mongoose connections.

Best regards and thank you again.

**Comment by vkarpov15** [comment] 2016-04-18 15:35
Ok thanks, I'll keep this open for now. Either way, given the mongoose debug output, it doesn't look like the issue is with mongoose.

Re: event emitter, that's very strange. Can you come up with a script that reproduces that warning?

**Comment by fsanzv** [comment] 2016-04-20 15:49
Hi again @vkarpov15,

We have found the problem for the event emitter. We are using in our develop environments MongoDB without authentication and we are not taking it into account when we create the connection URL (mongodb://:@localhost/mydb), this doesn't fail in 4.1.6 but it does in 4.4.12. Now we are connecting without problem with this URL: mongodb://localhost/mydb.

We still have not been able to reproduce the update issue.

Best regards and thank you.

**Comment by vkarpov15** [comment] 2016-04-21 21:53
Hmm I don't get that error even if I use `mongoose.connect('mongodb://:@localhost/gh4076')`. That's weird. Well, I'll close this for now, re-open if you find the issue again.

**Closed by vkarpov15** 2016-04-21 21:53 UTC
Labels: can't reproduce
