### ISSUE TITLE
DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

### ISSUE THREAD

**Issue by bricss** [Automattic/mongoose#6890] opened 2018-08-18 09:38 UTC
After update to version `5.2.9` I'm getting this message in console all the time, when I start my web app:

`DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`

And I don't use neither of them.

**Comment by Fonger** [comment] 2018-08-18 09:50
duplicate of #6880

**Comment by lineus** [comment] 2018-08-18 10:52
Thanks for taking the time to report the issue @bricss. Mongoose calls `ensureIndex()` internally. You can safely ignore the warning for now, or silence it with the node flag `--no-deprecation`, or downgrade to 5.2.8 if there are no specific fixes in 5.2.9 that you were relying on. Follow #6880 for updates 👍

**Comment by nonniv** [comment] 2018-08-23 00:54
,unique: true,index: true is on one field in one of my schemas and this triggers this warning. Question how to ensure a unique value without getting this warning.

**Comment by vkarpov15** [comment] 2018-08-27 13:02
@nonniv upgrade to 5.2.10 and set `mongoose.set('useCreateIndex', true);`

**Comment by lineus** [comment] 2018-08-28 00:26
@samuelcecilio what specific deprecation warnings are you seeing? There are some helpful notes in the comment that opened #6922, or feel free to share your specific warnings here and I'll see if I can help.

**Comment by samuelcecilio** [comment] 2018-08-28 00:36
`(node:9125) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.`

**Comment by lineus** [comment] 2018-08-28 00:40
@samuelcecilio the `mongoose.set('useCreateIndex', true)` should stop that warning as demonstrated by this example:

### 6922.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
mongoose.set('useCreateIndex', true);

const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: {
    type: String,
    unique: true
  }
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'one' });

async function run() {
  console.log(`mongoose version: ${mongoose.version}`);
  await conn.dropDatabase();
  await test.save();
  return conn.close();
}

run();
```
### Output:
```
issues: ./6922.js
mongoose version: 5.2.10
issues:
```

are you certain that your project is using 5.2.10? are there other packages in your project using other versions of mongoose, etc?

**Comment by samuelcecilio** [comment] 2018-08-28 01:06
Hi, thanks for the reply. Yes, I checked the version three times lol:

````
$ npm list --depth=0
...
 mongoose@5.2.10
...
````

My code

app.js
````
...

const config = require('./config')
const mongoose = require('mongoose')
const express = require('express')
const app = express()

mongoose.connect(config.dbUri, { useNewUrlParser: true })
mongoose.set('useCreateIndex', true)

....

module.exports = app
````

bin/www
````
#!/usr/bin/env node

const app = require('../app')
const config = require('../config')
const debug = require('debug')('blitz')
const http = require('http')
const port = normalizePort(process.env.PORT || config.port)
const mongoose = require('mongoose')

app.set('port', port)

const server = http.createServer(app)

server.listen(port)
server.on('error', onError)
server.on('listening', onListening)

const mongo = mongoose.connection

mongo.on('error', error => { debug('mongo: ' + error.name) })
mongo.on('connected', () => { debug('mongo: Connected') })
mongo.on('disconnected', () => { debug('mongo: Disconnected') })

....
````

When I run `DEBUG=blitz* npm run dev`

````
> nodemon bin/www

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node bin/www`
  blitz Listening on port 3000 +0ms
  blitz mongo: Connected +14ms
(node:10622) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
````

**Comment by lineus** [comment] 2018-08-28 01:11
@samuelcecilio  maybe move the `mongoose.set('useCreateIndex', true)` to the `bin/www` file instead? I'll setup an express example and test as well.

**Comment by samuelcecilio** [comment] 2018-08-28 01:29
I use separate files for users, customers, suppliers, orders, items..

This stopped the warning:

models/user.js
````js
const addressSchema = require('./address')
const profileSchema = require('./profile')
const uuidv4 = require('uuid/v4')
const mongoose = require('mongoose')
const Schema = mongoose.Schema

mongoose.set('useCreateIndex', true)

const userSchema = new Schema({
  disabled: { type: Boolean, default: false },
  roles: { type: Array, default: [ 'assistant' ] },
  identity: { type: String, unique: true, required: true },
  username: { type: String, unique: true, required: true },
  name: { type: String, uppercase: true, required: true },
  password: { type: String, required: true },
  secret: String,
  profile: profileSchema,
  address: addressSchema,
  created: Date,
  modified: Date
}, {
  collection: 'users'
})

userSchema.pre('save', function (next) {
  const doc = this
  doc.created = Date.now()
  doc.modified = Date.now()
  doc.secret = uuidv4()
  next()
})

module.exports = mongoose.model('User', userSchema)

````

I figured it would be some global setting, but apparently I have to add in all the files.

**Comment by lineus** [comment] 2018-08-28 01:41
@samuelcecilio you could wrap mongoose in a custom file, something like

### myMongoose.js
```js
const mongoose = require('mongoose')
mongoose.set('useCreateIndex', true);
//etc
module.exports = mongoose
```
and then require your wrapper instead of mongoose everywhere. That's probably something like what I'll end up having to do when I start upgrading beyond 5.2.8.

**Comment by samuelcecilio** [comment] 2018-08-28 01:59
Still I would have to modify all current files. For each file in the `models` folder, I would replace `require ('mongoose')` with `require('myMongoose')`. The same would apply to `app.js` and `bin/www`.

The question is: in a future version of `mongoose` I will not need to include `mongoose.set ('useCreateIndex', true)` or will this be normal, for compatibility issues with older versions of mongo, node, etc ...?

**Comment by lineus** [comment] 2018-08-28 02:12
I suspect the behavior will remain as it is now until the next major version (ie **6.0.0** ) of mongoose.

**Comment by samuelcecilio** [comment] 2018-08-28 02:35
For now, I've added `mongoose.set('useCreateIndex', true)` to all files that contain `require('mongoose')`. I'm thinking of using a wrapper `('./myMongoose')` or `('./mongoose-custom')`. What do you think?

Should this be global? Is it an express issue?

**Comment by bricss** [comment] 2018-08-28 08:54
It's really uncomfortable to add `mongoose.set('useCreateIndex', true)` in every single file that contain model declarations.
Why is not make it work from `connect` options as well, or set it before connection?

**Comment by vkarpov15** [comment] 2018-08-29 18:10
You don't need to put this in every file, but unfortunately it looks like right now you need to put mongoose.set('useCreateIndex', true) before any mongoose.model() calls. That is tricky if you export models as opposed to schemas. Will add a fix for this.

**Closed** 2018-09-02 14:04 UTC
Labels: enhancement

**Comment by samuelcecilio** [comment] 2018-09-05 01:54
After upgrading to version 5.2.13, should this stop the warnings? Thanks

````javascript
mongoose.connect(config.dbUri, {
  useCreateIndex: true,
  useNewUrlParser: true
})
````

````bash
the options [useCreateIndex] is not supported
server: listening on port 3000 +0ms
mongo: Connected +34ms
(node:18457) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
````

**Comment by lineus** [comment] 2018-09-05 11:17
@samuelcecilio `useCreateIndex` isn't a connection option, but as long as you call `mongoose.set('useCreateIndex', true);` before calling `mongoose.model()` ( even in other files ) all subsequent calls to mongoose.model should fallback to the option you set with `mongoose.set()`. I tested 5.2.13 with my example above,  instead calling `mongoose.set('useCreateIndex', true)` in the bin/www file and **not** in my route. It works now.

**Comment by LucHighwalker** [comment] 2018-09-06 15:59
I have my mongo connection in a separate script. This way I just call mongoose.set('useCreateIndex', true); right before actually connecting to mongo. Then there's no need to put it in any of my model declarations.

**Comment by cloakedch** [comment] 2018-09-23 13:17
Is there any functional difference between

```
mongoose.connect(encodeMongoURI(dbURI), options);
mongoose.set('useCreateIndex', true);
```

and 

```
mongoose.set('useCreateIndex', true);
mongoose.connect(encodeMongoURI(dbURI), options);
```

? Because both seem to work just fine in 5.2.17

**Comment by samuelcecilio** [comment] 2018-09-23 14:30
````
mongoose.connect(config.dbUri, {
  useCreateIndex: true,
  useNewUrlParser: true
})
````

Works with the latest version

**Comment by cloakedch** [comment] 2018-09-23 15:07
Okay, i guess @types/mongoose are behind then (Doesn't work on typescript yet).

**Comment by jrmatos** [comment] 2018-09-25 23:46
@Dionesio's answer did the trick to me. Thanks!

**Comment by darshanan24** [comment] 2018-10-05 10:43
mongoose.connect("mongodb://localhost:27017/test", {useNewUrlParser: true});
mongoose.set('useCreateIndex', true);


This solved all my deprecation warnings.

**Comment by amolbhandari52** [comment] 2018-11-28 10:22
> @samuelcecilio after playing around with this some, I found that I needed to set useCreateIndex to true in the route file that contained the model. In my case, after using the express cli tool, I needed to set useCreateIndex in the index route shown below:
> 
> ```js
> var express = require('express');
> var router = express.Router();
> const mongoose = require('mongoose');
> mongoose.set('useCreateIndex', true);
> const Test = mongoose.model('test', { name: {type: String, unique: true }});
> 
> /* GET home page. */
> router.get('/', function(req, res, next) {
>   Test.create({ name: 'billy' }).then((doc) => {
>     return res.status(200).json({ done: true, test: doc.id });
>   }).catch((e) => {
>     return res.status(500).json({ err: e });
>   });
> });
> 
> module.exports = router;
> ```
> 
> without the option set in the index route I got:
> 
> ```
> [nodemon] starting `node bin/www`
> version: 5.2.10
> (node:17042) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
> ```
> after setting the option in the route I got:
> 
> ```
> [nodemon] starting `node bin/www`
> version: 5.2.10
> ^C
> ```
> I tried setting it in bin/www but that did not get rid of the warning. Only setting it in the route was successful.
> 
> ### output of curling localhost
> ```
> ~>: curl localhost:3000/
> {"done":true,"test":"5b84a4e13ec72e4352475426"}~>: 
> ~>: 
> ```
Thanks - Adding mongoose.set('useCreateIndex', true); fixed my issue
