### ISSUE TITLE
removing parent document does not call embedded documents pre('remove' middleware

### ISSUE THREAD

**Issue by barroudjo** [Automattic/mongoose#2348] opened 2014-10-06 15:05 UTC
Given a simple embedded document scheme like this one:
```
var answersSchema = new Schema({
    answerer: { type: Schema.Types.ObjectId, ref: 'User' },
    answersList: [{index: Number, value: Number}]
});

answersSchema.pre('remove', function (next) {
    console.log('went through "remove" middleware for embedded doc !');
});

var questionnaireSchema = new Schema({
    name: String,
    answers: [answersSchema],
});
```

I would expect that calling: 
```
Questionnaire.find({name: 'test'}, function (err, questionnaire) {
    questionnaire.remove(function (err) {
        console.log('removed questionnaire');
    });
});
```
would get the pre('remove' middleware defined above for the embedded doc called. But it does not. Is this a bug or normal behavior ?

**Comment by radekn** [comment] 2015-02-04 16:37
I've been bitten by this just now. The issue is closed, does it mean it has been fixed in some version?

**Comment by vkarpov15** [comment] 2015-02-04 18:53
Woops, yeah, this was closed unexpectedly.

**Comment by barroudjo** [comment] 2015-02-04 19:03
Sorry, I'm the that closed it as I used the workaround I posted above.

**Comment by Malusia** [comment] 2015-09-02 16:08
Status?

**Comment by vkarpov15** [comment] 2015-09-02 16:45
No progress yet.

**Comment by Malusia** [comment] 2015-09-02 16:58
Ok, thank you for the fast answare. A little Question: Did you see any problems in this workaround, based on the workaround from barroudjo?

```javascript
'use strict';

var async = require('async');

/**
 * Mongoose plugin
 *
 * @param schema
 */
module.exports = function (schema) {

	/**
	 * This workaround will trigger the remove middleware of embedded documents.
	 *
	 * @see https://github.com/Automattic/mongoose/issues/2348
	 */
	schema.pre('remove', function (next) {

		async.eachSeries(Object.keys(this._doc), function (key, next) {
			if (!this._doc[key].isMongooseDocumentArray) {
				return next();
			}

			async.eachSeries(this._doc[key], function (embedded, next) {
				embedded.remove(next);
			}, next);
		}.bind(this), next);
	});
};
```

**Comment by vkarpov15** [comment] 2015-09-02 18:23
It'll only trigger remove hooks on top-level document arrays, so if you have a document array in a subdocument, this won't trigger it. Otherwise, should work.

**Comment by Malusia** [comment] 2015-09-03 06:55
Ok, thank you. Yes I have to add this plugin to every schema.

**Comment by antonsamarsky** [comment] 2015-09-07 08:59
Malusia,
Thank you for a the plugin. Looks like it also need to check if embedded document has _id.
For my case some embedded documents don't have _id's of purpose, and it fails with "Error: For your own good, Mongoose does not know how to remove an EmbeddedDocument that has no _id".
Something like this:
async.eachSeries(this._doc[key], function(embedded, next) {
	if (!embedded._id) {
		return next();
	}

	embedded.remove(next);
}, next);

**Comment by Malusia** [comment] 2015-09-07 09:34
Good to know, I will add this to my plugin. Thank you!

**Comment by Malusia** [comment] 2015-09-07 10:45
I added your note to my unit tests. This error message occures everytime, with and without the plugin if a embedded document has no _id. The if statement will not work.

**Closed** 2016-06-13 13:48 UTC
Labels: enhancement, fixed?
