### ISSUE TITLE
findOneAndUpdate() with runValidators does not throw ValidationError

### ISSUE THREAD

**Issue by botv** [Automattic/mongoose#9311] opened 2020-08-09 03:20 UTC
### **Current behavior**

When using `findOneAndUpdate()` on an existing document with the `runValidators` option, no error is thrown if validation fails.

### **Steps to reproduce**

```js
const userSchema = new mongoose.Schema({
  name: { type: String, required: true }
  email: {
    type: String,
    required: true, 
    validate: () => false
  }
});

const user = await Release.findOneAndUpdate(
  { _id: '...' },
  { email: 'johndoe@gmail.com' },
  { runValidators: true, new: true },
);
```

### **Expected behavior**

A `ValidationError` should be thrown, because in the schema the validator will fail regardless of the value.

### **Environment**

- **Node.js**: v14.7.0
- **Mongoose**: v5.9.26

**Comment by LudwikJaniuk** [comment] 2020-08-09 15:55
I can't reproduce it. Same node.js version and mongoose version, and the operation correctly does throw an error:
```
Error: Validation failed: email: Validator failed for path `email` with value `johndoe@gmail.com`
```

However that does require that there really is an existing document. This is nontrivial for your schema, since that validator makes it impossible to create any documents. To test this, I first wrote it with the validator returning true, and under that schema I created a document. Then I changed back and tried your findOneAndUpdate, substituting the id for the existing object. As said, error was successfully thrown, so I propose to close this issue.

**Closed** 2020-08-09 16:01 UTC
