### ISSUE TITLE
Timestamps and bulkWrite for insertOne

### ISSUE THREAD

**Issue by binarytracer** [Automattic/mongoose#5708] opened 2017-10-13 08:43 UTC
file: ReportModel.js
```js
const newSchema  = new Schema({
counter: {type: Number, default: 0},
name: {type: String, default: 'nothing' },
country: String
}, {versionKey: false});

module.exports = connection.model('reports', newSchema);
```
-------
file: another-job.js
```js
  await ReportModel.updateOne(recordConditions, {
        $inc: {
          'counter': 1
        },
      }, { upsert: true, setDefaultsOnInsert: true });

```
- **result:** upsert and setDefaultsOnInsert works here.
-------

file: job.js
```js
const reportOperations = [];

const filter = {
 country: 'US',
};

reportOperations.push({
     updateOne: {
       filter,
       update: {
         $inc: {
           'counter': 1,
         },
       },
       upsert: true,
      setDefaultsOnInsert: true,
     },
});

await ReportModel.bulkWrite(reportsOperations);
```
the **upsert** works here, but what seems to not work is the **setDefaultsOnInsert**.

the **upserted record** has no **report.name** property.

Whats needs to be done here?

sources: 
- http://mongoosejs.com/docs/api.html#model_Model.bulkWrite
- http://mongoosejs.com/docs/defaults.html

**Comment by vkarpov15** [comment] 2017-10-14 16:04
Thanks for reporting, will investigate

**Comment by vkarpov15** [comment] 2017-10-15 00:32
Confirmed, here's the repro script:

```javascript
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.set('debug', true);
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017/test', { useMongoClient: true });

const newSchema = new Schema({
  counter: {type: Number, default: 0},
  name: {type: String, default: 'nothing' },
  country: String
}, {versionKey: false});

const ReportModel = mongoose.model('reports', newSchema);

run().catch(error => console.error(error.stack));

async function run() {
  const reportOperations = [];

  const filter = {
    country: 'US',
  };

  reportOperations.push({
    updateOne: {
      filter,
      update: {
        $inc: {
          'counter': 1,
        },
      },
      upsert: true,
      setDefaultsOnInsert: true,
    }
  });

  await ReportModel.bulkWrite(reportOperations);
}
```

Looks like we don't do `setDefaultsOnInsert` in `bulkWrite()`. Still working on a fix :+1: :palm_tree:

**Comment by binarytracer** [comment] 2017-10-17 23:40
thanks @vkarpov15, its working now.

**Comment by ashishlal91** [comment] 2018-08-18 07:56
@vkarpov15 not working for me... what's the reason?

**Comment by vkarpov15** [comment] 2018-08-19 19:43
@ashishlal91 please provide code samples, if you don't give me some idea of what your code looks like I can't provide much help.

**Comment by ashishlal91** [comment] 2018-08-20 05:12
@vkarpov15 Thank you for the reply... Here is my code

```
const createInvite = await Invite.bulkWrite(
        payload.invites.map((invite) => 
          ({
            updateOne: {
              filter: { sender: user, receiver: invite, status: 2, senderWorkoutId: addWorkout._id }, //requested
              update: { sender: user, receiver: invite, status: 2, senderWorkoutId: addWorkout._id, author: user },
              upsert: true, setDefaultsOnInsert: true, runValidators: true
            }
          })
        )
      )
```

Collection is being created from the above code but the `createdAt` and `updatedAt` field not being inserted. I have put the `setDefaultOnInsert` but it doesn't work... Please help

**Comment by ashishlal91** [comment] 2018-08-21 11:35
@vkarpov15  Any update

**Comment by halu886** [comment] 2018-08-25 03:58
@vkarpov15 Hello！

**Comment by vkarpov15** [comment] 2018-08-26 21:43
Oh ok so the problem is timestamps not getting updated on bulkWrite? We will look into that, thanks for reporting

**Comment by ashishlal91** [comment] 2018-08-27 05:06
@vkarpov15  yes the timestamps is not getting inserted or updated in the database on `upsert: true` and also the default values. This might be the problem with the `setDefaultsOnInsert`. Anyway thanks for reopening the issue.

**Comment by halu886** [comment] 2018-08-27 05:47
@ashishlal91 @vkarpov15  And here has an other question,:sweat_smile:
the `DataUnLean` Object want to change the `member ` model object.
I write a line code.
`(new Member(memberUnLean)).toObject()`.
emmm,Can I ask for you,
Mongoose  have more convenient Function in this case，`static Function` such as...
thank you very much!  :smiley:

**Comment by vkarpov15** [comment] 2018-08-28 01:50
@halu886 I don't understand your question, can you please clarify?

**Comment by halu886** [comment] 2018-08-28 01:58
@vkarpov15  oh,sorry
I mean,there is a not lean Data  `memberUnlean`  

    {
            name:"asdfasd",
            type:1,
            from:"asdfadsf",
            creator:{
                name:"asdfa",
                age:21,
                position:"asdfasdf",
                createdBy:"asdfasdf",
                createdAt:"asdf",
                updatedBy:"asdf",
                updatedAt:"asdf",
            }
    }

I want to change it to model Object  

    new Schame("Member",{
        name:string,
        type:number,
        creator:{
            name:string,
            age:number
        }
    },{timestampz:true})

    {
        name:string,
        type:number,
        creator:{
            name:string,
            age:number
        }
    }

so I try it by `(new Member(memberUnLean)).toObject()`
I have the question that it has better way?😅

**Comment by vkarpov15** [comment] 2018-08-29 14:06
Still not sure exactly what you're asking, but perhaps try [`Model.hydrate()`](https://mongoosejs.com/docs/api.html#model_Model.hydrate) ?

**Comment by lineus** [comment] 2018-08-29 15:06
@halu886 in your example above you have `{timestampz:true}`. I think that should be `{timestamps:true}`

**Comment by mmenik** [comment] 2018-09-03 09:57
I also have the problem that timestamps (updatedAt) not updated when I use findByIdAndUpdate mongoose function.

This is my schema:

`
export const BagSchema = new mongoose.Schema({...},
{
   timestamps: true,
});
`
and when I updated data with:

`this.bagModel.findByIdAndUpdate(bag._id, bag, { new: true, runValidators: true })`

updatedAt not change.

**Comment by lineus** [comment] 2018-09-06 10:59
@ashishlal91 I just looked at your comment above with the code sample. It has this line:

> but it doesn't work and also I have put timeStamp: true in schema... Please help

it should be `timestamps: true`.

**Comment by vkarpov15** [comment] 2018-09-06 13:31
Fix will be in 5.2.14 :+1:

**Comment by vkarpov15** [comment] 2018-09-11 13:41
@lineus thanks for pointing this out, you were right, we needed to call `initializeTimestamps()` to make sure `createdAt` and `updatedAt` get set for `insertOne` and `replaceOne`.

**Closed** 2018-09-11 13:40 UTC

**Comment by rogerkirkness** [comment] 2018-10-18 13:30
@vkarpov15 setDefaultsOnInsert is not working on bulkWrite again in 5.3.4 but did in all prior versions we tried were as we've used it for a while. Let me know what you need to diagnose.

**Comment by lineus** [comment] 2018-10-18 19:45
@rogerkirkness can you elaborate on what you mean by "not working"? Can you point to an existing example, or create a minimal one necessary to reproduce what you're seeing?

**Comment by rogerkirkness** [comment] 2018-10-19 17:44
It doesn't set defaults, it just silently fails to. I haven't changed the code, it just changed behaviour.

**Comment by vkarpov15** [comment] 2018-10-26 20:11
@rogerkirkness can you provide some code samples, or better yet open up a new issue and follow the instructions? We have tests for setDefaultsOnInsert and they're passing

**Comment by sashahilton00** [comment] 2018-12-13 00:32
Also seeing this behaviour:

```
const bulkOps = docsArray.map(doc => ({
         updateOne: {
             filter: { email: doc.email },
             update: { $set: doc },
             upsert: true,
             setDefaultsOnInsert: true
          }
      }));
      insertResults = await model.Customer.bulkWrite(bulkOps)
```
Write is successful, but defaults not applied. You can use whatever schema you want, have tried with different ones, result is the same; fails silently.

**Comment by vkarpov15** [comment] 2018-12-14 22:45
@sashahilton00 ah so your issue is with defaults, not timestamps. Will open a separate issue to track
