### ISSUE TITLE
myModel.find() is not working

### ISSUE THREAD

**Issue by xandner** [Automattic/mongoose#10639] opened 2021-08-30 05:56 UTC
this is my function:

async function getCourseListe(){
    const courseListe = await courseModel.find({'}).exec();
    console.log(courseListe)
}
getCourseListe()

and this is my error:
MongoInvalidArgumentError: Method "collection.find()" accepts at most two arguments
but courseModel.findOne() is working very good

**Comment by Kamikadze4GAME** [comment] 2021-08-30 06:34
Duplicates #10634

**Comment by lorand-horvath** [comment] 2021-08-30 14:04
This is a duplicate of the issue I reported here initially https://github.com/Automattic/mongoose/issues/10610#issuecomment-907060604 and should be fixed in 6.0.3 via https://github.com/Automattic/mongoose/commit/9de60a771e37cc2fcb7af3d805294b49239aed17

**Closed** 2021-08-30 21:28 UTC
Labels: duplicate
