### ISSUE TITLE
deleteMany is inconsistent with MongoDB driver behavior

### ISSUE THREAD

**Issue by mehulmpt** [Automattic/mongoose#10946] opened 2021-10-31 18:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`deleteMany` on mongoose v6.0.5 removes all records IF the filter object is not valid.
`deleteMany` on MongoDB ideally does not remove all the records if wrong key is present in object filter.

**If the current behavior is a bug, please provide the steps to reproduce.**

#### Step 1
<img width="979" alt="Screenshot 2021-11-01 at 12 11 16 AM" src="https://user-images.githubusercontent.com/10388889/139597157-33022e74-321e-4759-91b7-50544681e066.png">

#### Step 2

<img width="820" alt="Screenshot 2021-11-01 at 12 11 50 AM" src="https://user-images.githubusercontent.com/10388889/139597171-bcf64edb-dc92-41bd-bdc6-118f552030bd.png">

**Note: deletedCount is 0**

#### Step 1

<img width="756" alt="Screenshot 2021-11-01 at 12 16 38 AM" src="https://user-images.githubusercontent.com/10388889/139597318-e634e4cc-a0eb-4c85-9480-be4c7f485960.png">

#### Step 2

<img width="686" alt="Screenshot 2021-11-01 at 12 19 05 AM" src="https://user-images.githubusercontent.com/10388889/139597382-cde70a73-4019-46cd-b588-056f6aa813ec.png">

<img width="503" alt="Screenshot 2021-11-01 at 12 17 59 AM" src="https://user-images.githubusercontent.com/10388889/139597353-941db765-16b7-420c-b656-24c7b9c65960.png">

**What is the expected behavior?**

Consistent behavior with MongoDB driver.

**Comment by IamAfnanSk** [comment] 2021-10-31 18:52
Nice catch

**Comment by sean-daley** [comment] 2021-11-01 10:52
This looks like another `strictQuery` situation? Check out https://github.com/Automattic/mongoose/issues/10932 which documents a setting you can enable if you want the other behavior. That issue is for find calls but hopefully it works for delete as well?

**Comment by mehulmpt** [comment] 2021-11-01 14:27
Thanks, I'll check it out. But isn't this a dangerous default to blow full collection if you typo-ed the field name?

**Comment by AbdelrahmanHafez** [comment] 2021-11-03 12:44
@mehulmpt 
I agree that it can be risky for `deleteMany`, the current solution would be to: `mongoose.set('strictQuery', false);`.

Do you have a suggestion on how to mitigate that risk without introducing a breaking change?

**Comment by vkarpov15** [comment] 2021-11-10 02:16
I agree @AbdelrahmanHafez , this is something we'll keep open for the future and see if we can think of another solution.

**Comment by hasezoey** [comment] 2022-09-05 11:05
as mentioned in #12389 this may also be a duplicate of (or at least related to) #4251

**Comment by vkarpov15** [comment] 2023-06-12 02:14
This is no longer an issue in Mongoose 7, strictQuery is false by default.

**Closed by vkarpov15** 2023-06-12 02:14 UTC
Labels: enhancement
