### ISSUE TITLE
Mongoose connect throwing some warning 

### ISSUE THREAD

**Issue by daveai** [Automattic/mongoose#5333] opened 2017-06-07 21:09 UTC
My connection string like this

mongodb://root:pass@127.0.0.1:27017/ai?authSource=admin

Everything working good but getting a wired message at the shell.

Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

For what is this ?

**Comment by varunjayaraman** [comment] 2017-06-11 19:54
this is a duplicate of https://github.com/Automattic/mongoose/issues/5304

**Closed by varunjayaraman** 2017-06-11 19:54 UTC

**Comment by gongg1975** [comment] 2017-06-29 12:23
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
MongoDB connection error: { MongoError: Authentication failed.
    at Function.MongoError.create (C:\Users\gonza\Desktop\myapp\express-locallibrary-tutorial\node_modules\mongodb-core\lib\error.js:31:11)
    at C:\Users\gonza\Desktop\myapp\express-locallibrary-tutorial\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (C:\Users\gonza\Desktop\myapp\express-locallibrary-tutorial\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (C:\Users\gonza\Desktop\myapp\express-locallibrary-tutorial\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (C:\Users\gonza\Desktop\myapp\express-locallibrary-tutorial\node_modules\mongodb-core\lib\connection\connection.js:321:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  code: 18,
  errmsg: 'Authentication failed.' }

Can someone helllllp meeee!!!!

**Comment by ToTopNeo** [comment] 2017-07-05 03:57
message: 'Authentication failed.',
ok: 0,
code: 18,
errmsg: 'Authentication failed.' }  
all these messages shows you are not allowed to log in database , you can check user&passwd&database,

**Comment by UmarEhsan** [comment] 2017-11-30 14:28
For Db.prototype.authenticate method will no longer be available Error try this.
var mongoose = require('mongoose');
mongoose.Promise = global.Promise;

mongoose.connect( "mongodb://username:password@ds125146.mlab.com:25146/dbName'", { useMongoClient: true } );

For MongoLab
Make sure you are using the database username and password not the account username and password from Mlab.
In MLab, formerly MongoLab, do the following
Navigate to Users
@Add Database User
Choose your username and password

**Comment by vkarpov15** [comment] 2017-12-09 03:45
Set `useMongoClient: true` and this warning will go away
