### ISSUE TITLE
Uncaught cast to ObjectId error thrown when updating

### ISSUE THREAD

**Issue by reinert** [Automattic/mongoose#3592] opened 2015-11-19 13:59 UTC
I noticed that if one pass an invalid id to Model#update, an uncaught cast error is thrown. Example:

```js
var invalidId = '564dd2c61c3d6b9625c26f';
Model.update({ _id: invalidId }, {}).exec().then(function(res, err) {
  console.log(err); // does not execute
});
```

The log:
```
Debug: internal, implementation, error 
    CastError: Uncaught error: Cast to ObjectId failed for value "564dd2c61c3d6b9625c26f" at path "_id"
    at MongooseError.CastError (/home/reinert/projects/congrega/node_modules/mongoose/lib/error/cast.js:19:11)
    at ObjectId.cast (/home/reinert/projects/congrega/node_modules/mongoose/lib/schema/objectid.js:134:13)
    at ObjectId.castForQuery (/home/reinert/projects/congrega/node_modules/mongoose/lib/schema/objectid.js:173:17)
    at Query._castUpdateVal (/home/reinert/projects/congrega/node_modules/mongoose/lib/query.js:2434:17)
    at Query._walkUpdatePath (/home/reinert/projects/congrega/node_modules/mongoose/lib/query.js:2381:25)
    at Query._castUpdate (/home/reinert/projects/congrega/node_modules/mongoose/lib/query.js:2254:23)
    at Query.update (/home/reinert/projects/congrega/node_modules/mongoose/lib/query.js:2064:22)
    at Function.update (/home/reinert/projects/congrega/node_modules/mongoose/lib/model.js:1898:13)
    ...
```

**Comment by vkarpov15** [comment] 2015-11-19 16:56
Duplicate of #3529, #3512, etc. Unfortunately this behavior is a feature rather than a bug - for backwards compat, mongoose still supports try/catch around `.update()` for catching cast errors. As a workaround, use `Model.find({ _id: invalidId }).update({}).exec().catch()`.

**Closed by vkarpov15** 2015-11-19 16:56 UTC
