### ISSUE TITLE
Connection to Atlas cluster times-out in Deno

### ISSUE THREAD

**Issue by SkepticMystic** [Automattic/mongoose#13785] opened 2023-08-26 08:13 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.4.5

### Node.js version

Deno 1.36.1

### MongoDB server version

6.x

### Typescript version (if applicable)

5.x

### Description

- Deno supports node module imports (using the syntax `import mongoose from 'npm:mongoose'`).
- Connecting to localhost works fine: `await mongoose.connect("mongodb://localhost:27017");`
- However, connecting to an Atlas cluster times-out.

(I understand this may not be the best place to discuss Deno issues, but I'm doing so based on the previous issue #13075)

### Steps to Reproduce

- `deno init` a new Deno project
- In `main.ts`:

```ts
import mongoose from "npm:mongoose";

await mongoose.connect("mongodb+srv://<username>:<password>@<cluster>/?retryWrites=true&w=majority");

// Check to see connection status.
console.log(mongoose.connection.readyState);
```

- Run with `deno run --allow-read --allow-env --allow-sys --allow-net main.ts`
- After some time, the following error occurs: `Uncaught MongooseServerSelectionError: connection timed out`

### Expected Behavior

Similarly to how connecting to `mongodb://localhost:27017` works, one expects to be able to connect to an Atlas cluster

**Comment by IslandRhythms** [comment] 2023-09-15 21:12
I whitelisted all ips and it still wouldn't connect, citing that the main issue could be the ip is not whitelisted.

**Comment by vkarpov15** [comment] 2023-09-15 21:34
Can you please confirm what version of Mongoose you're using? There was an issue that was fixed in v6.11.0 that prevented connecting to Atlas in Deno. And, while the script you gave does fail for me, the issue is that the script uses Mongoose 6.8 for some reason. The following script works fine:

```ts
import mongoose from "npm:mongoose@7.x";
  
await mongoose.connect("mongodb+srv://user:pwd@omitted.xyz.mongodb.net/?retryWrites=true&w=majority");

// Check to see connection status.
console.log(mongoose.connection.readyState);
console.log(mongoose.version);

```

**Comment by IslandRhythms** [comment] 2023-09-15 22:54
6.12

**Comment by SkepticMystic** [comment] 2023-09-17 07:04
@vkarpov15 Oh wow, I think it works if you specify `@7.x` :D 
I will be able to more fully confirm during the coming week, but this is good for now.
Weird the Deno doesn't grab the latest version if it's unpinned?

Thanks for your help, happy to close.

**Comment by vkarpov15** [comment] 2023-09-26 14:37
Yeah I'm not certain why Deno was picking that particular 6.x version. Glad that 7.x works for you :+1:

**Closed by vkarpov15** 2023-09-26 14:37 UTC
Labels: can't reproduce

**Comment by ReturnXDev** [comment] 2023-10-11 12:30
I am also getting this error...

**Server:**
deno 1.37.1 (release, x86_64-pc-windows-msvc)
v8 11.8.172.6
typescript 5.2.2

**Code:**
```
import mongoose from "npm:mongoose@7.5.2";

const username = Deno.env.get("MONGO_USERNAME");
const password = Deno.env.get("MONGO_PASSWORD");
const MONGO_URI = `mongodb+srv://${username}:${password}@<cluster>/<collection>?
retryWrites=true&w=majority`;

try {
  await mongoose.connect(
    MONGO_URI,
    { useNewUrlParser: true, useUnifiedTopology: true }
  );
  console.log("Connected to MongoDB");
} catch (error) {
  console.error("mongoose.connect", error);
}
```

I know the error suggests the whitelisting but this is not the issue, the settings are set to connect from anywhere and this 'times out' as in I wait 30 seconds before getting this error:

I tried the above suggestions and currently as the import suggests am using the latest version..

**Error:**
mongoose.connect MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/

Full error:

on {
        address: "REDACTED",
        type: "Unknown",
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 17538,
        lastWriteDate: 0,
        error: null,
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        "$clusterTime": null
      },
      "REDACTED" => ServerDescription {  
        address: "REDACTED",
        type: "Unknown",
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 17538,
        lastWriteDate: 0,
        error: null,
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        "$clusterTime": null
      },
      "REDACTED" => ServerDescription {  
        address: "REDACTED",
        type: "Unknown",
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        "$clusterTime": null
      },
      "REDACTED" => ServerDescription {
        address: "REDACTED",       
        type: "Unknown",
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 17538,
        lastWriteDate: 0,
        error: null,
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        "$clusterTime": null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: "REDACTED",
    maxElectionId: new ObjectId("7fffffff0000000000000180"),
    maxSetVersion: 359,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
