### ISSUE TITLE
Cannot read property '$__' of undefined TypeError: Cannot read property '$__' of undefined

### ISSUE THREAD

**Issue by barczaG** [Automattic/mongoose#3889] opened 2016-02-18 11:22 UTC
Since version 4.4.4 i get this error:
```
Cannot read property '$__' of undefined TypeError: Cannot read property '$__' of undefined
    at SchemaType.Embedded.cast (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schema/embedded.js:62:46)
    at SchemaType.default (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schematype.js:93:16)
    at new SchemaType (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schematype.js:41:15)
    at SchemaType.Embedded (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schema/embedded.js:46:14)
    at Function.Schema.interpretAsType (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schema.js:579:12)
    at Schema.path (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schema.js:506:29)
    at Schema.add (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schema.js:390:12)
    at new Schema (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mongoose/lib/schema.js:93:10)
    at Object.<anonymous> (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/api/models/Session.js:71:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.cls_wrapMethod [as _load] (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/newrelic/lib/shimmer.js:235:38)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Service._loadInstance (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Module.js:113:22)
    at /Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Module.js:67:29
    at Function._.each._.forEach (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/underscore/underscore.js:153:9)
    at /Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Module.js:60:9
    at Function._.each._.forEach (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/underscore/underscore.js:153:9)
    at Service._loadApi (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Module.js:57:7)
    at Service._loadCurrentApi (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Service.js:133:10)
    at /Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Service.js:56:12
    at next (native)
    at onFulfilled (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:65:19)
    at /Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:54:5
    at new wrappedPromise (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/newrelic/lib/instrumentation/core/globals.js:108:18)
    at co (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:50:10)
    at Service.start (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/@ghostmonitor/gm-core-lib/lib/Service.js:55:12)
    at Object.<anonymous> (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/app.js:10:26)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Context.<anonymous> (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/test/bootstrap.js:43:9)
    at next (native)
    at onFulfilled (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:65:19)
    at /Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:54:5
    at Promise._execute (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/bluebird/js/release/promise.js:468:18)
    at new Promise (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/bluebird/js/release/promise.js:77:14)
    at Context.co (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:50:10)
    at Context.createPromise (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co/index.js:30:15)
    at callFn (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mocha/lib/runnable.js:315:21)
    at Hook.Runnable.run (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mocha/lib/runnable.js:308:7)
    at Hook.Runnable.run (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/co-mocha/lib/co-mocha.js:43:16)
    at next (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mocha/lib/runner.js:298:10)
    at Immediate._onImmediate (/Users/gergobarcza/Projects/ghostmonitor/gm-session-mservice/node_modules/mocha/lib/runner.js:320:5)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

my model:
```
var SessionSchema = new Schema({
  email: {
    type: String,
    validate: [ validator.isEmail, 'invalid email' ]
  },
  phone: {
    type: String
  },
  name: {
    type: String
  },
  site: {
    type: Schema.Types.ObjectId,
    required: true,
    es_indexed: true
  },
  isArActive: {
    type: Boolean,
    default: false
  },
  sessionType: {
    type: String,
    default: 'visitor',
    enum: ['visitor', 'junk_ghost', 'ghost', 'returning_ghost', 'customer_ghost', 'customer'],
    es_indexed: true
  },
  fields: {
    type: Schema.Types.Mixed,
    default: {}
  },
  cartData: {
    type: CartdataSchema,
    default: {
      value: 0,
      itemCount: 0,
      returnUrl: ''
    },
    es_indexed: true
  },
  cartItems: {
    type: [ProductSchema],
    es_indexed: false
  },
  shortCartUrl: {
    type: String
  },
  startedAt: {
    type: Date,
    default: Date.now
  },
  lastHeartbeatAt: {
    type: Date,
    default: Date.now
  },
  cartStartedAt: {
    type: Date,
    default: new Date(0),
    es_indexed: true
  },
  convertedAt: {
    type: Date,
    default: new Date(0),
    es_indexed: true
  },
  atc: {
    type: Schema.Types.Mixed,
    default: {
      show: 0,
      hide: 0,
      emailProvide: 0
    }
  }
}, schemaOptions)
```

**Comment by stefankutko** [comment] 2016-02-18 16:49
Same here, downgrading to 4.4.3 fixes it.. not sure root cause.

**Comment by vkarpov15** [comment] 2016-02-18 19:21
This is almost certainly a consequence of the fix for #3880. Will investigate.

**Comment by andrenarchy** [comment] 2016-02-19 17:03
I have the same issue:
```
    TypeError: Cannot read property '$__' of undefined
        at SchemaType.Embedded.cast (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/schema/embedded.js:62:46)
        at Query._castUpdateVal (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/query.js:2417:22)
        at Query._walkUpdatePath (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/query.js:2336:27)
        at Query._castUpdate (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/query.js:2265:23)
        at castDoc (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/query.js:2463:18)
        at Query._findAndModify (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/query.js:1753:17)
        at Query._findOneAndUpdate (/home/andre/git-repos/paperhive-backend/node_modules/mongoose/lib/query.js:1621:8)
        at /home/andre/git-repos/paperhive-backend/node_modules/kareem/index.js:156:8
        at /home/andre/git-repos/paperhive-backend/node_modules/kareem/index.js:18:7
        at nextTickCallbackWith0Args (node.js:453:9)
        at process._tickCallback (node.js:382:13)
```

**Comment by vkarpov15** [comment] 2016-02-19 17:58
@andrenarchy can you provide some sample code that shows how you're running into this issue? Looks like you're using a `findOneAndUpdate()`?

**Comment by normark** [comment] 2016-02-20 02:47
It appears to be related to using findOneAndUpdate(...) with $set to update the contents of an embedded subdocument.

I can reproduce on 4.4.4 by
```
var m   = require('mongoose');
m.connect('mongodb://localhost:27017/mtest');
m.connection.on('connected', function () {
  // Setup
  var EmbedSchema = new m.Schema({
    prop2     : { type : String }
  });
  var UserSchema = new m.Schema({
    prop1     : { type : String },
    embedded  : EmbedSchema
  });

  var User = m.model('User', UserSchema);

  // Test
  var data = { 
    prop1     : 'somevalue', 
    embedded  : { prop2 : 'somevalue' } 
  };

  User.create(data, function(err, user){
    User.findOneAndUpdate(
      { _id : user.id }, 
      {'$set' : { embedded : { prop2 : 'newvalue' }}}, 
      function(err, user){
        if(err) throw err;
        process.exit(0);
    });
  });
}); 
```

But it works fine if you manually find(...), modify and save(...), i.e. the following does not throw an exception
```
User.create(data, function(err, user){
    user.embedded.prop2 = 'newvalue';
    user.save(function(err, user){
      if(err) throw err;
      process.exit(0);
    });
  });
```

Updating properties not related to the embedded subdoc poses no problems either. This is probably related to #3894

**Comment by vkarpov15** [comment] 2016-02-20 21:34
Fixed in https://github.com/Automattic/mongoose/commit/7aef0f0da90cfaa49304cf6583fd08c4dc6e15c7

**Closed by vkarpov15** 2016-02-20 21:34 UTC

**Comment by AbdelrahmanHafez** [comment] 2019-11-14 20:20
Getting this error after upgrading to Node 12, will see if I can reproduce it.
```
 TypeError: Cannot read property '$__' of undefined
    at _updateParentPopulated (/root/speero/node_modules/mongoose/lib/types/documentarray.js:323:14)
    at CoreDocumentArray.push (/root/speero/node_modules/mongoose/lib/types/documentarray.js:187:5)
```
mongoose v5.7.7
Node v12.13.0

**Comment by vkarpov15** [comment] 2019-11-16 15:16
@AbdelrahmanHafez if you manage to repro it consistently, please open up a new issue with some code samples :+1:
