### ISSUE TITLE
Mongoose cannot find module deploying to Heroku

### ISSUE THREAD

**Issue by snewcomer** [Automattic/mongoose#2958] opened 2015-05-04 02:49 UTC
mongoose/lib/node-mongodb-native -->
`var ObjectId = require('mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid');`

Path to file is correct; however get this error:

```
Starting process with command `node ./bin/www`
 Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
 Recommending WEB_CONCURRENCY=1
     at require (module.js:380:17)
 Error: Cannot find module 'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid'
 
     at Module._compile (module.js:456:26)
     at Function.Module._load (module.js:312:12)
           ^
     at Module.require (module.js:364:17)
     at Module.require (module.js:364:17)
     at Object.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:9:16)
     at Object.Module._extensions..js (module.js:474:10)
     at Module.load (module.js:356:32)
 module.js:340
     throw err;
     at Function.Module._resolveFilename (module.js:338:15)
     at Function.Module._load (module.js:280:25)
```

Anybody know why I am getting these errors?  It seems never-ending with these cannot find module errors related to mongoose and mongodb.

**Comment by vkarpov15** [comment] 2015-05-04 13:13
Duplicate of #2957, #2908, et. all. Will be fixed for 4.0.3.

**Closed by vkarpov15** 2015-05-04 13:13 UTC
