### ISSUE TITLE
instance of mongoose.Schema.Types.String returns false (HMR)

### ISSUE THREAD

**Issue by whydrae** [Automattic/mongoose#9391] opened 2020-09-05 12:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Seems to be a bug (or a non-documented behavior).

**What is the current behavior?**
After HMR in the Nuxt application, check in [mongoose-intl](https://github.com/alexsk/mongoose-intl) plugin `schemaType instance of mongoose.Schema.Types.String` returns `false`. 

I know, that this might be a Nuxt issue, but can anybody help me to understand why is this happening?

Original Nuxt issue: https://github.com/nuxt/nuxt.js/issues/8019

**If the current behavior is a bug, please provide the steps to reproduce.**
Use [this project ](https://github.com/whydrae/nuxt-mongoose-plugin-error) to reproduce the issue. It's created from nuxt express-template with mongoose and mongoose-intl package.

1. npm install
2. npm run dev
3. change anything in api/models/blog.js file and save

**What is the expected behavior?**
HMR without any issues.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
- nuxt: v2.14.4
- node: v14.0.0
- mongoose: v5.10.3

**Comment by vkarpov15** [comment] 2020-09-07 21:15
You're right, this issue is due to https://github.com/nuxt/nuxt.js/pull/7938 . The issue is that Nuxt HMR completely re-inits all of Mongoose, but doesn't re-init mongoose-intl. So mongoose-intl's copy of `require('mongoose')` is no longer the same object as `blog.js`'s copy of `require('mongoose')`.

I don't know Nuxt well enough to know if there's any way you can work around this issue. But here's a couple possibilities:

1) Move mongoose-intl's `require('mongoose')` call into the plugin function - move https://github.com/alexsk/mongoose-intl/blob/ed7fcf35e36a76ebe4da8bc72d22c0c395a45f03/lib/mongoose-intl.js#L3 to L7. This will ensure mongoose-intl doesn't keep a stale copy of mongoose after Nuxt HMR. Unfortunately, numerous other plugins would be affected by this same issue.

2) Work with the Nuxt team to rework https://github.com/nuxt/nuxt.js/pull/7938 - that seems like an unnecessary and brittle change.

**Comment by vkarpov15** [comment] 2020-09-10 16:24
Closing this in favor of https://github.com/Automattic/mongoose/issues/9406.

**Closed by vkarpov15** 2020-09-10 16:24 UTC
Labels: interop issue
