### ISSUE TITLE
Problem with update when using Map type

### ISSUE THREAD

**Issue by jzwiesler** [Automattic/mongoose#7466] opened 2019-01-30 10:03 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I got a problem with the new mongoose type Map. I use mongoose 5.2.10 and can't update to a newer version at the moment. I got the problem, that, when using a map in a subdocument, when updating the document i get the error, that mongoDb cannot create a field '-1' in the subdocument, even when not changing the subdocument.

My Schemas

```js
var parentSchema = module.exports = new mongoose.Schema({
    _id: {type: String, required: true},
    child: [childSchema]
}, {
    id: false,
    usePushEach: true
});
parentSchema.updatableAttributes = ["child"];

var mapSchema = new mongoose.Schema({
    foo: { type: String, required: true },
    bar: { type: String, required: true },
    blub: String,
    isSomething: Boolean
}, {
    id: false
});

mapSchema.set("toJSON", {
    virtuals: true,
    transform: util.excludeFields("_id")
});

mapSchema.updatableAttributes = ["foo", "bar", "blub", "isSomething"];
mapSchema.ignorableAttributes = ["id"];


var childSchema = new mongoose.Schema({
    _id: { type: String, required: true },
    maps: {type: Map, of: mapSchema}
}, {
    id: false
});

childSchema.updatableAttributes = ["maps"];
childSchema.ignorableAttributes = ["id"];
```

The call
```js
Document.findById(theDocumentId, function (err, document) {
  return test.save().then( function(returnDocument) {
    ...
    }).catch(function (err) {
      console.log(err)
    })
})
```

always throwsn an error: Cannot create field '-1' in element {child: ...}

When debugging into the save from mongoose, I saw, that in the ```  document.$__.activePaths.states.modify ```, after the find there are the child routes like "child.-1.maps.$.foo" or "child.-1.maps.$.bar" referenced and it seems, that on "save" these are send to mongoDb causing the error. Is there something I'm doing wrong?

**What is the expected behavior?**

I can update my document

**Please mention your node.js, mongoose and MongoDB version.**
Node,js: 8.5.4
mongoose: 5.2.10
mongoDb 4.0.5

**Comment by mhombach** [comment] 2019-01-30 10:46
Can you please put your code into the apropriate syntax-highlighting? :)

\`\`\`js
your code goes here -->
\`\`\`

**Comment by jzwiesler** [comment] 2019-01-30 11:11
> 
> 
> Can you please put your code into the apropriate syntax-highlighting? :)
> 
> ```js
> your code goes here -->
> ```

Sorry, like this?

**Comment by vkarpov15** [comment] 2019-02-03 15:37
Where is `mapSchema` defined in your code?

**Comment by vkarpov15** [comment] 2019-02-08 15:53
@jzwiesler the below script executes without any errors for me. Please modify the below script to repro your issue:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7466`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const mapSchema = new mongoose.Schema({
    foo: { type: String, required: true },
    bar: { type: String, required: true },
    blub: String,
    isSomething: Boolean
  }, {
    id: false
  });

  mapSchema.set("toJSON", {
    virtuals: true,
    transform: function(doc, ret) {
      delete ret._id;
      return ret;
    }
  });

  var childSchema = new mongoose.Schema({
    _id: { type: String, required: true },
    maps: {type: Map, of: mapSchema}
  }, {
    id: false
  });

  const Child = mongoose.model('Child', childSchema);
  await Child.create({ _id: 'test', maps: { key: { foo: '1', bar: '2' } } });

  const doc = await Child.findOne();
  await doc.save();
}
```

**Comment by jzwiesler** [comment] 2019-02-08 17:13
If I expand it like this, I get the error

```js
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7466`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();

  const mapSchema = new mongoose.Schema({
    foo: { type: String, required: true },
    bar: { type: String, required: true },
    blub: String,
    isSomething: Boolean
  }, {
    id: false
  });

  mapSchema.set("toJSON", {
    virtuals: true,
    transform: function(doc, ret) {
      delete ret._id;
      return ret;
    }
  });

  var childSchema = new mongoose.Schema({
    _id: { type: String, required: true },
    maps: {type: Map, of: mapSchema}
  }, {
    id: false
  });
  
  const parentSchema = new mongoose.Schema({
    _id: {type: String, required: true},
    child: [childSchema]
    }, {
        id: false,
        usePushEach: true
    });

  const Parent = mongoose.model('Parent', parentSchema);
  await Parent.create({child: [{ _id: 'test', maps: { key: { foo: '1', bar: '2' } } }],_id: "parent"});

  const doc = await Parent.findOne();
  await doc.save();
}
```

**Comment by vkarpov15** [comment] 2019-02-09 15:41
@jzwiesler this looks like a duplicate of #7272 , your script works fine with Mongoose `>= 5.3.15`. Upgrade to 5.3.15 for the fix.

**Closed by vkarpov15** 2019-02-09 15:41 UTC
Labels: has repro script
