### ISSUE TITLE
Typings Regression: `Model.bulkSave`

### ISSUE THREAD

**Issue by ecnaidar** [Automattic/mongoose#11599] opened 2022-03-30 17:07 UTC
**Do you want to request a *feature* or report a *bug*?**

Typings bug report

**What is the current behavior?**

Invalid typings; giving error with when using `Model.bulkSave()`
```
Property 'bulkSave' does not exist on type 'Model<ToolScheduleBlockMongoose, {}, {}>'.ts(2339)
```

This gets broken when going from `6.2.1` to `6.2.2`
Pinning version to `6.2.1` gives correct typings

`tsconfig.json`
```
{
  "extends": "../common/tsconfig.base.json",
  "compileOnSave": false,
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "lib": ["es2020"],
    "outDir": "dist",
    "typeRoots": ["./node_modules/@types", "../common/types"]
  },
  "include": ["server/**/*.ts"],
  "exclude": ["node_modules"]
}
```
`tsconfig.base.json`
```
{
  "compilerOptions": {
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "allowSyntheticDefaultImports": true,
    "noImplicitReturns": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": false,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictPropertyInitialization": false,
    "isolatedModules": true,
    "resolveJsonModule": true,
    "paths": {
      "common/types": ["./types"]
    }
  }
}

```

**What is the expected behavior?**

Types are not breaking compilation when package minor version is automatically updated

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Happens inside of the container "node:14-alpine", not sure which exact `npm` version is used

**Comment by AbdelrahmanHafez** [comment] 2022-03-31 15:56
@ecnaidar 
Does this happen with v6.2.9?
Can you provide a repro script?

**Comment by ecnaidar** [comment] 2022-03-31 17:23
Yes happened in `6.2.9` as well. Not really anything special in Model def, I think.
Forgot to mentioned quite important thing, TS version is `4.6.3`

and just to make some online TS based sandbox that replicates the issue and it seems that types are picked up correctly there while I was definitely able to reproduce it when switching between versions locally. 🤔 


```
import { Schema, Types, model } from 'mongoose';

const ToolScheduleSlotFields = {
  scheduleId: { type: String, required: true },
  bookerId: { type: String, required: true },
  customer: { type: String },
  location: { type: String },
  comment: { type: String },
  startDate: Date,
  endDate: Date,
};

export const ToolScheduleBlockSchema = new Schema<ToolScheduleBlockMongoose>({
  ...ToolScheduleSlotFields,
  bookings: {
    type: [{ type: Schema.Types.ObjectId, ref: 'ToolScheduleBlockSchema' }],
    default: undefined,
  },
  status: {
    type: String,
    required: true,
    enum: ['Draft', 'Confirmed'],
    default: 'Draft',
  },
});


export const ToolScheduleBlockModel = model(
  'ToolScheduleBlockSchema',
  ToolScheduleBlockSchema
);

```

**Comment by AbdelrahmanHafez** [comment] 2022-03-31 18:29
>the issue and it seems that types are picked up correctly there

Does that mean the issue is resolved for you now? I tested it and the typings seem to be working.

If not, can you modify the script below to demonstrate the issue you're facing?
```ts
'use strict';
import mongoose from 'mongoose';
const { Schema } = mongoose;

interface IUser{
  name: string
}
const userSchema = new Schema<IUser>({
  name: { type: String }
});


const User = mongoose.model<IUser>('User', userSchema);

await User.bulkSave([new User({ name: 'John Doe' })]);
```

**Comment by ecnaidar** [comment] 2022-03-31 20:01
Could be something with particular TS setup maybe? 

![image](https://user-images.githubusercontent.com/10078339/161139319-244a3f58-1cda-4241-81a6-c6cbcdade6cd.png)

**Comment by AbdelrahmanHafez** [comment] 2022-04-11 14:19
@ecnaidar I tried with the same TSConfig, and things seem to be working.

The only thing I can't have from your environment is the `../common/types`, I'm guessing that this is the culprit.
Can you provide a repository that reproduces the issue, including all the necessary setups?

**Comment by ecnaidar** [comment] 2022-04-11 14:56
@AbdelrahmanHafez Hey, made a repo with reproduction [here](https://github.com/ecnaidar/11599-mongoose-repro)
Simply deleted everything but single `model.ts` so it is not going to run in any shape or form 😬 
Was able to clone it on other machine and get aforementioned TS error.

**Comment by vkarpov15** [comment] 2022-05-15 21:26
@AbdelrahmanHafez is right. I don't have a good explanation for why this works in Mongoose 6.2.1, but not 6.2.2. But the problem is that `@types/passport-local-mongoose` is mostly broken with Mongoose 5, and completely broken with Mongoose 6. I don't expect to be able to push a fix up to DefinitelyTyped given that @AbdelrahmanHafez already tried with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59827 and got no response.

It looks like passport-local-mongoose itself is a bit more actively maintained, so we'll take a look and see if we can contribute there. It'll be a good opportunity to see if we can improve how we do typings for plugins - right now the user is responsible for knowing what stuff the plugin adds to models and documents.

**Comment by AbdelrahmanHafez** [comment] 2022-05-15 21:34
@vkarpov15 
Frankly, it's not an issue that I didn't get a response from DefinitelyTyped.
I tried a quick fix and it didn't work out on the first attempt so I closed the PR since I couldn't dedicate more time to it.

**Comment by vkarpov15** [comment] 2022-05-16 02:29
You got a response, just the equivalent of an automated recording on phone support :) I opened up a PR in passport-local-mongoose, we'll see where that goes.

**Comment by Uzlopak** [comment] 2022-05-28 22:31
the pr regarding passport-local-mongoose got merged.

Closing this PR as the underlying interop issue should be solved.

**Closed by Uzlopak** 2022-05-28 22:31 UTC
Labels: interop issue, typescript
