### ISSUE TITLE
Unhandled exception if $set object contains keys not given in schema

### ISSUE THREAD

**Issue by kevinbror** [Automattic/mongoose#4425] opened 2016-08-16 18:25 UTC
With version 4.5.9, if the $set object of an update contains a key not given in the schema and the timestamps option is `true`, an unhandled exception is thrown by line 865 of lib/schema.js when it cannot find that key and therefore not the $isSingleNested property on the schema. 

The following code will throw a TypeError with the message 'Cannot read property '$isSingleNested' of undefined' 
```
const M = require('mongoose');
const Mongoose = M.Mongoose;
const Schema = M.Schema;
const schema = new Schema({
    name: { type: String, required: true }
}, { timestamps: true });

const mongoose = new Mongoose();
mongoose.connect('mongodb://localhost/test');
const model = mongoose.model('thing', schema);
const db = mongoose.connection;
db.on('error', (err) => {

    console.error('connection error:', err);
});
db.once('open', () => {

    model.create({ name: 'sample' }, (err, thing) => {

        model.findOneAndUpdate(
            { _id: thing._id },
            { $set: { name: 'newName', propertyNotInSchema: { hi: 'there' } } },
            { new: true },
            (err, thing) => {

                console.log(err);
                console.log(thing);
                db.close();
            });
    });
});
```

**Comment by loris** [comment] 2016-08-18 10:35
Duplicate of https://github.com/Automattic/mongoose/issues/4424

**Comment by vkarpov15** [comment] 2016-08-22 02:18
Yeah also dip of #4418. It's fixed in master and I'll push a release tomorrow. Sorry for the trouble.

**Closed by vkarpov15** 2016-08-22 02:18 UTC
