### ISSUE TITLE
isModified behavior is different for 5.x and 6.x

### ISSUE THREAD

**Issue by rohanricky** [Automattic/mongoose#14079] opened 2023-11-14 11:44 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.3

### Node.js version

18.16.1

### MongoDB server version

4.4

### Description

We are facing the issue while migrating from v5.x to v6.x
the following code behaves differently in both versions v5.12.5 and v6.12.3.

### Steps to Reproduce

```
const mongoose = require('mongoose');
console.log(mongoose.version)
let Schema = mongoose.Schema
var eventSchema = new Schema({
  name: { type: String },
  __stateBeforeSuspension: {
    field1: { type: String },
    field2: { type: String },
    jsonField: {
        name: { type: String },
        ex: { type: String }
    }
  }
})

eventSchema.add({
  test: { 
    val1: { type: String },
    val2: { type: String }
   }
})

var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { field1: 'test', jsonField: { name: 'test3', ex: 'test' }}, test: { val1: 'hello', val2: 'there' } })
  eventObj.save(function (err, eventObj) {
    var newObject = eventObj.toObject()
    newObject.__stateBeforeSuspension = { field1: '12', jsonField: { name: 'test4', ex: 'test' }}
    newObject.test = { val2: 'he', val1: 'hello' }
    eventObj.set(newObject)
    console.log('__stateBeforeSuspension.field1', eventObj.isModified('__stateBeforeSuspension.field1'))
    console.log('__stateBeforeSuspension.jsonField.name', eventObj.isModified('__stateBeforeSuspension.jsonField.name'))
    console.log('__stateBeforeSuspension.jsonField.ex', eventObj.isModified( '__stateBeforeSuspension.jsonField.ex'))
    console.log('test.val2', eventObj.isModified('test.val2'))
    console.log('test.val1', eventObj.isModified('test.val1'))
  })
}
run();
```

Output with 5.12.5
```
5.12.5
__stateBeforeSuspension.field1 true
__stateBeforeSuspension.jsonField.name true
__stateBeforeSuspension.jsonField.ex false
test.val2 true
test.val1 false
```

Output with 6.12.3
```
6.12.3
__stateBeforeSuspension.field1 true
__stateBeforeSuspension.jsonField.name true
__stateBeforeSuspension.jsonField.ex true
test.val2 true
test.val1 true
```

isModified() behaves differently with 5.x and 6.x versions.

**Comment by IslandRhythms** [comment] 2023-11-15 16:54
duplicate of #14024

**Comment by vkarpov15** [comment] 2023-12-15 23:34
Unfortunately this is expected behavior. The intent behind `isModified()` is more about whether Mongoose will send this property to the MongoDB server than whether the property was updated in memory. Because `__stateBeforeSuspension` was set to a new value, Mongoose will send the entirety of `__stateBeforeSuspension` to the MongoDB server and overwrite the whole `__stateBeforeSuspension` in MongoDB.

Try the following script instead, which updates dotted paths directly instead of overwriting the entirety of `__stateBeforeSuspension`. This approach is more performant, and also gets you the desired output (`isModified('__stateBeforeSuspension.jsonField.ex') === false`)

```javascript
var Event = mongoose.model('Event', eventSchema)
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  let eventObj = new Event({ name: 'event object', __stateBeforeSuspension: { field1: 'test', jsonField: { name: 'test3', ex: 'test' }}, test: { val1: 'hello', val2: 'there' } })
  eventObj.save(function (err, eventObj) {
    var newObject = eventObj.toObject()
    newObject.__stateBeforeSuspension = { field1: '12', jsonField: { name: 'test4', ex: 'test' }}
    newObject.test = { val2: 'he', val1: 'hello' }
    eventObj.set('__stateBeforeSuspension.field1', '12');
    eventObj.set('__stateBeforeSuspension.jsonField.name', 'test4');
    eventObj.set('__stateBeforeSuspension.jsonField.ex', 'test');
    console.log('__stateBeforeSuspension.field1', eventObj.isModified('__stateBeforeSuspension.field1'))
    console.log('__stateBeforeSuspension.jsonField.name', eventObj.isModified('__stateBeforeSuspension.jsonField.name'))
    console.log('__stateBeforeSuspension.jsonField.ex', eventObj.isModified( '__stateBeforeSuspension.jsonField.ex'))
    console.log('test.val2', eventObj.isModified('test.val2'))
    console.log('test.val1', eventObj.isModified('test.val1'))
  })
}
run();
```

**Closed by vkarpov15** 2023-12-15 23:34 UTC
Labels: confirmed-bug
