### ISSUE TITLE
Nonexistent fields get omitted from query

### ISSUE THREAD

**Issue by ahmedelshenawy25** [Automattic/mongoose#11048] opened 2021-12-06 05:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Nonexistent fields get omitted from query which yields unexpected results.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
import mongoose from 'mongoose';
import assert from 'assert';

run().catch(console.error);

async function run () {
  mongoose.set('debug', true);
  await mongoose.connect('mongodb://localhost:27017/test');

  const userSchema = new mongoose.Schema({ name: String });
  const User = mongoose.model('User', userSchema);

  await User.create({ name: 'foo' });
  const user = await User.findOne({ wrongField: 'bar' });

  assert.strictEqual(user, null);
}
```

**What is the expected behavior?**
it shouldn't return any documents.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v16.13.0
Mongoose: v6.0.14
MongoDB: v5.0.4

**Comment by Kamikadze4GAME** [comment] 2021-12-06 07:43
Duplicate of #10763, #10778, #10932

**Comment by ahmedelshenawy25** [comment] 2021-12-06 12:26
I can understand removing nonexistent fields from `create` or `update`, but imagine making a typo or having an old field which got removed from schema but not from the rest of our code in `update` filter. This could have significant unexpected results.

**Comment by vkarpov15** [comment] 2021-12-07 17:14
`mongoose.set('strictQuery', false)`. We agree this change has had some unintended consequences and we're sorry for the inconvenience. Please use the workaround `mongoose.set('strictQuery', false)` for now if this causes you issues.

**Closed by vkarpov15** 2021-12-07 17:14 UTC
Labels: duplicate

**Comment by florianwalther-private** [comment] 2022-08-21 13:32
@vkarpov15 The option is not working for me (with Mongoose `6.2.9`), no matter if I set it all the way at the beginning of my code, other after connecting mongoose.

**Comment by vkarpov15** [comment] 2022-09-14 16:26
@florianwalther-private make sure you do `mongoose.set('strictQuery', false)` _before_ calling `mongoose.model()` or `connection.model()`

**Comment by florianwalther-private** [comment] 2022-09-14 18:51
Sorry, I forgot to update this. My mistake was that I called it after setting up my routes (which in turn had dependencies on the models). It's all working now, I just needed to call it early enough :)
