### ISSUE TITLE
(node:1124) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

### ISSUE THREAD

**Issue by Lucio-Valder** [Automattic/mongoose#8506] opened 2020-01-14 19:01 UTC
I solved this Issue in my application  using this value in my mongoose connection:

mongoose.connect('mongodb+srv://lucio:<password>@cluster0-6izqv.mongodb.net/test?retryWrites=true&w=majority',{
 useCreateIndex:true,
} );

**Comment by AbdelrahmanHafez** [comment] 2020-01-15 00:19
Duplicate of https://github.com/Automattic/mongoose/issues/6880

**Comment by vkarpov15** [comment] 2020-01-17 22:13
https://mongoosejs.com/docs/deprecations.html

**Closed** 2020-01-17 22:13 UTC
