### ISSUE TITLE
Method "collection.aggregate()" accepts at most two arguments

### ISSUE THREAD

**Issue by DavideViolante** [Automattic/mongoose#10722] opened 2021-09-15 08:02 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`Error: Method "collection.aggregate()" accepts at most two arguments`
```
MongoInvalidArgumentError: Method "collection.aggregate()" accepts at most two arguments
    at Collection.aggregate (/home/dave/projects/asd/node_modules/mongodb/lib/collection.js:367:19)
    at NativeCollection.<computed> [as aggregate] (/home/dave/projects/asd/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:200:33)
    at NativeCollection.Collection.doQueue (/home/dave/projects/asd/node_modules/mongoose/lib/collection.js:135:23)
    at /home/dave/projects/asd/node_modules/mongoose/lib/collection.js:82:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
    import Client from '../models/client';
    ...
    const clients = await Client.aggregate([
      { $match: { active: true } },
      { $project: {
          name: 1,
          image: 1,
          maxContract: {
            $arrayElemAt: [ '$contracts', { $indexOfArray: ['$contracts.endDate', { $max: '$contracts.endDate' }] } ]
          }
        }
      },
      { $match: { 'maxContract.endDate': { $lte: date, $gte: new Date() } } },
      { $sort: { 'maxContract.endDate': 1 } }
    ]);
```
Happens also with a simple match query inside aggregate:
```ts
    import Client from '../models/client';
    ...
    const clients = await Client.aggregate([
      { $match: { active: true } }
    ]);
```

**What is the expected behavior?**
Working as v5?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node: v14.17.6, Mongoose: v6.0.5, TypeScript: v4.2.4

I have this error since v6, it's working fine with v5. I can't find where the breaking change is documented tbh...
Any help is appreciated, thanks.

Also, TypeScript aggregate signature is:
```
(method) Model<IClient, {}, {}>.aggregate<any>(pipeline?: any[]): Aggregate<any[]> (+1 overload)
```
But if the arguments must be different, TypeScript should tell before compiling.

**Comment by DavideViolante** [comment] 2021-09-16 07:56
Adding also the Client  schema here:
```ts
import { Document, model, Schema } from 'mongoose';

const ClientSchema = new Schema({
  name: { type: String, required: true, trim: true },
  image: { type: String, default: '' },
  contracts: [{
    id: Number,
    name: String,
    startDate: Date, 
    endDate: Date,
    created_at: Date,
    updated_at: Date
  }],
  active: { type: Boolean, default: true },
});

export interface IClient extends Document {
  _id: any;
  name: string;
  image: string;
  contracts: any[];
  active: boolean;
}

const Client = model<IClient>('Client', ClientSchema);

export default Client;

```

**Comment by IslandRhythms** [comment] 2021-09-16 19:04
Modify script below to reproduce your error and I will try again.

```
import * as mongoose from 'mongoose';

const ClientSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true },
  image: { type: String, default: '' },
  contracts: [{
    id: Number,
    name: String,
    startDate: Date, 
    endDate: Date,
    created_at: Date,
    updated_at: Date
  }],
  active: { type: Boolean, default: true },
});

export interface IClient extends Document {
  _id: any;
  name: string;
  image: string;
  contracts: any[];
  active: boolean;
}

const Client = mongoose.model<IClient>('Client', ClientSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/');
    await mongoose.connection.dropDatabase();
    const clients = await Client.aggregate([
        { $match: { active: true } },
        { $project: {
            name: 1,
            image: 1,
            maxContract: {
              $arrayElemAt: [ '$contracts', { $indexOfArray: ['$contracts.endDate', { $max: '$contracts.endDate' }] } ]
            }
          }
        },
        { $match: { 'maxContract.endDate': { $lte: new Date(), $gte: new Date() } } },
        { $sort: { 'maxContract.endDate': 1 } }
      ]);
      
      const test = await Client.aggregate([ { $match: { active: true } }]);
      console.log('done');
}




test();
```

**Comment by syffs** [comment] 2021-09-17 13:32
@IslandRhythms not sure if it helps, but there's a question about the same issue on [stack](https://stackoverflow.com/questions/69063771/mongodb-collection-aggregrate-accept-only-two-arguments)

**Comment by IslandRhythms** [comment] 2021-09-17 15:48
@syffs still can't reproduce it. I'm on the latest version of mongoose so it may have been patched.
```javascript
const mongoose = require('mongoose');

const Rooms = new mongoose.Schema(
    {adminID: {
            type: String,
            required: true,
        },  
    roomID: {
            type: String,
            required: true,
        },  
    roomName: {
            type: String,
            required: true,
        },  
    users: [
            {
                id: {
                    type: String,
                    required: true,
                    unique: true,
                },
            },
        ],
    },
    { timestamps: true } ); 

const Test = mongoose.model('Test', Rooms);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/', {useNewUrlParser: true,
    useUnifiedTopology: true,});
    await mongoose.connection.dropDatabase();
    await Test.create({adminID: '1234', roomID: '5678', roomName: 'bed', users: [{id: '90'},{id: '80'} ]});
    const data = await Test.aggregate([{ $match: { adminID: "1234" } }]);
    console.log(data);
    console.log('done');
}

test();
```

**Comment by vkarpov15** [comment] 2021-09-18 20:55
Confirmed this bug, fix will be in 6.0.7 on Monday :+1:

**Comment by DavideViolante** [comment] 2021-11-08 09:21
> Did this bug get fixed? If yes which version of ^6.0 onward? Because it would seem I am still getting it.

It got fixed on >=6.0.7

**Comment by nkalinov** [comment] 2021-11-17 07:53
On 6.0.13 and it's still an issue. Any suggestions?
Here's my query fwiw:
```
    const aggregated = await PushNotification.aggregate([
      {
        $match: {
          sendDate: { $lte: moment().toISOString() },
          status: 'pending',
        },
      },
      {
        $groupBy: {
          _id: {
            $concat: ['$to', '__', '$data.type'],
          },
          docs: {
            $push: '$$CURRENT',
          },
        },
      },
    ]);
```

**Comment by nkalinov** [comment] 2021-11-19 09:21
FYI I've pruned my Docker volumes, recreated the containers and it works now. No idea what was going on but when it was broken I had verified that the containers were using the latest mongoose version. I'm in a monorepo using Yarn3 so it could be an issue with another (peer) dependency maybe?

**Comment by vkarpov15** [comment] 2021-11-27 18:58
@nkalinov probably an old Mongoose version somewhere. If it's fixed now, that's good enough for me :+1:

**Closed by vkarpov15** 2021-11-27 18:58 UTC
Labels: needs repro script
