### ISSUE TITLE
Replacing unpopulated properties with populated properties doesn't work

### ISSUE THREAD

**Issue by thnima** [Automattic/mongoose#8285] opened 2019-10-28 08:43 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Request a document and populate it's properties
2. Request the same document without populating the properties
3. Assign the populated properties from document in step 1 to the document in step 2 -> Document 2 still has the unpopulated version assigned

Looks like the bug got introduced with the fix in #8247 

This script reproduces the behaviour (works in 5.7.5 and fails in later version)
```
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh8285`;
const connectionString = `mongodb://@localhost:27017/${ GITHUB_ISSUE }`;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, { useNewUrlParser: true });
  await mongoose.connection.dropDatabase();

  const referenceSchema = new mongoose.Schema({
    name: {
      type: String
    }
  });
  const Reference = mongoose.model('Reference', referenceSchema);
  const referenceDoc = new Reference({ name: "Reference 1" });
  await referenceDoc.save();

  const subSchema = new mongoose.Schema({
    referenceProp: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Reference',
      required: true
    }
  })

  const parentSchema = new mongoose.Schema({
    child: {
      type: subSchema,
      required: true
    }
  })
  const Parent = mongoose.model('Parent', parentSchema);
  const parentDoc = new Parent({
    child: {
      referenceProp: referenceDoc._id
    }
  });
  await parentDoc.save();

  const parentDocSaved = await Parent
    .findById(parentDoc._id)
    .populate('child.referenceProp')

  const parentDocSaved2 = await Parent
    .findById(parentDoc._id)
  parentDocSaved2.child.referenceProp = parentDocSaved.child.referenceProp

  console.log("\nExpected output: " + parentDocSaved)
  console.log("\nActual output: " + parentDocSaved2)
}
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

The snippet works as expected in 5.7.5 and doesn't work in later versions anymore.

**Comment by vkarpov15** [comment] 2019-11-03 19:51
This looks like a duplicate of #8273, I can confirm your script works with the fix for #8273. Thanks for the detailed repro script and sorry for the trouble, the fix will be in 5.7.8.

**Closed by vkarpov15** 2019-11-03 19:51 UTC
