### ISSUE TITLE
Cannot read property 'options' of undefined at UnorderedBulkOperation.execute

### ISSUE THREAD

**Issue by monasingh27294** [Automattic/mongoose#7453] opened 2019-01-25 11:21 UTC
```javascript
mongoose.connection.db.collection("bank", function (err, collection) {
    collection.find({type: 'debit'}).toArray(function (err, data) {
        if (data.length !== 0) {
            let bulk = annexure.collection.initializeUnorderedBulkOp();
            let batchSize = 1000;

            data.forEach(function (doc, index) {
                delete doc._id;
                doc.transaction_id = `BS-DR-${counter}`;
                // doc.receipt_number = doc.receipt_number;
                doc.created_at = moment().tz('Asia/Calcutta').toDate();
                counter++;
                bulk.insert(doc);

                if (index % batchSize === 0) {
                    bulk.execute();
                    bulk = annexure.collection.initializeUnorderedBulkOp()

                }
            });

            bulk.execute(function (err, result) {
                if (err) {
                    reject(err)
                } else {
                    console.log(`created docs `);

                }
            });
        }


    })
})
```

I am getting error at bulk.execute

**Cannot read property 'options' of undefined at UnorderedBulkOperation.execute**

is something wrong am I doing?

**Comment by vkarpov15** [comment] 2019-01-25 18:09
What version of Mongoose?

**Comment by monasingh27294** [comment] 2019-01-27 06:02
5.2.18

**Comment by vkarpov15** [comment] 2019-02-12 18:47
This looks like a duplicate of #7467, I'm going to close this.

**Closed by vkarpov15** 2019-02-12 18:47 UTC
Labels: needs clarification
