### ISSUE TITLE
Problems with readPreference seconday or secondaryPreferred

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#9309] opened 2020-08-07 18:22 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
when I define readPreference to secondary or secondaryPreferred the module stops responding.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've this 2 codes
```javascript
"use strict";
const mongoose = require("mongoose");
const poolSize = 10;
const maxPoolSize = poolSize * 2;
[...Array(poolSize).keys()].forEach(async (id) => {
  let db = new mongoose.Mongoose();
  console.log(id, "start");
  await db.connect(
    "mongodb+srv://someSrv/test?w=majority&retryWrites=true&readPreference=secondary",
    {useNewUrlParser: true, useUnifiedTopology: true, poolSize, maxPoolSize}
  );
  console.log(id, "connected");
  const test = new db.Schema({
    test: String,
  });
  const Test = db.model("Test", test);
  console.log(id, "model created");
  try {
    const start = Date.now();
    const result = await Promise.race([Test.find(), new Promise((res, rej) => setTimeout(rej, 5000, "timeout"))]);
    console.log(id, Date.now() - start, result);
  } catch (err) {
    console.error(id, err);
  } finally {
    db.disconnect();
  }
});
```
resulting something like this:
```
0 start
1 start
2 start
3 start
4 start
5 start
6 start
7 start
8 start
9 start
9 connected
9 model created
7 connected
7 model created
3 connected
3 model created
6 connected
6 model created
4 connected
4 model created
5 connected
5 model created
8 connected
8 model created
0 connected
0 model created
1 connected
1 model created
2 connected
2 model created
7 1514 []
2 1504 []
9 timeout
3 timeout
6 timeout
4 timeout
5 timeout
8 timeout
0 timeout
1 timeout
``` 
and this other one:
```javascript
"use strict";
const {MongoClient, ReadPreference} = require("mongodb");
const url =
  "mongodb+srv://someSrv/test?w=majority&retryWrites=true&readPreference=secondary";
const dbName = "test";
const poolSize = 10;
const maxPoolSize = poolSize * 2;
[...Array(poolSize).keys()].forEach(async (id) => {
  const client = new MongoClient(url, {
    useUnifiedTopology: true,
    poolSize,
    maxPoolSize,
    readPreference: ReadPreference.SECONDARY,
  });
  console.log(id, "start");
  await client.connect();
  const db = client.db(dbName);
  console.log(id, "connected");
  try {
    const start = Date.now();
    const result = await Promise.race([
      db.collection("test").find().toArray(),
      new Promise((res, rej) => setTimeout(rej, 5000, "timeout")),
    ]);
    console.log(id, Date.now() - start, result);
  } catch (err) {
    console.error(id, err);
  } finally {
    client.close();
  }
});
```
resulting:
```
0 start
1 start
2 start
3 start
4 start
5 start
6 start
7 start
8 start
9 start
2 connected
0 connected
9 connected
8 connected
4 connected
5 connected
2 232 []
7 connected
6 connected
1 connected
0 226 []
3 connected
9 213 []
8 217 []
5 215 []
7 214 []
6 215 []
1 225 []
4 1292 []
3 1305 []
```
**What is the expected behavior?**
First of all, it looks somehow weird the mongoose behavior, as it looks like sync, and mongoose sometimes works and sometimes it ain't.
I set the timeout just for testing purposes, what really happens is the find promise never resolves.
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
yarn why mongodb
├─ mongoose@npm:5.9.27
│  └─ mongodb@npm:3.5.10 (via npm:3.5.10)
│
└─ test@workspace:.
   └─ mongodb@npm:3.6.0 (via npm:^3.6.0)
```
node 14.6.0

**Comment by chumager** [comment] 2020-08-07 18:24
Just realize if I use the 3.5.10 mongodb driver the behavior is the same like mongoose in terms of apparently sync flow.

Regards.

**Comment by vkarpov15** [comment] 2020-08-14 15:02
Sorry for the delay in getting back to you, this looks like a duplicate of #9295. There was a change in how the MongoDB driver emitted events that caused this issue. Please upgrade to v5.9.28 or higher for the fix.

**Closed by vkarpov15** 2020-08-14 15:02 UTC

**Comment by chumager** [comment] 2020-08-14 20:02
Hi, I tested it and it works...

Thanks a lot.
