### ISSUE TITLE
Errors in model function callbacks are swallowed

### ISSUE THREAD

**Issue by brutaldev** [Automattic/mongoose#3273] opened 2015-08-15 10:14 UTC
If there is a programmatic error or even a thrown error in a model callback function, the error is swallowed and nothing is reported to the user.

Here is a sample app to highlight the problem:
```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect("mongodb://localhost/testdb");

var TestSchema = new Schema({ test: String });
var TestModel = mongoose.model('Test', TestSchema);

var success = new TestModel({test: 'success'});
success.save(function (err) {
  console.log('inside save callback for "success", no errors created in callback.');
});

var userError = new TestModel({test: 'userError'});
success.save(function (err) {  
  console.log('inside save callback for "userError", about to cause a unhandled error that will be swallowed.');
  
  var item = {};
  console.log(item.oops.nothinghere);
  
  console.log('after unhanded error callback for "userError"');
});

var throwError = new TestModel({test: 'throwError'});
success.save(function (err) {  
  console.log('inside save callback for "throwError", about to throw an error that will be swallowed.');
  
  throw new Error('Something bad happened in the callback, we wanted to throw an error but no-one will ever know...')
  
  console.log('after unhanded error callback for "throwError"');
});
```

There is no console output for any of the errors, whether user thrown or an unhandled programmatic error. The application has no knowledge that anything bad happened which makes this really difficult to debug.

Failures like this prevent Promise resolving as well. The calls fail at [line 266 of model.js](https://github.com/Automattic/mongoose/blob/d563355be9/lib%2Fmodel.js#L266) and/or [line 1643 of document.js](https://github.com/Automattic/mongoose/blob/d563355be9/lib%2Fdocument.js#L1643) which prevents the resolve on the caller from being called and handled.

**Comment by vkarpov15** [comment] 2015-08-16 18:08
Duplicate of #3222. Working on it.

**Closed** 2015-08-27 12:15 UTC
