### ISSUE TITLE
callback.apply is not a function after removing document and calling findById() again

### ISSUE THREAD

**Issue by useo6** [Automattic/mongoose#6640] opened 2018-06-30 16:59 UTC
**Do you want to request a *feature* or report a *bug*?**

- [x] bug
- [ ] feature

**What is the current behavior?**

I've a small express-based webserver that serves a page where I can see my products and delete them if necessary. But when I try to delete one of my products, I'm getting the following exception:

> 2018-06-30T16:35:56.747Z - error: uncaughtException: callback.apply is not a function date=Sat Jun 30 2018 18:35:56 GMT+0200 (Mitteleuropäische Sommerzeit), pid=13216, uid=null, gid=null, cwd=C:\Projects\test, execPath=C:\Program Files\nodejs\node.exe, version=v8.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Projects\test\index.js], rss=109969408, heapTotal=96772096, heapUsed=69630352, external=18207349, loadavg=[0, 0, 0], uptime=542708.4915952
> TypeError: callback.apply is not a function
>     at C:\Projects\test\node_modules\mongoose\lib\model.js:3949:16
>     at Immediate._handleWriteOpResult (C:\Projects\test\node_modules\mongoose\lib\queryhelpers.js:261:12)
>     at Immediate._onImmediate (C:\Projects\test\node_modules\mquery\lib\utils.js:119:16)
>     at runCallback (timers.js:794:20)
>     at tryOnImmediate (timers.js:752:5)
>     at processImmediate [as _immediateCallback] (timers.js:729:5)

I figured out that the document was removed successfully from my database, so I'm redirecting the client to the page that contains the list of products. So, the workflow is as follows:

1. access /category/123
2. choose a product to delete from my database by accessing /category/delete/product
3. after deleting the chosen product, redirect to /category/123
4. uncaughtException: callback.apply is not a function

I can access /category/123 without any error, but when I choose a product to delete and redirect back to /category/123 I'm facing  the callback.apply-error.

I've added a console.log() output  for debug purposes to C:\Projects\test\node_modules\mongoose\lib\model.js:3949:16 (Model.$wrapCallback method) and after removing a product and redirecting back to /category/123, the callback parameter is suddently the removed document. This occurs when calling Category.findById() (see below)

**If the current behavior is a bug, please provide the steps to reproduce.**
```
  app.get(`/category/:id`, (req, resp) => {
    async.auto({
      products: (cb) => {
        Category.findById(req.params.id)
          .populate({
            path: 'products',
            populate: {
              path: 'prices',
              model: PriceModel
            }
          })
          .exec(cb)
      }
    }, (err, products) => {
      if (err) {
        return resp.send(err)
      } else {
        return resp.render('category', products)
      }
    })
  })

  app.post(`/category/delete/product`, (req, resp) => {
    async.waterfall([
      (cb) => {
        Product.findById(req.body.prodId, cb)
      },
      (prod, cb) => {
        prod.remove(cb)
      }
    ], (err) => {
      console.log(err)
      return resp.redirect(`/category/${req.body.categoryId}`)
    })
  })
```

**Please mention your node.js, mongoose and MongoDB version.**

mongoose: 5.0.17
node: v8.10.0

**Comment by vkarpov15** [comment] 2018-07-03 18:55
Thanks for reporting, will investigate asap

**Comment by vkarpov15** [comment] 2018-07-15 16:35
I'm unable to repro, below script works fine with mongoose 5.0.17. Please modify the below script to reproduce this issue. In the meantime, I'll add some code to throw a readable error if `$wrapCallback()` gets a non-function.

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);
  
const GITHUB_ISSUE = `gh6640`;
const connectionString = `mongodb://localhost:27017/${ GITHUB_ISSUE }`;
const { Schema } = mongoose;
    
const async = require('async');
  
run().then(() => console.log('done')).catch(error => console.error(error.stack));
    
async function run() { 
  await mongoose.connect(connectionString);
  await mongoose.connection.dropDatabase();
  
  const PriceModel = mongoose.model('Price', new Schema({ val: Number }));
  const Product = mongoose.model('Product', new Schema({
    name: String, 
    prices: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Price' }]
  }));    
  const Category = mongoose.model('Category', new Schema({
    name: String, 
    products: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Product' }]
  }));    

  const price = await PriceModel.create({ val: 5 }); 
  const [p1, p2] = await Product.create({ name: 'laptop', prices: [price._id] }, { name: 'phone', prices: [price._id] });
  const category = await Category.create({ name: 'Electronics', products: [p1._id, p2._id] });

  async.waterfall([
      (cb) => {
        Product.findById(p1._id, cb)
      },      
      (prod, cb) => {
        prod.remove(cb)
      }       
    ], (err) => {
      console.log(err)
      setTimeout(() => next());
    })      
          
  function next() {
    async.auto({
      products: (cb) => {
        Category.findById(category._id)
          .populate({
            path: 'products',
            populate: {
              path: 'prices',
              model: PriceModel
            }
          })
          .exec(cb)
      }
    }, (err, products) => {
      console.log(err, products.products)
    })
  }
}
```

**Comment by vkarpov15** [comment] 2018-07-16 18:42
I'm closing this just for task management purposes so I remember to put 5ceff45 in the release notes. Will re-open later.

**Comment by vkarpov15** [comment] 2018-07-30 01:36
Closing because this has gone stale. Re-open if this is still an issue

**Closed by vkarpov15** 2018-07-30 01:36 UTC
Labels: can't reproduce
