### ISSUE TITLE
duplicate key error mongoose with discriminators

### ISSUE THREAD

**Issue by shiwaniB** [Automattic/mongoose#6343] opened 2018-04-13 10:49 UTC
I have implemented discriminators with mongoose and connecting to Azure cosmos db's Mongo APIs.
I have a base collection as bases and 2 other collections say collection1 and collection2.

Insert on collection at first time is successful But getting following error while inserting second object
MongoError: E11000 duplicate key error collection: bases Failed _id or unique key constraint

Example Models:-
1) BaseModel:-

const baseOptions = {
    discriminatorKey: '__type',
    collection: 'baseModel'
}
const Base = mongoose.model('Base', new mongoose.Schema({}, baseOptions));

2) Collection1:-

var userSchema = baseModel.discriminator('userdetails', new Schema({
    _id: { type: Schema.ObjectId, auto: true},
    emailId: { type: String, unique: true, index: true},
    firstName: {type: String},
}));

3) Collection2:-

var deviceSchema = baseModel.discriminator('devicedetails', new Schema({
    _id: { type: Schema.ObjectId, auto: true},
    name: { type: String, unique: true, index: true},
    model: {type: String}
}));

**Comment by lineus** [comment] 2018-04-13 13:16
@shiwaniB Can you please provide a reproducible example that shows not only your schemas, but sample data and behavior that causes the error you are seeing?

**Comment by shiwaniB** [comment] 2018-04-14 05:59
Apart from models I have a mongoose code to save device data in collection.
device.create(devicedata, function (error, result) {
        if (error) {
res.status(500).send(error);
        }
else{
        res.status(200).send(result);
}
    });

My json request to API is  function is:-
{
"name": "device1",
"model": "model1"
}

First time it saves a data in collection, but after that even if I change device name in request its throwing ** MongoError: E11000 duplicate key error collection: Failed _id or unique key constraint**

Note:- **It is observed that if I just run code with device model schema then its working file.
              But when i also add second collection schema i.e user with unique constraint its getting failed**

**Comment by lineus** [comment] 2018-04-14 11:47
@shiwaniB 

I created the following example based on your schemas above:

### 6343.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const baseOptions = {
  discriminatorKey: '__type',
  collection: 'baseModel'
};

const Base = mongoose.model('Base', new mongoose.Schema({}, baseOptions));

const userSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  emailId: { type: String, unique: true, index: true },
  firstName: { type: String },
});

const User = Base.discriminator('userdetails', userSchema);

const deviceSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  name: { type: String, unique: true, index: true },
  model: { type: String }
});

const Device = Base.discriminator('devicedetails', deviceSchema);


const base = new Base({});

const user = new User({
  emailId: 'billy123@mail.com',
  firstName: 'Henry'
});

const device = new Device({
  name: 'Samsung',
  model: 'kindling'
});

async function run () {
  await conn.dropDatabase();
  await base.save();
  await user.save();
  await device.save();
  return conn.close();
}

run().catch((e) => {
  console.error(e.message);
  return conn.close();
});
```
### output:
```
issues: ./6343.js
E11000 duplicate key error index: test.baseModel.$name_1 dup key: { : null }
issues:
```

**When we add a unique index on a path in a schema, it creates a unique index for that path on the mongodb server collection**. 

By first saving a Base instance without a name path set, then saving a User instance without a name path set, we have attempted to create 2 documents with non-unique values for that path, hence the error. 

Because discriminators share a collection, the only paths eligible for uniqueness are ones defined on the base schema ( so that all discriminators inherit the exact same path ), and only if they are required ( the value can't be null on 2 documents ).

**Comment by lineus** [comment] 2018-04-14 16:56
@shiwaniB Indexes only apply to the specific collection they are defined on. 

for example:

if you create separate collections ( Models ) for users and devices, you can then use a unique index on the specific path in each schema that you use to create the models.

```
const userSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  emailId: { type: String, unique: true, index: true },
  firstName: { type: String },
});

const User = mongoose.model('User', userSchema);

const deviceSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  name: { type: String, unique: true, index: true },
  model: { type: String }
});

const Device = mongoose.model('Device', deviceSchema);
```

This will cause mongodb to throw an error any time you attempt to save a document with a duplicated value for the specified unique path across documents in that specific collection. 

## I think there is a feature request here though.

Mongodb also has an index type called a partial index. Partial indexes can filter indexes on fields beyond the indexed field. This **should** allow us to create unique indexes on discriminator schemas that will only apply to documents with that specific discriminator key. I'll explore this further and put in a PR for a future release of mongoose.

**Comment by lineus** [comment] 2018-04-14 19:15
# We can do this now :)

After giving it a little more thought, you can create a partial index on a schema with options that will make this work now:

```
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/test');
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const baseOptions = {
  discriminatorKey: '__type',
  collection: 'baseModel'
};

const Base = mongoose.model('Base', new mongoose.Schema({}, baseOptions));

const userSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  emailId: { type: String },
  firstName: { type: String },
});

userSchema.path('emailId').index({ 
  unique: true, 
  partialFilterExpression: {
    '__type': 'userdetails'
  }
});

const User = Base.discriminator('userdetails', userSchema);

const deviceSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  name: { type: String },
  model: { type: String }
});

deviceSchema.path('name').index({
  unique: true,
  partialFilterExpression: {
    '__type': 'devicedetails'
  }
});

const Device = Base.discriminator('devicedetails', deviceSchema);


const base = new Base({});

const user = new User({
  emailId: 'billy123@mail.com',
  firstName: 'Henry'
});

const device = new Device({
  name: 'Samsung',
  model: 'kindling'
});

const secondDevice = new Device({
  name: 'Samsung',
  model: 'firestarter'
});

async function run () {
  await conn.dropDatabase();
  await base.save();
  await user.save();
  await device.save();
  await secondDevice.save();
  return conn.close();
}

run().catch((e) => {
  console.error(e.message);
  return conn.close();
});
```
As you can see by the output below, this allows us to apply the index specifically to the documents with the matching discriminator key for our type.  

The example is fine with saving all three different doc types:
```
> db.baseModel.find().pretty()
{ "_id" : ObjectId("5ad25036967f285ba82a9aeb"), "__v" : 0 }
{
        "_id" : ObjectId("5ad25036967f285ba82a9aec"),
        "__type" : "userdetails",
        "emailId" : "billy123@mail.com",
        "firstName" : "Henry",
        "__v" : 0
}
{
        "_id" : ObjectId("5ad25036967f285ba82a9aed"),
        "__type" : "devicedetails",
        "name" : "Samsung",
        "model" : "kindling",
        "__v" : 0
}
>
```

and still honors the unique index on the name path of the device schema:

```
issues: ./6343.js
E11000 duplicate key error index: test.baseModel.$name_1 dup key: { : "Samsung" }
issues:
```

I think it would be cool if `.discriminator()` could detect the unique option on a discriminator schema path, and create a partial index for us. I'll investigate a PR for this idea.

**Comment by lineus** [comment] 2018-04-15 09:09
@shiwaniB I'm happy I could help 👍 

Would you mind closing this issue? Feel free to subscribe to #6347 to get updates on it's progress.

**Comment by shiwaniB** [comment] 2018-04-17 03:40
@lineus Sure you can close the issue.

Thanks for the help.

**Comment by vkarpov15** [comment] 2018-04-23 16:50
Follow #6347 for updates on this. Until then, [partial unique indexes](http://thecodebarbarian.com/enforcing-uniqueness-with-mongodb-partial-unique-indexes) are the way to go.

```javascript
const baseOptions = {
  discriminatorKey: '__type',
  collection: 'baseModel'
};

const baseSchema = new mongoose.Schema({}, baseOptions);

baseSchema.index({ emailId: 1 }, {
  unique: true,
  partialFilterExpression: {
    __type: 'User'
  }
});

const Base = mongoose.model('Base', baseSchema);

const userSchema = new Schema({
  _id: { type: Schema.ObjectId, auto: true },
  emailId: { type: String, unique: true, index: true },
  firstName: { type: String },
});

const User = Base.discriminator('userdetails', userSchema);
```

**Closed by vkarpov15** 2018-04-23 16:50 UTC
