### ISSUE TITLE
CastError: Cast to ObjectId failed for value "56d79e4a52637adc45e874b4" at path "_id" for model "User"

### ISSUE THREAD

**Issue by KavenWork** [Automattic/mongoose#4887] opened 2017-01-11 08:35 UTC
findById

mongoose@4.3.6 is right

4.7.6 has this problem

**Comment by dongyingtao** [comment] 2017-01-11 09:36
Same problem. I was using 4.6.8. It worked fine. Today, when I deployed a new server with npm install. It installs 4.7.6 with mongodb@2.2.19 which has the regression.
This is pretty big regression. Everyone seems to be complaining.

**Comment by varunjayaraman** [comment] 2017-01-11 16:51
Guessing this is a duplicate of https://github.com/Automattic/mongoose/issues/4867 but can you please post a code snippet or follow the issue template please so we can at least see what's causing the bug?

**Comment by varunjayaraman** [comment] 2017-02-14 18:28
@KavenWork any update on this? Otherwise I'm going to close this issue as stale.

**Closed** 2017-02-16 02:31 UTC
Labels: needs clarification

**Comment by MadeoIT** [comment] 2017-12-31 09:49
fuking tard what are you closing
