### ISSUE TITLE
How does populate works with multiple documents?

### ISSUE THREAD

**Issue by MilenkoM** [Automattic/mongoose#9512] opened 2020-11-02 10:53 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am trying to populate my Post.

 

```
 async function createPost() {
    try {
      const mycomment = await Comment.create({
        postedBy : mongoose.Types.ObjectId('5f97c071bad24d1a81b25dd1'),
        body: 'These were the days!'
      });
      await Post.create({title: 'Vou comer K.! ',
        body: 'What a wonderful life!',
        postedBy: mongoose.Types.ObjectId('5f97c071bad24d1a81b25dd1'),
        comments: mycomment,
      });
      const post = await Post.findOne().populate('comments');
    } catch (err) {
      console.log(err);
    }
  }

My Post schema

> const PostSchema = new mongoose.Schema({
>   title: String,
>   body: String,
>   createdAt: {
>     type: Date,
>     default: Date.now,
>   },
>   postedBy: {
>     type: mongoose.Schema.Types.ObjectId,
>     ref: 'User',
>   },
>   comments: [{
>     type: String,
>     ref: 'Comment',
>   }] 
> });

```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I want that multiple comments could be attached to my Post.
![Screenshot from 2020-11-02 11-47-10](https://user-images.githubusercontent.com/13464056/97859854-7761c100-1d01-11eb-8371-97a26a174d38.png)

The above image(from MongoDB Atlas),shows last Post collection. What should I change to have body Comments in Post collections?

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

> MongoDB shell version v4.4.1
> node -v
> v14.8.0
> mongoose": "^5.10.10"

**Comment by vkarpov15** [comment] 2020-11-04 00:33
In your `await Post.create()` call, you create a post with exactly one comment. So I'm not sure what the issue is here?

**Comment by AbdelrahmanHafez** [comment] 2020-11-04 19:12
Welcome @Milenko
You're defining `comments` as an array of strings, which will not work with populate, you need to define it as an array of object ids that refer to the `Comment` model/collection.
So instead of:
```js
   comments: [{
     type: String,
     ref: 'Comment'
   }] 
```

Do:
```js
   comments: [{
     type: Schema.ObjectId,
     ref: 'Comment'
   }] 
```

Here's a full example on how to populate multiple documents:
### 9512.js
```js
'use strict';
const mongoose = require('mongoose');
const assert = require('assert');

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  const postSchema = new mongoose.Schema({
    title: String,
    body: String,
    createdAt: {
      type: Date,
      default: Date.now
    },
    postedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    comments: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Comment'
    }]
  });

  const Post = mongoose.model('Post', postSchema);
  const commentSchema = new mongoose.Schema({
    content: String,
    postedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }
  });

  const Comment = mongoose.model('Comment', commentSchema);

  const post = new Post({
    title: 'My cool post',
    body: 'body goes here',
    postedBy: mongoose.Types.ObjectId() // random id
  });

  const comments = await Comment.insertMany([
    {
      content: 'first comment',
      postedBy: mongoose.Types.ObjectId() // random id
    },
    {
      content: 'second comment',
      postedBy: mongoose.Types.ObjectId() // random id
    }
  ]);

  post.comments = [
    comments[0]._id,
    comments[1]._id
  ];

  await post.save();

  const foundPost = await Post.findOne().populate('comments');
  assert.equal(foundPost.title, 'My cool post');
  assert.equal(foundPost.comments[0].content, 'first comment');
  assert.equal(foundPost.comments[1].content, 'second comment');

  console.log('All assertions passed.');
}
```
### Output
```
$ node ./9512.js
All assertions passed.
```

I'll close this, please let me know if I can help with anything else.

**Closed by AbdelrahmanHafez** 2020-11-04 19:12 UTC
Labels: needs clarification

**Comment by MilenkoM** [comment] 2020-11-05 00:57
Hafez,
I understand now.
