### ISSUE TITLE
when loading mongoose, have the error "Cannot find module 'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid'"

### ISSUE THREAD

**Issue by mike-aungsan** [Automattic/mongoose#2984] opened 2015-05-13 01:59 UTC
npm -v
2.7.4

node -v
v0.12.2

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

npm install mongoose

var mongoose  = require('mongoose');

Error: Cannot find module 'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mike_api/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:9:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
Program node server_no_cluster.js exited with code 1

**Comment by vkarpov15** [comment] 2015-05-13 02:17
Duplicate of #2908, #2906, etc. etc. will be fixed when 4.0.3 is released, which should be tomorrow.

**Closed by vkarpov15** 2015-05-13 02:17 UTC
