### ISSUE TITLE
browser-side validation on nested schema skips validating path on parent

### ISSUE THREAD

**Issue by captaincaius** [Automattic/mongoose#7493] opened 2019-02-06 17:11 UTC
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Hard to describe this properly, but modifying a nested document doesn't seem to mark as modified the field that's the nested schema on the parent...  So validating skips it :'(.

Yeah, that was a mouthful.  A test in browser.test.js would illustrate it better ;)

``` javascript
    it('validates parent when child schema modified (gh-7493)', function(done) {
      const childSchema = new Schema({
        from: {
          type: Number,
          min: 0,
          max: 100
        },
        to: {
          type: Number,
          min: 0,
          max: 100
        }
      });
      const parentSchema = new Schema({
        payrate: {
          type: childSchema,
          default: {},
          validate: [
            {
              isAsync: false,
              validator: (payrate) => {
                return !payrate.from || !payrate.to || payrate.from<payrate.to;
              }
            }
          ]
        }
      });

      const parentDoc = new Document({}, parentSchema);

      parentDoc.payrate.from = 20;
      parentDoc.payrate.to = 10;
      console.log('before - fails to validate');
      assert.ok(parentDoc.validateSync());

      parentDoc.markModified('payrate');
      console.log('after - works');
      assert.ok(parentDoc.validateSync());

      done();
    });
```

The test above fails, but if you comment out the first assert.ok() it passes.

**What is the expected behavior?**

No need to manually mark modified.

**Please mention your node.js, mongoose and MongoDB version.**

node 10, and mongo nothing ;) browser-side.

Tested this on master and it still fails.

**Comment by vkarpov15** [comment] 2019-02-12 16:40
Looks like this isn't a bug with just the browser side. The issue is because of the `default` and the fix for #5885: Mongoose skips validators on single nested paths if just a subpath is modified, but we don't account for cases where the single nested path has a default and a subpath is modified. Fix will be in 5.4.12 :+1:

**Closed** 2019-02-12 16:41 UTC
Labels: confirmed-bug

**Comment by captaincaius** [comment] 2019-02-12 19:46
you're a machine! \o/

**Comment by vkarpov15** [comment] 2019-02-13 00:04
"I am a cybernetic organism, living tissue over a metal endoskeleton" :rofl: 

![Terminator](https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Terminator-2-judgement-day.jpg/250px-Terminator-2-judgement-day.jpg)
