### ISSUE TITLE
Mongoose 4.10 ValidationError "message" being serialized as "_message"

### ISSUE THREAD

**Issue by siboulet** [Automattic/mongoose#5309] opened 2017-05-30 16:44 UTC
Since 4.10 it seems Mongoose ValidationError *message* property was renamed to *_message*, or that it is no longer being properly serialized to *message* when converted to JSON.

Code:

```
doc.validate(function(err) {
    console.log(JSON.stringify(err, null, 4));
});
```

Result in 4.9:

```
{ errors: 
   { aa: 
      { message: 'Cast to Date failed for value "test" at path "aa"',
        name: 'CastError',
        stringValue: '"test"',
        kind: 'Date',
        value: 'test',
        path: 'aa',
        reason: [Object] },
     bb: 
      { message: 'Path `bb` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'bb' } },
  message: 'Model validation failed',
  name: 'ValidationError' }
```

In 4.10 (notice _message instead of message):

```
{ errors: 
   { aa: 
      { message: 'Cast to Date failed for value "test" at path "aa"',
        name: 'CastError',
        stringValue: '"test"',
        kind: 'Date',
        value: 'test',
        path: 'aa',
        reason: [Object] },
     bb: 
      { message: 'Path `bb` is required.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'required',
        path: 'bb' } },
  _message: 'Model validation failed',
  name: 'ValidationError' }
```

**Comment by luiselizondo** [comment] 2017-06-02 14:40
Yes, this broke my tests a couple of days ago.

**Comment by varunjayaraman** [comment] 2017-06-07 01:35
yep, it looks like this was caused by https://github.com/Automattic/mongoose/pull/5146/commits/68a94d004f498c10af41ac7a64f6fc3f58110361

so `message` became a getter, so it must not be serialized properly.

Here's a repro script:

```javascript
const mongoose = require('mongoose');
const co = require('co');
mongoose.Promise = global.Promise;
const GITHUB_ISSUE = `gh-5309`;

exec()
  .then(() => {
    console.log('successfully ran program');
    process.exit(0);
  })
  .catch(error => {
    console.error(`Error: ${ error }\n${ error.stack }`);
  });


function exec() {
  return co(function*() {
    const db = mongoose.createConnection(`mongodb://localhost:27017/${ GITHUB_ISSUE }`)
    const schema = new mongoose.Schema({
      name: { type: String, required: true }
    });


    const Model = db.model('Model', schema);

    const doc = new Model();
    
    try {
      yield doc.validate();
    } catch (error) {
      console.log(JSON.stringify(error, null, 4)); // `message` renamed to `_message`

    }
  });
}
```

**Comment by paranormal** [comment] 2017-06-09 09:24
Same here.
This would solve the issue, but it's quickly written and probably out of scope approach.
```
--- a/lib/error/validation.js
+++ b/lib/error/validation.js
@@ -44,6 +44,9 @@ Object.defineProperty(ValidationError.prototype, 'message', {
   get: function() {
     return this._message + ': ' + _generateMessage(this);
   },
+  set: function(message) {
+    return this._message = message;
+  },
```

**Closed** 2017-06-11 04:59 UTC
Labels: bug?
