### ISSUE TITLE
Mongoose 6.3.6 Performance slowdown

### ISSUE THREAD

**Issue by nikosszzz** [Automattic/mongoose#11919] opened 2022-06-09 12:47 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the performance issue has not already been reported

### Last performant version

6.3.5

### Slowed down in version

6.3.6

### Node.js version

16.14.2

### 🦥 Performance issue

Hello!

The latest version of mongoose which is 6.3.6 has significantly increased my bot's start up time and increased memory usage, as you can see in this picture:
![image](https://user-images.githubusercontent.com/53112175/172849885-8918080a-48f1-4e12-bf34-e11a9c55149e.png) (this picture shows how long it took to import a command.)

Meanwhile with 6.3.5, the results differ alot: 
![image](https://user-images.githubusercontent.com/53112175/172849966-1e08e277-3738-4fdb-96b7-f4acd2f6cb50.png)

As you can see it slows down the bot significantly by around 1000~ ms!

Also  here is how I connect to my MongoDB database:
```
import mongoose from "mongoose";
import { config } from "../../utils/config";

export async function database(): Promise<void> {
    mongoose.connect
        (
            config.MONGODB_URI
        )
        .then(() => console.log(`[DATABASE] Connected to database.`))
        .catch(err => console.log(`[DATABASE] Oops, there was an error! ${err}`));
}
```

### Steps to Reproduce

Run a discord bot with mongoose installed as a npm package and make it connect to a MongoDB database.

### Expected Behavior

Should not slow down the bot in any way.

**Comment by nikosszzz** [comment] 2022-06-09 12:51
Also, here is a great example of how bad it is jumping up the memory, the following image is using version 6.3.6:
![image](https://user-images.githubusercontent.com/53112175/172851061-897c692c-556f-4bca-b8c4-2ef7d0c4e454.png)


And this one is using 6.3.5:
![image](https://user-images.githubusercontent.com/53112175/172851068-379cb9a6-fec4-4b66-95e0-c93b63c7ed62.png)

**Comment by Uzlopak** [comment] 2022-06-10 13:03
There are not many changes from [6.3.5 to 6.3.6](https://github.com/Automattic/mongoose/compare/6.3.5...automattic:6.3.6)

Can you try to determine which one of the changes in the lib/*.js files resulted in the higher memory consumption?

**Comment by AbdelrahmanHafez** [comment] 2022-06-10 13:07
Welcome @nikosszzz 

We can't reproduce the whole system you have with discord bot and mongoose. Can you modify the script below to make it demonstrate the issue you're facing?
### 11919.js
```js
'use strict';
const mongoose = require('mongoose');
const assert = require('node:assert');


run().catch(console.error);

async function run() {
  const startAt = Date.now();
  await mongoose.connect('mongodb://localhost:27017/test');
  const connectedAt = Date.now();

  const millisecondsToConnect = connectedAt - startAt;
  console.log(millisecondsToConnect);
  assert.equal(millisecondsToConnect < 40, true);

  const mongoServerVersion = await getMongoServerVersion();

  console.log(mongoServerVersion);
  console.log(mongoose.version);

  console.log('All assertions passed.');
}

async function getMongoServerVersion() {
  const MongoAdmin = new mongoose.mongo.Admin(mongoose.connection.db);
  const info = await MongoAdmin.buildInfo();
  const mongoServerVersion = info.version;
  return mongoServerVersion;
}
```

### Output
```
$ node 11919.js
31
5.0.9
6.3.5
All assertions passed.

$ node 11919.js
28
5.0.9
6.3.6
All assertions passed.
```

The connection time is consistent for me: 10~35 milliseconds for both versions.

**Comment by nikosszzz** [comment] 2022-06-10 15:00
![image](https://user-images.githubusercontent.com/53112175/173093721-05dccc7c-55e6-48a3-abd6-adafa26a58bd.png)
It seems to fail at the assertion part, though it does show the time it took to connect.

**Comment by nikosszzz** [comment] 2022-06-10 15:06
Perhaps this is some issue with the default TSC compiler I use for my TypeScript discord bot? When I use SWC as the compiler, it is completely fine and way faster.

**Comment by AbdelrahmanHafez** [comment] 2022-06-10 15:19
What version of MongoDB are you using? What operating system are you using as well?

Can you move the assertions to the bottom of the function so the logs show up?
I'm guessing that this is related to https://github.com/Automattic/mongoose/issues/6566. Can you try to use this line to connect instead?
```js
  await mongoose.connect('mongodb://127.0.0.1:27017/test', { family: 4 });
```

**Comment by Uzlopak** [comment] 2022-06-10 15:25
I think it would really help if you patch in your project in node_modules/mongoose the changes you see in the link i provided and report back which of those changes resulted in the performance regression.

**Comment by nikosszzz** [comment] 2022-06-10 15:30
@AbdelrahmanHafez 

I'm using Windows 11 21H1 (build 22000.708).
MongoDB 5.0.8 Enterprise.

with the ```family: 4``` option:
![image](https://user-images.githubusercontent.com/53112175/173099556-d55426c6-93fd-473a-be7c-3bfb499175e2.png)

**Comment by Uzlopak** [comment] 2022-06-15 11:48
We will probably not be able to reproduce your issue, if you dont hint which of the few changes resulted in that slowdown. Just saying that you dont get sad, when this issue will get marked as stale and then auto-closed.

**Comment by vkarpov15** [comment] 2022-06-17 19:36
@nikosszzz try upgrading to 6.3.9. I suspect this may be due to #11898, which was released in 6.3.6 and caused a slowdown in the TypeScript compiler

**Comment by nikosszzz** [comment] 2022-06-18 12:10
Hmmm, yes. It seems to have improved and is back to normal.

**Comment by AbdelrahmanHafez** [comment] 2022-06-18 12:15
@vkarpov15 Is #11898 a typo? How can a TS PR affect JS connection performance?

**Comment by vkarpov15** [comment] 2022-06-18 13:10
@AbdelrahmanHafez OP is running through ts-node and reporting slow startup time. ts-node usually runs typescript compilation as part of startup. So that's my guess as to the root cause here

**Closed by vkarpov15** 2022-06-18 13:10 UTC
Labels: needs clarification

**Comment by AbdelrahmanHafez** [comment] 2022-06-18 13:22
I didn't notice the ts-node bit.

However, running the script in https://github.com/Automattic/mongoose/issues/11919#issuecomment-1152341631 calculates the time of the connection, which still demonstrates the issue, so this eliminates the possibility that this is a TS issue.

However, the issue is solved now, so I think we're good.
