### ISSUE TITLE
Validation of required field in non-required sub-document fails if the sub-document is changed before removal

### ISSUE THREAD

**Issue by anurag-rai** [Automattic/mongoose#8190] opened 2019-09-23 13:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

- Document schema has an array of sub-documents.
- Sub-document has a `required` field.
- Changing required field of one such sub-document but removing it from the array before saving the document gives a validation error for the required field.
- [Extension of [#1860](https://github.com/Automattic/mongoose/issues/1860)]

```
ValidationError: model validation failed: optionalSubdocuments.0.requiredField: Path `requiredField` is required.
```
**If the current behavior is a bug, please provide the steps to reproduce.**
```
// Schema and Model
var mongoose = require('mongoose');
var optionalSubdocSchema = new mongoose.Schema({
    requiredField: {
        type: String,
        required: true
    }
});
var Model = mongoose.model('model', new mongoose.Schema({
    name: { type: String, required: true },
    optionalSubdocuments: [optionalSubdocSchema]
}), 'test');

// Runner
function run() {
    createDocument()
        .then(function () { return updateOptionalDocument(); })
        .then(function () { return removeOptionalDocument(); })
        .then(function () { console.log('Success'); })
        .catch(err => console.log(err));
}

// ------------//
function createDocument() {
    return new Promise((resolve, reject) => {
        var x = new Model({ name: 'asd' });
        x.save(function (err) {
            if (err) return reject(err);
            resolve();
        });
    });
}
function updateOptionalDocument() {
    return new Promise((resolve, reject) => {
        Model.findOne({ name: 'asd' }, function (err, doc) {
            if (err) return reject(err);
            doc.optionalSubdocuments.push({
                requiredField: 'r1'
            });
            doc.save(function (err) {
                if (err) return reject(err);
                resolve();
            });
        });
    });
}
function removeOptionalDocument() {
    return new Promise((resolve, reject) => {
        Model.findOne({ name: 'asd' }, function (err, doc) {
            if (err) return reject(err);
            doc.optionalSubdocuments[0].requiredField = 'someOtherValue';   //Assigning a value
            doc.optionalSubdocuments.splice(0, 1);  // Removing the sub-document
            doc.save(function (err) {
                if (err) return reject(err);
                resolve();
            });
        });
    });
}
```

**What is the expected behavior?**
The document should be save after removing the sub-document and there should be no validation on the required field since no sub-documents exist in the final state.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Mongoose - 5.0.12
Node - 8.11.1
MongoDB - 4.0.4

**Comment by vkarpov15** [comment] 2019-09-27 17:45
This issue was fixed in Mongoose 5.3.13, I believe this is a duplicate of #7249. Please upgrade to Mongoose `>= 5.3.13` :+1:

**Closed by vkarpov15** 2019-09-27 17:45 UTC
Labels: has repro script
