### ISSUE TITLE
`$in` operator expects a union of strings to be an array of one these unions

### ISSUE THREAD

**Issue by ahmedelshenawy25** [Automattic/mongoose#10771] opened 2021-09-23 15:42 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`$in` operator expects a union of strings to be an array of one these unions
```
No overload matches this call.
  Overload 1 of 3, '(callback?: Callback<(Document<any, any, ICat> & ICat & { _id: string | ObjectId; })[]>): Query<(Document<any, any, ICat> & ICat & { ...; })[], Document<...> & ... 1 more ... & { ...; }, {}, ICat>', gave the following error.
    Type '{ $in: string[]; }' is not assignable to type 'string'.
  Overload 2 of 3, '(filter: FilterQuery<ICat>, callback?: Callback<ICat[]>): Query<(Document<any, any, ICat> & ICat & { _id: string | ObjectId; })[], Document<...> & ... 1 more ... & { ...; }, {}, ICat>', gave the following error.
    Type '("foo" | "bar" | "baz")[]' is not assignable to type 'RegExp[] | "foo"[] | "bar"[] | "baz"[]'.
      Type '("foo" | "bar" | "baz")[]' is not assignable to type 'RegExp[]'.
        Type 'string' is not assignable to type 'RegExp'.
          Type 'string' is not assignable to type 'RegExp'.
  Overload 3 of 3, '(filter: FilterQuery<ICat>, projection?: any, options?: QueryOptions, callback?: Callback<(Document<any, any, ICat> & ICat & { _id: string | ObjectId; })[]>): Query<...>', gave the following error.
    Type '("foo" | "bar" | "baz")[]' is not assignable to type 'RegExp[] | "foo"[] | "bar"[] | "baz"[]'.ts(2769)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

```js
import mongoose, { Types } from 'mongoose';

await mongoose.connect('mongodb://localhost:27017/test');

interface ICat {
  _id: Types.ObjectId | string;
  name?: 'foo' | 'bar' | 'baz';
}

const catSchema = new mongoose.Schema<ICat>({
  name: { type: String, enum: ['foo', 'bar', 'baz'], default: 'foo' }
});

const Cat = mongoose.model<ICat>('Cat', catSchema);

async function findCats() {
  await Cat.find({ name: { $in: ['foo', 'bar', 'baz'] } });
}
```

```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true
  }
}
```
**What is the expected behavior?**
It should allow an array of unions not an array of only one of these unions
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js: v14.15.5
Mongoose: v6.0.7
MongoDB: v4.43

**Comment by IslandRhythms** [comment] 2021-09-23 15:44
duplicate of #10767

**Comment by ahmedelshenawy25** [comment] 2021-09-23 15:53
My bad I didn't notice

**Closed** 2021-09-23 16:07 UTC
Labels: duplicate
