### ISSUE TITLE
findByIdAndUpdate() fails when readPreference=secondaryPreferred using a replica set

### ISSUE THREAD

**Issue by HolgerFrank** [Automattic/mongoose#2899] opened 2015-04-20 07:09 UTC
Log says: "MongoError: not master"
Happens in mongoose version 4.0.1
Worked in mongoose version 3.8.x

**Comment by vkarpov15** [comment] 2015-04-20 13:57
Duplicate of #2823.

**Closed** 2015-04-28 15:45 UTC
