### ISSUE TITLE
$geoNear, $near, and $nearSphere are not allowed in this context

### ISSUE THREAD

**Issue by Polqk** [Automattic/mongoose#6981] opened 2018-09-05 16:26 UTC
Hi,
After mongoose, mongodb update i have an error message with $near, I don't know if it mongodb or mongoose problem, before update it's work fine, thanks for help

api : 
![near](https://user-images.githubusercontent.com/36846411/45107055-a8053a80-b138-11e8-8890-a5b7f61646a0.png)

client : 
![near2](https://user-images.githubusercontent.com/36846411/45107065-b2273900-b138-11e8-8abf-6483d0c2b315.png)

client code : 
![near3](https://user-images.githubusercontent.com/36846411/45107080-bb180a80-b138-11e8-8cd3-c97256425ffd.png)

**Comment by lineus** [comment] 2018-09-05 19:49
Here are some questions @Polqk 

#### what versions of { mongoose, mongodb } did you upgrade { from, to } ?

#### what indexes have you created on the collection?

#### can you distill your current code down to a reproducible example including your schema that shows the error?

**Comment by Polqk** [comment] 2018-09-05 20:05
Hello,
upgraded versions : 
- mongoose 5.0.6 to 5.2.13
- mongodb 3.0.2 to 3.1.4
- mongodb-core 3.1.3

My collection that uses $near :

`module.exports = function (app) {
  const mongooseClient = app.get('mongooseClient');
  const { Schema } = mongooseClient;

  const places = new Schema({
    reference: { type: String }, // Faut mettre unique parking_id + reference
    price: Number,
    name: String,
    fees: Number,
    deposit: Number,
    available: Boolean,
    type: String, // parking, box, moto
    handicapped: Boolean,
    double: Boolean,
    outdoor: Boolean,
    owner_type: String,
  });

  const address = new Schema({
    number: { type: String, required: true },
    street: { type: String, required: true },
    zipcode: { type: String, required: true },
    city: { type: String, required: true },
    country: { type: String, required: true },
    streetview_url: String,
  });

  const parkings = new Schema({
    managers: [{
      type: Schema.Types.ObjectId, ref: 'users'
    }],
    agency_id: { type: Schema.Types.ObjectId, ref: 'agencies'},
    address,
    location: {
      type: { type: String, default: 'Point' },
      coordinates: { type: [Number], default: [0, 0] }
    },
    places: [places],
    reference_nomad: { type: String, required: true, index: { unique: true }},
    reference_owner: { type: String, required: true, index: { unique: true }},
    size: String,
    brightness: Boolean,
    available: Boolean,
    disable_reason: String, //orders_limit, availability, manager_inert, manual, manager_missing, address_missing, holidays
    images: [String],
    cctv: Boolean,
    enable_date : Date
  }, {
    timestamps: true
  });

  parkings.index({ location: '2dsphere' });
  return mongooseClient.model('parkings', parkings);
};
`

Client code : 
`app.service('parkings').find({
    query: {
      $limit:limit,
      $skip:skip,
      available: true,
      location: {
        $near: {
          $geometry: {
            type: 'Point',
            coordinates: [lat, lng],
          },
          $maxDistance: distance,
        },
      },
    },
  })`

Environment : FeathersJS, Express

Thanks

**Comment by lineus** [comment] 2018-09-05 21:03
@Polqk can you try to run the following script against your db and see if you get the same error as your express app?

### 6981.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  location: {
    type: String,
    coordinates: Array
  }
}, { typeKey: 'tipe'});

schema.index({ location: '2dsphere' });
const Test = mongoose.model('test', schema);

const tests = [];

for (let i = 1; i < 6; i++) {
  let long = ( i % 2 !== 0) ? i: -i;
  let lat = ( i % 2 !== 0) ? i + 2: -(i + 2);
  tests.push(new Test({
    name: `Test${i}`,
    location: {
      type: 'Point',
      coordinates: [long, lat]
    }
  }));
}

async function run() {
  await conn.dropDatabase();
  await Test.init().catch(e => console.error(e));
  await Test.create(tests);

  let query = {
    location: {
      $near: {
        $geometry: {
          type: 'Point',
          coordinates: [1,3]
        },
        $maxDistance: 775437
      }
    }
  };

  let docs = await Test.find(query);
  console.log(JSON.stringify(docs.map(o => o.name), null, 2));
  return conn.close();
}

run();
```

### Output:

```
issues: ./6981.js
[
  "Test1",
  "Test3",
  "Test5"
]
issues:
```

if you get the same results I got ( **Output above** ), you might try calling `mongoose.set('debug', true)` in your express app and share the query that gets sent to the db with $near in it.

For example, when I set 'debug' to true in the above script I get:
```
Mongoose: tests.find({ location: { '$near': { '$geometry': { type: 'Point', coordinates: [ 1, 3 ] }, '$maxDistance': 775437 } } }, { projection: {} })
```

**Comment by Polqk** [comment] 2018-09-06 08:26
Hi,

This is my results : 
- first run 
`node src/
[
  "Test1",
  "Test3",
  "Test5"
]
Done in 4.10s.
`

-second

`node src/
Mongoose: tests.createIndex({ location: '2dsphere' }, { background: true })
Mongoose: tests.insertOne({ location: { coordinates: [ 1, 3 ], type: 'Point' }, _id: ObjectId("5b90e444eb9e1c6a18a69c74"), name: 'Test1', __v: 0 })
Mongoose: tests.insertOne({ location: { coordinates: [ -2, -4 ], type: 'Point' }, _id: ObjectId("5b90e444eb9e1c6a18a69c75"), name: 'Test2', __v: 0 })
Mongoose: tests.insertOne({ location: { coordinates: [ 3, 5 ], type: 'Point' }, _id: ObjectId("5b90e444eb9e1c6a18a69c76"), name: 'Test3', __v: 0 })
Mongoose: tests.insertOne({ location: { coordinates: [ -4, -6 ], type: 'Point' }, _id: ObjectId("5b90e444eb9e1c6a18a69c77"), name: 'Test4', __v: 0 })
Mongoose: tests.insertOne({ location: { coordinates: [ 5, 7 ], type: 'Point' }, _id: ObjectId("5b90e444eb9e1c6a18a69c78"), name: 'Test5', __v: 0 })
Mongoose: tests.find({ location: { '$near': { '$geometry': { type: 'Point', coordinates: [ 1, 3 ] }, '$maxDistance': 775437 } } }, { projection: {} })
[
  "Test1",
  "Test3",
  "Test5"
]
Done in 3.96s.
`

**Comment by lineus** [comment] 2018-09-06 10:10
@Polqk can you add the debug statement to your app, and share the `$near` query that gets sent to the db here?

**Comment by Polqk** [comment] 2018-09-06 13:00
@lineus this is the query in API before reading db
`query { '$limit': '50',
  '$skip': '0',
  available: 'true',
  location:
   { '$near': { '$geometry': [ '48.88017199999999', '2.353329199999962' ], '$maxDistance': '3000' } } }
`

**Comment by lineus** [comment] 2018-09-06 13:12
@Polqk The purpose of my asking for the mongoose debug output is to rule out the possibility that feathersjs is causing any issues, perhaps misinterpreting your query into something unusable by mongodb.

By seeing the **actual** query that gets sent to the DB we might gain some insight into what's going wrong.

I can stand up a feathers/express instance if it will help, are you using feathers-mongoose?

**Comment by Polqk** [comment] 2018-09-10 16:09
Mongodb-core query in commands/Query() looks fine :/

![mongodbquery](https://user-images.githubusercontent.com/36846411/45309649-6d2e4880-b524-11e8-9c3f-f65ebfd5609d.png)

**Comment by lineus** [comment] 2018-09-12 20:55
@Polqk that actually looks like an `aggregate` call as opposed to a `find` query as previously discussed. 

The same error can be generated using only mongoose with the following code:

### 6981.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.connect('mongodb://localhost:50794/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  location: {
    type: String,
    coordinates: Array
  }
}, { typeKey: 'tipe' });

schema.index({ location: '2dsphere' });
const Test = mongoose.model('test', schema);

const tests = [];

for (let i = 1; i < 6; i++) {
  let long = (i % 2 !== 0) ? i : -i;
  let lat = (i % 2 !== 0) ? i + 2 : -(i + 2);
  tests.push(new Test({
    name: `Test${i}`,
    location: {
      type: 'Point',
      coordinates: [long, lat]
    }
  }));
}

async function run() {
  await conn.dropDatabase();
  await Test.init().catch(e => console.error(e));
  await Test.create(tests);

  let pipeline = [
    {
      $match: {
        location: {
          $near: {
            $geometry: {
              type: 'Point',
              coordinates: [1, 3]
            },
            $maxDistance: 775437
          }
        }
      }
  }
];

  let docs = await Test.aggregate(pipeline);
  console.log(JSON.stringify(docs.map(o => o.name), null, 2));
  return conn.close();
}

run().catch(console.error);
```
### Output:
```
issues: ./6981.js
{ MongoError: $geoNear, $near, and $nearSphere are not allowed in this context
    at queryCallback (/Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /Users/lineus/dev/node/mongoose/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
  ok: 0,
  errmsg:
   '$geoNear, $near, and $nearSphere are not allowed in this context',
  code: 2,
  codeName: 'BadValue',
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
^C
issues:
```

Is the output that you shared in the last image a result of the feathers find query? or are you calling aggregate directly somewhere?

**Comment by Polqk** [comment] 2018-09-13 08:20
Hello @lineus 
No, I don't call aggregate directly in my code, but as I see feathers-mongoose use it.

My last image is the query before reading DB in mongodb-core.

**Comment by lineus** [comment] 2018-09-13 11:59
@Polqk I created the following feathers/express app to test this, **can you modify it to reproduce the error you are seeing?** 

For convenience you can clone [this gist](https://gist.github.com/lineus/0e76d9b6a8c6689ab3c689b3a72c6092) to get the following files.

```
$ mkdir test
$ cd test
$ git clone https://gist.github.com/lineus/0e76d9b6a8c6689ab3c689b3a72c6092 .
$ npm install
$ seed.js
$ node app.js
```


### seed.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  available: Boolean,
  location: {
    type: String,
    coordinates: Array
  }
}, { typeKey: 'tipe' });

schema.index({ location: '2dsphere' });
const Test = mongoose.model('test', schema);

const tests = [];

for (let i = 1; i <= 20; i++) {
  let long = (i % 2 !== 0) ? i : -i;
  let lat = (i % 2 !== 0) ? i + 2 : -(i + 2);
  tests.push(new Test({
    name: `Test${i}`,
    available: true,
    location: {
      type: 'Point',
      coordinates: [long, lat]
    }
  }));
}

async function run() {
  await conn.dropDatabase();
  await Test.init().catch(e => console.error(e));
  await Test.create(tests);

  let docs = await Test.find();
  console.log(`inserted ${docs.length} docs.`);
  return conn.close();
}

run();
```

### app.js
```js
'use strict';

const URI = 'mongodb://localhost:27017/test';
const OPTS = { useNewUrlParser: true };
const assert = require('assert');
const feathers = require('@feathersjs/feathers');
const express = require('@feathersjs/express');
const socketio = require('@feathersjs/socketio');
const service = require('feathers-mongoose');
const mongoose = require('mongoose');
mongoose.set('debug', true);
mongoose.set('useCreateIndex', true);
mongoose.connect(URI, OPTS);

const Model = require('./model');

const app = express(feathers());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.configure(express.rest());
app.configure(socketio());

app.use( '/run', service({ Model }));

let query = {
  query: {
    $limit: 3,
    $skip: 1,
    available: true,
    location: {
      $near: {
        $geometry: {
          type: 'Point',
          coordinates: [1, 3]
        },
        $maxDistance: 950000
      }
    }
  }
};

app.service('run').find(query)
  .then(function(docs) {
    assert.strictEqual(docs.length, 3);
    assert.deepEqual(docs.map(d => d.name), ['Test3', 'Test5', 'Test2']);
    console.log('All Assertions Pass');
    process.exit(0);
  })
  .catch(function(e) {
    assert.ifError(e);
  });

app.use(express.errorHandler());

const port = 3030;
app.listen(port, () => {
  console.log(`Feathers server listening on port ${port}`);
});
```
### model.js
```js
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const schema = new Schema({
  name: String,
  available: Boolean,
  location: {
    type: String,
    coordinates: Array
  }
}, { typeKey: 'tipe' } );

schema.index({ location: '2dsphere' });

module.exports = mongoose.model('test', schema);
```
### package.json
```
{
  "name": "6981",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@feathersjs/express": "^1.2.5",
    "@feathersjs/feathers": "^3.2.1",
    "@feathersjs/socketio": "^3.2.4",
    "express": "^4.16.3",
    "feathers-mongoose": "^6.1.4",
    "mongoose": "^5.2.14"
  }
}
```
### Output:
```
6981: ./seed.js
inserted 20 docs.
6981: node app.js
Feathers server listening on port 3030
Mongoose: tests.createIndex({ location: '2dsphere' }, { background: true })
Mongoose: tests.find({ available: true, location: { '$near': { '$geometry': { type: 'Point', coordinates: [ 1, 3 ] }, '$maxDistance': 950000 } } }, { limit: 3, skip: 1, projection: {} })
All Assertions Pass
6981:
```

**Comment by Polqk** [comment] 2018-09-13 13:03
@lineus no error this time

inserted 20 docs.
C:\Users\***\***\0e76d9b6a8c6689ab3c689b3a72c6092>node app.js
Feathers server listening on port 3030
Mongoose: tests.createIndex({ location: '2dsphere' }, { background: true })
Mongoose: tests.find({ available: true, location: { '$near': { '$geometry': { type: 'Point', coordinates: [ 1, 3 ] }, '$maxDistance': 950000 } } }, { limit: 3, skip: 1, projection: {} })
All Assertions Pass

**Comment by lineus** [comment] 2018-09-13 13:31
I'd be happy to see if I can help sort out what's going on in your project if you'd like. You can post the url to the repo here or send it to me in an email ( lineus@gmail.com ). You can also join us on [Gitter.im](https://gitter.im/Automattic/mongoose) or [Slack](https://mongoose
jsteam.slack.com/) and pm me there.

**Comment by lineus** [comment] 2018-09-19 15:44
After looking at @Polqk's backend source, I was still unable to replicate this with just mongoose or with express/feathers/feathers-mongoose. @Polqk is investigating a workaround on his side. 

@vkarpov15 can you help me verify whether the error message in question `MongoError: $geoNear, $near, and $nearSphere are not allowed in this context` **only** occurs in aggregate? I'm not familiar enough with C to be 100% certain, but it appears that way to me.

**Comment by Polqk** [comment] 2018-09-19 17:57
It's feathers-mongoose package the problem, It works on v6.1.2 and on v6.1.4 it's same error

**Comment by vkarpov15** [comment] 2018-09-26 17:59
@lineus I can't confirm that, I don't have nearly enough experience with the mongodb server to do anything beyond what you've already done.

**Comment by vkarpov15** [comment] 2018-09-26 18:00
I'm going to close this for now @Polqk . Feel free to re-open if it turns out this is an issue with Mongoose and not feathers-mongoose.

**Closed by vkarpov15** 2018-09-26 18:00 UTC
Labels: help

**Comment by StefanBalea** [comment] 2018-10-01 19:17
Hi, using **countDocuments** in combination with near query leads to the same error. I used **estimatedDocumentCount** instead and it works ok. :)

**Comment by vkarpov15** [comment] 2018-10-07 20:46
@StefanBalea that sounds like a problem. [`estimatedDocumentCount()` does **not** take a filter parameter](https://mongoosejs.com/docs/api.html#query_Query-estimatedDocumentCount). Using `estimatedDocumentCount()` with `$near` doesn't make sense because you can't specify a query.

**Comment by Christilut** [comment] 2019-01-14 17:37
Just ran into this error with this query on `countDocuments()`:
````
{
  location: {
    '$nearSphere': {
      '$geometry': {
            type: 'Point',
            coordinates: [10, 30]
      },
        '$minDistance': 0,
          '$maxDistance': 5000
    }
  }
}
```

However it works fine with `count()` but since it's deprecated I don't really want to use it.

Mongoose 5.3.9
Mongo 4.0.3

**Comment by Polqk** [comment] 2019-01-14 20:40
@cbeninati Hi, I just downgraded the feathers-mongoose package to 6.1.3

**Comment by cbeninati** [comment] 2019-01-14 20:42
@Polqk Thanks for the quick response. Unfortunate it involves a downgrade. :(

**Comment by Polqk** [comment] 2019-01-14 20:46
@cbeninati Just check releases one by one. In my project, it was 6.1.4 before downgrade

**Comment by cbeninati** [comment] 2019-01-14 21:09
Apologies for the cross-posting, but for the sake of the all-powerful Google and posterity, here's the solution (for `feathersjs-mongoose`).

When instantiating your mongoose service, set the `useEstimatedDocumentCount` option to `true`.

```js
const createService = require('feathers-mongoose');

createService({ useEstimatedDocumentCount: true });
```
https://github.com/feathersjs-ecosystem/feathers-mongoose/issues/264#issuecomment-454161365
