### ISSUE TITLE
Error: SubDocs.remove() is not a function  #parent.children.id(_id).remove() --> "remove() is not a function"

### ISSUE THREAD

**Issue by AliQasim165878** [Automattic/mongoose#13284] opened 2023-04-17 15:33 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

7.0.3

### Node.js version

19.8.1

### MongoDB server version

6.0

### Description

**1 - This is the code in embedding.js**
```
const mongoose = require("mongoose");

mongoose
  .connect("mongodb://127.0.0.1/playground")
  .then(() => console.log("Connected to MongoDB..."))
  .catch((err) => console.error("Could not connect to MongoDB...", err));

const authorSchema = new mongoose.Schema({
  name: String,
  bio: String,
  website: String,
});

const Author = mongoose.model("Author", authorSchema);

const Course = mongoose.model(
  "Course",
  new mongoose.Schema({
    name: String,
    authors: [authorSchema],
  })
);

async function removeAuthor(courseId, authorId) {
  const course = await Course.findById(courseId);
  console.log(course);
  var theAuthor = course.authors.id(authorId);
  console.log(theAuthor);
  theAuthor.remove();
  console.log(await course.save());
}

removeAuthor("643d59f229408d7d1b928522", "643d5bc8cd1f1d2976ae45fa");
```
**2 - When I run following code**
**node .\embedding.js**

**3 - I get the following error**
C:\Node\mongo-demo\embedding.js:57
  theAuthor.remove();
            ^

TypeError: theAuthor.remove is not a function
    at removeAuthor (C:\Node\mongo-demo\embedding.js:57:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Steps to Reproduce

**1 - Create a file embedding.js**
```
const mongoose = require("mongoose");

mongoose
  .connect("mongodb://127.0.0.1/playground")
  .then(() => console.log("Connected to MongoDB..."))
  .catch((err) => console.error("Could not connect to MongoDB...", err));

const authorSchema = new mongoose.Schema({
  name: String,
  bio: String,
  website: String,
});

const Author = mongoose.model("Author", authorSchema);

const Course = mongoose.model(
  "Course",
  new mongoose.Schema({
    name: String,
    authors: [authorSchema],
  })
);

async function removeAuthor(courseId, authorId) {
  const course = await Course.findById(courseId);
  console.log(course);
  var theAuthor = course.authors.id(authorId);
  console.log(theAuthor);
  theAuthor.remove();
  console.log(await course.save());
}

removeAuthor("643d59f229408d7d1b928522", "643d5bc8cd1f1d2976ae45fa");
```
**2 - Run following code on terminal**
**node .\embedding.js**

**3 -Get following error**
C:\Node\mongo-demo\embedding.js:57
  theAuthor.remove();
            ^

TypeError: theAuthor.remove is not a function
    at removeAuthor (C:\Node\mongo-demo\embedding.js:57:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Expected Behavior

The Author with the specified id (as the second parameter) should be deleted from the Mongoose Collection Courses "from its sub document Authors"

**Comment by IslandRhythms** [comment] 2023-04-18 20:31
triple backticks ` on the opening and closing to create a code block

**Comment by IslandRhythms** [comment] 2023-04-19 19:47
I'm reading the docs and don't see anywhere listed where a remove function is described. Here is an alternative do doing what you want.

```javascript
const mongoose = require("mongoose");


const authorSchema = new mongoose.Schema({
  name: String,
  bio: String,
  website: String,
});

const Author = mongoose.model("Author", authorSchema);

const Course = mongoose.model(
  "Course",
  new mongoose.Schema({
    name: String,
    authors: [authorSchema],
  })
);
let authorId = '';
let courseId = '';
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const author = await Author.create({
    name: 'author', bio: 'authorbio', website: 'google.com'
  })

  const entry = await Course.create({
    name: 'Course',
    authors: [author]
  });
  authorId = author._id;
  courseId = entry._id;
}


async function removeAuthor(courseId, authorId) {
  const course = await Course.findById(courseId);
  console.log('Found a course', course);
  course.authors.pull({_id: authorId});
  await course.save();
  console.log('course after deletion', course);
}

async function test() {
  await run();
  await removeAuthor(courseId, authorId);
}

test();
```

**Comment by IslandRhythms** [comment] 2023-04-19 19:56
`pull()` works just fine

```javascript

const mongoose = require("mongoose");


const authorSchema = new mongoose.Schema({
  name: String,
  bio: String,
  website: String,
});

const Author = mongoose.model("Author", authorSchema);

const Course = mongoose.model(
  "Course",
  new mongoose.Schema({
    name: String,
    authors: [authorSchema],
  })
);
let authorId = '';
let courseId = '';
async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const author = await Author.create({
    name: 'author', bio: 'authorbio', website: 'google.com'
  })

  const entry = await Course.create({
    name: 'Course',
    authors: [author]
  });
  authorId = author._id;
  courseId = entry._id;
}


async function removeAuthor(courseId, authorId) {
  const course = await Course.findById(courseId);
  console.log('Found a course', course);
  // course.authors.pull({_id: authorId});
  const theAuthor = course.authors.id(authorId);
  console.log('what is the author', theAuthor);
  theAuthor.remove();
  await course.save();
  console.log('course after deletion', course);
}

async function test() {
  await run();
  await removeAuthor(courseId, authorId);
}

test();
```

**Comment by vkarpov15** [comment] 2023-04-23 17:41
@hasezoey is right, the issue is that `remove()` has been renamed `deleteOne()`. `theAuthor.remove();` -> `theAuthor.deleteOne();` should work :+1:

**Closed by vkarpov15** 2023-04-23 17:41 UTC
Labels: confirmed-bug
