### ISSUE TITLE
Doing bulkWrite using updateOne with upsert and setDefaultsOnInsert inserts new document with filtered property value

### ISSUE THREAD

**Issue by Krickew** [Automattic/mongoose#9180] opened 2020-06-26 13:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When doing `bulkWrite` on model using `updateOne` with the options `upsert` and `setDefaultsOnInsert` set to true the inserted documents gets the specified filter property value instead of the default property value in model schema.

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
import mongoose, { Schema, Document } from 'mongoose';

interface Item extends Document {
  uuid: string;
  name: string;
}

(async () => {
  const dbUri = 'mongodb://localhost:27017/test';
  const db = await mongoose.connect(dbUri, { useNewUrlParser: true });

  const schema = new Schema({
    uuid: {
      type: String,
      default: 'default uuid',
    },
    name: {
      type: String,
    },
  });

  const model = mongoose.model<Item>('item', schema);

  const item = await model.create({ name: 'John Doe' });

  await model.bulkWrite([
    {
      // works as expected when document already exists
      updateOne: {
        filter: { uuid: item.uuid },
        update: { $set: { name: 'Jane Doe' } },
        upsert: true,
      },
    },
    {
      // new document gets the filtered uuid value on insert
      updateOne: {
        filter: { uuid: 'none existing uuid' },
        update: { $set: { name: 'John Doe' } },
        upsert: true,
      },
    },
    {
      // new document gets the filtered uuid value on insert
      updateOne: {
        filter: { uuid: 'none existing uuid 2' },
        update: { $set: { name: 'John Doe' } },
        upsert: true,
        setDefaultsOnInsert: true, // does not work
      },
    },
  ]);

  await db.disconnect();
  process.exit(0);
})();
```

**What is the expected behavior?**
New documents should be provided the default value specified in model schema when not provided in update query and setDefaultsOnInsert is set to true.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node v12.16.3
MongoDB v4.2.3
Mongoose v5.9.20

**Comment by AbdelrahmanHafez** [comment] 2020-06-26 16:26
I believe this is by design, correct me if I am wrong here @vkarpov15 

`upsert` takes the values from `update`, adds it to the values in `filter`, and that's the new document you're getting.

`setDefaultsOnInsert` sets defaults **only** when a field is not present in the replacement document, which is the merged objects.

### 9180.js
```js
'use strict';
const mongoose = require('mongoose');
const { Schema } = mongoose;
const assert = require('assert');

const userSchema = new Schema({
  name: { type: String, default: 'Default Name' },
  age: Number
});

const User = mongoose.model('User', userSchema);

run().catch(console.error);

async function run () {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();

  await test1();
  await test2();
  await test3();

  console.log('All assertions passed.');
}


async function test1 () {
  // merges both values
  const res = await User.updateOne(
    { name: 'Hafez' },
    { age: 25 },
    { upsert: true, setDefaultsOnInsert: true }
  );
  const userId = res.upserted[0]._id;

  const user = await User.findOne({ _id: userId });
  assert.equal(user.name, 'Hafez');
  assert.equal(user.age, 25);
}

async function test2 () {
  // `update` has higher priority over `filter`
  const res = await User.updateOne(
    { name: 'Non existing doc' },
    { name: 'Name from update', age: 25 },
    { upsert: true, setDefaultsOnInsert: true }
  );
  const userId = res.upserted[0]._id;

  const user = await User.findOne({ _id: userId });
  assert.equal(user.name, 'Name from update');
  assert.equal(user.age, 25);
}

async function test3 () {
  // `setDefaultsOnInsert` works when field is not present
  const res = await User.updateOne(
    { age: 999 },
    { age: 25 },
    { upsert: true, setDefaultsOnInsert: true }
  );
  const userId = res.upserted[0]._id;

  const user = await User.findOne({ _id: userId });
  assert.equal(user.name, 'Default Name');
  assert.equal(user.age, 25);
}
```

### Output:
```
All assertions passed.
```

**Comment by Krickew** [comment] 2020-06-29 08:10
I see now that the actual documentation says the very thing you mention so i guess it works as expected.

But Isn't that a strange behaviour in some cases tho? Let's say i have an incoming body with both new and existing documents that i want to either insert or update depending on if the provided `_id` exists. I provide the `upsert` option expecting the existing documents to update and non existing to be inserted but instead i get a document with an invalid `_id`. I do not expect having to handle the `_id` value on my own here. 

Couldn't there be an additional option to only insert the `update` query data if wanted?

```ts
import mongoose, { Schema, Document } from 'mongoose';

interface Item extends Document {
  name: string;
  age: number;
}

(async () => {
  const dbUri = 'mongodb://localhost:27017/test';
  const db = await mongoose.connect(dbUri, { useNewUrlParser: true, useUnifiedTopology: true });

  const schema = new Schema({
    name: {
      type: String,
    },
    age: {
      type: Number,
    },
  });

  const model = mongoose.model<Item>('item', schema);

  const item = await model.create({
    name: 'John Doe',
    age: 20,
  });

  const body = [
    {
      _id: item.id,
      age: 21,
    },
    {
      name: 'Jane Doe',
      age: 20,
    },
  ];

  await Promise.all(
    body.map((item) =>
      model.updateOne({ _id: item._id }, item, {
        upsert: true,
        // onlyInsertUpdate: true?
      })
    )
  );

  await db.disconnect();
  process.exit(0);
})();
```

**Comment by AbdelrahmanHafez** [comment] 2020-07-04 03:46
`null` is a valid `_id` in MongoDB, so when you set `_id` to `null` it gets inserted as is, this behavior is defined by MongoDB, mongoose doesn't know whether or not a document exists at the time of constructing the query.

But since you already know whether this is an update (document has `_id`) or an insert, why don't you just use an if-else statement?

###  9180.js
```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('assert');

(async function() {
  const dbUri = 'mongodb://localhost:27017/test';
  const db = await mongoose.connect(dbUri, { useNewUrlParser: true, useUnifiedTopology: true });

  await db.connection.dropDatabase();

  const userSchema = new Schema({
    name: {
      type: String
    },
    age: {
      type: Number
    }
  });

  const User = mongoose.model('User', userSchema);

  const user = await User.create({
    name: 'John Doe',
    age: 20
  });

  const usersFromBody = [
    {
      _id: user.id,
      age: 21
    },
    {
      name: 'Jane Doe',
      age: 20
    }
  ];

  const res = await Promise.all(
    usersFromBody.map(async(user) => {
      if (user._id) {
        return await User.updateOne({ _id: user._id }, user);
      } else {
        return await User.create(user);
      }
    })
  );

  assert.equal(res[0].nModified, 1);
  assert.ok(res[1]._id);

  console.log('All assertions passed.');

  await db.disconnect();
  process.exit(0);
})();
```

### Output
```
All assertions passed.
```

**Comment by vkarpov15** [comment] 2020-07-04 14:51
I took a closer look and this is expected behavior. What ends up in the `filter` is what ends up getting stored by default, and we can't disable that because that's MongoDB server behavior that isn't configurable. You can work around this by using `$setOnInsert` as shown below:

```javascript
  await model.bulkWrite([
    {
      // new document gets the filtered uuid value on insert
      updateOne: {
        filter: { uuid: 'none existing uuid 2' },
        update: { $set: { name: 'John Doe' }, $setOnInsert: { uuid: 'default uuid' } },
        upsert: true,
      },
    },
  ]);
```

**Closed** 2020-07-04 14:51 UTC
Labels: has repro script

**Comment by Krickew** [comment] 2020-07-06 12:53
> But since you already know whether this is an update (document has `_id`) or an insert, why don't you just use an if-else statement?
> 

I wanted to avoid doing multiple writes for each update/insert through mongoose and thought that `bulkWrite` would be better suited.

I understand if it got confusing that `bulkWrite` wasn't used in the latter example, i must have missed to change it back when experimenting.. The example works out there too anyway as it is still not what I expect when inserting a new document directly with `updateOne` using the `upsert` option.

I instead got around  it by assigning a default ObjectId when destructuring the _id as followed:

```ts
import { Types } from 'mongoose';

const { ObjectId } = Types;

await model.bulkWrite(
  body.map((item) => {
    const { _id = ObjectId() } = item;
    return {
      updateOne: {
        filter: { _id },
        update: { $set: { name: 'Jane Doe' } },
        upsert: true,
      },
    };
  })
);
```
