### ISSUE TITLE
Docs page for how to fix deprecation warnings

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#6922] opened 2018-08-27 01:13 UTC
After #6917 it should now be possible to clear up all deprecation warnings by:

* Replacing `update()` with `updateOne()`, `updateMany()`, or `replaceOne()`
* Replacing `remove()` with `deleteOne()` or `deleteMany()`
* Setting `mongoose.set('useFindAndModify', false);`
* Setting `mongoose.set('useCreateIndex', true);`
* Setting `mongoose.set('useNewUrlParser', true);`

Need a docs page to summarize this.

**Comment by isLishude** [comment] 2018-08-27 07:03
If these are set, would it be incompatible with or breaking the current  program?

**Comment by ulrichb** [comment] 2018-08-27 14:00
I set `mongoose.set('useCreateIndexes', true)` and still get `DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead`.

**Comment by Fonger** [comment] 2018-08-27 14:16
@ulrichb Are you sure that you're using mongoose@5.2.10 that released an hour ago?

**Comment by lineus** [comment] 2018-08-27 14:31
I can replicate what @ulrichb is seeing on 5.2.10 with:

### 6922.js
```js
#!/usr/bin/env node
'use strict';

const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
mongoose.set('useCreateIndexes', true);

const conn = mongoose.connection;
const Schema = mongoose.Schema;

const schema = new Schema({
  name: {
    type: String,
    unique: true
  }
});

const Test = mongoose.model('test', schema);

const test = new Test({ name: 'one' });

async function run() {
  console.log(`mongoose version: ${mongoose.version}`);
  await conn.dropDatabase();
  await test.save();
  return conn.close();
}

run();
```
### Output:
```
issues: ./6922.js
mongoose version: 5.2.10
(node:7186) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
issues:
```

**Comment by saagar2000** [comment] 2018-08-27 15:13
I think it is mongoose.set('useCreateIndex', true)

**Comment by lineus** [comment] 2018-08-27 15:21
updated the original comment to reflect @saagar2000's observation. Thanks @saagar2000 !

**Comment by MongoExpUser** [comment] 2018-08-28 05:05
Yes, it should be: 
**mongoose.set('useCreateIndex', true)**  **not** mongoose.set('useCreateIndex**es**', true)

Remove the "es" at the end of Index.

**Comment by mycompassspins** [comment] 2018-08-29 14:47
I'm seeing the `collection.{remove|update} is deprecated` warning on `Document.{remove|update}` operations. 

```
const doc = await model.findById(someId);
await doc.update({ $set: { someProp: true }}); // Deprecation warning
await doc.remove() // Deprecation warning
```

**Comment by vkarpov15** [comment] 2018-08-29 19:53
@adamreisnz yeah we should add an alias `doc.delete()`, ditto for `doc.update()` @mycompassspins

**Comment by ParikshitChavan** [comment] 2018-09-03 03:10
mongoose.set('useCreateIndex', true) has no affect for me. 😞 
still getting the 'DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.'

**Comment by Fonger** [comment] 2018-09-03 11:47
@ParikshitChavan Did you set this option before calling `mongoose.model()`?

**Comment by govindrai** [comment] 2018-09-03 17:30
Using mongoose 5.2.12. I also get this: `the options [useCreateIndex] is not supported` in addition to the deprecation warning.

**Comment by pumano** [comment] 2018-09-03 21:39
looks like it should work properly when pass as connection option, but it doesn't. only after explicit `mongoose.set()`

**Comment by ParikshitChavan** [comment] 2018-09-04 05:50
@Fonger @govindrai 
I tried doing this through connection options and though mongoose.set()
before and after connection to the DB.
the 'DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.' always seems to persist.

**Comment by Avcajaraville** [comment] 2018-09-04 09:32
Same here, cant get rid of `collection.ensureIndex is deprecated`warning ... No matter if use set or as an option...

**Comment by Fonger** [comment] 2018-09-04 11:31
@ParikshitChavan @govindrai @Avcajaraville 

You have to put `mongoose.set('useCreateIndex', true)` before **EVERY** `mongoose.model()` call
(Note: not `mongoose.connect()` ).

This should be fixed in a later version.

**Comment by arastu** [comment] 2018-09-05 23:30
@Fonger after upgrade to 5.2.13 the issue still exists

**Comment by lineus** [comment] 2018-09-06 00:42
@arastu can you create a reproducible example with one or more files where you demonstrate that you are using 5.2.13 and are seeing one or more of these warnings?

For Example:

### index.js
```js
#!/usr/bin/env node
'use strict';

const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('useCreateIndex', true);
mongoose.set('useFindAndModify', false);
mongoose.connect('mongodb://localhost:27017/test', { useNewUrlParser: true });
const conn = mongoose.connection;


const One = require('./one');
const Two = require('./two');

const one = new One({ name: '1' });
const two = new Two({ name: '2' });

async function run() {
  assert.strictEqual(mongoose.version, '5.2.13');
  await conn.dropDatabase();
  await Promise.all([One.init(), Two.init()]);
  await one.save();
  await two.save();
  await One.findOneAndUpdate({}, { name: 'one' });
  await Two.findOneAndUpdate({}, { name: 'two' });
  console.log(`${mongoose.version} should show no deprecations with the new settings.`);
  return conn.close();
}

run();
```
### one.js
```js
'use strict';

const mongoose = require('mongoose');

const schema = new mongoose.Schema({ name: { type: String, unique: true } });

module.exports = mongoose.model('one', schema);
```
### two.js
```js
'use strict';

const mongoose = require('mongoose');

const schema = new mongoose.Schema({ name: { type: String, unique: true } });

module.exports = mongoose.model('two', schema);
```

### Output:
```
6922: ./index.js
5.2.13 should show no deprecations with the new settings.
6922:
```

**Comment by govindrai** [comment] 2018-09-07 23:50
working for me in 5.2.13. @lineus will useCreateIndex be supported as a connection option? Currently getting `the options [useCreateIndex] is not supported`

i.e.
 `mongoose.connect(
      process.env.MONGODB_URI,
      {
        useNewUrlParser: true,
        autoIndex: false,
        useCreateIndex: true,
      }
    )
`

**Comment by vkarpov15** [comment] 2018-09-10 23:41
@govindrai right now you should do `mongoose.set('useCreateIndex', true)` as specified in the [deprecation warning docs](https://mongoosejs.com/docs/deprecations.html#summary). But we'll add that as well.

**Comment by mycompassspins** [comment] 2018-09-11 20:05
I've upgraded to `5.2.14` and am still seeing deprecation warnings that don't make sense. For instance, `collection.update is deprecated . . .` when I'm actually using `document.update`. Same for the `remove` method of both the model and the document. Switching to `document.updateOne` produces` TypeError: document.updateOne is not a function`. Am I missing something here?

**Comment by Avcajaraville** [comment] 2018-09-12 10:11
@mycompassspins Did you track the stack producing the warning ?

For instance, in my case turns out the deprecation warning was happening due to [connect mongo](https://github.com/jdesboeufs/connect-mongo#connect-mongo).

If you follow the above instructions, at least for me, all deprecation warning where gone :)

**Comment by mycompassspins** [comment] 2018-09-12 14:00
Here's the stack:

```
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
    at NativeCollection.(anonymous function) [as update] (/MyProject/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:143:28)
    at NodeCollection.update (/MyProject/node_modules/mquery/lib/collection/node.js:66:19)
    at model.Query._updateThunk (/MyProject/node_modules/mongoose/lib/query.js:3233:23)
    at model.Query.Query._execUpdate (/MyProject/node_modules/mongoose/lib/query.js:3245:23)
    at process.nextTick (/MyProject/node_modules/kareem/index.js:333:33)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
Obviously, `Model.update` is actually executed, even though I'm calling `MongooseDocument.update`. This is what I'm doing, more or less:

```
async UpdateMyDocument(id:string, update:MyDocument):Promise<MyDocument>
{
	const doc = await MyModel.findById(id)
		.populate({ path: 'somePath', populate: [{ path: 'somePath.nested' }] });

	return await doc.update(update); // <= MongooseDocument.update is producing a Model.update deprecation warning
}
```

**Comment by vkarpov15** [comment] 2018-09-16 19:58
@mycompassspins are you sure you're on 5.2.14? We [added `doc.updateOne(update)` in 5.2.13](https://github.com/Automattic/mongoose/blob/master/History.md#5213--2018-09-04)

**Comment by lineus** [comment] 2018-09-21 11:13
There's an internal configuration typo in `@5.2.16` that causes the deprecation notice for createIndexes to reemerge when you call createIndexes explicitly.

**Comment by venkyyPoojari** [comment] 2018-10-07 05:48
(node:6455) DeprecationWarning: GridStore is deprecated, and will be removed in a future version. Please use GridFSBucket instead. What about this ??

**Comment by vkarpov15** [comment] 2018-10-11 00:28
@venkyyPoojari that's an old one, predates mongoose 5, but worth addressing. We will fix.

**Comment by venkyyPoojari** [comment] 2018-10-11 01:51
Thanks, I am going to use this for production, so please help as soon as possible

**Comment by vkarpov15** [comment] 2018-10-15 04:28
@venkyyPoojari @romain10009 that's because gridfs-stream is out of date. The MongoDB driver has a new streaming API for GridFS that you should use instead: https://thecodebarbarian.com/mongodb-gridfs-stream

**Closed** 2018-10-15 04:45 UTC
Labels: docs

**Comment by piavgh** [comment] 2020-04-27 07:24
@vkarpov15 : Hi, how can I access `db.fs.files` from mongoose?

I tried this but it does not work:

```javascript
var mongoose = require('mongoose');
var conn = mongoose.connection;
conn.db.fs.files.findOne({_id: mongoId}, callback);
```

It will throw error `Uncaught TypeError: Cannot read property 'files' of undefined`
