### ISSUE TITLE
Property 'Buffer' does not exist on type 'typeof globalThis'.

### ISSUE THREAD

**Issue by kevit-amish-faldu** [Automattic/mongoose#10415] opened 2021-07-03 10:42 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/86599083/124351443-f18f7000-dc17-11eb-8c0d-b151b94d0c61.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

steps to reproduce issue
1. Create a test folder
2. Run "npm init"
3. Run "npm i mongoose"
4. Run "npm i typescript@latest --save-dev"
5. Create a test.ts file and only import mongoose
6. Run "tsc test.ts" in terminal

**What is the expected behavior?**
Compile without any errors

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js version - v16.4.1
Mongoose version - v5.13.1
MongoDb version - v4.4.6

**Comment by SFVII** [comment] 2021-07-03 12:34
I just send  pull request https://github.com/Automattic/mongoose/pull/10417 i think that will fix your problem

**Comment by SFVII** [comment] 2021-07-03 13:26
For the moment try to use this npm install --save sfvii/mongoose

**Comment by ekow-mensah** [comment] 2021-07-03 16:26
I tried using this i.e. "npm install --save sfvii/mongoose " and still ran into the same issue

**Comment by nickjtch** [comment] 2021-07-03 17:22
@SFVII thank you for this!

Any updates regarding this issue?

**Comment by Markkop** [comment] 2021-07-03 17:27
`npm install --save sfvii/mongoose` didn't work for me too. Is there any other possible workaround?

**Comment by nickjtch** [comment] 2021-07-03 17:58
Tried downgrading to previous versions. Still doesn't help.

**Comment by geordle** [comment] 2021-07-03 18:05
Think explicitly adding `@types/node` should work as a workaround. `npm i --save-dev @types/node@^14.0.0`.

**Comment by ekow-mensah** [comment] 2021-07-03 18:10
> Think explicitly adding `@types/node` should work as a workaround. `npm i --save-dev @types/node@^14.0.0`.

yes this works! thanks @geordle

**Comment by vkarpov15** [comment] 2021-07-03 21:38
Fix is in https://github.com/Automattic/mongoose/commit/726ce8ba1499bb2ad629d887bba79e9fb33c03ca.

As a workaround, add `@types/node: "15.x"` to your dependencies in `package.json`. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53669.

**Closed by vkarpov15** 2021-07-03 21:38 UTC

**Comment by SFVII** [comment] 2021-07-04 20:35
Just put @types/node: "15.x"  on last line of depencies of your package.json that will override the other. But be sure that is placed on the last line. If you want to use npm install --save sfvii/mongoose  samethink on last line

**Comment by ejacevedo** [comment] 2021-07-08 21:30
> Piense que agregar explícitamente `@types/node`debería funcionar como una solución temporal. `npm i --save-dev @types/node@^14.0.0`.

thanks, it works

**Comment by ejacevedo** [comment] 2021-07-08 21:31
> Think explicitly adding `@types/node` should work as a temp workaround. `npm i --save-dev @types/node@^14.0.0`.

thanks, it works

**Comment by SubJunk** [comment] 2021-07-12 22:59
Can someone please clarify whether this is a problem with just that types project, or is mongoose incompatible with Node 16?

**Comment by vkarpov15** [comment] 2021-07-13 15:08
@SubJunk the issue is with the types project, they introduced a sizable breaking change that has nothing to do with the Node.js runtime. Mongoose supports Node v16.

**Comment by SubJunk** [comment] 2021-07-14 00:28
@vkarpov15 thanks for clarifying

**Comment by SerhiiShkv** [comment] 2021-07-21 07:53
Still the same problem with node: "16.x" versions
