### ISSUE TITLE
Configure the mongodb library

### ISSUE THREAD

**Issue by medez** [Automattic/mongoose#6743] opened 2018-07-19 13:13 UTC
Hello, 

I would love like to use mongoose with an in-memory database system. I read two issues where you explain that you cannot maintain the compatibility with mongodb and maintain your own system, which I completely understand. 

So I would like to purpose you an alternative, just give the availability to configure the mongodb library to use, for example with an envrionment variable, and let the developer maintain it if they want to. 

For example, in my unit tests that run on an CI system, I need to use mongo-mock instead of mongodb, because I cannot install a mongoDB server on it. I could set process.env.MONGOOSE_MONGO_LIB = 'mongo-mock'.

What do you think about it ? If you want, I can also make a pull request.

Regards

**Comment by vkarpov15** [comment] 2018-07-22 22:08
Sure, you're welcome to try a pull request. We have a notion of "drivers" that behaves similarly to what you described, it just isn't very well fleshed out.

**Comment by vkarpov15** [comment] 2019-02-15 19:10
Looking more closely, this is a duplicate of #3129. Please follow that issue for updates.

**Closed by vkarpov15** 2019-02-15 19:10 UTC
