### ISSUE TITLE
Typescript error when passing union type from function argument in query

### ISSUE THREAD

**Issue by Fish-o** [Automattic/mongoose#10711] opened 2021-09-11 17:03 UTC
When having a model with these types:
```ts
export type Cooldown = PlayerCooldown | TeamCooldown;
export interface PlayerCooldown {
  id: string;
  for: "player";
  playerId: string;
}
export interface TeamCooldown {
  id: string;
  for: "team";
  teamId: string;
}
```

you can run all of this without problems:
 ```ts
let forWho:  "team" = "team";
CooldownModel.findOne({for:forWho});

let forWho: "player" = "player";
CooldownModel.findOne({for:forWho});

let forWho: "player" | "team" = "team";
CooldownModel.findOne({for:forWho});
 ``` 

### BUT

when the type of forWho is a union type, AND it is form a function argument, typescript gives an error

example:
```ts
async function getCooldownFromId(
  forWho: "team" | "player",
  cooldownId: string
): Promise<undefined> {
  const res = await CooldownDB.findOne({
    id: cooldownId,
    for: forWho,
    // The error is on the line above this one 
  });
  return undefined;
}
```
the error is:
```
Type '"player" | "team"' is not assignable to type 'Condition<"team"> | undefined'.
  Type '"player"' is not assignable to type 'Condition<"team"> | undefined'
```

These are the versions:
Mongoose v6.0.5
Typescript v4.4.3
Node v16.5.0
MongoDB v4.1.1

**Comment by IslandRhythms** [comment] 2021-09-13 14:57
```
import * as mongoose from 'mongoose';



export interface PlayerCooldown {
  id: string;
  for: "player";
  playerId: string;
}
export interface TeamCooldown {
  id: string;
  for: "team";
  teamId: string;
}
export type Cooldown = PlayerCooldown | TeamCooldown;

const testSchema = new mongoose.Schema<Cooldown>({id: String, for: String, playerId: String, teamId: String});

const CooldownModel = mongoose.model<Cooldown>('Test', testSchema);


async function test() {
    await mongoose.connect('mongodb://localhost:27017/');
    await mongoose.connection.dropDatabase();
    const entry = await CooldownModel.create({
        id: '123456789012',
        for: 'team'
    });
    await CooldownModel.create({
        id: '120987654321',
        for: 'player'
    });
    let forWho:  "team" = "team";
   await CooldownModel.findOne({for:forWho});
   await getCooldownFromId(forWho, entry.id);
}
async function test1() {
    let forWho: "player" = "player";
   await CooldownModel.findOne({for:forWho});
}

async function test2() {
    let forWho: "player" | "team" = "team";
    await CooldownModel.findOne({for:forWho});
}

async function getCooldownFromId(forWho: "team" | "player", cooldownId: string): Promise <undefined> {
    const res = await CooldownModel.findOne({
        id: cooldownId,
        for: forWho
    });
    return undefined;
}

test();
test1();
test2();
```

**Comment by vkarpov15** [comment] 2021-09-25 22:48
This is potentially a TypeScript bug, I opened an issue here: https://github.com/microsoft/TypeScript/issues/46059 . We can fix this in Mongoose, but only by removing the ability to query strings by `RegExp`. Here's a TypeScript playground issue that shows this issue independent of Mongoose: https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgBQBtMBPNAYQgkIBMIB3JOAbwCg5EaAuOAZxijIA5gG52cdNB4AiMMTJRpYjnNJoAktz4DhYgL6tQkWIhRosuOABVgmALaVqdRi3EIt-QUlHjJUGaj2SuKBdpo8nrqsBkbQ8DAkYHiOtAxMALwE8hRUqS4APta2DrnOSGKsCUlwAGIIhKhQAIoArmgkADxWAHxwmWwcANr4pnAA1sAkEOjWALoA-DxWw7NwhUgtdgBGaPoVmLwkSNgSLccwCBBMqPwAFACUrhxwhMDwfgDqABYQAcXSazgsmyij6QNCwWemHomAQ8CEbxSZRqUAgYRot0+PwANHAAOQ3GB4+76VisA5HE7oM7YC5XOAImBItIotGaTHQb6-cH-QHAtSKXHYUppcLaLxCe48fCouwIXh4DpnGjAdDIYA0XoDZ6veAAfSx3P5CgBhWkELBhuUOrecAAjjw6g00K12h1mYxev0JFI4AbOTjODxhU5RTQ4HprRwoG8WlAmMrVeqaKTKsA7iSgA

**Comment by hansemannn** [comment] 2022-10-19 14:02
The parent issue was closed as `Working as Intended`, could this be reopened? No blocker, just curious for a more streamlined Typescript experience in mongoose.

**Comment by vkarpov15** [comment] 2022-10-24 23:56
@hansemannn in that case, we'll have to close this issue. Realistically, this is a limitation in TypeScript, and there isn't really a way for Mongoose to work around this issue without dropping support for querying by regular expressions in TypeScript.

**Closed by vkarpov15** 2022-10-24 23:56 UTC
Labels: underlying library issue, typescript
