### ISSUE TITLE
serious: deleteOne({id:null}), deleteOne({mid:"628c6582f24dcd25814c4f0d") and deleteOne() deletes random entry

### ISSUE THREAD

**Issue by thiscantbeserious** [Automattic/mongoose#12714] opened 2022-11-22 14:38 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

16.17.0

### MongoDB server version

4.12.0

### Description

deleteOne with invalid parameters - be it an id that is accidently **null** or an misspelled id property leads to a query that actually will delete an entry instead of erroring out (the last?).

This can lead to deletion of entire production collections being wiped of the earth - I don't think thats anywhere near smart.

In case of memory leak, processing error, or anything else that wasn't catched - say for example params is an object that somebody or something changed.

### Steps to Reproduce

````        
let paramsFromExternalFunction = { renamedPropertyThatDoesntExist: false }
await LocationModel.deleteOne(paramsFromExternalFunction).exec(); //deletes randomly
await LocationModel.deleteOne({id:null}).exec(); //deletes randomly
await LocationModel.deleteOne().exec(); //arguable, also deletes randomly
````

### Expected Behavior

A destructive method should only execute on code that absolutely matches the conditions and parameters.

If there is a non-existing parameter - be it in the model or database it should simply do nothing and/or throw an Error.

That is by sane defaults - not having to enable non-discarding of parameters that doesn't exist.

**Comment by Uzlopak** [comment] 2022-11-22 15:50
Well. This is also affected by strictQuery filtering out invalid fields. So a virtual field like id will be potentially filtered out, resulting in a deleteOne({}) call,deleting a random document.

Anyway. I think this is something which is happening at runtime. In my opinion this has to be covered by unit tests of the implememtation.

If you have a technical solution to your issue, we can consider this to implement. Or you provide a PR with the solution.

But this is a normal behavior.

**Comment by sean-daley** [comment] 2022-11-22 19:08
If related to strictQuery (which seems likely), additional info on this can be found in https://github.com/Automattic/mongoose/issues/10747 and https://github.com/Automattic/mongoose/issues/12389

Those are the delete specific ones. There are other issues which go into more detail around find as well.

https://github.com/Automattic/mongoose/issues/11861 also goes over the plan to try and change this default for Mongoose 7.

**Comment by DeviantCTO** [comment] 2022-11-23 05:00
So far absolutely unprofessional. I have been trying to explain why my production database has been randomly disappearing. Good job devs. So now you are stating that when a random patient is updated with data from another patient then that is standard behavior? Or when removing data and deleteOne does not find anything which matches the query, "Well dont throw an error, just make 'em happy and delete something".  The proper behavior is if a key does not exist, do nothing, throw error.  If query finds nothing, then do nothing as no target was found.

If an _id is not found don't delete some random record. WTF? Now I have zero confidence in the integrity of my database and data because of Mongoose and am forced to remove it from the firm. But no worries, that is normal behavior too.

Unit tests are not the answer as they will never fail. Or even better, now we must wrap every Mongoose method in a check for "do these params exist and is my dynamic variable populated" before we execute the method.

The question for all Chief Technology Officers, Techleads and Architects now is "Why do we need /use Mongoose?"

**Comment by vipul-sharma-deshaw** [comment] 2022-11-23 05:21
Hi @thiscantbeserious, I suppose you can globally disable this behavior by setting `mongoose.set('strictQuery', false);` as documented [here](https://mongoosejs.com/docs/guide.html#strictQuery). However, I too find [this](https://mongoosejs.com/docs/migrating_to_6.html#strictquery-is-removed-and-replaced-by-strict) werid and ideally instead of having to globally unset this, it should be like https://github.com/Automattic/mongoose/issues/11861. Not sure why Mongoose did [this](https://mongoosejs.com/docs/migrating_to_6.html#strictquery-is-removed-and-replaced-by-strict).

**Comment by Uzlopak** [comment] 2022-11-23 08:57
@DeviantCTO 

Kind of hash to claim that it I gave an unprofessional answer. I did not even blame the OP and gave just a short technical analysis and opinion of the behaviour. I assume that @thiscantbeserious works for you, and you are not satisfied with the first reaction. 

strictQuery was introduced with mongoose v6 to ensure that the mongoose Schema gets strictly respected and avoiding storing data in fields, which are not specified in the Schema.

But anyhow you have been given a "proper" answer by @sean-daley, who wrote that you can disable strictQuery. Even @vipul-sharma-deshaw  gave you the corresponding codeline to disable strictQuery. Also you have been informed, that we will set strictQuery to false in mongoose v7 as it would be backwards breaking. 

So no need to wrap it in a function to check for fields. Just do `mongoose.set('strictQuery', false);`

I hope CTOs, Techleads and Architects all over the world can now sleep again calm. ;)

I sent a networking request on linkedin, if you want to talk.

**Comment by DeviantCTO** [comment] 2022-11-23 10:41
The answer itself was not unprofessional . The development and responsibility of the dev team is unprofessional.

I found a "typo" in our code  where 

   `try{ Model.deleteOne( {id: blaId} ) }catch(err){ throw new Error(err) } `

resulted in the query deleting our entire database over time as it never triggered the catch or throw any error.  That is unacceptable. What you should have done is trigger an error and stop the query with a statement that the key does not exist not go delete a random  target. It was obviously the intent of the developer to delete a specific target and you rewrote the query. This likely also applies to

 `try{ Model.updateOne( { id: blaId }, { key:value } ) }catch(err){ throw new Error(err) } `

So your excuse is that I can set strict mode so that I can "beg" your library to throw an error. Really? That should not even exist. On top of that, your non-shalant attitude about the responsibility you chose to accept with data handling is poor. 

Fact is that now because of your library you have rendered the integrity of the data untrustworthy. This costs a huge amount of money in full data reviews, code reviewing and refactoring, unit test refactoring and even inspections on unit tests quality which are expanded because of this illogical thought matrix. So essentially you have cost my organization a phenomenal amount of time and money. So the best answer to return confidence to our customers and the quality of our data is to eject Mongoose from the organization and warn all other.

Industrial customers whom pay 10s of millions for data services can deal with setbacks like this, depending on the swift and overwhelming response and correction which follows to prevent it from happening again. If you are going to accept the responsibility for the quality and handling of data for your users, DO BETTER.

**Comment by Uzlopak** [comment] 2022-11-23 13:33
Duplicate of #11861

**Closed by Uzlopak** 2022-11-23 13:33 UTC

**Comment by sean-daley** [comment] 2022-11-23 15:44
So while mongoose definitely has issues around the whole strictQuery thing, I think mongo itself will delete a random entry when passed in `{id: null}` or `empty`. The fact that `deleteOne({mid:"xxxx"})` converts to `deleteOne({})` if mid is not a valid field is a mongoose issue related to the `strictQuery` setting. But, at the very least, using the mongo shell, deleteOne has the following behavior:

```
> db.books.count()
2
> db.books.deleteOne({ unknownField: 'some_value' })
{ "acknowledged" : true, "deletedCount" : 0 }
> db.books.deleteOne({ unknownField: null })
{ "acknowledged" : true, "deletedCount" : 1 }
> db.books.deleteOne({})
{ "acknowledged" : true, "deletedCount" : 1 }
```

So, in the above, I have a collection with 2 records in it.
1. I do `deleteOne({ unknownField: 'some_value' })` and nothing gets deleted ... seems fine
2. I do `deleteOne({ unknownField: null })` and a "random" item gets deleted ... seems weird probably?
3. I do `deleteOne({})` and a "random" item gets deleted ... may seem weird but it's documented behavior by MongoDB that an empty filter will delete the first document returned in the collection

I can only assume that either 2 is a bug in mongo or it's some expected behavior somehow. You'd have to ask those folks. Nothing pops out immediately in the docs on it.

I just wanted to write this as I don't think any `strictQuery` setting in mongoose will help all of the issues discussed here as even mongo will delete the first item in the collection when passed `{}` or `{id: null}`. I didn't do extensive testing here though so i may be missing something but I noticed that `{id: null}` would delete an item even when using mongoose 5 which should have the old strictQuery behavior I think. That got me looking at what the Mongo shell does on a deleteOne as well.

**Comment by vkarpov15** [comment] 2022-11-23 16:27
We're very sorry for any trouble this behavior change caused. We're switching this behavior back in Mongoose 7 with #11861

**Comment by thiscantbeserious** [comment] 2022-11-24 08:57
@vkarpov15 thanks for the response, hopefully version 7.0.0 will happen soon ... one question: aren't important bugfixes merged down to older version or is the versioning schema of mongoose not structured like that (simply don't know it)?

@sean-daley

Doing a `deleteOne({_id:null})`  **with the underlying mongodb-driver directly does not exhibit that behaviour** (with the listed mongodb version above).  However you are right in that there are circumstances where not throwing an error might be feasible, or even contraproductive.

@Uzlopak 

It is also not possible to catch that behaviour by unit-tests as deleteOne only responds with the number of deleted entries - 

**0/1**.  So you deleted _something_ or not. 

Specifically saying - **where is the unit-test within mongoose for that implementation change that catched this?** (trick question)

**Unit-Tests are written for the implementation they are targeting** - so that goes with the changes that strictQuery/strict introduced.

They do not have access to the database, or just a mocked version of it. They are targed at catching implementation faults not related to the frameworks/libraries you're using but to make sure the results of your business implementation are somewhat sane.

They are not the answer to everything.

From how I'm seeing it this is the state since over 1 year now (if I look at the cross-mentioned issues above).

I don't have the time or desire to proof it because its no use to anyone, so I'm just leaving this as a side-note.

This is certainly not "normal behaviour" ... that's also why I took the time to report this here to begin with.

**Comment by Uzlopak** [comment] 2022-11-24 11:53
@thiscantbeserious 

Replace "normal behaviour" with "expected behaviour". Also you got the answer, that strictQuery will be set to false by default on mongoose 7. It is not a bug per se, if it is expected behaviour.

I quite dont catch your remarks. When I develop for a mongo database, I actually spawn a mongodb-memory-server and test against a real mongodb. This is also what we do with mongoose. We spawn a mongo server and check against a real database. For local development you can do a "npm run mongo" and spawn locally a mongo server. Then run the tests against it. So we actively avoid mocking in our unit tests. We can even specify a version of mongodb by doing e.g. "npm run mongo -- 5.0.0".

And this is also what we did at my former employer. We spawned mongo databases, run the unit tests against them and actually checked if the changes are really done on the database and we ensured we did not made faulty queries, like what happened in your case.

**Comment by thiscantbeserious** [comment] 2022-11-24 12:25
@Uzlopak you can't really tell me that .deleteOne({id:null}) as to where null is considered expected === sane behaviour that it deletes a random/last entry. 

The MongoDB-Driver itself also doesn't do that.

It litterally goes AGAINST what the very word **_STRICT_** defines in any textbook.

_(STRICT = as in doesn't match the desired input parameters -> discard, do nothing or throw an error, don't allow it)_

You are litterally the only one trying to argue that it's sane - as in expected - to do that. 

So now by the very next change in 7.0.0 its set to "false" as default to get back the old behaviour.

So we're saying strictQuery === false is the new default but that is still not actually correct for this case alone.

Why are you trying so hard to argue around the problem itself? 

And: Did you actually fire up your editor and tested the respective code-parts yourself or are you trusting your "tests"?

Because that's my experience lately with people not matter how big projects are: They just throw away the responsibilities and defend with word or experiences that don't match the very simple case given.

We can agree, to not aggree on the responsibility part as well how sanity looks like. 

For me thats more or less a thing of personal attitude.

I wish you the very best and that you never get anything like that to happen to you or your business/customers.

Over and out.

**Comment by Uzlopak** [comment] 2022-11-24 15:02
![image](https://user-images.githubusercontent.com/5059100/203814899-75c344a8-b314-4998-9e56-6bc76780d298.png)

**Comment by sean-daley** [comment] 2022-11-24 15:08
> The MongoDB-Driver itself also doesn't do that.

As I showed earlier, the mongo shell DOES do that. If you do `db.deleteOne({id: null})` it will delete a "random" item in your collection. The javascript driver does the same:
```
const mongodb = require('mongodb')
// Replace the uri string with your MongoDB deployment's connection string.
const uri = "mongodb://127.0.0.1:27017";
const client = new mongodb.MongoClient(uri);
const run = async () => {
  try {
    const database = client.db("sample_mflix");
    const haiku = database.collection("haiku");
    // create a document to insert
    const doc = {
      title: "Record of a Shriveled Datum",
      content: "No bytes, no problem. Just insert a document, in MongoDB",
    }
    const result = await haiku.insertOne(doc);
    console.log(`Record count = ${await haiku.count()}`)
    await haiku.deleteOne({ id: null });
    console.log(`Record count = ${await haiku.count()}`)

  } finally {
    await client.close();
  }
}
run().catch(console.dir);
```

If you run that (at least against 4.4) you will get:
```
Record count = 1
Record count = 0
```

And there is nothing mongoose related in that program. It purely uses the mongodb driver.
