### ISSUE TITLE
Schema toObject default "depopulate" option is not applied

### ISSUE THREAD

**Issue by mserege** [Automattic/mongoose#6313] opened 2018-04-04 14:08 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Schema toObject default "depopulate" option is not applied when called on a document.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require('mongoose');

const { Schema } = mongoose;

const personSchema = Schema({
  name: String,
  car: {
    type: Schema.Types.ObjectId,
    ref: 'Car',
  },
});

personSchema.set('toObject', {
  depopulate: true,
});

const carSchema = Schema({
  name: String,
});

const Car = mongoose.model('Car', carSchema);
const Person = mongoose.model('Person', personSchema);

const car = new Car({
  name: 'Ford',
});

const person = new Person({
  name: 'John',
  car,
});

// Test
console.log(person.toObject().car); // Expected id
console.log(person.toObject({ depopulate: true }).car); // Expected id
```

**What is the expected behavior?**
Expected output of console logs is:
```
5ac4db7ddcb2084498b99c2e
5ac4db7ddcb2084498b99c2e
```
Actual output however is:
```
{ _id: 5ac4db7ddcb2084498b99c2e, name: 'Ford' }
5ac4db7ddcb2084498b99c2e
```
Objects should have depopulated car property in both cases because "depopulate" was set in default toObjctions options.

**Please mention your node.js, mongoose and MongoDB version.**
Nodes.js : 8.11.0
Mongoose : 5.0.12
MongoDB : 3.6.0

**Comment by lineus** [comment] 2018-04-06 14:31
@mserege You're right, `toObject.depopulate` doesn't work when set at the schema level. 

I modified your example slightly 
### 6313.js
```js
#!/usr/bin/env node
'use strict'

const mongoose = require('mongoose')
const { Schema } = mongoose
mongoose.connect('mongodb://localhost/test')

const carSchema = Schema({
  name: String
})

const personSchema = Schema({
  name: String,
  car: {
    type: Schema.Types.ObjectId,
    ref: 'Car'
  }
})

personSchema.set('toObject', { depopulate: true })

const Car = mongoose.model('Car', carSchema)
const Person = mongoose.model('Person', personSchema)

const car = new Car({
  name: 'Ford'
})

const person = new Person({
  name: 'John',
  car: car._id
})

async function run () {
  await Car.remove({})
  await Person.remove({})
  await car.save()
  await person.save()
  let doc = await Person.findOne({}).populate('car', 'name').exec()
  let popDoc = doc.toObject()
  console.log(`depopulated at schema level:`)
  console.log(popDoc)
  let dePopDoc = doc.toObject({ depopulate: true })
  console.log('depopulated at doc level:')
  console.log(dePopDoc)
  return mongoose.connection.close()
}

run()

```
### output:
```
issues: ./6313.js
depopulated at schema level:
{ _id: 5ac77d92ccf2fc3f259509ae,
  name: 'John',
  car: { _id: 5ac77d92ccf2fc3f259509ad, name: 'Ford' },
  __v: 0 }
depopulated at doc level:
{ _id: 5ac77d92ccf2fc3f259509ae,
  name: 'John',
  car: 5ac77d92ccf2fc3f259509ad,
  __v: 0 }
issues:
```

@vkarpov15 $toObject is explicitly only looking at the passed in options object for depopulation. Should this be a documentation change excluding schema level depopulation in toObject?

```js
  if (options.depopulate && options._isNested && this.$__.wasPopulated) {
    // populated paths that we set to a document
    return clone(this._id, cloneOptions);
  }
```
Or should I keep trying to find a fix? Various ideas I've had so far for allowing schema level depopulation have broken other tests, but I'm not going to give up yet :)

**Comment by varunjayaraman** [comment] 2018-04-09 19:34
i get the same results @lineus, i'll mark this as a confirmed bug for now.

**Comment by vkarpov15** [comment] 2018-04-12 17:50
Thanks for reporting, fix is in master and will be deployed with 5.0.15 :+1:

**Closed** 2018-04-12 17:50 UTC
Labels: confirmed-bug

**Comment by surajpra** [comment] 2020-08-28 06:20
is anyone fixed this issue because iam still getting same response with mongoose 5.10.1.

**Comment by vkarpov15** [comment] 2020-08-31 19:04
@surajpra please open a new issue and follow the issue template.
