### ISSUE TITLE
Method name cannot match field name

### ISSUE THREAD

**Issue by steebchen** [Automattic/mongoose#4791] opened 2016-12-09 19:24 UTC
When setting a method which has the same name as a normal schema field, an error gets thrown. Regardless of whether this is expected behavior or a bug, it should at least show an error message like "Cannot use a method with the same name as a schema field".

```js
const schema = new mongoose.Schema({
  name: 'hi'
})

schema.methods.name = function () {}
```

Error:

```
node_modules/mongoose/lib/document.js:1712
        return this.set.call(this.$__.scope || this, path, v);
                                     ^
TypeError: Cannot read property 'scope' of undefined
    at model.set [as name] (node_modules/mongoose/lib/document.js:1712:38)
    at applyMethods (node_modules/mongoose/lib/model.js:3255:31)
    at Function.compile (node_modules/mongoose/lib/model.js:3200:3)
    at Mongoose.model (node_modules/mongoose/lib/index.js:392:17)
    at Object.<anonymous> (models/User.js:41:34)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.extensions..js (node_modules/espower-loader/index.js:48:13)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
```

mongoose@4.6.0

**Comment by vkarpov15** [comment] 2016-12-16 02:17
Upgrade to 4.6.1, this is a duplicate of #4475

**Closed by vkarpov15** 2016-12-16 02:17 UTC
