### ISSUE TITLE
#5434 regression in 5.0.6

### ISSUE THREAD

**Issue by bazineta** [Automattic/mongoose#6157] opened 2018-02-21 05:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
As in #5434, setters are being run twice during findOne().

**If the current behavior is a bug, please provide the steps to reproduce.**

See the repro in #5434; the same trace on the setter function demonstrates the issue; i.e., the setter function is called twice, once with the original input, and then again with the result of the first transformation.

**What is the expected behavior?**
Setter function should only be called once during findOne().

**Please mention your node.js, mongoose and MongoDB version.**
node 8.9.4
mongoose 5.0.6
MongoDB 3.2.11

**Comment by bazineta** [comment] 2018-02-21 06:03
I should add that in my test case differs slightly from the script in #5434 in that it does a find().exec(), while mine does a find().populate().exec().

**Comment by bazineta** [comment] 2018-02-21 06:26
A further note that the presence or absence of populate() does not change the repro. The 'set' function is always called twice, and a mongoose debug trace does indeed show the result of the setter being called recursively as the parameter to the query.

**Comment by vkarpov15** [comment] 2018-02-21 22:20
Thanks for reporting, will investigate ASAP

**Comment by vkarpov15** [comment] 2018-02-22 01:14
Can't reproduce, the repro script from #5434 gives me the expected output in 5.0.6:

```
$ npm install mongoose@5.0.6

+ mongoose@5.0.6
added 4 packages in 7.048s
$ node gh-5434.js 
Running query...
===>>> Setter called with type: string, value: 123
Returning: 123
Got result: []
^C
$ 
```

Script is below

```javascript
var mongoose = require('mongoose');

mongoose.Promise = Promise;

var UserSchema = new mongoose.Schema({
        name: String,
        foo: {
                type: Number,
                get: function(val) {
                        return val.toString();
                },
                set: function(val) {
                        console.log('===>>> Setter called with type: %s, value: %s', typeof val, val);
                        if (typeof val !== 'string') {
                                throw new Error('Must be called with string');
                        }

                        var res = parseFloat(val);
                        console.log('Returning:', res);
                        return res;
                }
        }
}, {collection: 'users', runSettersOnQuery: true});

var UserModel = mongoose.model('User', UserSchema);

var connStr = 'mongodb://127.0.0.1/test';
mongoose.connect(connStr);

console.log('Running query...');
UserModel.find({foo: '123'}).exec().then(res => {
        console.log('Got result:', res);
}).catch(err => {
        console.error('ERROR:', err)
});
```

Also, I checked and confirmed that the test case for #5434 is working correctly. Can you please provide a script that reproduces your issue?

**Comment by bazineta** [comment] 2018-02-22 05:48
Test case result:
```
npm install mongoose@5.0.6
+ mongoose@5.0.6
added 20 packages in 3.482s
node 5434.js
Running query...
===>> Setter called, value 123
===>> Setter called, value 123123
Got result: null
^C
```
Test case:
```javascript
var mongoose = require('mongoose');

var UserSchema = new mongoose.Schema({
        name: String,
        foo: {
                type: String,
                set: function(val) {
                        console.log('===>> Setter called, value', val);
                        return val + val;
                }
        }
}, {collection: 'users'});

var UserModel = mongoose.model('User', UserSchema);

mongoose.connect('mongodb://127.0.0.1/test');

console.log('Running query...');
UserModel.findOne({foo: '123'}).exec().then(res => {
        console.log('Got result:', res);
}).catch(err => {
        console.error('ERROR:', err)
});
```
Note that if the findOne() is changed to find(), then the results are instead:
```
node 5434.js
Running query...
===>> Setter called, value 123
Got result: []
^C
```

**Comment by bazineta** [comment] 2018-02-22 22:25
So, to net this out (apologies for not making this as simple as possible to begin with):

`find()` does **not** exhibit the issue; setters are called *once* on query.
`findOne()` does exhibit the issue; setters are called *twice* on query.

**Comment by vkarpov15** [comment] 2018-02-24 17:34
Fixed in master, thanks for helping us find this issue :+1:

**Closed by vkarpov15** 2018-02-24 17:34 UTC
Labels: confirmed-bug
