### ISSUE TITLE
Collation with numericOrdering: true and alternate: "shifted" not working

### ISSUE THREAD

**Issue by FilipaBarroso** [Automattic/mongoose#8526] opened 2020-01-20 18:50 UTC
When sorting my collection by prices, a field that contains both numbers and strings, I would like to able to sort it such that "950 000" > "970". I expected that setting numericOrdering to true and alternate to "shifted" should do it but it isn't the case.

My code: 
```javascript
const page = parseInt(req.query.page);
const size = parseInt(req.query.rowsPerPage);
const queryOptions = {
  skip: size * page,
  limit: size,
  sort: { [req.query.sortBy]: req.query.order }
};

// numericOrdering -> "10" > "2"
// alternate and maxVariable-> ignore spaces
if (req.query.sortBy === "usefulArea" || req.query.sortBy === "price")
  queryOptions.collation = {
    locale: "pt",
    numericOrdering: true,
    alternate: "shifted",
    maxVariable: "space"
  };

let query = {};
if (req.query.purpose) query["purpose"] = req.query.purpose;
if (req.query.type) query["type"] = req.query.type;
if (req.query.typology) query["typology"] = req.query.typology;
if (req.query.district) query["address.Distrito"] = req.query.district;

const advertisements = await AdvertisementModel.find(
  query,
  {},
  queryOptions
).exec();
```

**Comment by vkarpov15** [comment] 2020-01-25 01:50
I'm able to repro this with the below script, but I haven't been able to figure out how to get the collation options to sort so that '970' comes before '950 000'.

```javascript
'use strict';

const mongoose = require('mongoose');
const { Schema } = mongoose;

run().catch(err => console.log(err));

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test', {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });

  await mongoose.connection.dropDatabase();
  
  const AdvertisementModel = mongoose.model('Test', mongoose.Schema({
    price: {
      type: String
    }
  }));

  const queryOptions = { sort: { price: 1 } };
  
    queryOptions.collation = {
      locale: "pt",
      numericOrdering: true,
      alternate: "shifted",
      maxVariable: "space"
    };

  await AdvertisementModel.create([
    { price: '950 000' },
    { price: '970' } 
  ]);

  let query = { };

  const advertisements = await AdvertisementModel.find(
    query,
    {},
    queryOptions
  ).exec();

  console.log(require('util').inspect(advertisements, { depth: 100 }));
}
```

Can you please clarify your version of MongoDB and Mongoose?

**Comment by FilipaBarroso** [comment] 2020-01-27 11:56
My versions are 6.13.6 for Mongoose and 4.2.0 for MongoDB

**Comment by vkarpov15** [comment] 2020-01-28 22:53
I haven't been able to figure out how to work around this, this behavior looks like it is part of the MongoDB server. I opened up an issue on their jira board here: https://jira.mongodb.org/browse/SERVER-45833 . We'll see what they say.

**Comment by vkarpov15** [comment] 2020-02-07 20:09
MongoDB closed this as "works as designed" unfortunately: https://jira.mongodb.org/browse/SERVER-45833 . I wish I had better news but there isn't Mongoose can do here, collations all live on the MongoDB server. Your best bet would be to migrate your data to standardize number formatting, and use [custom setters](https://mongoosejs.com/docs/tutorials/getters-setters.html) to ensure numeric strings have a more consistent format.

**Closed by vkarpov15** 2020-02-07 20:09 UTC
Labels: help, underlying library issue
