### ISSUE TITLE
When populate documents with clone: true, i got TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by supermay** [Automattic/mongoose#8807] opened 2020-04-17 10:27 UTC
I'm using mongoose 5.9.9, use `clone` option with `lean`
*bug*
When populate documents with clone: true, i got TypeError: Invalid value used as weak map key
**If the current behavior is a bug, please provide the steps to reproduce.**

For example, I have product model and image model. 
product has primary image, and images array, which are all references to the image model.
When I try to get product with primary image and images array populated, 

**Without the options {clone: true},**
It doesn't matter if my primary image exists or not, or if the primary image id actually really refers to any documents in the image collection, because mongoose just gives me null when it cannot be populated. 
This is similar to images array, mongoose automatically removes the ones cannot be populated from the array. 

**With the options {clone: true},**
When documents cannot be populated, I got the error: 
TypeError: Invalid value used as weak map key

**This is the part in the code:**
It's from assignRawDocsToIdStructure
      if (options.lean) {
        const _model = leanPopulateMap.get(doc);
        doc = utils.clone(doc);
        leanPopulateMap.set(doc, _model);

Thanks for your effort to make this clone true option, and please let me know if the issue is unclear.

**Comment by vkarpov15** [comment] 2020-04-26 16:13
Thanks for the bug report, the issue is fixed and will be released with v5.9.11

**Closed** 2020-04-26 16:12 UTC
Labels: needs repro script
