### ISSUE TITLE
Node 0.10 style steam support?

### ISSUE THREAD

**Issue by jwerre** [Automattic/mongoose#2150] opened 2014-06-18 18:09 UTC
Do you have plans to implement Node 0.10 style steam and if so, ETA?

**Comment by vkarpov15** [comment] 2016-06-01 22:42
Duplicate of #1907, will be fixed in 4.5.0, see http://thecodebarbarian.com/cursors-in-mongoose-45.html

**Closed by vkarpov15** 2016-06-01 22:42 UTC
Labels: enhancement
