### ISSUE TITLE
Virtual population with setter

### ISSUE THREAD

**Issue by br0p0p** [Automattic/mongoose#5749] opened 2017-10-25 19:57 UTC
Node: 8.1.2
Mongoose: 4.12.4
MongoDB: 3.4.5

I've got Parent and Child models defined like so:
```js
const ParentSchema = new Schema({
     name: String
});

// Should populate a virtual "children" field with array of "Child" documents
ParentSchema
    .virtual('children', {
         ref: 'Child',
         localField: '_id',
         foreignField: 'parent'
    })
    .set(function(children) {
        Child.updateMany({ _id: { $in: children }}, { parent: this._id }, (err, res) => {
            console.log(err, res);
        });
    });

const ChildSchema = new Schema({
     name: String,
     parent: { type: Schema.Types.ObjectId, ref: 'Parent' }
});

const ParentModel = mongoose.model('Parent', ParentSchema);
const ChildModel = mongoose.model('Child', ChildSchema);
```

I'm able to set the "children" field like this using `Model.create`:
```js
// WORKS
new Parent({ name: 'test', children: ['id1', 'id2'] }).save();
```

but when I try to use `Model.findOneAndUpdate` the "children" setter does not run, even if I set `runSettersOnQuery: true`:
```js
// DOES NOT WORK
Parent.findByIdAndUpdate(_id, { children: ['id3', 'id4'] }, { new: true });
```

What am I doing wrong here?

**Comment by br0p0p** [comment] 2017-10-25 22:29
See #5643.

**Comment by br0p0p** [comment] 2017-10-25 22:35
Related: #5643

**Comment by varunjayaraman** [comment] 2017-10-29 21:37
yeah i'll label this a feature request since its the same thing as #5643, not sure when on the timeline we plan on implementing this. thoughts @vkarpov15 ?

**Comment by vkarpov15** [comment] 2017-10-30 19:07
Yeah this is a duplicate of #5643 with a little of #5763. We currently don't have a timeline for when we're going to implement that, but currently `runSettersOnQuery` only works for getters/setters, **not** virtuals. Please follow #5763 for updates on that. We also do not support setters for populate virtuals, see #5643.

**Closed by vkarpov15** 2017-10-30 19:07 UTC
Labels: new feature

**Comment by br0p0p** [comment] 2017-10-30 19:25
Cool – thanks for your response.
