### ISSUE TITLE
Mongoose Hooks don't work on my macOS Sierra machine

### ISSUE THREAD

**Issue by IonicaBizau** [Automattic/mongoose#4952] opened 2017-02-03 07:59 UTC
**Do you want to request a *feature* or report a *bug*?**

I guess it's a bug.

**What is the current behavior?**

The Mongoose hooks are not triggered on macOS.

**If the current behavior is a bug, please provide the steps to reproduce.**
See this question: http://stackoverflow.com/q/42019171/1420197

```js
const Mongoose = require("mongoose");
Mongoose.connect("mongodb://localhost/test", (err, db) => {

    console.log(err);
    // => undefined
    //    (success)

    // Create the model
    const t = Mongoose.model("t", {
        s: "string"
    });

    // Do something pre save
    t.schema.pre('save', function(next) {
        // This is not triggered
        console.log(">>>>>>>>>>>>>");
        console.log(this);
        next();
    });

    // Insert a new object
    new t({ s: "foo" }).save((err, data) => {
        console.log(err, data);
    });
});
```

**What is the expected behavior?**
The hooks should be triggered, as documented.

**Please mention your node.js, mongoose and MongoDB version.**

```sh
$ node --version
v7.0.0
$ mongo --version
MongoDB shell version: 3.2.6
$ vim package.json 
$ npm list | grep mongoose
├─ mongoose@4.8.1
$ npm view mongoose version
npm http request GET https://registry.npmjs.org/mongoose
npm http 304 https://registry.npmjs.org/mongoose
4.8.1
```

**Comment by varunjayaraman** [comment] 2017-02-03 15:01
This is a duplicate of https://github.com/Automattic/mongoose/issues/4946:

Basically, you're creating your hook incorrectly. You have to set the hook before calling `mongoose.model()`

**Closed** 2017-02-03 15:01 UTC

**Comment by IonicaBizau** [comment] 2017-02-05 06:49
Thanks!

@varunjayaraman I quickly took a look at that discussion. Actually, does that mean we cannot append new hooks after we create the model? What's the reason for that?

I don't really like this idea, tho...

**Comment by IonicaBizau** [comment] 2017-02-05 06:52
The strange thing is that my method does work just for one model. I have no idea why.
