### ISSUE TITLE
Typescript: Group interface for type PipelineStage has conflicting index signatures

### ISSUE THREAD

**Issue by meteohr** [Automattic/mongoose#11059] opened 2021-12-08 08:49 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If you provide a "group" stage with the mandatory `_id` property in your aggregration pipeline, typescript will throw an error:
```
TS2322: Type '{ _id: string; imageResource: { $first: string; }; }'
is not assignable to type
'{ [key: string]: { $count?: any; $accumulator?: any; $addToSet?: any; $avg?: any; $first?: any; $last?: any; $max?: any; $mergeObjects?: any; $min?: any; $push?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }; _id: any; }'.
Property '_id' is incompatible with index signature.
Type 'string' has no properties in common with type '{ $count?: any; $accumulator?: any; $addToSet?: any; $avg?: any; $first?: any; $last?: any; $max?: any; $mergeObjects?: any; $min?: any; $push?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
 const aggregateSomething: PipelineStage = {
        $group: {
            _id: 'name',
            imageResource: { $first: 'something' },
        }
    }
```

tsconfig:
```
{
    "compilerOptions": {
        "target": "es2017",
        "module": "commonjs",
        "moduleResolution": "node",
        "outDir": "./dist",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "sourceMap": true,
        "pretty": true,
        "allowJs": false,
        "strict": true,
        "esModuleInterop": true,
        "isolatedModules": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noUncheckedIndexedAccess": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "types": ["jest"],
        "lib": ["esnext"],
        "importHelpers": true,
        "resolveJsonModule": true
    },
    "include": ["src/**/*", "tests/**/*"],
    "exclude": ["node_modules"]
}
```
**What is the expected behavior?**
Property `_id` accepts `any`, instead of only accepting the object with `AccumulatorOperator` as type. 

Typescript suggests to use a union of all property types, see: https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures

This is most probably connected to #10971

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
node version: 14
mongoose version: 6.1.0
mongo version: 4.2.12
typescript version: 4.5.2

**Comment by rongem** [comment] 2021-12-09 05:50
I get the same problem with node version 16. Sticking to 6.0.14 for the moment as workaround.

**Comment by ahmedelshenawy25** [comment] 2021-12-10 00:54
```ts
import mongoose, { Types } from 'mongoose';
const { Schema } = mongoose;

run().catch(console.error);
async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');

  interface IUser {
    _id: Types.ObjectId | string;
    name?: string;
  }

  const userSchema = new Schema<IUser>({ name: String });
  const User = mongoose.model<IUser>('User', userSchema);

  await User.aggregate([
    {
      $group: { _id: '$_id' }
    }
  ])
}
```

**Comment by XopoIII** [comment] 2021-12-10 06:51
@ahmedelshenawy25 did not help

**Comment by rongem** [comment] 2021-12-10 06:59
If you want to reproduce, please try out my project at
https://github.com/rongem/cmdb/tree/master/njs-backend
If you run tsc, it works. If you update to mongoose 6.1.0 and run tsc, it fails to compile with above error.

**Comment by orgads** [comment] 2021-12-10 07:02
I worked around it by casting the pipeline to `any`.

**Comment by rongem** [comment] 2021-12-10 07:07
Casting to any did not work for me.
Just tested 6.1.1, problem persists.

**Comment by meteohr** [comment] 2021-12-10 08:39
@XopoIII I thin @ahmedelshenawy25 just wanted to provide a reproduction script. This is just a minimalistic setup for getting the error.
You can work around that error by doing `$group: { _id: '$name' as any }` in @ahmedelshenawy25 s example.

**Comment by ahmedelshenawy25** [comment] 2021-12-10 12:20
@XopoIII ye as @meteohr that's minimal reproduction script

**Comment by XopoIII** [comment] 2021-12-12 23:29
@ahmedelshenawy25 @meteohr thx!

**Comment by DavideViolante** [comment] 2021-12-13 10:45
Upgrading from 6.0.14 to 6.1.1, all those TS errors appeared in **aggregate pipelines**:

### 1
```
{ $group: { _id: { $month: '$date' }, count: { $sum: 1 } } },
```

```
Type '{ _id: { $month: string; }; count: { $sum: number; }; }' is not assignable to type '{ [key: string]: { $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }; _id: any; }'.
  Property '_id' is incompatible with index signature.
    Type '{ $month: string; }' is not assignable to type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.
      Object literal may only specify known properties, and '$month' does not exist in type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.ts(2322)
```
### 2
```
{ $group: { _id: '$activity', count: { $sum: 1 } } },
```

```
Type '{ _id: string; count: { $sum: number; }; }' is not assignable to type '{ [key: string]: { $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }; _id: any; }'.
  Property '_id' is incompatible with index signature.
    Type 'string' has no properties in common with type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.ts(2322)
```

### 3
```
{ $project: { _id: 1, name: 1, count: 1 } },
```

```
(property) _id?: false | 0
Type '1' is not assignable to type 'false | 0'.ts(2322)
index.d.ts(3106, 19): The expected type comes from property '_id' which is declared here on type '{ [field: string]: any; _id?: false | 0; }'
```
### 4
```
{ $group: { _id: { $ifNull: [ '$name', 'ND' ] }, count: { $sum: 1 } } },
```

```
Type '{ _id: { $ifNull: string[]; }; count: { $sum: number; }; }' is not assignable to type '{ [key: string]: { $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }; _id: any; }'.
  Property '_id' is incompatible with index signature.
    Type '{ $ifNull: string[]; }' is not assignable to type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.
      Object literal may only specify known properties, and '$ifNull' does not exist in type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.ts(2322)
```
### 5
```
{ $group: { _id: { $isoWeek: '$date' }, count: { $sum: 1 } } },
```

```
Type '{ _id: { $isoWeek: string; }; count: { $sum: number; }; }' is not assignable to type '{ [key: string]: { $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }; _id: any; }'.
  Property '_id' is incompatible with index signature.
    Type '{ $isoWeek: string; }' is not assignable to type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.
      Object literal may only specify known properties, and '$isoWeek' does not exist in type '{ $min?: any; $max?: any; $addToSet?: any; $push?: any; $count?: any; $accumulator?: any; $avg?: any; $first?: any; $last?: any; $mergeObjects?: any; $stdDevPop?: any; $stdDevSamp?: any; $sum?: any; }'.ts(2322)
```

**Comment by meteohr** [comment] 2021-12-13 11:01
@DavideViolante I would say cases 1, 2, 4 and 5 are coming from the reported issue with the Group interface. About number 3 I'm not sure, maybe open another ticket if you are sure, that this is a real bug.

**Comment by rpenido** [comment] 2021-12-15 01:52
@DavideViolante In Case 3, you can ajust you code. `_id` will always shows on projection. you only use `{_id: 0}` to remove it

You can use de code bellow with the same effect:
```
{ $project: { name: 1, count: 1 } },
```

**Comment by SergioSuarezDev** [comment] 2021-12-15 16:02
I have the same errors 1, 2 and 4

**Comment by DavideViolante** [comment] 2021-12-16 13:18
I think this PR https://github.com/Automattic/mongoose/pull/10971 caused these TS errors. Maybe @jeremyben can help to fix it.

**Comment by jeremyben** [comment] 2021-12-16 18:55
@DavideViolante Thanks for the heads up.
I tried to solve this problem, and this is what I came up with:

First this is the `Group` stage signature right now, following the [mongodb documentation itself](https://docs.mongodb.com/manual/reference/operator/aggregation/group/):

```ts
interface Group {
	$group: { 
		_id: any; 
		[key: string]: { [op in AccumulatorOperator]?: any }
	}
}
```
It seems, based on errors, that the compiler is unable to pin down the `_id` key to `any` and instead uses the index signature for it.

So we unfortunately have to lose the narrowing of operators when `_id` is defined, and this is the fallback I came up with while tinkering: 

```ts
interface Group {
	$group: { _id: any; [key: string]: any } | { [key: string]: { [op in AccumulatorOperator]?: any } }
}
```

Or more radically we just go back to a mere index signature with `any` for everything: 

```ts
interface Group {
	$group: { [key: string]: any }
}
```

**Comment by rpenido** [comment] 2021-12-16 22:25
Hi @jeremyben !

> ```ts
> interface Group {
> 	$group: { _id: any; [key: string]: any } | { [key: string]: { [op in AccumulatorOperator]?: any } }
> }
> ```

This will allow ommit the `_id`, like in `$group: { someField: {$sum: 1}}`, and will generate an error on runtime.

It's a trick problem.

There is a discusion here #11104 

For some reason (that I don't understand) this works (and the compiler reconizes the operator):
```ts
interface Group {
  $group: { _id: any} | {_id: any, [key: string]: { [op in AccumulatorOperator]?: any } }
}
```

**Comment by jeremyben** [comment] 2021-12-17 09:49
@rpenido Bravo, this is the one signature.
I forgot the mandatory _id while trying to find the solution no matter what.

But this is it indeed !
```ts
interface Group {
  $group: { _id: any } | {_id: any, [key: string]: { [op in AccumulatorOperator]?: any } }
}
```

I honestly don't know either why this would work and not the first one.

**Comment by DavideViolante** [comment] 2021-12-20 09:43
I tried the proposed solution in my code and it fixes the TS errors. I just sent a PR. ^
@vkarpov15 this should be high priority and next release due to number of people affected.

**Comment by Uzlopak** [comment] 2021-12-20 17:15
Shame. I thought I could call myself after my PR being merged contributor of mongoose. Well :D

**Comment by ollydixon** [comment] 2022-07-04 12:57
I have this issue upgrading from node `16.13.0 -> 16.15.1`

Casting any doesn't seem to help, we have to place @ts-ignore everywhere, not good.

**Comment by vkarpov15** [comment] 2022-07-16 02:49
@ollydixon the below script compiles fine in Mongoose 6.4.1. Please open a new issue, follow the issue template, and modify the below script to demonstrate the issue you're seeing.

```ts
import mongoose from 'mongoose';
  
run().catch(err => console.log(err));

async function run() {
  const schema = new mongoose.Schema({ name: String });
  const Test = mongoose.model('Test', schema);

  await Test.aggregate([
    {
       $set: {
         roomMembers: "$$ROOT",
       },
     },
  ]);
}
```

**Closed by vkarpov15** 2022-07-16 02:49 UTC
Labels: typescript
