### ISSUE TITLE
puny code module deprecated warning

### ISSUE THREAD

**Issue by AhmadTahir999** [Automattic/mongoose#14108] opened 2023-11-22 13:50 UTC
### Prerequisites

- [X] I have written a descriptive issue title

### Mongoose version

8.0.1

### Node.js version

21.2.0

### MongoDB version

MongoDB atlas

### Operating system

macOS

### Issue

I am using mongoose and it has started giving puny code module deprecated warning, Please use a userland alternative instead. 
mongoose connection is causing the warning if don't use the connection I have given below warning goes away. Can anyone guide me on how can I get rid of this warning? thank you for your time 
```
const mongoose = require("mongoose");

mongoose.Promise = global.Promise;

const connect = async () => {
   try {
      await mongoose.connect(process.env.MONGO_URI);
      console.log("mongodb connected...");
   } catch (error) {
      console.log(error.message);
      process.exit(1);
   }
};

const connection = mongoose.connection;

exports.connect = connect;
exports.connection = connection;
```

**Comment by vkarpov15** [comment] 2023-11-25 17:18
Duplicate of #14104, will be fixed in 8.1

**Closed** 2023-11-25 17:18 UTC
Labels: underlying library issue
