### ISSUE TITLE
Type error if an object with type 'any' is passed to the model's create method (Typescript)

### ISSUE THREAD

**Issue by artemkosenko** [Automattic/mongoose#11970] opened 2022-06-22 10:00 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.4.0

### Node.js version

16.15.0

### MongoDB server version

5.x

### Description

The 'create' method returns wrong object type if the prototype passed to it is of type 'any'

### Steps to Reproduce

A code snippet to reproduce.

```typescript
export interface ImportantObject extends BaseSchema {
    field_one: string;
    field_two: string;
}

const importantObjectSchema = new Schema({
    field_one: {type: String, required: true},
    field_two: {type: String, required: true},
}, {_id: false});

export const ImportantObjectModel = mongoose.model<ImportantObject>("important_objects", importantObjectSchema);


const createOne = async (field_one: string, field_two: string): Promise<ImportantObject> => {
    /* any type is to reproduce the issue */
    const proto: any = {
        field_one,
        field_two
    }
    /*
     TS2740: Type 'Document  { _id: any; }>>> & Omit { _id: any; }> & { _id: ObjectId; }' is missing the following properties from type 'ImportantObject': field_one, field_two, owner, group, and 8 more.
    */
    const new_one: ImportantObject = await ImportantObjectModel.create(proto);
    return new_one;
}

```

![image](https://user-images.githubusercontent.com/13176396/175001436-dfcf9b84-0420-4884-bdde-fda0d5165e7b.png)

### Workaround
1) Stick to mongoose ~6.3.x
2) add ```// @ts-ignore```

### Expected Behavior

A correct type must be returned.

**Comment by vkarpov15** [comment] 2022-07-01 17:50
I'm sorry for the issue, it looks like this bug was introduced in #11563, and fixed by https://github.com/Automattic/mongoose/commit/9ba3f1289e1d16b5c661a786cb85f5aa6caef797 with #12001. I can confirm that the provided script fails to compile with 6.4.2, but succeeds with 9ba3f1289e1d16b5c661a786cb85f5aa6caef797. Fix will be in 6.4.2.

**Closed by vkarpov15** 2022-07-01 17:50 UTC
Labels: typescript
