### ISSUE TITLE
Error that hasn't been happening before (started 2 days ago)

### ISSUE THREAD

**Issue by xMyThoLoGyx** [Automattic/mongoose#11200] opened 2022-01-08 23:15 UTC
I've been having this error pop up on me recently :

MongooseError: Operation `importantids.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/root/disgo/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

I successfully connect to the database and interact with it in my app, but recently, it keeps doing that error at random times and will not stop until I restart the app.

Mongoose version :  5.13.7 (won't update using npm update)

**Comment by vkarpov15** [comment] 2022-01-10 01:17
Not enough information for us to repro. Please provide a code sample that demonstrates this issue.

**Comment by fakelag** [comment] 2022-01-11 11:54
Can second this. For me the issue seems to be that the new mongoose version (we are using 6.1.6) tries to resolve the replica set hostname by itself and throws `getaddrinfo ENOTFOUND mongod-0` (mongod-0 is resolvable from the mongodb server, but not from connecting client). However previous versions and mongosh connects fine. It can not connect and so buffered operations fail with timeout.

Fixed by setting `directConnection: true` in mongoose connection options like so. It feels like previous versions potentially had the connection default to direct connect or something similar?

```typescript
    const connectionPromise = mongoose.connect(mongoUrl, {
        directConnection: true,
    });
```

**Comment by GCastilho** [comment] 2022-01-14 23:17
> Not enough information for us to repro. Please provide a code sample that demonstrates this issue.

I think I can provide more info on this

I have a replica set configured on my raspberry pi, on a different machine, the rs was initiated using: 

```js
rs.initiate({
  _id : "rs0",
    members: [
      { _id: 0, host: "127.0.0.1:27017" },
    ]
})
```

On mongodb 5.13.14, the last from major 5, the `127.0.0.1` was correctly resolved to the rpi ip on the network, but updating to any version post 6 and it tries to connect on `127.0.0.1` from _my_ machine. Here's some logs:

```
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (C:\repo\node_modules\mongoose\lib\connection.js:797:32)
    at C:\repo\node_modules\mongoose\lib\index.js:341:10
    at C:\repo\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\repo\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\repo\node_modules\mongoose\lib\index.js:1167:10)
    at Mongoose.connect (C:\repo\node_modules\mongoose\lib\index.js:340:20)
    at Object.<anonymous> (C:\repo\src\db\mongoose.ts:13:10)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\Gabriel\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1365:23) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(1) { '127.0.0.1:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'Raspberry-PI',
    maxSetVersion: 1,
    maxElectionId: new ObjectId("7fffffff0000000000000043"),
    commonWireVersion: 9,
    logicalSessionTimeoutMinutes: undefined
  }
}
```

I've tested on the same repositório, only changing from 5.13.14, 6.0 and 6.1.6 (latest)

Hope it helps

**Comment by vkarpov15** [comment] 2022-01-17 16:12
@fakelag take a look at the docs on [replica set hostnames](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). The "tries to resolve the replica set hostname by itself" behavior is definitely not new in 6.1.6, we've had that behavior since 5.13 at least, if you had `useUnifiedTopology: true`. What version are you upgrading from?

@GCastilho sounds like you where running with `useUnifiedTopology: false` in 5.x. See [replica set hostnames docs](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). In 6.x, you need to make sure that the replica set member hostnames are something that your app server can resolve.

**Comment by fakelag** [comment] 2022-01-20 13:58
> @fakelag take a look at the docs on [replica set hostnames](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). The "tries to resolve the replica set hostname by itself" behavior is definitely not new in 6.1.6, we've had that behavior since 5.13 at least, if you had `useUnifiedTopology: true`. What version are you upgrading from?

We have had `useUnifiedTopology: true` in previous versions of mongoose (the latest before upgrade was 5.13.6) and the connection has worked every time with that version. Only upon upgrading to the newest version the problem started occurring, and as I said setting directConnect to true has fixed the issue.

After upgrading, we also do not supply `useUnifiedTopology: true` anymore as it defaults to true, but even setting it to true manually doesn't have any effect. Again, only directConnect: true fixes the issue

**Comment by GO-DIE** [comment] 2022-02-13 15:44
> @fakelag take a look at the docs on [replica set hostnames](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). The "tries to resolve the replica set hostname by itself" behavior is definitely not new in 6.1.6, we've had that behavior since 5.13 at least, if you had `useUnifiedTopology: true`. What version are you upgrading from?
> 
> @GCastilho sounds like you where running with `useUnifiedTopology: false` in 5.x. See [replica set hostnames docs](https://mongoosejs.com/docs/connections.html#replicaset-hostnames). In 6.x, you need to make sure that the replica set member hostnames are something that your app server can resolve.

I also encountered the same problem when upgrading from version 5.13.8 to version 6.0.0. Has the problem been resolved?

**Comment by GO-DIE** [comment] 2022-02-13 15:44
I also encountered the same problem when upgrading from version 5.13.8 to version 6.0.0. Has the problem been resolved?

**Comment by vkarpov15** [comment] 2022-02-20 16:42
I took a closer look and I don't see anything to indicate this is anything other than a case of [replica set hostname inconsistency](https://mongoosejs.com/docs/connections.html#replicaset-hostnames), which is documented and expected behavior in the MongoDB Node driver. You need to make sure that the self-reported `hostname` on the machine that's hosting your MongoDB server is resolvable from your application server.

**Closed by vkarpov15** 2022-02-20 16:42 UTC
Labels: needs repro script
