### ISSUE TITLE
Jest Enviroment: remove pre hook cannot be fired

### ISSUE THREAD

**Issue by JunyuanZheng** [Automattic/mongoose#5449] opened 2017-07-09 05:36 UTC
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
pre remove hook is not fired in jest.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have two Schema, The first one is `Course`, and the second one is `Lesson`.

And those two schema all has its own `remove pre hook`.

Part of the code:
```
courseSchema.pre('remove', async function (next) {
  try {
    ...do something
    next();
  } catch (e) {
    next(new Error(e));
  }
});
```

```
lessonSchema.pre('remove', async function (next) {
  // TODO: Delete Azure assets on delete
  try {
   ...do something
    next();
  } catch (e) {
    next(new Error(e));
  }
});
```

And I am using the pre hook like this:
```
const courseQueryResult = req.middleware.courseQueryResult;
await courseQueryResult.remove();
```

```
const lessonQueryResult = req.middleware.lessonQueryResult;
await lessonQueryResult.remove();
```
In my code `middleware` will provide a document.

**What is the expected behavior?**
1. When running inside Jest, the `Lesson` Schema's pre hook **can** be fired.
2. When running inside Jest, the `Course` Schema's pre hook **cannot** be fired.

I tried to remove `Lesson` unit tests, and `Course` pre hook behave the same, **cannot** be fired.

**Please mention your node.js, mongoose and MongoDB version.**
Node V8, mongoose: 4.11.1, MongoDB: v3.4.6

**Comment by JunyuanZheng** [comment] 2017-07-09 05:37
I will try to create a script to reproduce this issue. Everything works fine in Mocha & Chai.

**Comment by JunyuanZheng** [comment] 2017-07-09 06:11
I cannot create a simple script to reproduce this issue. When I use postman to send a request to that endpoint, it can return the correct result. but not in Jest.

**Comment by vkarpov15** [comment] 2017-07-12 21:39
Likely a duplicate of https://github.com/Automattic/mongoose/issues/4943 . If you're familiar with jest I'd appreciate your help in debugging this, jest seems to do a lot of magic that I don't understand and it causes a lot of bugs with mongoose.

**Comment by JunyuanZheng** [comment] 2017-07-12 22:00
I tried to minimize the code. When I only have courseLessonSchema, everything worked. I will spend some time this week to see if I can provide you a script.

**Comment by JunyuanZheng** [comment] 2017-07-13 06:22
I cannot minimize the code. but if I add `--env=node` to Jest, the problem will be gone.

I create an issue ticket in Jest repo.

https://github.com/facebook/jest/issues/4024

**Comment by alonronin** [comment] 2017-07-13 19:35
i'll take a look at this asap.

**Comment by JunyuanZheng** [comment] 2017-07-13 22:47
probably related to jsdom, the Jest use jsdom as default environment. Someone had similar issue before: https://github.com/facebook/jest/issues/3045

**Comment by vkarpov15** [comment] 2017-07-22 19:01
Below script works in jest for me. Please modify it to reproduce this issue:

```javascript
const mongoose = require('mongoose');

test('pre remove', async function() {
  const nestedSchema = new mongoose.Schema({});

  nestedSchema.pre('remove', function(next) {
    console.log('called remove');
    next();
  });

  const schema = new mongoose.Schema({ nested: nestedSchema });
  mongoose.connect('mongodb://localhost:27017/test');
  const M = mongoose.model('Test', schema);

  const doc = await M.create({ nested: {} });
  await doc.remove();
});
```

Output:

```
$ ../node_modules/.bin/jest
(node:9012) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:9012) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
 PASS  ./gh-5449.test.js
  ✓ pre remove (59ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.112s
Ran all test suites.
  console.log gh-5449.test.js:3
    test

  console.log gh-5449.test.js:9
    called remove

^C
$ 
```

Using jest 20.0.4

**Closed** 2017-07-25 23:03 UTC
Labels: can't reproduce, help wanted
