### ISSUE TITLE
Calling remove() on an instance purges my entire collection in v4.1.4

### ISSUE THREAD

**Issue by davidmgarrett** [Automattic/mongoose#3328] opened 2015-09-01 19:46 UTC
npm install mongoose@4.1.3 resolved the issue

this deleted a single car last week:
>>>  deleteModel(Car, '55e5f7d65ad322fc41eb1aaa');

var mongoose = require('mongoose');
var q = require('q');

//define simple schema mapped to "cars" collection in mongo
var carSchema = mongoose.Schema({
	make: {type:String, required:'Make is required!'}
});

mongoose.model('Car', carSchema, 'cars');

//helper functions
var getById = function(model, id) {
	
	var deferred = q.defer();
	
	try 
	{
		model.findOne({_id:id}).exec(function(err, record) {
			deferred.resolve(record);
		});		
	} catch (error) {
		deferred.reject(error);
	}
	
	return deferred.promise;
};

var deleteModel = function(model, id) {
	
	var deferred = q.defer();

	getById(model, id).then(function(record) {
                //extra validation, because I couldn't figure out why collection was purging
		if (!record) {
			deferred.reject('failure finding id: ' + id);
		} else if (!record._id || record._id != id)
			deferred.reject('failure getting id: ' + id);
		{
			record.remove(function(err) {
				if(err) {
					deferred.reject(err.toString());					
				} else {
					deferred.resolve(record);
				}
			});
		}
	}, deferred.reject);
	
	return deferred.promise;
};

**Comment by zackurben** [comment] 2015-09-01 19:57
Heads up, this was fixed earlier today: https://github.com/Automattic/mongoose/commit/83929e8dfb8b142772e54d6726b780b0570cec1d

Duplicate of: https://github.com/Automattic/mongoose/issues/3326 and https://github.com/Automattic/mongoose/pull/3325

**Comment by vkarpov15** [comment] 2015-09-01 21:22
Fixed in 4.1.5, upgrade please :)

**Closed by vkarpov15** 2015-09-01 21:22 UTC
