### ISSUE TITLE
Setting value resets invalidation errors in 4.0.3 (inconsistent with 3.8.28)

### ISSUE THREAD

**Issue by jlchereau** [Automattic/mongoose#2997] opened 2015-05-18 18:07 UTC
I have a pre-validate middleware with a business rule that prevents changing the version title on a modified object:
```
if (!this.isNew) {
...
    if (that.isModified('version.title')) {
        that.invalidate('version.title', '`{PATH}` is invalid: cannot change summary.', that.version.title);
    }
...
}
```

In the same pre-validate middleware, a business rule which applies both to new and modified objects checks the existence of a version and if the version id exists updates the version title, especially when only the version id is supplied:

```
if (that.isModified('version') && that.version._summaryId instanceof mongoose.Types.ObjectId) {
    var Summary = mongoose.model('Summary'), fields; //We assume Summary is registered and found
    Summary.findOne({language: that.version.language, _id: that.version._summaryId}, {title: 1}).lean(true).exec(function (err, summary) {
        if (!err && summary) {
            //Update summary in activity
            that.version.title = summary.title;
        } else {
            var message = util.format('`{PATH}` is invalid: language `%s` and id `%s` could not be found in the summaries collection.', that.version.language, that.version.summaryId);
            that.invalidate('version.language', message, that.version.language);
            that.invalidate('version._summaryId', message, that.version.summaryId);
        }
        parallel_cb(err);
    });
} else {
    parallel_cb();
}
```

In the scenario I am referring to:

1. ```that.invalidate('version.title', '`{PATH}` is invalid: cannot change summary.', that.version.title);``` is first executed, and
2. ```that.version.title = summary.title;``` is then executed.

In mongoose 3.8.28, that.invalidate creates an error on the mongoose document, which the assignment of that.version.title does not delete. So with 3.8.28 save fails.

In mongoose 4.0.3, that.invalidate creates an error on the mongoose document, which the assignment of that.version.title deletes. So with 4.0.3 save succeeds.

**Comment by vkarpov15** [comment] 2015-06-08 13:11
This is by design, mongoose 4 specifically marks a path as being valid when a set succeeds. This is related to issues like #2237, #2506, #2886. In most cases I'd argue that wiping out invalidate() calls on set() is a sensible default, but I'm open to arguments to the contrary.

In your case, you can just avoid setting `version.title` if its invalid:

```javascript
if (!err && summary && that.$isValid('version.title')) {
  //Update summary in activity
  that.version.title = summary.title;
}
```

**Comment by vkarpov15** [comment] 2015-06-29 20:10
Gonna close this, re-open if its still an issue.

**Closed by vkarpov15** 2015-06-29 20:10 UTC
Labels: help
