### ISSUE TITLE
Improve "Cannot read property 'findOne' of null" error message with `bufferCommands = false`

### ISSUE THREAD

**Issue by vkarpov15** [Automattic/mongoose#9239] opened 2020-07-14 19:38 UTC
Right now, with `bufferCommands: false`, executing `Model.findOne()` results in an unhelpful `Cannot read property 'findOne' of null` error message. We should get rid of that error, or at least make that error message more readable.

**Comment by Ignigena** [comment] 2020-07-15 20:46
FWIW just want to point out that this was actually a breaking change for us in a production app due to the previous behaviour.

We had `bufferCommands: false` set up on the Connection to fail quickly, per [the official recommendation](https://mongoosejs.com/docs/lambda.html) on Lambda, but were also calling `.connect` after `.model`. For our purposes this was intentional because we wanted to set up Mongoose and all the models during the Lambda cold start but not establish a Mongo connection until it was needed.

Previously this worked just fine, though I gather this is because we were inadvertently taking advantage of the inconsistency that was fixed in https://github.com/Automattic/mongoose/commit/9a23c4256b27c80e748df134f3c19dceffea1c05. Once we upgraded to 5.9.24 everything broke with the error message above.

A more helpful error message definitely would have helped identify the cause of the problem quicker. But I might also suggest updating the docs on Lambda to better explain the `bufferCommands` setting and how it affects model creation before a connection is established.

I suppose this is just a length way of saying **+1** 😄

**Comment by vkarpov15** [comment] 2020-07-16 16:26
@Ignigena in that case you want to use `bufferCommands: true`, or just not set `bufferCommands` at all. Before 9a23c42, if you called `connect()` with `bufferCommands: false` after `model()`, that's identical to running with `bufferCommands: true`.

Sorry for the inconvenience, I think this is a case where the line between 'bug fix' and 'breaking change' is a little blurry. But if you want to go back to pre-9a23c42 behavior, you should just set `bufferCommands: true`.

**Closed** 2020-07-16 17:00 UTC
Labels: developer-experience

**Comment by Ignigena** [comment] 2020-07-16 17:05
> @Ignigena in that case you want to use `bufferCommands: true`, or just not set `bufferCommands` at all. Before [9a23c42](https://github.com/Automattic/mongoose/commit/9a23c4256b27c80e748df134f3c19dceffea1c05), if you called `connect()` with `bufferCommands: false` after `model()`, that's identical to running with `bufferCommands: true`.
> 
> Sorry for the inconvenience, I think this is a case where the line between 'bug fix' and 'breaking change' is a little blurry. But if you want to go back to pre-9a23c42 behavior, you should just set `bufferCommands: true`.

That's exactly what we did 👍 

No worries at all, we were unwittingly taking advantage of a bug so breaking change for us but good to have the consistency and explanation going forward.
