### ISSUE TITLE
Style documentation http://mongoosejs.com/docs/schematypes.html

### ISSUE THREAD

**Issue by borovik96** [Automattic/mongoose#3850] opened 2016-02-03 20:41 UTC
![image](https://cloud.githubusercontent.com/assets/9018702/12796395/93fd7a72-cacf-11e5-8bbc-1ece4cb2b8dd.png)

**Comment by mynameiscoffey** [comment] 2016-02-03 20:56
Duplicate of #3843

**Comment by tech-boy** [comment] 2016-02-05 02:33
Hey, 
Why is the webpage bug not resolved yet?

**Comment by vkarpov15** [comment] 2016-02-05 16:08
Haven't deployed changes yet, should be fixed with 4.4.2 release today.

**Closed** 2016-02-05 17:31 UTC
