### ISSUE TITLE
Unable to change virtual on cloned Schema

### ISSUE THREAD

**Issue by chumager** [Automattic/mongoose#14019] opened 2023-10-30 21:03 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.12.2

### Node.js version

18.17.1

### MongoDB server version

4.4.2

### Description

Hi, if I remove a virtual with ```schema.removeVirtual```, the virtual is removed, but if I try to assign it again the old virtual is restored.

More precisely if I remove a virtual in a Schema, I can't redefine it.

### Steps to Reproduce

```js
import db from "mongoose";                   
const Schema1 = new db.Schema({              
  a: String                                  
});                                          
Schema1.virtual("test", {                    
  prop1: 1,                                  
  prop2: 2                                   
}).get(function test1() {                    
  return this.a;                             
});                                          
                                             
console.log(Schema1.virtuals.test);          
Schema1.removeVirtual("test");               
console.log(Schema1.virtuals.test);          
Schema1.virtual("test", {                    
  prop3: 1,                                  
  prop4: 2                                   
}).get(function test2() {                    
  return this.a;                             
});                                          
console.log(Schema1.virtuals.test);          
```

### Expected Behavior

To be able to remove a virtual and redefine it without any trace of the previous virtual.

This is giving me a lot of problems because I use ```schema.clone()``` a lot and need to change virtuals.

Regards.

**Comment by vkarpov15** [comment] 2023-10-31 10:33
Confirmed this is an issue in 6.x, but looks to be fixed in 7.x.

```
$ node gh-14019.js 
VirtualType {
  path: 'test',
  getters: [ [Function: test1] ],
  setters: [],
  options: { prop1: 1, prop2: 2 }
}
undefined
VirtualType {
  path: 'test',
  getters: [ [Function: test1], [Function: test2] ],
  setters: [],
  options: { prop1: 1, prop2: 2 }
}
```

Working on a fix now

**Comment by vkarpov15** [comment] 2023-10-31 10:46
Duplicate of #13085, we just didn't backport that fix. I just cherry-picked the fix here: https://github.com/Automattic/mongoose/commit/be441a0300c2b88737e8c374f53b511c05d94c98 . Will ship a release for this in the next 24 hours.

**Closed by vkarpov15** 2023-10-31 10:46 UTC
Labels: priority

**Comment by chumager** [comment] 2023-10-31 14:21
Hi Valery, I've another issue with 7.X, I tried but had problems with transactions, I still have no time to make a simple demo to put it in an issue, thks for the fast response...

**Comment by vkarpov15** [comment] 2023-10-31 14:47
Feel free to share any info you have on the transaction issues you're having, shoot me a message in Slack
