### ISSUE TITLE
Handle CastError on Model.update using promises

### ISSUE THREAD

**Issue by jacruzca** [Automattic/mongoose#2021] opened 2014-04-13 15:52 UTC
Hello,

I just found a bug when I tried to update a model using Model.update using promises. The CastError is not passed to the _onReject_. 

The complete report of this: http://stackoverflow.com/questions/23038557/handle-casterror-with-mongoose-using-promises

When I use the findOneAndUpdate function, everything works as expected.

**Comment by vkarpov15** [comment] 2017-11-29 20:22
Duplicate of #3512, please follow that issue for updates

**Closed by vkarpov15** 2017-11-29 20:22 UTC
