### ISSUE TITLE
No disconnection event after manually connect

### ISSUE THREAD

**Issue by tomgrossman** [Automattic/mongoose#3729] opened 2016-01-04 15:02 UTC
I am using mongoose 4.3.1 with node 4.2.2 and i'm having some disconnection/reconnection issues.

this is my connection code:

```javascript
var MongoDBURL = nconf.get('BackendDB');
var isConnected = false;

var BackendConnection = mongoose.createConnection();
BackendConnection.open(MongoDBURL);

BackendConnection.on('connecting', function () {
    console.log('connecting');
});

BackendConnection.on('connected', function () {
    console.log('connected');
});

BackendConnection.on('open', function () {
    isConnected = true;
    console.log('open');
});

BackendConnection.on('disconnecting', function  () {
    console.log('disconnecting');
});

BackendConnection.on('disconnected', function  () {
    isConnected= false;
    console.log('disconnected');
});

BackendConnection.on('close', function  () {
    isConnected= false;
    console.log('close');
});

BackendConnection.on('reconnected', function () {
    isConnected = true;
    console.log('reconnected');
});

BackendConnection.on('error', function  (Error) {
    isConnected = false;
    console.log('error');
});

exports.IsConnected = function () {
    if (!isConnected) {
        BackendConnection.open(MongoDBURL);
    }

    return isConnected;
};
```

I can see that if I'm stopping the MongoDB the 'disconnected' and 'close' events are firing, and when starting the DB, the 'connected' and 'reconnected' events are firing, this is the good scenario.
The bad scenario is as follows:
1. stop MongoDB
2. 'disconnected' and 'closed' are firing
3. after ~30 seconds, 'closed' event is fired again.
4. start MongoDB
5. no events are firing
6. calling the exported "IsConnected" function, which recognizes that isConnected = false and therefore calling the BackendConnection.open(MongoDBURL) function.
7. 'connecting' , 'connected' , 'open' events are firing, so the isConnected = true
8. stop MongoDB
9. no events are firing, so as for my app, the `isConnected = true`, but the MongoDB is down.
I've checked this scenario with `console.log(BackendConnection.readyState);` when calling the `IsConnected` function and it shows 1 when it should show 0

So it looks like that when using the open function, disconnections are not longer firing the events.

**Comment by vkarpov15** [comment] 2016-01-04 15:36
Duplicate of #3615.

**Comment by tomgrossman** [comment] 2016-01-04 15:44
I don't think it's duplicate.
in [#3615](https://github.com/Automattic/mongoose/issues/3615) you are saying:
>and any future requests will be automatically buffered by mongoose until you explicitly reconnect

That's what I did in step 6 in my issue, I have no problem with that.
The problem is that after this reconnection, disconnection events are not firing when the DB is down again.

**Comment by vkarpov15** [comment] 2016-01-04 23:08
The solution is to [increase the `reconnectTries` and `reconnectInterval` as suggested](http://mongodb.github.io/node-mongodb-native/2.0/api/Server.html) in the above issue. The underlying mongodb driver will stop trying to reconnect after 30 seconds by default. That's behavior that I want to improve on in mongoose, but unfortunately that's the default atm.

**Comment by tomgrossman** [comment] 2016-01-05 07:09
This solution may help, but there will still be "full disconnection" after sometime no matter how much you increase it.
I am talking about what happens after manual re-connection - disconnection events are not fired at all.
I don't know how your solution can help with that.

**Comment by vkarpov15** [comment] 2016-01-05 16:57
Ah ok I see, I didn't read your question carefully enough. Will take a look at this soon, but may take a few days because there's been a lot of issues opened up while I was off for the holidays.

**Closed** 2016-01-07 15:10 UTC
