### ISSUE TITLE
$lookup is not working using mongoose and node but its working in mongo shell 

### ISSUE THREAD

**Issue by monasingh27294** [Automattic/mongoose#5090] opened 2017-03-20 15:39 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, mongoose and MongoDB version.**

**Comment by monasingh27294** [comment] 2017-03-20 15:41
db.userprofile.aggregate([
        "$lookup": {
            "from": "transaction",
            "localField": "uid", 
            "foreignField": "uid",
            "as": "result"
        }
 ])


is working in mongo shell but not node using mongoose i am getting empty array of result not getting data of another collection

**Comment by varunjayaraman** [comment] 2017-03-24 02:10
closing this since it's a duplicate of https://github.com/Automattic/mongoose/issues/5089

**Closed by varunjayaraman** 2017-03-24 02:10 UTC

**Comment by saurabh2325** [comment] 2017-07-21 12:18
how to work $lookup in mean aplication ?

**Comment by monasingh27294** [comment] 2017-07-24 01:44
Hey it's working you have to use the collection name which is in mongo...
Not the model name which you definend in node

For example 
Suppose you have defined 
Var User=require('./models/user')

Here collection name is User but in mongo shell collection name would be users


So use users instead of User
Hope you get this

**Comment by saurabh2325** [comment] 2017-07-24 07:21
Thank u for the reply.

**Comment by monasingh27294** [comment] 2017-07-24 12:04
its worked for you?

**Comment by Stingre** [comment] 2017-08-10 22:08
I was dealing with the same problem and solved it the collection name which is in mongo, as @monasingh27294 said.

Even when this solves the problem, shouldn't mongoose make this name conversion?

**Comment by monasingh27294** [comment] 2017-08-11 08:16
yeah... but mongoose is not making this conversion

**Comment by monasingh27294** [comment] 2017-08-11 08:16
I dont know why 
but it should be...

**Comment by olegmedoed** [comment] 2017-11-10 21:17
@monasingh27294 , I think it shouldn't, $lookup is mongodb related feature, not mongoose. So it introduce unnecessary complexity and confusion, in my opinion.

**Comment by raju2dev** [comment] 2019-03-06 14:47
> db.userprofile.aggregate([
> "$lookup": {
> "from": "transaction",
> "localField": "uid",
> "foreignField": "uid",
> "as": "result"
> }
> ])
> 
> its working in mongo shell but not in node using mongoose i am getting empty array of result not getting data of another collection(transaction)
> 
> using in node as
> db.userprofile.aggregate([
> "$lookup": {
> "from": "transaction", //collection name
> "localField": "uid", // uid is exists in both collection
> "foreignField": "uid",
> "as": "result"
> }
> ]).exec().then(function(data){
> console.log(data)
> }).catch(function(err){
> console.log(err)
> })
> not working getting empty array of result

I am facing the same issue, i am also using the mongoose.createConnection() for connecting db.
Please reply if anyone knows about it.

**Comment by vkarpov15** [comment] 2019-03-11 00:40
@raju2dev please provide some code samples. Also, make sure you're [pluralizing the `from` collection correctly](https://mongoosejs.com/docs/models.html#compiling). You need to pass the collection name to `from`, **not** the model name

**Comment by ankitkataria9** [comment] 2019-07-15 09:47
In case of mongoose(v5.6), use POPULATE. [here it is](https://mongoosejs.com/docs/populate.html)
