### ISSUE TITLE
Mongoos connect warning!

### ISSUE THREAD

**Issue by Thinkdiff** [Automattic/mongoose#5360] opened 2017-06-14 14:24 UTC
I`m using Mongo Atlas and now got this warning!! 

Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin DB and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

I can read and write into database but how can I fix this warning?

**Comment by Quinton** [comment] 2017-06-14 14:39
#5304

**Comment by vkarpov15** [comment] 2017-06-16 21:42
Duplicate of #5304. Safe to ignore this error for now, there will be a workaround in 4.11.0.

**Closed by vkarpov15** 2017-06-16 21:42 UTC
