### ISSUE TITLE
Bug: did not update doc with timestamps in scheme options

### ISSUE THREAD

**Issue by yidinghan** [Automattic/mongoose#4989] opened 2017-02-16 07:34 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Output with debug flag, in version 4.8.3

```shell
Mongoose: tags.remove({}, {})
Mongoose: tags.insert({ updatedAt: new Date("Thu, 16 Feb 2017 07:25:10 GMT"), createdAt: new Date("Thu, 16 Feb 2017 07:25:10 GMT"), name: 'test', _id: ObjectId("58a553d63c8b3681f702e00b"), tags: [], __v: 0 })
Mongoose: tags.findOne({}, { fields: undefined })
Mongoose: tags.update({ _id: ObjectId("58a553d63c8b3681f702e00b") }, { '$set': { updatedAt: new Date("Thu, 16 Feb 2017 07:25:10 GMT") }, '$setOnInsert': { createdAt: new Date("Thu, 16 Feb 2017 07:25:10 GMT") } }, { overwrite: undefined })
Mongoose: tags.findOne({ _id: ObjectId("58a553d63c8b3681f702e00b") }, { fields: undefined })
{ _id: 58a553d63c8b3681f702e00b,
  updatedAt: 2017-02-16T07:25:10.938Z,
  createdAt: 2017-02-16T07:25:10.917Z,
  name: 'test',
  __v: 0,
  tags: [] }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduce script

```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/mongoose-issue');
mongoose.set('debug', true);

const TagSchema = new Schema({
    name: String,
    tags: [{
        enum: ['test1', 'test2'],
        type: String,
        index: true,
    }],
}, {
    timestamps: true,
});

const Tag = mongoose.model('Tag', TagSchema);
let tagId;

Tag.remove({}).
    then(() => Tag.create({ name: 'test' })).
    then(() => Tag.findOne()).
    then((tag) => {
        tagId = tag._id;
        return Tag.update({
            _id: tagId
        }, {
            $set: {
                tags: ['test1']
            }
        });
    }).
    then(() => Tag.findById(tagId)).
    then(console.log);
```

**What is the expected behavior?**

In version 4.8.2

```shell
Mongoose: tags.remove({}, {})
Mongoose: tags.insert({ updatedAt: new Date("Thu, 16 Feb 2017 07:30:28 GMT"), createdAt: new Date("Thu, 16 Feb 2017 07:30:28 GMT"), name: 'test', _id: ObjectId("58a55514714bd682afe1e5fa"), tags: [], __v: 0 })
Mongoose: tags.findOne({}, { fields: undefined })
Mongoose: tags.update({ _id: ObjectId("58a55514714bd682afe1e5fa") }, { '$setOnInsert': { createdAt: new Date("Thu, 16 Feb 2017 07:30:28 GMT") }, '$set': { tags: [ 'test1' ], updatedAt: new Date("Thu, 16 Feb 2017 07:30:28 GMT") } }, { overwrite: undefined })
Mongoose: tags.findOne({ _id: ObjectId("58a55514714bd682afe1e5fa") }, { fields: undefined })
{ _id: 58a55514714bd682afe1e5fa,
  updatedAt: 2017-02-16T07:30:28.611Z,
  createdAt: 2017-02-16T07:30:28.592Z,
  name: 'test',
  __v: 0,
  tags: [ 'test1' ] }
```

**Please mention your node.js, mongoose and MongoDB version.**

```
➜ node --version
v7.3.0
➜ npm ls | grep mongo
├─┬ mongoose@4.8.3
│ ├─┬ mongodb@2.2.22
│ │ ├─┬ mongodb-core@2.1.7
```

**Comment by zivester** [comment] 2017-02-17 02:49
I'm also experiencing timestamps not being set in `mongoose@4.8.3` (they work fine in `mongoose@4.8.2`).

I have `timestamps` on the doc, but even set an explicit `Date` fields value doesn't work:

```
MyModel.update({ key }, { dateField: new Date() });
```

Mongoose says a document was updated, but the resulting doc does not have the new value for `dateField`.

```
zivester@zives:/tmp/test$ npm ls | grep mongo
└─┬ mongoose@4.8.3
  ├─┬ mongodb@2.2.24
  │ ├─┬ mongodb-core@2.1.8
```

**Comment by bdentino** [comment] 2017-02-17 03:52
I believe this might be a regression caused by this commit: https://github.com/Automattic/mongoose/commit/dadeb303c1453fbbbd079ac5cb9b1643afbbc298#diff-32a8cfb1af74860f3233cd24dcd57fadR2490

Indeed, I am having similar issues with plugins that modify the update/findOneAndUpdate fields in middleware.

**Comment by varunjayaraman** [comment] 2017-02-17 17:34
yeah setting the `timestamps` flag seems to mess up the `update` op. Thanks for the repro script, this is def a bug.

**Comment by vkarpov15** [comment] 2017-02-17 22:11
Will be fixed in next release, thanks for reporting.

**Closed** 2017-02-17 22:11 UTC
Labels: confirmed-bug
