### ISSUE TITLE
_id { $in: [ ] } leads to MongooseError: Cast to ObjectId failed for value "[ null ]" at path "_id"

### ISSUE THREAD

**Issue by idibidiart** [Automattic/mongoose#5012] opened 2017-02-23 20:25 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
for this query: _id { $in: [ ] } I get MongooseError: Cast to ObjectId failed for value "[ null ]" at path "_id" 

I believe it's a regression as I have not seen it in the older version of Feathers-Mongoose which had an older Mongoose dependency

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using Mongoose from Feathers-Mongoose ... Would be happy to share relevant parts of the code 

**What is the expected behavior?**
empty array or null or whatever is normal returned type when query fails to match

**Please mention your node.js, mongoose and MongoDB version.**
3.4

**Comment by varunjayaraman** [comment] 2017-02-24 22:12
What version of mongoose is Feathers-Mongoose using ? I'd ideally like to test this separately from Feathers-Mongoose.

**Comment by idibidiart** [comment] 2017-02-28 16:17
@varunjayaraman 

I'm able to repro within my app but so far have not been able to isolate it. I'm producing what seems t be the exact conditions for the bug but I couldn't repro yet independent of my app... will keep trying

I have isolated another issue with Mongoose: https://github.com/Automattic/mongoose/issues/5029

**Comment by BridgeAR** [comment] 2017-04-03 10:06
This is an issue with the current Mongoose version (4.9.3). The issue is, that it's not expected to have arrays for objectIds. The `conditionalHandlers` should be expanded to also handle `$in` and `$nin`.

I can open a PR if you want me to.

**Comment by varunjayaraman** [comment] 2017-05-24 05:51
I'm going to close this without context. Feel free to open again when you have more info.

**Closed by varunjayaraman** 2017-05-24 05:51 UTC
Labels: needs clarification
