### ISSUE TITLE
QueryCursor Bug

### ISSUE THREAD

**Issue by gost442** [Automattic/mongoose#11396] opened 2022-02-14 21:44 UTC
/home/container/node_modules/mongoose/lib/cursor/QueryCursor.js:144
QueryCursor.prototype.map = function(fn) {
                          ^
TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
    at Object.<anonymous> (/home/container/node_modules/mongoose/lib/cursor/QueryCursor.js:144:27)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/container/node_modules/mongoose/lib/query.js:12:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
Node.js v17.5.0

**Comment by RobGordon406** [comment] 2022-02-15 00:59
Pretty sure this might be a duplicate of #11377 and #11384

**Comment by Uzlopak** [comment] 2022-02-15 07:25
It is a duplicate.

**Comment by Uzlopak** [comment] 2022-02-15 23:37
@vkarpov15 
@IslandRhythms 
We can close this, as the underlying bug is fixed already.

**Comment by Uzlopak** [comment] 2022-02-17 07:07
This is resolved with version 6.2.2

**Closed** 2022-02-22 01:02 UTC
Labels: duplicate
