### ISSUE TITLE
Typescript + schema should type check for whether field is required or optional.

### ISSUE THREAD

**Issue by tianhuil** [Automattic/mongoose#11158] opened 2021-12-30 05:12 UTC
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
Consider the following example:
```
interface User {
  name: string;
  email: string;
  avatar?: string;
}

const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});
```
In the following, if `avatar` were required, no corresponding change in the schema's `avatar` would have to be made.  Similarly, if `name` were optional, no corresponding change in the schema's `name` would have to be made.  This appears to be expected (see [docs](https://mongoosejs.com/docs/typescript.html))

> You as the developer are responsible for ensuring that your document interface lines up with your Mongoose schema. For example, Mongoose won't report an error if `email` is `required` in your Mongoose schema but optional in your document interface.

**What is the expected behavior?**
I would like for the schema to type-check whether a field is required.  This is possible using typescript's typing system (e.g. [Stackoverflow](https://stackoverflow.com/questions/53809467/typescript-how-get-optional-keys-of-type)):
```ts
type MappedC<A, B> = {
  [K in keyof A & keyof B]:
  A[K] extends B[K]
    ? never
    : K
};

type OptionalKeys<T> = MappedC<T, Required<T>>[keyof T];
```

If there is interest, I'm happy to contribute a PR.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
This appears to be true for all versions of Mongoose and MongoDB.

**Comment by DavideViolante** [comment] 2021-12-31 07:58
I think duplicate of https://github.com/Automattic/mongoose/issues/9715

**Comment by vkarpov15** [comment] 2022-01-05 17:30
@tianhuil I'm not sure that would be entirely correct. For example, you could do:

```ts
interface User {
  name: string;
  email: string;
  avatar: string;
}

const schema = new Schema<User>({
  name: { type: String, required: true },
  email: { type: String, required: true },
  avatar: String
});

schema.path('avatar').required(true); // Make `avatar` required
```

That's perfectly valid, even though `avatar` is not required in the original schema definition. The issue comes down to the fact that the schema definition doesn't necessarily represent the complete state of the schema.

Another example: you can also make all string fields required by default using `mongoose.SchemaTypes.String.set('required', true);`, which would mean all strings are `required` even though you don't set `required` in the schema definition.

**Closed by vkarpov15** 2022-01-05 17:30 UTC
Labels: new feature

**Comment by tianhuil** [comment] 2022-02-15 19:01
@vkarpov15: that's an interesting use case and not one that I would use.

Apparently the recommended solution is to use https://github.com/lstkz/ts-mongoose

Unfortunately, that project has not been updated since Nov. 2020.
