### ISSUE TITLE
Add document field that stores whether this document was the result of an upsert

### ISSUE THREAD

**Issue by wy193777** [Automattic/mongoose#6417] opened 2018-05-02 18:39 UTC
**Do you want to request a *feature* or report a *bug*?**

Might be a bug.

**What is the current behavior?**

```javascript
let doc = await model.findOneAndUpdate(model, {$set: newModel}, {upsert: true, new: true})
```

Then doc.isNew always equal to false even a new document indeed been created. 

**What is the expected behavior?**

doc.isNew should equal to true if a new document has been created. 

**Please mention your node.js, mongoose and MongoDB version.**
nodejs: V10.0.0
mongoose: 5.0.17
MongoDB: 3.4.8

**Comment by vkarpov15** [comment] 2018-05-04 23:30
@wy193777 this is intended behavior. `isNew` is only true if you created the doc with `let doc = new model(obj)` and have **not** saved the document to the database yet. If you want to see whether a new document was upserted or not, you will have to use [the `rawResult` option for `findOneAndUpdate()`](http://mongoosejs.com/docs/api.html#query_Query-findOneAndUpdate)

**Comment by syffs** [comment] 2020-04-28 20:47
@vkarpov15 wouldn't it make sense to add a flag `wasUpserted` or something similar to advise whether the document was upserted or not ?

**Comment by vkarpov15** [comment] 2020-05-03 20:14
@syffs good idea :+1:

**Comment by Ehbraheem** [comment] 2022-09-02 05:31
@vkarpov15 Any update on this?

**Comment by vkarpov15** [comment] 2022-09-26 18:09
@Ehbraheem not currently.

**Comment by vkarpov15** [comment] 2023-08-14 13:38
I'm going to close this, because with the MongoDB Node driver's new `includeResultMetadata` option it won't always be possible for Mongoose to tell whether a document was upserted or not. Specifically, if `includeResultMetadata = false`, Mongoose can't distinguish between doc that was upserted and doc that was updated.

**Comment by vkarpov15** [comment] 2023-08-15 18:06
Here's a script demonstrating how to do this in the case of [`rawResult` or `includeResultMetadata`](https://mongoosejs.com/docs/tutorials/findoneandupdate.html#raw-result). If `includeResultMetadata` is set, there's no way for Mongoose to know whether document was upserted. It is still possible for Mongoose internals to know whether document was upserted in the case of `rawResult == true`, because `rawResult` is a Mongoose option; but `rawResult` is deprecated.

```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
  name: String
});

testSchema.post('findOneAndUpdate', function(res) {
  console.log('what is res', res);
  if (!this.mongooseOptions().rawResult && !this.options.includeResultMetadata) {
    return;
  }
  if (!res.lastErrorObject.updatedExisting) {
    res.value.$locals.wasUpserted = true;
  }
})

const Test = mongoose.model('Test', testSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const doc = await Test.findOneAndUpdate({}, { name: 'Test' }, { upsert: true, new: true, includeResultMetadata: true });
  console.log('what the document upserted?', doc.value.$locals.wasUpserted);
  mongoose.connection.close();
}

run();
```

**Closed by vkarpov15** 2023-08-15 18:06 UTC
Labels: enhancement, developer-experience
