### ISSUE TITLE
findOneAndUpdate options `setDefaultsOnInsert` looks weird.

### ISSUE THREAD

**Issue by SimonSun1988** [Automattic/mongoose#5455] opened 2017-07-11 12:03 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
findOneAndUpdate options `setDefaultsOnInsert` looks weird.

**If the current behavior is a bug, please provide the steps to reproduce.**

schema:

```
import mongoose from 'mongoose';
let Schema = mongoose.Schema;

let schema = new Schema({
    placement: {
        type: String,
        default: null
    },
    name: {
        type: String,
        default: null
    },
    exposure: {
        type: Number,
        default: 0
    },
    click: {
        type: Number,
        default: 0
    },
    createdAt: {
        type: Date,
        default: Date.now
    }
}, {
    versionKey: false
});

module.exports = schema;
```

my code:

```
let foo = await myModel.findOneAndUpdateAsync({
    placement,
    name
}, {
    $inc: { exposure: 1 }
}, {
    upsert: true,
    new: true,
    setDefaultsOnInsert: true
});
```

`console.log(foo)` result:

```
{
    _id: 5964bdac86968efd5a0b8564,
    createdAt: 2017-07-11T11:59:40.130Z,
    click: 0,
    exposure: 1,
    name: 'XXXXXXXXXXX',
    placement: null
}
```

debug mode log:

```
Mongoose: nowlinks.findAndModify({ name: 'LunchVideoAD', placement: 'lunch' }, [], { '$inc': { exposure: 1 }, '$setOnInsert': { placement: null, click: 0, createdAt: new Date("Tue, 11 Jul 2017 12:18:28 GMT") } }, { upsert: true, new: true, setDefaultsOnInsert: true, remove: false, fields: {} })
```

**What is the expected behavior?**
I pass the **name** and **placement** arguments to model and not *undefined* or *null* , but **name** is `not null`  but **placement** is `null`

**Please mention your node.js, mongoose and MongoDB version.**
mongoose: 4.11.1
node: 7.7.2

**Comment by varunjayaraman** [comment] 2017-07-18 01:34
yup this looks like a confirmed bug:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const Schema = mongoose.Schema;
const GITHUB_ISSUE = `gh-5455`;

exec();

async function exec() {
  try {
    mongoose.connect(`mongodb://localhost:27017/${GITHUB_ISSUE}`, { useMongoClient: true });
    let schema = new Schema({
      placement: {
        type: String,
        default: null
      },
      name: {
        type: String,
        default: null
      },
      exposure: {
        type: Number,
        default: 0
      },
      click: {
        type: Number,
        default: 0
      },
      createdAt: {
        type: Date,
        default: Date.now
      }
    }, {
        versionKey: false
      });


    const Model = mongoose.model('Model', schema);

    const doc = await Model.findOneAndUpdate(
      {
        placement: 'test-placement',
        name: 'test-name'
      }, {
        $inc: { exposure: 1 }
      }, {
        upsert: true,
        new: true,
        setDefaultsOnInsert: true
      });

    console.log('doc', doc); // placement is `null`

    process.exit(0);
  } catch (error) {
    console.error(`Error: ${error}\n${error.stack}`);
    process.exit(2);
  }
}

```

**Comment by vkarpov15** [comment] 2017-07-23 21:00
Thanks for the detailed repro, looks like the issue was a subtle typo in `setDefaultsOnInsert`. The issue is fixed in master and we'll release 4.11.5 with the fix later this week :+1: :beers:

**Closed** 2017-07-23 21:00 UTC
Labels: confirmed-bug

**Comment by dandv** [comment] 2020-05-26 23:23
I might be seeing a related issue. Should `setDefaultsOnInsert` appear in the debug messages?

My code:
```js
Model.findByIdAndUpdate(id, { ...fields }, {
  setDefaultsOnInsert: true,  // set the `username` on insert, which is an autogenerated nanoid
  new: false,
  upsert: true,
});
```

Debug log:

```js
collection.findOneAndUpdate({ _id: '...' }, {
  '$set': {
    ...fields,
  },
  '$setOnInsert': {
    __v: 0,
    createdAt: new Date("..."),
    username: '732901',  // good
  },
}, { setDefaultsOnInsert: true, upsert: true, remove: false, projection: {}, returnOriginal: true })                        
```

I think I expect to not see `setDefaultsOnInsert` in the debug output among the `findOneAndUpdate` options, because it's [not an actual MongoDB `findOneAndUpdate` option](https://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#findOneAndUpdate), since I don't see `new` either (the Mongoose alias), only `returnOriginal` (the actual MongoDB option). But on the other hand I see `remove`, so I'm not sure:

* is the debug output only supposed to include what actually gets sent to MongoDB on the wire?
* does Mongoose actually send all that we see here (including `setDefaultsOnInsert: true, remove: false`) and MongoDB just ignores unrecognized options? Seems like a small improvement could be made in that case.

**Comment by vkarpov15** [comment] 2020-06-03 15:50
@dandv I opened up a separate issue to track :point_up: 

The debug output includes what Mongoose sends to the MongoDB driver. Which isn't necessarily what gets sent over the wire, but close enough for most developers because it also looks close to mongo shell commands. MongoDB ignores the `setDefaultsOnInsert` and `remove` options.
