### ISSUE TITLE
Hard references to BSON files in mongodb driver breaks if BSON module is use in package.

### ISSUE THREAD

**Issue by jaalfaro** [Automattic/mongoose#2908] opened 2015-04-24 17:42 UTC
After upgrading to 4.0.2, I'm having issue that for mongoose/lib/drivers/node-mongodb-native/objectid & binary make hard references to the BSON library under the mongodb modules.  The problem is if you are using the BSON package in your project, npm will only load it once and not under mongodb.  So the hard references break.

**Comment by vkarpov15** [comment] 2015-04-24 17:57
Looks like a duplicate of #2906, thanks for the clarification. Mongoose does make these hard references in order to avoid including the entirety of node-mongodb-native in the browserify build. I'm not sure why 4.0.2 breaks this specifically though - are you upgrading from 4.0.1 or 3.8.x?

**Comment by jaalfaro** [comment] 2015-04-24 18:16
Coming from 3.8.x.  

I did test without including BSON in my project explicitly, and it includes it as part of the mongodb install.  So NPM is checking for duplicaItes even when i move BSON to install after mongodb so there is some though going on there.  

I can think of a couple of ways to solve this.
1.  Include the files you need as part of the package
2.  Look in MongoDB package and if not there, look in BSON package.  That should cover the use cases we know of at this point.
3.  Do a check to see if we are in Browserify or node and act accordingly.

It may be to use a combination of the 2.  

Also, apologies for not even looking at #2906 The title didn't even look close.

**Comment by CKarper** [comment] 2015-04-24 20:28
+1 on this one.  Very frustrating.   bson is a *deep* file dependency, and promoting it to shorten path names now breaks my app.  Using TFS I'm subjected to a 260 character path limit, and mongoose introduces an extremely long dependency chain....    This hard reference to bson really mucks things up.

**Comment by jaalfaro** [comment] 2015-04-24 20:58
I've done a little bit of checking on this.  There doesn't seem to be a good way to determine if you are in node or in the browser.  There are a few tests, but they appear to be somewhat fragile.

So, looking at the notes, this goal is to minimize what Browserify needs to load.  I'm thinking that since mongoose is dependent on mongodb and mongodb on bson, just loading the one file in an attempt to not load all of the BSON library doesn't change things.  However, I'm not sure if Browserify has the same caching of modules that node.js has.  So maybe the concern is having multiple instances of BSON references floating around and the solution in place now would minimize that impact.

My current work around is to attempt to load the path in the file now in a try catch, and if that doesn't work try a second path.  I'm storing these in an array and shift them out in order until I run out or it works.  

So, as a solution for CKarper, your problem sounds like you might be keeping the module files as part of your solution instead of using package.json and npm to mange that on a deployment.  My current fix doesn't solve that problem.

**Comment by CKarper** [comment] 2015-04-24 21:05
No, that would work perfectly for me.  The TFS build server is pulling the modules in when packaging the app for publishing, and that's when the file path gets too long due to the deep dependency chain.  I can "fix" (read: hack around) with that by promoting some deeper modules as first class dependencies in my app...   so, being able to move `bson` and `node-pre-gyp` up fixes my major issue.

My other option is to go fix .NET to allow for the full 32k path spec.  Complaining here seemed easier. ;-)

**Comment by vkarpov15** [comment] 2015-04-24 21:21
I think the solution I'm going to go with is adding bson as a direct dependency for mongoose. It adds a little bit of complexity in that we'd need to bump bson version every time we bump node version, but it would enable us to avoid including the node driver in the browserify build in a more elegant way. What do y'all think?

**Comment by CKarper** [comment] 2015-04-24 21:25
Seems reasonable to me. If you're dependent on the `bson` module, then
adding a dependency to `bson` would be appropriate.

**Comment by jaalfaro** [comment] 2015-04-24 21:32
Not sure that will help in this case.  If I understand the change you are making, that won't fix the problem CKarper or I am having.  

At least in OS X, this is what I see.
If you only reference Mongoose and not BSON or Mongodb, BSON will be mongoose/node_modules/mongodb/node_modueles

If you include Mongodb, BSON will be MongoDB/node_modules

If you include BSON, its in bson.

If you add BSON as a direct dependency of mongoose only, BSON will be in mongoose/node_modules/bson and no longer in mongoose/node_modules/mongodb/node_modueles.

But again, if someone adds in BSON, it will be in BSON and not mongoose/node_modules.

My solution is to just check 
    *'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid', //When mongodb has it
    *'mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid', //When only mongoose is added
    *'bson/lib/bson/objectid'    //When BSON is a specified modules

If you add BSON as an immediate dependancy, you'd have to add
mongoose/node_modules/bson/objectid

I've forked and made the changes and will do a pull shortly.  If you want to see the codes its in https://github.com/jaalfaro/mongoose
binary and objectid are modified.

**Comment by vkarpov15** [comment] 2015-04-24 22:00
Would it not help if mongoose just did `require('bson')` and tracked bson as a dependency? I think that would solve this issue in a much simpler way.

**Comment by jaalfaro** [comment] 2015-04-24 22:09
That would be ideal.  I was trying to find a solution that met with the goal of minimizing the impact on Browserify.  But require('bson') solves the problem best.

**Comment by vkarpov15** [comment] 2015-04-25 01:32
The whole point of the hard references is so that browserify doesn't pick up the mongodb driver or mongodb-core, which would inflate our file size considerably with code that isn't applicable to the browser. I hadn't considered the implications re: if you include "mongodb" or "bson" as a package.json dependency, but I think it should be doable to add bson as a dependency and just use that in mongoose's driver wrapper. I'll give that a shot on Sunday and see how it works.

**Closed** 2015-04-28 16:03 UTC
