### ISSUE TITLE
With Mongoose 6, find queries now return new ObjectId("612771d292715ed65983cc7a") instead of "612771d292715ed65983cc7a"

### ISSUE THREAD

**Issue by Sideral-Inc** [Automattic/mongoose#10780] opened 2021-09-24 18:46 UTC
Prior to update to Mongoose 6, every ids (_id or ref of type mongoose.Schema.Types.ObjectId) was returning objectId as string.

Just update to 6.0.7 and new, all ids are returned as new ObjectId("...").

I looked up to the breaking changes document but find nothing related to that.

Don't know if it's a bug or i am missing a settings.

**Comment by IslandRhythms** [comment] 2021-09-24 21:17
I've seen a couple issues arise that have this similar problem. #10766 has this same problem

**Comment by BorisKotlyarov** [comment] 2021-09-27 13:50
I have a similar problem 
If you use **typescript** and call it as a function (without new operator), you get the error "`TS2348: Value of type 'typeof ObjectId' is not callable. Did you mean to include 'new'?`"

But if you use it with the `new ObjectId("someObjectId")` constructor, the result will be a new ObjectId (not "someObjectId")

**Comment by vkarpov15** [comment] 2021-10-02 17:49
Duplicate of #10808. Same response:

This is expected behavior in v4.x of the MongoDB Node driver, but it only affects how your documents look `console.log()` output. You don't get `new ObjectId(...)` if you, say, pass a document to Express' res.json() function. In other words, this is a purely cosmetic change to make `console.log()` output more copy/pastable given that `ObjectId` is now an ES6 class, and shouldn't affect anything else.

**Closed by vkarpov15** 2021-10-02 17:49 UTC
Labels: help
