### ISSUE TITLE
ObjectId.prototype.cast assumes all "ref" values populated

### ISSUE THREAD

**Issue by jgeorgal** [Automattic/mongoose#3053] opened 2015-06-05 10:44 UTC
npm version of mongoose: 4.0.4

For the following schema:

```javascript
var Group = mongoose.model('Group', new mongoose.Schema({
    name: String,
    _sec: {
	    groups: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Group' }]
    }
}));
```

And for, e.g., the following entries in mongodb:

```javascript
mongoshell> db.groups.find({});

{ "name" : "Hallo", "_id" : ObjectId("54dc5ca7c20652f01bf0c818"), "_sec" :
  { "groups" : [] }, "__v" : 0 }
{ "name" : "Hallo2", "_id" : ObjectId("54e18c95985cc9e42733e284"), "_sec" :
  { "groups" : [  ObjectId("54dc5ca7c20652f01bf0c818") ] }, "__v" : 0 }
```

When groups are retrieved as, e.g.:

```javascript
Group.find({}, function(err, groups) {
  // if (err) ...
  groups.forEach(groups, function(g) {
    console.log(g._sec.groups);
  });
});
```

`g._sec.groups` is empty for both groups, when it should clearly contain a single value for the "Hallo2" group.

Trying to pinpoint the source of the problem, I found that the `ObjectId.prototype.cast` function in `lib/schema/objectid.js:77`, when the schema's type is "ref", i.e., `if (SchemaType._isRef(...))`, assumes that the value is populated. In the function's body from line 103, the following code is found: 

```javascript
var path = doc.$__fullPath(this.path);
var owner = doc.ownerDocument ? doc.ownerDocument() : doc;
var pop = owner.populated(path, true);
var ret = new pop.options.model(value);
ret.$__.wasPopulated = true;
return ret;
```

In the above, `pop` (which is returned by the function defined in `lib/document.js:2079`) is (probably correctly) undefined and thus the following line fails with the exception `[TypeError: Cannot read property 'options' of undefined]`.

All values are retrieved correctly if I replace the last three lines above with:

```javascript
if (pop) {
  var ret = new pop.options.model(value);
  ret.$__.wasPopulated = true;
  return ret;
}
else
  return value;
```

Note that the above example worked fine in pre 4 versions of mongoose. Is this a mongoose bug or am I missing something?

**Comment by vkarpov15** [comment] 2015-06-05 15:27
Duplicate of #3020 and related issues. Will be fixed when I push 4.0.5 today.

**Closed by vkarpov15** 2015-06-05 15:27 UTC
