### ISSUE TITLE
Unhandled promise rejection using callbacks with model.insertMany and other fns

### ISSUE THREAD

**Issue by zbjornson** [Automattic/mongoose#5784] opened 2017-11-03 00:07 UTC
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
`model.insertMany(docs, callback)` (and others) returns a promise that can be rejected, which hits node.js's `unhandledRejection` listener.

**What is the expected behavior?**
The promise shouldn't be rejected (or maybe even returned) if a callback is provided.

```js
mongoose.Promise = global.Promise;

process.on("unhandledRejection", function (uhr) {
  console.log("UNHANDLED", uhr);
  // In our app, this get triggered
});

var UniqueSchema = new mongoose.Schema({
  k1: {type: Number, unique: true}
});
  
var Unique = mongoose.model('UniqueColl', UniqueSchema);

var u1 = new Unique({k1: 5});

Unique.on('index', function() {
  u1.save(function(err) {
    if (err) throw err;
    const retr = Unique.insertMany([{k1: 5}], function(err, result) {
      console.log("CB", err);
      // We handle the error here, don't care about the promise rejection
    });
  });
});
```

Note that I'm having a hard time reproducing this as a stand-alone unit test. I stepped through the issue when the error happens in our application and it leads to this chunk: 
https://github.com/Automattic/mongoose/blob/a48219b66930d9408c7925afdd4340a36a552c1a/lib/model.js#L3884-L3888

Changing those lines to the following fixes the issue:
```js
        if (error) {
          return callback ? callback(error) : reject(error);
        }
```

I'm not sure if fixing this should be considered a breaking change because it's weird to use both callbacks and promises together, and that would be the only scenario that this breaks.

node-mongodb-native does this correctly: https://github.com/mongodb/node-mongodb-native/blob/834a0e299a518d370e65b2bdb76994e97dbde63f/lib/collection.js#L425-L435

Related to #3931. It seems like this might be wide-spread throughout Mongoose; I see it for `model.remove`, `model.init`, `ensureIndexes`, `bulkWrite`, `mapReduce`, `geoNear`, `geoSearch` and `populate`. `model.create` looks correct.

I'm happy to submit a PR for this if it would be accepted.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js v6.11.1
Mongoose master (a48219b)
MongoDb 3.4

**Comment by varunjayaraman** [comment] 2017-11-03 03:13
i agree i think it is weird to reject a promise inside the callback, especially because the callback might execute some asynchronous logic itself. Thoughts @vkarpov15 ?

**Comment by vkarpov15** [comment] 2017-11-06 22:16
Will investigate ASAP :+1:

**Comment by vkarpov15** [comment] 2017-11-07 15:50
Yeah a PR would be most welcome, just make it against the 5.0 branch please :+1: This is a duplicate of several other issues, like #3931 and #4269 , so I'll close this one for now.

**Closed by vkarpov15** 2017-11-07 15:50 UTC
Labels: bug?
