### ISSUE TITLE
MongoError: Timed out waiting for connection - Change Stream

### ISSUE THREAD

**Issue by Karman40** [Automattic/mongoose#9870] opened 2021-01-27 21:52 UTC
**Versions:**
```
"@nestjs/common": "^7.6.5",
"@nestjs/mongoose": "^7.2.1",
"mongoose": "^5.11.11",
"@types/mongoose": "^5.10.3",
```

**Mongo server:**
OS: WIN10 (in ubuntu works fine 👍), i tried Community release, same problem, also 4.4.2 is same problem
![image](https://user-images.githubusercontent.com/32225709/106058753-fa709880-60f1-11eb-8c85-35992ffb34dc.png)

OS: ubuntu 20.04 LTS, work good
![image](https://user-images.githubusercontent.com/32225709/106059186-a0bc9e00-60f2-11eb-88b0-e58d6af32bc2.png)

**Mongo connect config:**
```
MongooseModule.forRoot(process.env.MONGO_URL, {
   useFindAndModify: false,
   autoIndex: true,
   useCreateIndex: true,
   useUnifiedTopology: true,
   auth: { user: process.env.MONGO_USER, password: process.env.MONGO_PASS },
   authSource: process.env.MONGO_AUTH_DB
}),
```

**Change Stream code:**
```
  constructor(
    private algolia: AlgoliaService,
    @InjectModel('users') private userDB: Model<UserDocument>,
    @InjectModel('profiles') private profileDB: Model<ProfileDocument>,
  ) {
    this.userSUB();
  }

  private userSUB() {
    const stream = this.userDB.watch([], {fullDocument: 'updateLookup', maxAwaitTimeMS: Infinity});
    stream.on('change', async (change) => {
      try {
        if (change.operationType === 'delete') {
          const id = change.documentKey._id.toHexString();
          await this.algolia.delete(userIndex, id);
          this.logger.log(`user ${id} delete successfull`);
        }
        else if (change.operationType === 'update' || change.operationType === 'insert' || change.operationType === 'replace') {
          const id = change.documentKey._id.toHexString();
          await this.algolia.save(userIndex, id, change.fullDocument);
          this.logger.log(`user ${id} save successfull`);
        }
      } catch (e) {
        this.logger.error(e);
      }
    });
  }
```

**The error log:**
```
MongoError: Timed out waiting for connection
    at Timeout._onTimeout (D:\nestJS\elit-it-backend\node_modules\mongoose\node_modules\mongodb\lib\change_stream.js:475:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Emitted 'error' event on ChangeStream instance at:
    at ChangeStream.<anonymous> (D:\nestJS\elit-it-backend\node_modules\mongoose\lib\cursor\ChangeStream.js:41:51)
    at ChangeStream.emit (events.js:315:20)
    at unresumableError (D:\nestJS\elit-it-backend\node_modules\mongoose\node_modules\mongodb\lib\change_stream.js:535:20)
    at D:\nestJS\elit-it-backend\node_modules\mongoose\node_modules\mongodb\lib\change_stream.js:553:23
    at Timeout._onTimeout (D:\nestJS\elit-it-backend\node_modules\mongoose\node_modules\mongodb\lib\change_stream.js:475:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by IslandRhythms** [comment] 2021-02-01 21:06
@Karman40 Hey, we're trying to see if this is an issue with mongoose and so it would be helpful if we could get a full script from you. We don't know what the AlgoliaService is and how you used it in your pseudo script above and what other imports you have. If you could send us a more complete script that would be great.

**Comment by Karman40** [comment] 2021-02-02 00:08
Hello @IslandRhythms! If you send me your email address i add you from our private gitlab repo if that's good for you?

**Comment by IslandRhythms** [comment] 2021-02-02 15:09
@Karman40 The reason why we need a script from you is to double check that the error is in fact with mongoose and not something on your local machine. Adding me to the private gitlab repo wouldn't help that I believe. Try and create a similar script to the one you are having an issue with that will replicate the issue. Make sure to define everything used so for example instead of the process.env.url its the actually url and if you include a variable name like AlgoiliaService make sure you also include where it was defined.

**Comment by Karman40** [comment] 2021-02-02 22:21
[mongoose-error-demo-1_master.zip](https://github.com/Automattic/mongoose/files/5914782/mongoose-error-demo-1_master.zip)

@IslandRhythms here is the demo app. Algolia config is on the code, this works perfect, but if uyo want change to own api key.


1. create db with name "error-db"
2. npm run serve
3. create table "users" and/or "users2"
4. create any record for a table (the code sync data to algolia)
5. press enter (now reload code automatic)
6. wait and see error / add new record for table and wait the error

**Comment by IslandRhythms** [comment] 2021-02-04 21:49
@Karman40 So a few things:
1. should I create a cluster in mongodb? Is that what you mean by create db with name "error-db"
2. There is no serve dependency in the package.json so I don't know what that is suppose to accomplish.
3. I don't see the connect config anywhere in the directory.

**Comment by Karman40** [comment] 2021-02-04 21:58
@IslandRhythms sorry, i forgot push my code to git. 👎 

Here is the good code: 
[mongoose-error-demo-1_master (1).zip](https://github.com/Automattic/mongoose/files/5928768/mongoose-error-demo-1_master.1.zip)

Before view code plase run this code: `npm i -g @nestjs/cli`

**Comment by IslandRhythms** [comment] 2021-02-04 23:02
@Karman40 so I ran it on my local machine and I'm not getting any errors. Must be something on your end. Sorry.

**Comment by IslandRhythms** [comment] 2021-02-04 23:03
@Karman40 Is this code going to work or is it going to create an error like the one you reported?

**Comment by Karman40** [comment] 2021-02-04 23:06
This code is going to error

**1. press enter (any where in the code, like app controller) (now reload code automatic)**
**2. wait and see error / add new record for table and wait the error**

**Comment by IslandRhythms** [comment] 2021-02-04 23:15
@Karman40 alright so I have good news and bad news. The good news is that I did not get the errors you got when you made this issue. This means it is not an issue with mongoose and so the problem is on your machine. The bad news is that you now have to find what is causing that problem. I would double check everything in your connection string and make sure everything is set up properly

**Comment by Karman40** [comment] 2021-02-04 23:20
@IslandRhythms just i moment, i create short reproduce video

**Comment by Karman40** [comment] 2021-02-04 23:22
Here is the reproducate video:
https://user-images.githubusercontent.com/32225709/106967864-21f5df80-6748-11eb-8591-652fb6deed29.mov

**Comment by Karman40** [comment] 2021-02-04 23:22
@IslandRhythms Here is the reproducate video:
https://user-images.githubusercontent.com/32225709/106967864-21f5df80-6748-11eb-8591-652fb6deed29.mov

**Comment by IslandRhythms** [comment] 2021-02-04 23:28
@Karman40 Again, I'm not getting that error on my machine so it has to something on your end.

**Comment by Karman40** [comment] 2021-02-04 23:29
@IslandRhythms i tried reinstall mongodb but not helped :/ do you have any idea what could be wrong? WIN 10 error can not be? Ubuntu works.

**Comment by IslandRhythms** [comment] 2021-02-04 23:32
@Karman40 Anything is possible at this point, windows 10 does have weird problems sometimes like how you can't update node via npm. Its possible maybe its a combination of the os + nestjs is creating a weird problem. I can't say anything for sure. Maybe try asking on the nestjs github page and see what they say? I'm not going to close this issue as your still experiencing a problem and so maybe someone will come along and be able to help you. Best of luck.

**Comment by Karman40** [comment] 2021-02-04 23:38
Here is nestjs answare, so helpfull :) 
https://github.com/nestjs/mongoose/issues/650

@IslandRhythms thank you for your help, Best regards! 👍

**Comment by edenjiga** [comment] 2021-02-11 16:07
Im having the same problem, I think the issue is with the change stream, if you close the mongodb connection, the change stream keep working. there is a way to close all the change stream before close the mongodb connection?.

**Closed** 2021-03-29 12:21 UTC
Labels: can't reproduce, has repro script, help, typescript
