### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by ALWISHARIFF** [Automattic/mongoose#9083] opened 2020-06-02 20:42 UTC
**I want to request a *feature***

**I would like to request for Deno Support  Mongoose Plugin**

**Comment by vkarpov15** [comment] 2020-06-04 20:00
What exactly does this mean? Please follow the issue template next time.

**Comment by ALWISHARIFF** [comment] 2020-06-04 22:28
Are you going to make a plugin like mongoose for deno?
I want to know if you have any plans as a team to do so.
thank you

**Comment by Green-Cat** [comment] 2020-06-05 09:45
@vkarpov15 This is a duplicate of #9056.

**Comment by vkarpov15** [comment] 2020-06-11 21:52
I haven't tried out Mongoose with Deno, so I'm not aware of how much work we need to do to support Deno.

**Comment by vkarpov15** [comment] 2020-06-11 21:53
Will close this in favor of #9056

**Closed by vkarpov15** 2020-06-11 21:53 UTC
Labels: needs clarification
