### ISSUE TITLE
Pre save middleware after model definition on 4.8.x

### ISSUE THREAD

**Issue by cartuchogl** [Automattic/mongoose#4982] opened 2017-02-13 19:43 UTC
The following code with mongoose 4.7.9 show 1, 2 but with 4.8.x only show 1:
````js
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost/test-mongoose');

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', () => {

  const kittySchema = mongoose.Schema({
      name: String
  });

  kittySchema.pre('save', (next) => {
    console.log(1);
    setImmediate(next);
  });

  const Kitten = mongoose.model('Kitten', kittySchema);

  // not called on 4.8.x, works on <= 4.7.9
  kittySchema.pre('save', (next) => {
    console.log(2);
    setImmediate(next);
  });

  const fluffy = new Kitten({ name: 'fluffy' });

  fluffy.save((err) => {
    if (err) {
      console.error(err);
    }
    db.close();
  });

});
````

I tested with node 6.9.5 and mongodb 3.2.11 on linux 64bit

**Comment by varunjayaraman** [comment] 2017-02-13 20:29
You're using pre hooks incorrectly. All hooks have to be registered before you call `mongoose.model()`. I'm closing this because it's a duplicate of https://github.com/Automattic/mongoose/issues/4971

**Closed** 2017-02-13 20:29 UTC
