### ISSUE TITLE
Add `typesVersion` with minimum TypeScript version

### ISSUE THREAD

**Issue by elszczepano** [Automattic/mongoose#12529] opened 2022-10-05 19:07 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.6.5

### Node.js version

16.16.0

### MongoDB server version

6.0.2 (not required)

### Description

I've experienced an issue with mongoose above version `6.6.3`. When I try to build a project that uses mongoose in version `6.6.4` or higher I receive:

![Screenshot 2022-10-05 at 20 58 43](https://user-images.githubusercontent.com/23155008/194141352-b51afc3c-cff6-4978-be7c-e913693ec3f7.png)

When I switched to `6.6.3` the issue does not occur. My TS config:
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src",
    "esModuleInterop": true,
    "lib": [
      "es2021",
      "dom"
    ],
    "module": "commonjs",
    "target": "es2021",
    "moduleResolution": "node",
    "allowJs": true,
    "noImplicitAny": true,
    "composite": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "include": [
        "src/**/*"
    ]
  }
}
```

As I briefly checked, the pointed places seem to be syntactically correct so the issue is a bit awkward for me. I'd be grateful for a hint if an issue is on my side.

### Steps to Reproduce

Just run `tsc --build` for a project that uses `mongoose`.

### Expected Behavior

The project is built correctly.

**Comment by vkarpov15** [comment] 2022-10-05 21:11
@elszczepano what version of TypeScript? I'm able to run `tsc --build` with a slightly fixed version of your `tsconfig.json` with TypeScript 4.8.4.

Maybe because your `tsconfig.json` is invalid? You're missing a `,` after `"esModuleInterop": true` and `include` is not a valid `compilerOptions` property.

**Comment by ultrarunner** [comment] 2022-10-06 06:59
I have the exact issue as @elszczepano with typescript 4.3.4, node 14.19.

**Comment by elszczepano** [comment] 2022-10-06 16:58
> Maybe because your tsconfig.json is invalid? You're missing a , after "esModuleInterop": true and include is not a valid compilerOptions property.

Even after fixing the tsconfig the issue still occurs in my case. Regarding the TS version, I use `4.6.3`.

**Comment by kYem** [comment] 2022-10-06 19:54
I had exactly same problem with TS 4.6.4, had to upgrade to latest version and it went away.

**Comment by hasezoey** [comment] 2022-10-07 08:05
Duplicate of #12512

**Comment by hasezoey** [comment] 2022-10-07 08:06
@ultrarunner 

>  node_modules/mongoose/types/query.d.ts:619:29 - error TS2304: Cannot find name 'this'. 619 toConstructor(): typeof this; ~~~~ Found 1 error.

this should be changed with #12522, which was included in mongoose 6.6.5

**Comment by YooItsMaster** [comment] 2022-10-09 08:08
mongoose@6.6.5 
Typescript@4.8.4
node v18.9.0

Facing following `query.d.ts` errors.
![image](https://user-images.githubusercontent.com/77050598/194745244-74b371bb-14e9-42d8-a6a5-3b79bc060d67.png)
Please help

**Comment by hasezoey** [comment] 2022-10-09 08:29
@YooItsMaster did you already try clearing the node modules and re-installing? also are you sure you are using typescript 4.8 to compile?

**Comment by YooItsMaster** [comment] 2022-10-09 08:58
Oh although i had ts v4.8.4 installed it was still using v4.6.2 for compilation. That fixed it. Sry, Thank

**Comment by AlexRMU** [comment] 2022-10-09 11:01
Dude...
![image](https://user-images.githubusercontent.com/61969794/194753099-9e9302f3-cc76-4f7e-b895-43eb78633a46.png)

**Comment by hasezoey** [comment] 2022-10-09 11:05
@AlexRMU from what i can tell, the current types (`typeof Query`) is correct, because the function `toConstructor` is meant to return a *Class constructor* not a *instance of a class*, and because `Query` is a class, by default in typescript this means that the type is a *instance of a class*

https://github.com/Automattic/mongoose/blob/8ea0a44b8ee6e5580a18621762702033a1984d57/types/query.d.ts#L172

**Comment by hxtree** [comment] 2022-10-20 03:08
> Oh although i had ts v4.8.4 installed it was still using v4.6.2 for compilation. That fixed it. Sry, Thank

I ran into the same issue. I had Typescript 4.8.4 installed globally but in a monorepo package.json there was 4.6.2, which needed to change to.
``` 
  "devDependencies": {
    "typescript": "4.8.4"
  },
```
This is a really obscure requirement to find, Perhaps the Typescript minimum version could be placed [README](https://github.com/Automattic/mongoose#mongoose) or similar to help distribute this info?

**Comment by hxtree** [comment] 2022-10-22 17:23
It appears, if a `typesVersions` were added to mongoose / package.json
```
  "typesVersions": {
    ">=4.8.4": { "*": "./types/index.d.ts"] }
  }
```
It would produce the following error or other for those using the package with an version not supported:

```
"'package.json' does not have a 'typesVersions' entry that matches version '{0}'."
```

References:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
https://github.com/microsoft/TypeScript/issues/32166
https://github.com/search?q=%22%3E%3D4.8.4%22+filename%3Apackage.json+typesversions

**Comment by sikmakn** [comment] 2022-10-31 08:17
I have the same problem. Typescript version 4.8.3

**Comment by Mankore** [comment] 2022-11-01 10:38
Same issue

node: 'v16.15.1'
npm: 8.13.2
"mongoose": "^6.7.0"
"typescript": "^4.8.4"

using "skipLibCheck": true, in typescript config or upgrading to latest version of typescript doesn't work for me

**Comment by vkarpov15** [comment] 2022-12-02 03:28
@hxtree I'm not getting any error when running with a TypeScript version that isn't listed in `typesVersion`, for example with the following:

```
"types": "./types/index.d.ts",
  "typesVersions": {
    ">=4.2": { "*": ["./types/index.d.ts"] }
  },
```

A sample Mongoose script compiles just fine with TypeScript 4.1. This looks to be expected behavior from TypeScript. For example, look at the following highlighted section in the TS docs you linked to.

![image](https://user-images.githubusercontent.com/1620265/205208412-1baffce2-32b4-4aa7-82e5-e87530eec9a3.png)

**Closed by vkarpov15** 2022-12-02 03:28 UTC
Labels: typescript
