### ISSUE TITLE
Empty nested object returned when not included in result

### ISSUE THREAD

**Issue by SamVerschueren** [Automattic/mongoose#2787] opened 2015-03-24 13:08 UTC
Hi everyone

This is the schema I have

```JavaScript
var UserSchema = new Schema({
    firstName:          {type: String, required: true},
    name:               {type: String, required: true},
    email:              {type: String, required: true},
    birthday:           {type: Date, required: true},
    phone:              {type: String, required: true},
    picture:            {type: String},
    address:            {
                            street:         {type: String},
                            number:         {type: String},
                            zipcode:        {type: String},
                            city:           {type: String},
                            country:        {type: String}
                        }
});
```

If I execute the following query
```JavaScript
User.find().select('firstName name birthday').exec(function(err, users) {
    if(err) {
        // something happened
    }

    console.log(users);
});
```

It returns the following results

```json
{ 
    "_id": "551161373ddc2b97abbeeef5",
    "firstName": "Foo",
    "name": "Bar",
    "birthday": "Sun Apr 16 1972 00:00:00 GMT+0100 (CET)",
    "address": {} 
} 
```

Why is it returning the address? I don't want it because I don't ask for it. If I run the same query directly in mongo it does not return the address field so this is mongoose related.

Thanks in advance

**Comment by vkarpov15** [comment] 2015-03-24 15:41
Duplicate of #2503. Known limitation in how mongoose builds docs - it builds all nested paths because it's not designed to know whether that path will be empty or not. Use the `minimize` option if you want to get rid of the empty object in `toObject()` or `toJSON()` output.

**Comment by SamVerschueren** [comment] 2015-03-24 15:44
Searched for this issue but didn't find it. Thanks for pointing me to #2503.

**Comment by inca** [comment] 2016-04-17 18:03
I've got the opposite: nested object is `undefined` (with no defaults) even if `minimize: false` is set and it's included in query. Is it intended?

**Comment by inca** [comment] 2016-04-17 18:07
Seems to be specific to Single Embedded Subdocs™ — probably worth creating a separate issue.

**Comment by vkarpov15** [comment] 2016-04-18 15:54
@inca yes please :)

**Closed by vkarpov15** 2016-04-18 15:54 UTC
