### ISSUE TITLE
Cannot exclude reference field when using virutal populate.

### ISSUE THREAD

**Issue by lklacar** [Automattic/mongoose#6653] opened 2018-07-03 14:24 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using virtual field and populate, excluded fields seem to be populated.
```js
const children = await Child.find({}).populate('parent', '_id -children');
```
Also, using this also populates ids for children
```js
const children = await Child.find({}).populate('parent', '_id');
```
Result should not include "children" field.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've pushed to code to reproduce this issue. Take a look here:
https://github.com/lklacar/virtual-populate-issue/blob/master/index.js

**What is the expected behavior?**
children field should not be included when using -children in populate.

**Please mention your node.js, mongoose and MongoDB version.**
Node version: 8.11.2
Mongoose version: 5.2.0

**Comment by vkarpov15** [comment] 2018-07-03 19:16
Thanks for reporting, will investigate ASAP

**Comment by vkarpov15** [comment] 2018-07-07 18:30
We looked into this and this is expected behavior. `populate()` overwrites `select()` because mongoose populate doesn't work without `foreignField`. Can you please describe your use case for this behavior?

**Comment by vkarpov15** [comment] 2019-02-15 15:05
Realistically, we're not going to be able to support excluding the `localField` because then there's no way for us to match local docs to foreign docs. I'm going to close this issue.

**Closed by vkarpov15** 2019-02-15 15:05 UTC
