### ISSUE TITLE
Upserts which create new documents are not validated against schema

### ISSUE THREAD

**Issue by pmaccart** [Automattic/mongoose#1868] opened 2014-01-10 16:44 UTC
When performing an upsert to create a new model, the resulting document does not 

Example:

``` javascript
var MySchema = Schema({
  name: {
    type: String,
    required: true,
    default: 'Mongoose'
  },
  description: {
    type: String
  }
});

var MyModel = mongoose.model('MyModel', MySchema);

MyModel.update({name: 'does not exist'}, {description: 'This is a new document'}, {upsert: true}, function (err) {
    MyModel.findOne({description: 'This is a new document'}, function (err, myModel) {
      console.log(myModel.name); //undefined
    });
});
```

Not sure if this is by design or not, but it seems like enforcing validation would be a nice feature to have for the upsert situation.  I haven't had time just yet to dig into any of the code to see what is exactly is (or isn't) happening with this, but I'll report back if I find anything useful.

Mongoose version: 3.8.0
Node: v0.10.12
Mongo: 2.4.4

**Comment by vkarpov15** [comment] 2017-11-29 21:56
Not able to reproduce this in mongoose 4.13, so I'm gonna close this

**Closed by vkarpov15** 2017-11-29 21:56 UTC
