### ISSUE TITLE
Node.js/Mongoose 4.0.2 "Cannot find module" error

### ISSUE THREAD

**Issue by snewcomer** [Automattic/mongoose#2959] opened 2015-05-04 05:54 UTC
```
Error: Cannot find module 'mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/objectid'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/snewcomer/GitHub/node-pipeline/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:9:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by vkarpov15** [comment] 2015-05-04 13:15
Duplicate of #2908 #2957 #2958 etc. etc. will be fixed in 4.0.3

**Closed by vkarpov15** 2015-05-04 13:15 UTC
