### ISSUE TITLE
Mongoose find() is returning undefined Docs when I send more then one request

### ISSUE THREAD

**Issue by jeffersonfpalheta** [Automattic/mongoose#7309] opened 2018-12-07 13:49 UTC
When I send more then one request from my web app I get this error:  

> TypeError: Cannot read property 'length' of undefined

but if I use only one request so it works well. Any help? 

Part of my code:

```
mongoose.connect(URL, { useNewUrlParser: true, useCreateIndex: true }, function (err) {

  if (err) {
    res.setHeader("Content-Type", "application/json");
    res.status(500).send({message: 'ERROR: COULD NOT CONNECT WITH DATABASE'});
    return;
  }


  DCV_ObjectID.find(query_specifiers, function(err, data) {

    try {
      dataLength=data.length
    } catch (err) {
      console.log(err);
      res.setHeader("Content-Type", "application/json");
      res.status(500).send({message: 'ERROR: FAIL\nTRY AGAIN!'});
      return
    }



    });
});

mongoose.Promise = global.Promise;

```

Thanks in advance !

**Comment by mhombach** [comment] 2018-12-07 16:12
That must be because `data` is undefined, that's what the errormessage tells you.
Why not print the content of `err` in that try-part? Then you could see what details about the error are available :)

**Comment by jeffersonfpalheta** [comment] 2018-12-07 17:07
> TypeError: Cannot read property 'length' of undefined
>
>     at /home/myProject/src/database/db_functions.js:65:21
>     at /home/myProject/node_modules/mongoose/lib/model.js:4528:16
>     at /home/myProject/node_modules/mongoose/lib/query.js:3831:14
>     at cb (/home/myProject/node_modules/mongoose/lib/query.js:1733:14)
>     at err (/home/myProject/node_modules/mongodb/lib/utils.js:415:14)
>     at executeCallback (/home/myProject/node_modules/mongodb/lib/utils.js:404:25)
>     at handleCallback (/home/myProject/node_modules/mongodb/lib/utils.js:128:55)
>     at cursor._endSession.cursor._endSession (/home/myProject/node_modules/mongodb/lib/operations/cursor_ops.js:212:38)
>     at ClientSession.endSession (/home/myProject/node_modules/mongodb-core/lib/sessions.js:113:43)
>     at Cursor._endSession (/home/myProject/node_modules/mongodb-core/lib/cursor.js:189:13)
>     at Cursor._endSession (/home/myProject/node_modules/mongodb/lib/cursor.js:226:59)
>     at cursor._next (/home/myProject/node_modules/mongodb/lib/operations/cursor_ops.js:212:20)
>     at nextFunction (/home/myProject/node_modules/mongodb-core/lib/cursor.js:644:14)
>     at Cursor.next (/home/myProject/node_modules/mongodb-core/lib/cursor.js:833:3)
>     at Cursor._next (/home/myProject/node_modules/mongodb/lib/cursor.js:211:36)
>     at fetchDocs (/home/myProject/node_modules/mongodb/lib/operations/cursor_ops.js:209:12)
>

**Comment by mhombach** [comment] 2018-12-07 20:58
Wait wait wait... i got it.
I already explained that to someone else here today, who had the same problem.
Please see my answer here, that should explain and solve your case:
https://github.com/Automattic/mongoose/issues/7300#issuecomment-445158777

If it's not clear what is meant by that, just @ me here and tell me, what part you didn't understand :)

**Comment by jeffersonfpalheta** [comment] 2018-12-09 12:50
It didn't work for me. So I need to add **poolSize** and **keepAlive**, and remove **mongoose.connection.close()** from inside the **mongoose.connect()**.

```
mongoose.connect(URL, { keepAlive: true, useNewUrlParser: true, poolSize: 10 }, function (err) {
...
}
```

the connect() is called when the Express server receives a request and the DB's URL is received from the request body.

**Comment by mhombach** [comment] 2018-12-09 21:49
Poolsize is irrelevant, you are using a Promise AND a callback together on the find-query and that's not going to work.
Please search for tutorials and explanations on what async/await is and what the difference to callback is :)

**Comment by jeffersonfpalheta** [comment] 2018-12-09 22:18
I'm not using async/await but thanks for help.

**Comment by mhombach** [comment] 2018-12-09 22:39
yes you are using async/await on this issue and as i told you, that wont work together with callbacks:
![567fcd0f-f4f8-46f4-a326-59531e1b7e8a](https://user-images.githubusercontent.com/34406120/49703908-6e4a4100-fc0b-11e8-8e81-9474048e57c7.jpeg)

Also, in the future, please add a note to your original post if you edit important stuff.

**Comment by jeffersonfpalheta** [comment] 2018-12-10 13:57
as I told you I'm not using async/await. With or without async/await it doesn't work. It just work if I add **poolSize** and **keepAlive**, and remove **mongoose.connection.close()** from inside the **mongoose.connect()**.

**Comment by mhombach** [comment] 2018-12-10 14:17
@jeffersonfpalheta 
1: You did use async/await in your original question. That's why i mentioned it.
2: "Poolsize" and "keepalive" were not your problem. You didn't know what `await` does or what a callback is and that caused the error. The `Document.find` functionality is stable in mongoose, because it is used everywhere. What caused you error, as i explained in the link i gave you, was that you executed the find-query 2 times at the same time. And one result will always be faster than the other and so the other gets `undefined`. The chance of you getting `undefined` was somewhat around 50% in your code.
3. I took your code above without any poolsize or connection close stuff and it ran perfectly (though i had to add a few lines on top because you didnt gave us 100% of the code). So the code is not the fault, the connection-parameters were also not the cause, but the async-await in conenction with callbacks, that caused the issue.
And as i already stated: "sneaky" changing the original code so the issue won't be seen, is not very nice. Please, if you change your original code, tell us about it, so we can change our answers accordingly.
This answer is not only meant for you, it's for others that might run into the same trap. And changing the poolsize is no solution. If you can indeed tell me WHY a change in poolsize would solve an undefined value, i would be happy.
Also, since you are talking about "connection.close": There is no "connection.close" in your (posted) code, so we can't predict that.
Overall, if your issue is solved now, you may close this issue.

**Closed** 2018-12-10 14:19 UTC
