### ISSUE TITLE
Custom ObjectIds not work with setDefaultsOnInsert

### ISSUE THREAD

**Issue by aliabdzad** [Automattic/mongoose#4069] opened 2016-04-13 07:47 UTC
hi all ...
i want to have a custom _id and i define it in schema . but when i use "**findOneAndUpdate**" and set "upsert" and "setDefaultsOnInsert" true for it , my custom _id is skipped and default object_id set for it

**Comment by vkarpov15** [comment] 2016-04-16 20:59
@aliabdzad can you provide a code sample please? Like what does your schema look like?

**Comment by aliabdzad** [comment] 2016-04-17 06:45
@vkarpov15 yes of course ,
my schema : 
`var shortid = require('shortid');
var Schema =  new mongoose.Schema({
    _id: {
	    type: String,
	    unique: true,
	    'default': shortid.generate
	},
	created: { type: Date, default: Date.now } ,
	updated: { type: Date, default: Date.now } ,
  creator: { type: String, ref: 'User' } ,
  updater: { type: String, ref: 'User' } ,
	status: { type: Number, default: 1 } 
});`
and my code :
`mongoose.model('Friendship')
    .findOneAndUpdate(
    	{'creator':'41CGahtCe'},
    	{
               creator:'41CGahtCe',
               updater:'41CGahtCe'
        },
    	{
    		new:true,
    		upsert:true,
    		runValidators:false,
    		setDefaultsOnInsert:true, 
            context: 'query'
    	},
        function(err,userItem){ 
         ...
        })`

thnaks ...

**Comment by vkarpov15** [comment] 2016-04-18 15:44
The below script works fine for me:

```javascript
'use strict';

var assert = require('assert');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost/gh4069');
mongoose.set('debug', true);

var shortid = require('shortid');
var Schema =  new mongoose.Schema({
    _id: {
        type: String,
        unique: true,
        'default': shortid.generate
    },
    created: { type: Date, default: Date.now } ,
    updated: { type: Date, default: Date.now } ,
  creator: { type: String, ref: 'User' } ,
  updater: { type: String, ref: 'User' } ,
    status: { type: Number, default: 1 }
});

var Model = mongoose.model('Test', Schema);

Model.create({ creator: 'abc', updater: '123', status: 1 }, function(error, model) {
  assert.ifError(error);
  Model
    .findOneAndUpdate(
        {'creator':'abc'},
        {
               creator:'abc',
               updater:'abc'
        },
        {
            new:true,
            upsert:true,
            runValidators:false,
            setDefaultsOnInsert:true, 
            context: 'query'
        },
        function(err,userItem){ 
          assert.ifError(err);
          console.log(userItem);
          process.exit(0);
        })
});
```

Can you modify it to reproduce your issue?

**Comment by aliabdzad** [comment] 2016-04-19 05:46
thanks but when we use "Model.create" to create new item , shortid generates successfully ... my problem is creating new item by "Model.findOneAndUpdate" .

**Comment by vkarpov15** [comment] 2016-04-21 21:45
@aliabdzad this is unfortunately by design right now because of backwards comaptibility: MongoDB 2.4 does **not** support update operations involving `_id`, even with `$setOnInsert`. You're going to have to set the _id manually for now, sorry :(

**Comment by aliabdzad** [comment] 2016-04-23 05:24
@vkarpov15 thanks for your response . good luck

**Comment by vkarpov15** [comment] 2017-12-13 04:11
Fixed in the 5.0 branch.

**Closed by vkarpov15** 2017-12-13 04:11 UTC
Labels: backwards-breaking, enhancement

**Comment by vkarpov15** [comment] 2017-12-13 04:14
Also, https://github.com/Automattic/mongoose/commit/409a88d09acc4736d32d821d979d376bdcc9dd1a

**Comment by usama-dev** [comment] 2019-03-22 19:46
I was using [mongoose-shortid-nodeps](https://www.npmjs.com/package/mongoose-shortid-nodeps) and faced the similar problem. That's maybe because that package is not updated since 3 years ago. Nevertheless, I switched the package to [shortid ](https://www.npmjs.com/package/shortid) and it's working perfectly.
