### ISSUE TITLE
InferSchemaType does not respect required attribute

### ISSUE THREAD

**Issue by Sotatek-TuanVo** [Automattic/mongoose#13825] opened 2023-09-05 10:58 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue
version: ^7.4.4

```
const exampleAddressSchema = new Schema(
  {
    address: {
      type: String,
      validate: {
        validator: isValidAddress,
        message: validationMessage,
      },
      required: [true, 'custom message'],
    },
    trackingStoppedLocked: { type: Boolean },
   }
  }
  )
   
 export type IExampleAddress = InferSchemaType<typeof exampleAddressSchema>
   ```

![image](https://github.com/Automattic/mongoose/assets/62934348/ca03dba9-9068-4b6f-9476-e3410ec9c22a)
 Why is address optional while required in schema?

**Comment by Uzlopak** [comment] 2023-09-05 11:06
Not reproducable.

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZQMYAsCmICGAaOASQDsAzTKNLXAFQE8xM4BfOUqCEOAIhAmIDmECAGdM3ALAAoUJFiI4mAB6NUMeoxZsOXbjBEATSVOmp+I+MpzgANpgCCBg1EwiRVbDjgBeOMUwA7igYngAU0nCIEZFwOE4ubgBcUVIxMTAMmMnIMFDAgnjRaS4AjgCuwC4GybllmIWpMcwNabk4qADW+QI5EGCMBgAyEJ2Y1QoZjMkAQsJ2OMQsLZHM0gCURRHKcvCTTIQAokrWYHaOzq4iPkRkFB60mQA8exCkise2DvGX9zgAfNIImZiBY4DBXDBkocPqcvhc3NcEEVYt8knAAOQAJgAzAAWdHLSJtTrdXr9MbDUbjUg4GxiCKrEypbaYNQaTCPABGc0wCwAPmViAZMKR8mM-qFwRYAHTErqCMkDSkdMYbZkqVnqJ4WPKCCVSmDSuLwkRrIA

**Comment by Sotatek-TuanVo** [comment] 2023-09-05 11:09
> 

error in macbook

**Comment by Uzlopak** [comment] 2023-09-05 11:09
Actually I am so annoyed, that you did not use the form to create this bug report. I basically want to close  this issue, because now you force me to ask you, which version of each product you use, despite using the form would have been forced to fill them out at the very beginning.

**Comment by Uzlopak** [comment] 2023-09-05 11:10
> > 
> 
> error in macbook

Then call apple support.

**Comment by Sotatek-TuanVo** [comment] 2023-09-06 02:28
@Uzlopak sorry, I wrote the wrong schema
`required: true => required: [true, 'custom message'],`

**Comment by pshaddel** [comment] 2023-09-09 21:25
@Sotatek-TuanVo @Uzlopak 
I have investigated a little bit regarding this issue. Looks like this problem is emerging in Typescript version 5.1.3 and 5.1.6 ([Playground](https://www.typescriptlang.org/play?ts=5.1.3#code/JYWwDg9gTgLgBAbzgZQMYAsCmICGAaOASQDsAzTKNLXAFQE8xM4BfOUqCEOAIhAmIDmECAGdM3ALAAoUJFiI4mAB6NUMeoxZsOXbjBEATSVOmp+I+MpzgANpgCCBg1EwiRVbDjgBeOMUwA7igYngAU0nCIEZFwOE4ubgBcUVIxMTAMmMnIMFDAgnjRaS4AjgCuwC4GyQDauWWYBADkbk0AuoWpMcydabk4qADW+QI5EGCMBgAyEEOY1QoZjMkAQsJ2OMQsvZHM0gCURRHKcvBLTIQAokrWYHaOzq4iPkRkFB60mQA85xCkijdbA54k8PjgAHzSCJmYgWOAwVwwZJXQF3YGPNwvBBFWIgpJwJoAJgAzAAWJo7SL9IYjMYTeYzOYLUg4GxiCJ7EypE6YNQaTBfABG60wmwAPmViAZMKR8vNwaEERYAHTU4aCOmTRmDeaHbkqXnqb4WPKCBVKmDKuIYkT7IA)) but it is not there in newer version which is [5.2.2](https://www.typescriptlang.org/play?ts=5.2.2#code/JYWwDg9gTgLgBAbzgZQMYAsCmICGAaOASQDsAzTKNLXAFQE8xM4BfOUqCEOAIhAmIDmECAGdM3ALAAoUJFiI4mAB6NUMeoxZsOXbjBEATSVOmp+I+MpzgANpgCCBg1EwiRVbDjgBeOMUwA7igYngAU0nCIEZFwOE4ubgBcUVIxMTAMmMnIMFDAgnjRaS4AjgCuwC4GyQDauWWYBADkbk0AuoWpMcydabk4qADW+QI5EGCMBgAyEEOY1QoZjMkAQsJ2OMQsvZHM0gCURRHKcvBLTIQAokrWYHaOzq4iPkRkFB60mQA85xCkijdbA54k8PjgAHzSCJmYgWOAwVwwZJXQF3YGPNwvBBFWIgpJwJoAJgAzAAWJo7SL9IYjMYTeYzOYLUg4GxiCJ7EypE6YNQaTBfABG60wmwAPmViAZMKR8vNwaEERYAHTU4aCOmTRmDeaHbkqXnqb4WPKCBVKmDKuIYkT7IA)

I think maybe it was a TS Issue and it is resolved in the newer version.

**Comment by vkarpov15** [comment] 2023-09-09 21:47
This is a duplicate of #13514. The workaround is to do `required: [true, 'custom message'] as [true, string]`

**Closed by vkarpov15** 2023-09-09 21:47 UTC
