### ISSUE TITLE
select: false on Schema definition does not work

### ISSUE THREAD

**Issue by fedescarpa** [Automattic/mongoose#2735] opened 2015-03-06 04:39 UTC
When I define a schema and I want to exclude some fields for all queries...

```js
var UserSchema = new mongoose.Schema({
  username: { type: String, lowercase: true, required: true, select: true },
  email: { type: String, lowercase: true, required: true, select: true },
  salt: { type: String, select: false },
  hash: { type: String, select: false }
});

var UserModel = mongoose.model('User', UserSchema);

UserModel.findOne().exec(console.log) // it return a mongoose object with salt and hash when it shouldn't
```

**Comment by vkarpov15** [comment] 2015-03-10 14:13
Hmm I can't quite reproduce. The below script:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var util = require('util');
var assert = require('assert');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh2735');

var UserSchema = new mongoose.Schema({
  username: { type: String, lowercase: true, required: true, select: true },
  email: { type: String, lowercase: true, required: true, select: true },
  salt: { type: String, select: false },
  hash: { type: String, select: false }
});

var UserModel = mongoose.model('User', UserSchema);

UserModel.create(
  { username: 'vkarpov15', email: 'a@b.co', salt: 'yes please', hash: 'LV426' },
  function(error, user) {
    assert.ifError(error);
    UserModel.findOne({ _id: user._id }, function(error, user) {
      assert.ifError(error);
      assert.ok(!user.salt);
      assert.ok(!user.hash);
      console.log(util.inspect(user));
      process.exit(0);
    });
  });
```

Outputs what I'd expect:

```
$ node gh-2735.js 
Mongoose: users.insert({ __v: 0, _id: ObjectId("54fefbd6d1d2b572296fd94e"), hash: 'LV426', salt: 'yes please', email: 'a@b.co', username: 'vkarpov15' }) {}  
Mongoose: users.findOne({ _id: ObjectId("54fefbd6d1d2b572296fd94e") }) { fields: { hash: 0, salt: 0 } }  
{ _id: 54fefbd6d1d2b572296fd94e,
  username: 'vkarpov15',
  email: 'a@b.co',
  __v: 0 }
```

on 3.8.24 and 4.0.0-rc3. Can you run this script and verify that you're still getting the salt and hash in your output? Also, can you confirm your versions of mongoose, node, and mongodb?

**Comment by GlennGeenen** [comment] 2015-03-18 12:04
It works as expected for me on Mongoose 3.8.25 with node v0.10.37 and MongoDB 3.0.1.

**Comment by vkarpov15** [comment] 2015-03-21 20:03
Can't repro and it's been a couple weeks since last response. Please re-open if this is still an issue.

**Comment by jrasanen** [comment] 2015-04-01 11:16
This bug is related to "passport-local-mongoose", I think.

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var util = require('util');
var assert = require('assert');
var passportLocalMongoose = require('passport-local-mongoose');

mongoose.set('debug', true);
mongoose.connect('mongodb://localhost/gh2735');

var UserSchema = new mongoose.Schema({
  username: { type: String, lowercase: true, required: true, select: true },
  email: { type: String, lowercase: true, required: true, select: true },
  salt: { type: String, select: false },
  hash: { type: String, select: false }
});


UserSchema.plugin(passportLocalMongoose, {
  selectFields: 'username email'
});

var UserModel = mongoose.model('User', UserSchema);

var user = new UserModel({ username: 'vkarpov15', email: 'a@b.co', salt: 'yes please', hash: 'LV426' });

user.save(function(error, user) {
    assert.ifError(error);
    UserModel.findOne({ _id: user._id })
    .exec(function(error, user) {
      assert.ifError(error);
      assert.ok(!user.salt);
      assert.ok(!user.hash);
      console.log(util.inspect(user));
      process.exit(0);
    });
  });
```
   
this code outputs:

    Mongoose: users.insert({ username: 'vkarpov15', email: 'a@b.co', salt: 'yes please', hash: 'LV426', _id: ObjectId("551bd2af69fda1530e95d63c"), __v: 0 })   
    Mongoose: users.findOne({ _id: ObjectId("551bd2af69fda1530e95d63c") }) { fields: undefined }  

    assert.js:86
      throw new assert.AssertionError({
            ^
    AssertionError: false == true
        at EventEmitter.<anonymous> (/home/jussi/development/mongoosebug/gh-2735.js:32:14)
        at EventEmitter.<anonymous> (/home/jussi/development/mongoosebug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:175:45)
        at EventEmitter.emit (events.js:107:17)
        at Promise.safeEmit (/home/jussi/development/mongoosebug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:81:21)
        at Promise.fulfill (/home/jussi/development/mongoosebug/node_modules/mongoose/node_modules/mpromise/lib/promise.js:94:24)
        at Promise.resolve (/home/jussi/development/mongoosebug/node_modules/mongoose/lib/promise.js:113:23)
        at /home/jussi/development/mongoosebug/node_modules/mongoose/lib/query.js:1169:16
        at /home/jussi/development/mongoosebug/node_modules/mongoose/node_modules/kareem/index.js:103:16
        at process._tickCallback (node.js:355:11)

**Comment by vkarpov15** [comment] 2015-09-14 17:13
Looks like this was fixed in passport-local-mongoose. Re-open if this is still an issue.

**Closed by vkarpov15** 2015-09-14 17:13 UTC
Labels: bug?
