### ISSUE TITLE
Trying to share a variable value between functions in a pre(save) hook and post(save) hook

### ISSUE THREAD

**Issue by jhyland87** [Automattic/mongoose#4558] opened 2016-09-23 16:53 UTC
I'm using Mongoose (which is awesome btw!) in my current NodeJS projects, and I have a MDB collection thats going to store the changes of documents in a different collection (Basically a _changelog_ storing what was modified)

How I'm trying to accomplish that is create a function that stores a JSON version of the document, which is done via the `pre('save')` hook. Then create another hook, which gets executed via `post('save')`, to compare the data stored in `pre('save')`, and compare it with the documents new data.

Heres what I have thus far:

``` javascript

var origDocument 
var testVar = 'Goodbye World'

module.exports = ( schema, options ) => {
    schema.pre( 'save', function( next ) {
        // Store the original value of the documents attrCache.Description value
        origDocument = this.toJSON().attrCache.Description

        // Change the testVar value to see if the change is reflected in post(save)
        testVar = 'Hello World'
        next()
    } )

    schema.post( 'save', function(  ) {
        // Attempt to compare the documents previous value of attrCache.Description, with the new value
        console.log("BEFORE:", origDocument)
        console.log("AFTER:", this.toJSON().attrCache.Description)

        // Both of the above values are the same! >.<

        console.log('post(save):',testVar) // result: post(save):Hello World
        // But the above works just fine..
    } )
}
```

I originally didn't think this would work. To test that the two hooks get executed in the same scope, I created a test variable at the top of the page called `testVar` with some arbitrary value, then in the `post(save)` hook, retrieved the `testVar`, and the value modification of that variable **was seen** in the post save hook.

So from there, I just stored the value of `this.toJSON()` in a variable, then in the post(save) hook, I am trying to retrieve the cached version of this document, and compare it to `this.toJSON()`. However, it doesn't look like the document from the `pre(save)` doesnt hold the pre-modified data, it somehow has the value of the document **after** it was updated.

So why can I update the value of `testVar` from within a `pre(save)` hook, and that change is reflected from a `post(save)` hook function, but I cant do the same thing with the document itself?

Is what im trying to do here even possible? If so, what am I doing wrong? If not - How can I accomplish this?

Thank you

**Comment by jhyland87** [comment] 2016-09-23 17:03
## Update
I tried to run the data through `JSON.stringify()` before saving it in memory via the `pre(save)` hook, then do the same in the `post(save)`, like so:

```javascript
var origDocument 

module.exports = ( schema, options ) => {
    schema.pre( 'save', function( next ) {
      
        origDocument = JSON.stringify( this.toJSON().attributes[1].value )

        // Should store and output the CURRENT value as it was before the 
        // document update... but it displays the NEW value somehow
        console.log( '[MIDDLEWARE] ORIGINAL value:', origDocument )

        next()
    } )

    schema.post( 'save', function(  ) {
        var newDocument = JSON.stringify(this.toJSON().attributes[1].value)

        console.log( '[MIDDLEWARE] UPDATED value:', newDocument )
    } )
}
```

And here's the script that updates the mongoose document:

```javascript
Asset.getAsset( '56d0819b655baf4a4a7f9cad' )
    .then( assetDoc => {
        // Display original value of attribute
        console.log('[QUERY] ORIGINAL value:', assetDoc.attributes[1].value)

        var updateNum = parseInt( assetDoc.__v )+1
        assetDoc.attr('Description').set('Revision: ' + updateNum )

        return assetDoc.save()
    } )
    .then(data => {
        // Display the new value of the attribute
        console.log('[QUERY] UPDATED value:', data.attributes[1].value)
        //console.log('DONE')
    })
    .catch( err => console.error( 'ERROR:',err ) )
```

Heres the console output when I run the N:

> [QUERY] ORIGINAL value: Revision: 67
> [MIDDLEWARE] ORIGINAL value: "Revision: 68"
> [MIDDLEWARE] UPDATED value: "Revision: 68"
> [QUERY] UPDATED value: Revision: 68

As you can see, the *[QUERY] ORIGINAL* value and the *[QUERY] UPDATED* values show that there was an update. But the *[MIDDLEWARE]* original/updated values are still the same... So im still stuck as to why

**Comment by vkarpov15** [comment] 2016-09-27 01:31
So `pre('save')` hooks execute when you call `.save()`, which is _after_ the in-memory changes you do

```javascript
Asset.getAsset( '56d0819b655baf4a4a7f9cad' )
    .then( assetDoc => {
        // Display original value of attribute
        console.log('[QUERY] ORIGINAL value:', assetDoc.attributes[1].value)

        var updateNum = parseInt( assetDoc.__v )+1
        assetDoc.attr('Description').set('Revision: ' + updateNum )

        return assetDoc.save() // <-- this is where pre save hook happens, so `this.Description` should reflect the `.set()` above.
    } )
    .then(data => {
        // Display the new value of the attribute
        console.log('[QUERY] UPDATED value:', data.attributes[1].value)
        //console.log('DONE')
    })
    .catch( err => console.error( 'ERROR:',err ) )
```

I'd imagine what you're trying to do is take a snapshot of `assetDoc` before any `set()` operations take place. I'd imagine the right place to do that would be in a `post('find')` or `post('findOne')` hook rather than a `pre('save')` hook

**Comment by varunjayaraman** [comment] 2017-01-09 07:09
I'm going to close this issue since the actual behavior is also the expected behavior

**Closed** 2017-01-09 07:09 UTC
Labels: help

**Comment by muratsu** [comment] 2017-02-09 13:07
@vkarpov15 in the case where mongoose `save` is converted into a MongoDB `update`, shouldn't we know what the old object looked like?

**Comment by vkarpov15** [comment] 2017-02-12 01:33
@muratsu can you clarify your question please?
