### ISSUE TITLE
aggregate.exec with async=true is stuck in eternity

### ISSUE THREAD

**Issue by adonisv79** [Automattic/mongoose#5653] opened 2017-09-20 07:01 UTC
In line 629 of aggregate.js
```
return new Promise.ES6(function(resolve) {
        if (!_this._model.collection.buffer) {
          process.nextTick(function() {
            var cursor = _this._model.collection.
              aggregate(_this._pipeline, options || {});
            decorateCursor(cursor);
            resolve(cursor);
            callback && callback(null, cursor);
          });
          return;
        }
        _this._model.collection.emitter.once('queue', function() {
          var cursor = _this._model.collection.
            aggregate(_this._pipeline, options || {});
          decorateCursor(cursor);
          resolve(cursor);
          callback && callback(null, cursor);
        });
      });
```

I get true for '_this._model.collection.buffer', so what now? the code just hangs...
this is my call to it

```
                                        self.model.aggregate([
						{ $group: group },
						{ $match: match }
					]).cursor({async: true}).exec(() => {
						let i =1; //never hits the break here
					});
```

**Comment by adonisv79** [comment] 2017-09-20 07:23
also tested with the following
```
return self.model.aggregate([
						{ $group: {
							partner_script_id: "$partner_script_id"
						} }
					]).exec().then(() => {
                                              //never ever gets called so unit test is hanged here
                                              done();
                                        });

**Comment by nwkeeley** [comment] 2017-09-23 03:19
I think I am having some what of the same problem

```
app.models.Event.aggregate({$match: {user_id}}, {$group: {_id: null, count: {$sum: {$size: '$images'}}}}).then((result) => {
      console.log('result', result);
    }, (err) => {
      console.log('err', err);
    });    
```

When I run that query in the terminal I get a result:
```
{ 
    "_id" : null, 
    "count" : NumberInt(118)
}
```
But when I run it as above I get null.

**Comment by vkarpov15** [comment] 2017-09-26 01:07
I'm confused as to what the issue is now. Re: https://github.com/Automattic/mongoose/issues/5653#issuecomment-331607065 , most recent comment, is `user_id` a string or an ObjectId? That is usually the issue.

**Comment by nwkeeley** [comment] 2017-09-26 02:00
user_id is a string.... so ES6 its `aggregate.({$match: {user_id: user_id}, {$group..`

When I run that from the terminal it works fine, but with mongoose  I get get `null` from result

**Comment by vkarpov15** [comment] 2017-10-14 18:12
Gonna close this for now. If you can provide a more detailed example I'll re-open :+1: 🌴

**Closed by vkarpov15** 2017-10-14 18:12 UTC
Labels: needs clarification
