### ISSUE TITLE
Regression from 4.0.2

### ISSUE THREAD

**Issue by dlear** [Automattic/mongoose#3255] opened 2015-08-11 12:59 UTC
With 4.0.2 `model.findById(undefined, function(err,entity){})` correctly returns  with no error and `entity` null.

With all newer versions, this code will always find one entity (if any at all exist).  I think the  previous behaviour is better and more correct.

Interestingly, `model.findById(null, function(err,entity){})` does work correctly (entity is `null`) in all versions.

Can `findById` be fixed so that it behaves the same with `undefined` as with `null`?

**Comment by dlear** [comment] 2015-08-11 13:06
Test case
```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/test');
mongoose.connection.once('open', function () {

	var assetSchema = new mongoose.Schema({
			name : {
				type : String,
				required : true,
				index : true
			}
		});

	var Asset = mongoose.model('Asset', assetSchema);

	// Create some Assets
	var assetData = [{
			name : 'Asset1'
		}, {
			name : 'Asset2'
		}
	];

	Asset.create(assetData, function (err, assets) {
		if (err) {
			throw err;
		}

		console.log('assets created successfully');
	});

	Asset.findById(undefined, function (err, asset) {
		if (err) {
			throw err;
		}

		if (asset) {
			console.error('Found Asset for undefined!');
		} else {
			console.log('Did not find Asset as expected');
		}
	});
});

```

With 4.0.2 I get:
assets created successfully
Did not find Asset as expected

With >4.0.2 I get:
assets created successfully
Found Asset for undefined!

**Comment by vkarpov15** [comment] 2015-08-24 13:50
I suspect this may be a problem with your test case, because `findById(undefined)` always returned a doc. See below modified script:

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/test');
mongoose.connection.once('open', function () {
    var assetSchema = new mongoose.Schema({
            name : {
                type : String,
                required : true,
                index : true
            }
        });

    var Asset = mongoose.model('Asset', assetSchema);

    // Create some Assets
    var assetData = [{
            name : 'Asset1'
        }, {
            name : 'Asset2'
        }
    ];

    Asset.create(assetData, function (err, assets) {
        if (err) {
            throw err;
        }
        console.log('assets created successfully');

        Asset.findById(undefined, function (err, asset) {
          if (err) {
              throw err;
          }

          if (asset) {
              console.error('Found Asset for undefined!');
          } else {
              console.log('Did not find Asset as expected');
          }
        });
    });
});
```

The above script works as expected:

```
$ node gh-3255.js 
assets created successfully
Found Asset for undefined!
```

even on 4.0.2. I'm gonna close this - feel free to re-open if I'm incorrect. For the discussion of correct behavior re: `findById(undefined);`, see #3270.

**Comment by dlear** [comment] 2015-08-24 14:05
Please re-open this...

As you say, it found a doc for `undefined`, but to me that's wrong; that's the bug (regression).

**Comment by vkarpov15** [comment] 2015-08-25 16:11
It does return a doc, but it's not a regression because it still returns a doc in every version I've tried. #3270 is the discussion as to whether or not `findById(undefined)` should return null or first doc.

**Comment by dlear** [comment] 2015-08-25 16:58
Did you try 4.0.2 and earlier?

For me, with 4.0.2 I get:
````
assets created successfully
Did not find Asset as expected
````

That is, no doc was returned.

**Comment by vkarpov15** [comment] 2015-08-25 21:41
Are you running the script I provided? Your script had a small issue.

**Comment by dlear** [comment] 2015-08-26 07:01
Yes, I am running your modified script.

**Comment by vkarpov15** [comment] 2015-08-27 12:14
You're right. The modified script gave the wrong output on 4.0.1.

**Closed** 2015-08-27 12:13 UTC
