### ISSUE TITLE
Issue populating documents that contain embedded discriminators

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#5754] opened 2017-10-26 04:01 UTC
I would like to report what I believe to be a bug in mongoose `4.12.4`.

It seems that there are certain cases when populating documents that contain embedded discriminators (either in arrays or a subdoc) fails. I have provided a test to illustrate this:

```js
const assert = require('chai').assert
const mongoose = require('mongoose')

const Schema = mongoose.Schema

describe('Mongoose Discriminators', () => {
   it('Populating documents that contains disciminators should work', async () => {
      const eventSchema = new Schema(
         { message: String },
         { discriminatorKey: 'kind', _id: false }
      )

      const trackSchema = new Schema({
         event: eventSchema
      })

      const historySchema = new Schema({
         tracks: [{ type: Schema.Types.ObjectId, ref: 'track' }]
      })

      // Discriminator schemas

      const clickedSchema = new Schema({
         element: String
      }, { _id: false })

      const purchasedSchema = new Schema({
         product: String
      }, { _id: false })

      // Register the discriminators

      trackSchema.path('event').discriminator('Clicked', clickedSchema)
      trackSchema.path('event').discriminator('Purchased', purchasedSchema)

      // Create track doc which has an embedded discriminator

      const Track = mongoose.model('track', trackSchema)
      const track = new Track({
         event: {
            kind: 'Purchased',
            message: 'Test'
         }
      })

      await track.save()
      assert.equal(track.event.message, 'Test')
      assert.equal(track.event.kind, 'Purchased')
      assert.ok(!track.event.product)

      // Create history doc, which contains a reference to the newly-created track doc

      const History = mongoose.model('history', historySchema)
      const historyItem = new History({
         tracks: [track.id]
      })

      await historyItem.save()
      assert.equal(historyItem.tracks[0], track.id)

      // This works fine - notice that no selection is specified on populate

      let history = await History.find({}).populate('tracks').exec()
      assert.equal(history[0].tracks[0].event.kind, 'Purchased')
      assert.equal(history[0].tracks[0].event.message, 'Test')
      assert.ok(!history[0].tracks[0].event.product)

      // HERE'S THE ISSUE
      // For some reason, these tests don't all pass when a selection is specified on populate
      // Only the path that is the `discriminatorKey` (in this case, `kind`) shows up

      history = await History.find({}).populate('tracks', 'event').exec()
      assert.equal(history[0].tracks[0].event.kind, 'Purchased') // passes
      assert.equal(history[0].tracks[0].event.message, 'Test') // FAILS
      assert.ok(!history[0].tracks[0].event.product)
   })
})
```

I hope that's clear. Thanks for all your work on this library.

**Comment by Tyrannogina** [comment] 2017-10-26 11:58
I think this has to do with my problem, I wrote a comment in issue #3055, if you want to check.

**Comment by vkarpov15** [comment] 2017-10-30 18:36
Thanks for the detailed repro, will investigate asap :+1:

**Comment by vkarpov15** [comment] 2017-11-09 01:17
Confirmed that this bug is in 4.13.0, but its fixed in master. I suspect this is a duplicate of #5775.

**Closed by vkarpov15** 2017-11-09 01:17 UTC
Labels: bug?
