### ISSUE TITLE
Discriminator support for single nested documents

### ISSUE THREAD

**Issue by asabhaney** [Automattic/mongoose#5244] opened 2017-05-12 22:42 UTC
I first want to say amazing work on mongoose. 

I have a feature request I'd like to put out there that builds on the functionality provided by [single nested subdocuments](http://mongoosejs.com/docs/subdocs.html) and [discriminators in embedded array docs](https://github.com/Automattic/mongoose/pull/4910) (both of which have been added recently and have been very useful). 

I think it would be a valuable addition to be able to have support for discriminators for single nested subdocuments so that you could accomplish something like the following:

```js

const mediaSchema = new Schema({ 
   caption: String, 
   position: String,
   file: { type: Schema.Types.ObjectId, ref: 'file' }
}, { discriminatorKey: 'kind', _id: false })

const imageSchema = new Schema({ 
   width: Number,
   height: Number
})
  
const videoSchema = new Schema({ 
   duration: Number
})

// Now to make use of the schemas above...

const blogPostSchema = new Schema({
   title: { type: String, trim: true },
   body: { type: String, trim: true },

   // Note this is not an array!
   featureBanner: mediaSchema
})

blogPostSchema.path('featureBanner').discriminator('image', imageSchema)
blogPostSchema.path('featureBanner').discriminator('video', videoSchema)
```

Hope that makes sense!

Assuming I haven't misunderstood something, do you believe this to be a useful addition to mongoose? If so, I wouldn't mind taking a stab at opening a PR that adds this functionality. Thanks in advance!

**Comment by vkarpov15** [comment] 2017-05-16 19:03
Good suggestion, something we'll consider adding in the near future. However, it's unlikely we'll have this feature within the next 3 months.

**Comment by c1moore** [comment] 2017-07-17 14:32
I second this idea and actually gave a very similar implementation on #1856.

Since this feature isn't expected anytime soon, I took the liberty to find a temporary workaround.  Instead of creating Schemas, you'll can create a class and use `post("init")` to convert an object from the DB to an instance of the class.  Here's some sample code that is working with a few "tests" down at the bottom:

```
'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.Promise = require('bluebird');

mongoose.connect('mongodb://localhost/test', {
  useMongoClient: true
}).then(
  function() {
    var circle;

    function endProcess(error) {
      if(error) {
        console.error(error);
      }

      SomeModel.remove().then(process.exit, process.exit);
    }

    // "Discriminated" Class (i.e. the superclass or interface).
    function Shape() {}

    Shape.prototype.toDoc = function shapeToDoc() {
      throw new Error('NotImplementedError');
    };

    // One of the "Discriminator" Classes (i.e. a subclass or class that implements the interface).
    function Circle(radius) {
      this.radius = radius;
      this.__t = 'Circle';
    }

    Circle.prototype = Object.create(Shape.prototype);
    Circle.prototype.constructor = Circle;

    Circle.createFromDoc = function createFromDoc(document) {
      return new Circle(document.radius);
    };

    Circle.prototype.getArea = function getArea() {
      return (Math.PI * this.radius * this.radius);
    };

    // A factory to vend the Shapes after a document is returned from the DB.
    function ShapeFactory() {}

    ShapeFactory.vendShape = function vendShape(shapeDoc) {
      switch(shapeDoc.__t) {
        case 'Circle':
          return Circle.createFromDoc(shapeDoc);
        default:
          throw new Error('Unknown shape.');
      }
    };

    // Schema with a field that needs to be discriminated.
    const SomeSchema = new Schema({
      shape:  {
        type:     {},
        validate: {
          validator:  function validateShape(shape) {
            return shape && (shape instanceof Shape);
          },
          message:    'Shape must be a valid shape.'
        }
      }
    });

    // This is where the magic happens.  Convert the `shape` field to a Shape object.
    SomeSchema.post('init', function postInit() {
      this.shape = ShapeFactory.vendShape(this.shape);
    });

    const SomeModel = mongoose.model('Some', SomeSchema);

    // Tests
    var someModel = new SomeModel({shape: new Circle(5)});

    console.log("First: " + someModel.shape.getArea());

    return someModel.save().then(function(savedSomething) {
      console.log("Second: " + savedSomething.shape.getArea());

      return SomeModel.findOne();
    }).then(function(dbSomething) {
      console.log("Third: " + dbSomething.shape.getArea());
    });
  },
  function(error) {
    console.error(error);

    process.exit();
  }
).then(process.exit, process.exit);
```

**Comment by vkarpov15** [comment] 2017-07-18 17:38
@c1moore clever idea! We might implement this in a similar way, structure it as a plugin rather than changing core functionality.

**Comment by sebpiq** [comment] 2017-08-25 12:56
:+1:  for this feature ...

Has your code @c1moore been released as plugin or something?

**Closed** 2017-10-03 01:41 UTC
Labels: fixed?, new feature

**Comment by matze1234** [comment] 2019-05-27 12:52
So it's still not supported, right?

**Comment by vkarpov15** [comment] 2019-05-29 17:38
@matze1234 what makes you think that? The issue is closed with a milestone, there's a commit linked to above that closes this issue, and there's a "Fixed?" label. I'm not sure how you could get the impression this isn't supported.
