### ISSUE TITLE
Field skipped if empty when using text search

### ISSUE THREAD

**Issue by reilg** [Automattic/mongoose#3091] opened 2015-06-21 20:20 UTC
EDIT:
I also placed this [question](https://stackoverflow.com/questions/30969323/mongodb-mongoose-missing-default-fields-on-text-search) on SO if that helps.

I have a product schema that looks something like this:

````
var ProductSchema = new mongoose.Schema({

	name: { type: String, required: true },
	description: String,

	comments: [{ type: Number, ref: 'Comment' }],
	comment_count: { type: Number, default: 0 },
});
````
And index for text search the name and description:
`ProductSchema.index({ name: 'text', description: 'text' });`

I use the text search like so:
````
this.find(
	{ $text: { $search: keywords } },
	{ score: { $meta: "textScore" } }
)
.sort({ score: { $meta: "textScore" } })
.populate({
	path: 'comments',
	select: 'creator body date_created',
	options: {
		sort: { date_created: -1 }
	}
})
.exec( function(products) {
	... //-> snipped for brevity
});
````

Although the search works just fine, some items on the returned data set do not have a `comment_count` field which is supposed to default to 0.
The problem I think is when I try to return the the text search score because when I remove this line: `{ score: { $meta: "textScore" } }`. All items on the list have a comment_count field. 

I would like to make both work, as it makes a lot of sense to sort the data by text score.

NOTE:
I'd like to note that I call `this` during the search query because I placed this as a static method for `Product`.

I'd also like to note that `comment_count` is changed whenever a comment is added or deleted and isn't being populated during the search query. Not sure if this info might be helpful of if relevant at all, though.

**Comment by vkarpov15** [comment] 2015-06-22 13:12
This looks like a duplicate of #2166, try upgrading to 4.0.6 (or, if you're still on 3.8, to 3.8.31) to get the fix.

**Closed** 2016-06-01 22:40 UTC

**Comment by mathurs** [comment] 2017-09-28 13:32
This seems to be still happening in 4.11.13. In debug the fields is getting modified from
fields: { score: { '$meta': 'textScore' }}
to
fields: { score: { '$meta': 'textScore' }, __t: 1 }

**Comment by vkarpov15** [comment] 2017-10-02 04:09
@mathurs looks like you're running into some issue with discriminators. Can you please open up a separate issue with code samples please?
