### ISSUE TITLE
High number of connections on Mongoose 5.6.1

### ISSUE THREAD

**Issue by pravesh-curefit** [Automattic/mongoose#7948] opened 2019-07-01 17:27 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I use mongoose to connect to a replica set consisting of 1 primary and 3 secondary nodes. I recently updated my application from Mongoose 4.9.1 to 5.6.2. I've kept the connection pool size same as before (30) and used the new param minSize to set minimum as 2. I see my application using more connections than before with the same traffic. It's keeping ~20-22 connections open to primary as compared to 8-10 earlier. This leads me to reach the connection limit on my mongodb cluster.

Is there any change in mongoose that leads to this high number of connections being kept ready?

Here are the config options I am using.
`{
    minSize: 2,
    poolSize: 15,
    autoReconnect: true,
    reconnectTries: Number.MAX_VALUE,
    reconnectInterval: 5000,
    useNewUrlParser: true,
    useCreateIndex: true,
    socketTimeoutMS: 30000
}`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Number of connections to remain same as before.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
Node.js 8.9.4
Mongoose 5.6.1
MongoDB 3.4

**Comment by vkarpov15** [comment] 2019-07-03 18:32
Have you tried removing `minSize`? Also, what's the connection limit on your cluster? And how many application servers are you running?

**Comment by alolis** [comment] 2019-07-03 18:41
I am experiencing the same issue in which connections seem to stay open no matter what I try.

I am using the following connection settings:

```
useCreateIndex: true,
useNewUrlParser: true,
useFindAndModify: false
```

However, i noticed that if i add `socketTimeoutMS: 5000` (and more specifically a value less than 10000) the connections do close (only one stays connected which if i understand its the intended behavior).

What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.
Node.js 8.13
MongoDb 4.0.4
Mongoose 5.6.3

**Comment by pravesh-curefit** [comment] 2019-07-04 05:01
> Have you tried removing `minSize`? Also, what's the connection limit on your cluster? And how many application servers are you running?

The values mentioned here are for a single instance of the application. I notice increase per instance of the application. Values remain same without `minSize` as well.

**Comment by pravesh-curefit** [comment] 2019-07-04 06:53
> I am experiencing the same issue in which connections seem to stay open no matter what I try using a replica set (i haven't tested what happens in standalone mongodb) and the behavior is the same in both our production environment which is more complex and on my laptop with a local installation that has a single node and replication enabled.
> 
> I am using the following connection settings:
> 
> ```
> useCreateIndex: true,
> useNewUrlParser: true,
> useFindAndModify: false
> ```
> 
> However, i noticed that if i add `socketTimeoutMS: 5000` (and more specifically a value less than 10000) the connections do close (only one stays connected which if i understand its the intended behavior).
> 
> **What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
> Node.js 8.13
> MongoDb 4.0.4 (dev) & MongoDb 4.1.7 (production)
> Mongoose 5.6.3

I believe `socketTimeoutMS` used to be 30000 by default in Mongoose 4.9.1 as well so I would not want to change that.

**Comment by alolis** [comment] 2019-07-04 07:47
> I believe `socketTimeoutMS` used to be 30000 by default in Mongoose 4.9.1 as well so I would not > want to change that.

I do not mind that the default is 30000, the problem is that even after 30000 msec the connections stay open.

Verified via `netstat -a | grep 27017` and via mongo shell `db.serverStatus().connections`

I only see them closing if i specify a socketTimeoutMS >= 10000

Is there something I am missing here?

**Comment by vkarpov15** [comment] 2019-07-08 18:24
The 2nd socket will be destroyed after 30 seconds if you set socketTimeoutMS to 30000. If not, that's a bug that we'll try to  repro.

Why are you so concerned about closing idle sockets? In most cases you want extra sockets to stay open so you don't incur the performance overhead of opening a new socket very often.

**Comment by pravesh-curefit** [comment] 2019-07-09 06:27
While we do want to keep extra sockets open, I see there is a behaviour change between the two versions and I don't find any documentation of why this change has happened.
Since 4.9.1 was not keeping as many connections open, was it less efficient? Is there any benchmark data on this available?

**Comment by alolis** [comment] 2019-07-09 06:37
> Why are you so concerned about closing idle sockets? In most cases you want extra sockets to stay open so you don't incur the performance overhead of opening a new socket very often.

In our use case there is no benefit from keeping them open since they do not open that often but it is however a waste of resources since we now have thousands of idle connections at the moment.

**Comment by vkarpov15** [comment] 2019-07-11 15:39
@alolis I'm unable to repro this. Below script shows that the number of open connections drops from 2 to 1 after 20 seconds with a socketTimeoutMS of 12 seconds:

```javascript
const assert = require('assert');
const mongoose = require('mongoose');
mongoose.set('debug', true);

const GITHUB_ISSUE = `gh7948`;
const connectionString = `mongodb://localhost:27017,localhost:27018/${ GITHUB_ISSUE }?replicaSet=rs`;
const { Schema } = mongoose;

run().then(() => console.log('done')).catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString, {
    useNewUrlParser: true,
    poolSize: 2,
    socketTimeoutMS: 12000
  });

  console.log('Num open sockets to primary', mongoose.connection.db.s.topology.s.coreTopology.s.replicaSetState.primary.s.pool.availableConnections.length);

  await mongoose.connection.dropDatabase();

  const Model = mongoose.model('Test', Schema({ name: String }));

  await Model.create([{ name: 'foo' }, { name: 'bar' }]);
  console.log('Num open sockets to primary', mongoose.connection.db.s.topology.s.coreTopology.s.replicaSetState.primary.s.pool.availableConnections.length);

  await new Promise(resolve => setTimeout(resolve, 20000));
  console.log('Num open sockets to primary', mongoose.connection.db.s.topology.s.coreTopology.s.replicaSetState.primary.s.pool.availableConnections.length);
}
```

Can you modify the above script to demonstrate your issue please?

@pravesh-curefit I wouldn't be able to say why the behavior changed without looking at your code. There were numerous changes between 4.9.1 and 5.6.2 that might have an impact. For one thing, [you couldn't set a minimum pool size in 4.9.1](https://github.com/mongodb-js/mongodb-core/blob/master/HISTORY.md#300-rc0-2017-12-05). Out of curiosity, if 20 connections causes you to run out into a connection limit, why not reduce `poolSize`?

**Comment by alolis** [comment] 2019-07-16 09:09
@vkarpov15 , my apologies for haven't tested this yet but some other issues required my attention. I will get on it and reply to you.

**Closed** 2019-08-18 00:31 UTC
Labels: can't reproduce

**Comment by mallikarjunece** [comment] 2019-08-26 04:30
I am getting the following warning.

(node:3724) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.

How to overcome this ?
