### ISSUE TITLE
Query was always already executed in Node 16.14.0

### ISSUE THREAD

**Issue by Useless02** [Automattic/mongoose#11416] opened 2022-02-17 16:28 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a Bug

**What is the current behaviour?**
While the query executes normally in Node 16.13, the error "Query was already executed" is always present in Node 16.14; by switching Node version with nvm or installing Node 16.14 on an EC2 (Amazon Linux)

**If the current behaviour is a bug, please provide the steps to reproduce.**

The code, while is wrapped by a custom loader, is fairly straightforward:
``` javascript
// simplified version
app.get('/resource', async (req, res, next) => {
  let query = model('Resource').find(req.query);
  if (req.query.page) query = query.limit(10).skip(req.query.page - 1)
  // several lines of query builder here, basically handling pagination and population
  // methods used: orFail, sort, select, populate, limit, skip
  ...
  return res.status(200).json({ records: await query });
})
```

**What is the expected behaviour?**
In Node 16.13, the response reads: 
`{ records: [Object], [Object] }`

In Node 16.14, the response reads, after being caught by error handler:
`Query was already executed: Resource.find({})`

This behaviour persists even with deleting node_modules and reinstalling all packages

**Edit:**
The following variations have been tested and the behaviour persists
``` javascript
await model('Resource').find(req.query) // await the find directly, disabling the query builder altogether 
await model('Resource').find(req.query).exec() // await the find with exec
await query.exec() // await the query with exec

const query = model('Resource').find(req.query);
  // build query with and without reassignment, i.e. query = query.limit(10)
await query; // await the query after building,
```

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
| |version|remarks
|--|--|--|
|Node|16.14| |
|Mongoose|6.2.2| |
|MongoDB|5.0.6| MongoDB Atlas Free tier (M0) |

**Comment by Useless02** [comment] 2022-02-17 18:14
> Do `await model('Resource').find(req.query);` and see if that fixes it.

@IslandRhythms sorry but this defeats the whole query builder, I need the Query object to wait until the very end, then execute.

**Comment by Uzlopak** [comment] 2022-02-17 18:15
@IslandRhythms  
I think he wants to use the query builder. So awaiting it will not fix it. 

I suspect this line:
`if (req.query.page) query = query.limit(10).skip(req.query.page - 1)`

methods on the query builder are mutating the query/query builder. So there is no need to assign the mutated query to the query object.
Maybe in node 16.14.0 the promise gets executed when assigned to a variable?!

**Comment by Useless02** [comment] 2022-02-17 19:35
> @IslandRhythms I think he wants to use the query builder. So awaiting it will not fix it.
> 
> I suspect this line: `if (req.query.page) query = query.limit(10).skip(req.query.page - 1)`
> 
> methods on the query builder are mutating the query/query builder. So there is no need to assign the mutated query to the query object. Maybe in node 16.14.0 the promise gets executed when assigned to a variable?!

Just tried commenting out the reassignment, still getting the same error, I do think it is something related to Node itself, since Node 16.13 runs without any problem

**Comment by Uzlopak** [comment] 2022-02-17 19:55
What happens if you do await query.exec() ?

**Comment by Useless02** [comment] 2022-02-18 03:13
@Uzlopak I have updated the question itself to include all the tests I've done, and await query.exec() still fails

**Comment by IslandRhythms** [comment] 2022-02-18 17:30
```javascript
const mongoose = require('mongoose');

const testSchema = new mongoose.Schema({
    name: String
});

const Test = mongoose.model('Test', testSchema);

async function run() {
    await mongoose.connect('mongodb://localhost:27017');
    await mongoose.connection.dropDatabase();

    await Test.create({name: 'Test'});

    let query = mongoose.model('Test').find({name: 'Test'});
    query = query.limit(10).skip(0);
    console.log(await query);
}

run();
```

**Comment by Uzlopak** [comment] 2022-02-18 17:48
I can not reproduce it on my system. 
@IslandRhythms 
do you get that message of "Query was already executed" when running the script in node 16.14?

**Comment by Uzlopak** [comment] 2022-02-18 17:49
Oh I see, you added the "can't reproduce" label to this issue. nvm

**Comment by kfitzgerald** [comment] 2022-03-19 21:31
I seemingly ran into this on node 16.14.2 with mongoose 6.2.7 as I was upgrading some legacy code. I too use the query builder feature, but in my case, it was `query.setOptions(...)` that caused the duplicate execs. 

Offending line: https://github.com/aheckmann/mquery/blob/master/lib/mquery.js#L183

This was due to an issue with my app, which was doing something like this:

```
function getQuery(criteria, options) {
    const { skip, take, ...additionalOptions } = options;
    const query = myModel.find(criteria);
    query.skip(skip);
    query.limit(take);
    
    // Send any unknown options along to the query engine
    if (additionalOptions) query.setOptions(additionalOptions);
    
    return query;
}

const q = getQuery({ stuff: "things" }, { skip: 5, exec: false });
```

where the getQuery fn was passing any unknown options along to the `Query.setOptions()` method. Since it was passing `{ exec: false }`, mquery was in turn doing this:

```
this[method].apply(this, args);
```

where `method="exec"` and `args=[false]`

So, careless setOptions usage in my app was to blame for this.

Perhaps this revelation could help in some way?

Thanks,
-Kevin

**Comment by AbdelrahmanHafez** [comment] 2022-03-19 21:57
Thanks @kfitzgerald

### 11416.js
```js
'use strict';
const mongoose = require('./');
const { Schema } = mongoose;
const assert = require('node:assert');

run().catch(console.error);

async function run() {
  await mongoose.connect('mongodb://localhost:27017/test');
  await mongoose.connection.dropDatabase();

  const userSchema = new Schema({
    name: { type: String }
  });


  const User = mongoose.model('User', userSchema);
  await User.create({ name: 'Hafez' });
  // exec: false
  const users = await User.find({ name: 'Hafez' }).setOptions({ exec: false });

  assert.ok(users.length, 1);

  console.log(mongoose.version);
  console.log('All assertions passed.');
}
```
### Mongoose v5.13.14
```
5.13.14
All assertions passed.
```

### Mongoose v6.0.0
```
MongooseError: Query was already executed: User.find({ name: 'Hafez' })
    at model.Query._wrappedThunk [as _find] (mongoose\lib\helpers\query\wrapThunk.js:21:19)
    at mongoose\node_modules\kareem\index.js:370:33
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  originalStack: 'Error\n' +
    '    at model.Query._wrappedThunk [as _find] (mongoose\\lib\\helpers\\query\\wrapThunk.js:25:28)\n' +
    '    at mongoose\\node_modules\\kareem\\index.js:370:33\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:78:11)'
}
```

**Comment by kfitzgerald** [comment] 2022-03-19 23:12
> I couldn't find a reference to the exec option in the [setOptions docs](https://mongoosejs.com/docs/api/query.html#query_Query-setOptions) anywhere.
Do you happen to know where I can find more information about it?

It was some old app-specific logic, that had nothing to do with Mongoose. The old logic would strip specific options out and pass the rest to `setOptions`. The legacy code used `exec` to conditionally execute the query (true) or return the query without executing it (false). That logic was removed some time ago, but various unit tests still carried the exec:false option, which caused the issue. Interestingly, the neglected `exec` option did not pose a problem in Mongoose 5.8.9, the previously used version in the app.

Luckily, it wasn't Mongoose's fault at all, rather poor handing of my own app tests.

**Comment by AbdelrahmanHafez** [comment] 2022-03-19 23:20
Thanks for the clarification.

Do you happen to be working with OP on the same project? It would be an interesting coincidence if you're not working on the same project and had the same case.

**Comment by kfitzgerald** [comment] 2022-03-19 23:35
@AbdelrahmanHafez Nope, though the line in their example:
```
  // several lines of query builder here, basically handling pagination and population
```
leads me to believe there could be a similar issue.

Though, it is a bit concerning that `setOptions` is able to execute methods on query if they happen to match, but perhaps that's intended.

**Closed** 2022-03-27 16:03 UTC
Labels: confirmed-bug

**Comment by rhythmshandlya** [comment] 2023-01-01 13:51
I have the same confusion, If anyone can clear the air it would be a great help.

According to the [documentation](https://mongoosejs.com/docs/queries.html#queries-are-not-promises)  a query is different from a promise 
```
const q = MyModel.updateMany({}, { isDeleted: true }, function() {
  console.log('Update 1');
});

q.then(() => console.log('Update 2'));
q.then(() => console.log('Update 3'));
```
However, in practice this gives an error:

```
MongooseError: Query was already executed: geeksforgeeks.findOne({ age: { '$gt': 18, '$lt': 60 } })
    at model.Query._wrappedThunk [as _findOne] (/home/rhythm/Documents/mongoose/node_modules/mongoose/lib/helpers/query/wrapThunk.js:23:19)
    at /home/rhythm/Documents/mongoose/node_modules/kareem/index.js:494:25
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  originalStack: 'Error\n' +
    '    at model.Query._wrappedThunk [as _findOne] (/home/rhythm/Documents/mongoose/node_modules/mongoose/lib/helpers/query/wrapThunk.js:27:28)\n' +
    '    at /home/rhythm/Documents/mongoose/node_modules/kareem/index.js:494:25\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)'
}
```
