### ISSUE TITLE
[5.9.15] Nested populate fails if populate is string

### ISSUE THREAD

**Issue by eusonlito** [Automattic/mongoose#9064] opened 2020-05-27 20:47 UTC
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Upgrade from `5.9.14` to `5.9.15` breaks nested populate (breaks also on version `5.9.16`).

**If the current behavior is a bug, please provide the steps to reproduce.**

Working populate nested on `5.9.14`:

```js
Post.find().populate([
    {
        path: 'category',
        select: ['code', 'name', 'enabled']
    }, {
        path: 'page',
        populate: [
            {
                path: 'modules',
                populate: {
                    path: 'module',
                    populate: 'type'
                }
            },

            {
                path: 'urls'
            }
        ]
    }
]);
```
Error is:
```
/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: options.populate.map is not a function
    at populate (/node_modules/mongoose/lib/model.js:4464:37)
    at _populate (/node_modules/mongoose/lib/model.js:4341:5)
    at cb (/node_modules/mongoose/lib/model.js:4317:5)
    at promiseOrCallback (/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Function.Model.populate (/node_modules/mongoose/lib/model.js:4315:10)
    at populate (/node_modules/mongoose/lib/model.js:4467:20)
    at _populate (/node_modules/mongoose/lib/model.js:4341:5)
    at cb (/node_modules/mongoose/lib/model.js:4317:5)
    at promiseOrCallback (/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Function.Model.populate (/node_modules/mongoose/lib/model.js:4315:10)
    at cb (/node_modules/mongoose/lib/query.js:1933:17)
    at /node_modules/mongodb/lib/utils.js:731:5
    at handleCallback (/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (/node_modules/mongodb/lib/cursor.js:841:66)
    at handleCallback (/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/node_modules/mongodb/lib/cursor.js:929:16)
    at Cursor.close (/node_modules/mongodb/lib/cursor.js:948:12)
    at cursor._next (/node_modules/mongodb/lib/cursor.js:841:27)
    at handleCallback (/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/node_modules/mongodb/lib/core/cursor.js:685:38)
    at self._endSession (/node_modules/mongodb/lib/core/cursor.js:694:39)
    at Cursor._endSession (/node_modules/mongodb/lib/core/cursor.js:395:7)
    at _setCursorNotifiedImpl (/node_modules/mongodb/lib/core/cursor.js:694:10)
    at setCursorNotified (/node_modules/mongodb/lib/core/cursor.js:685:3)
    at setCursorDeadAndNotified (/node_modules/mongodb/lib/core/cursor.js:678:3)
    at nextFunction (/node_modules/mongodb/lib/core/cursor.js:839:5)
    at Cursor._next (/node_modules/mongodb/lib/core/cursor.js:202:5)
    at fetchDocs (/node_modules/mongodb/lib/cursor.js:833:16)
    at cursor._next (/node_modules/mongodb/lib/cursor.js:854:11)
    at handleCallback (/node_modules/mongodb/lib/core/cursor.js:32:5)
    at nextFunction (/node_modules/mongodb/lib/core/cursor.js:870:5)
    at self._initializeCursor (/node_modules/mongodb/lib/core/cursor.js:745:7)
    at done (/node_modules/mongodb/lib/core/cursor.js:454:7)
    at queryCallback (/node_modules/mongodb/lib/core/cursor.js:500:18)
    at executeOperation (/node_modules/mongodb/lib/core/cursor.js:550:9)
    at executeCallback (/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
    at callbackWithRetry (/node_modules/mongodb/lib/operations/execute_operation.js:118:14)
    at fn (/node_modules/mongodb/lib/cmap/connection_pool.js:352:13)
    at handleOperationResult (/node_modules/mongodb/lib/core/sdam/server.js:489:5)
    at MessageStream.messageHandler (/node_modules/mongodb/lib/cmap/connection.js:270:5)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:710:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
```
Updated with this nested populate `populate: 'type'` > `populate: ['type']` works as expected:

```js
Post.find().populate([
    {
        path: 'category',
        select: ['code', 'name', 'enabled']
    }, {
        path: 'page',
        populate: [
            {
                path: 'modules',
                populate: {
                    path: 'module',
                    populate: ['type']
                }
            },

            {
                path: 'urls'
            }
        ]
    }
]);
```

**What is the expected behavior?**

Do not fail with populate as string as `5.9.14` version.

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

```
$> mongoose
5.9.15

$> node -v
v10.20.1

$> mongo
MongoDB shell version v3.6.3
MongoDB server version: 3.6.3
```

**Comment by eusonlito** [comment] 2020-05-27 21:45
Previous `5.9.14` `model.js` code:

https://github.com/Automattic/mongoose/blob/dbdc417f6186c2ebc6c654db75ab549ff8236bc9/lib/model.js#L4442-L4444

Updated `5.9.15` `model.js` code:

https://github.com/Automattic/mongoose/blob/8ac42aa79daa3915dfe887b9b6256f362bd377d2/lib/model.js#L4460-L4470

**Comment by vkarpov15** [comment] 2020-06-04 19:45
I believe this is a duplicate of #9073 , so it should be fixed in v5.9.17. Sorry for the trouble :+1:

**Closed by vkarpov15** 2020-06-04 19:45 UTC

**Comment by eusonlito** [comment] 2020-06-04 19:55
No problem! (but mine was the first issue report :P)

**Comment by vkarpov15** [comment] 2020-06-11 21:49
The mistake is ours, we read #9073 before this one. Sorry for the inconvenience :+1:
