### ISSUE TITLE
Discriminator inheritance in embedded documents

### ISSUE THREAD

**Issue by mitsos1os** [Automattic/mongoose#3879] opened 2016-02-12 17:49 UTC
Hi there,
It would be great if the inheritance of schemas could work independently from the model (discriminator) function.
This could be useful in cases such as when you want an embedded document array in a model that can host any kind of inherited schemas, that upon loading, they would be instantiated to the correct type according to their discriminatorKey.
So if I take the Events model example from the discriminator guide page, we could have a field in a model with type of [EVENTSGENERIC] that upon loading of the parent document, each element of the embedded document array would be loaded using either Event schema or ClickEvent schema based on their 'kind' key.

**Comment by vkarpov15** [comment] 2016-02-14 19:36
Duplicate of #1856, track progress on this feature there.

**Closed by vkarpov15** 2016-02-14 19:36 UTC
