### ISSUE TITLE
CastError: Cast to ObjectId failed for value "XXX" at path "_id" for model "XXX"

### ISSUE THREAD

**Issue by ramya-Senthamaraikannan** [Automattic/mongoose#10208] opened 2021-05-05 12:53 UTC
**Do you want to request a *feature* or report a *bug*?**
Requesting a feature

**What is the current behavior?**
_id is only accepting ObjectId even if we override it with string

**What is the expected behavior?**
It need _id to accept strings rather than ObjectId

**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**
String in _id is supporting in Mongoose version - 5.12.6, which we are using. But it is not supported in Mongoose 5.12.7

**Comment by IslandRhythms** [comment] 2021-05-05 14:32
Please provide a code sample.

**Comment by ramya-Senthamaraikannan** [comment] 2021-05-06 05:09
_**Issue 1:**_
Sample data:
{ "_id" : "ejeLoP_FH1620208025781", firstName: "xxxx", lastName : "yyyy" }

after installing the latest version, any updates to this collection throws an error
"CastError: Cast to ObjectId failed for value "XXX" at path "_id" for model "XXX""

**_Issue 2:_**
Sample data:
const mongoose = require("mongoose");
const schema = new mongoose.Schema({ _id:String, firstName: String, lastName: String });

Inserting a new Record, the result is
{
_id : ObjectId("609269995b2e888426d019ef"),
firstName: "xxxx",
lastName : "xxxx"
}

But the expected result is,
{
_id : "609269995b2e888426d019ef",
firstName: "xxxx",
lastName : "xxxx"
}


we have our own logic to generate the _id as a String, which is not happening. Instead, it is creating its own ObjectId.
This is only happening after the latest release.

**Comment by IslandRhythms** [comment] 2021-05-06 14:45
```
const mongoose = require('mongoose');
const {Schema} = mongoose;
const testSchema = new Schema({
    _id:String,
    firstName: String,
    lastName: String
});
const Test = mongoose.model('Test', testSchema);

async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useCreateIndex: true,
        useUnifiedTopology: true,
        useFindAndModify: true,
        useNewUrlParser: true,
    });
    await mongoose.connection.dropDatabase();
    console.log(await Test.create({_id:"ejeLoP_FH1620208025781", firstName: "Test"}));
    console.log(await Test.create({_id: "609269995b2e888426d019ef"}))
    console.log(await Test.find());
    await Test.find().updateOne({lastName: 'Testerson'});
    console.log(await Test.find());
}

test();

```

**Comment by ramya-Senthamaraikannan** [comment] 2021-05-07 09:36
const mongoose = require('mongoose');
const { Schema } = mongoose;
const ObjectId = mongoose.Types.ObjectId;


// having _id in a separate schema and we are trying to extend in all the other schemas
const UniqueObjectId = new Schema({
    _id: {
        type: String,
        default: function () {
            return new ObjectId().toString()
        }
    }
})

// **_Schema 1:_**
const testSchema = new Schema({
    firstName: String,
    lastName: String
});

testSchema.add(UniqueObjectId)
const Test = mongoose.model('Test', testSchema);

// **_Schema 2:_**
const testSchema2 = new Schema({
    location: String,
    gender: String
});

testSchema2.add(UniqueObjectId)
const Test2 = mongoose.model('Test2', testSchema2);


async function test() {
    await mongoose.connect('mongodb://localhost:27017/test', {
        useCreateIndex: true,
        useUnifiedTopology: true,
        useFindAndModify: true,
        useNewUrlParser: true,
    });
    await mongoose.connection.dropDatabase();
    console.log(await Test.create({_id:"ejeLoP_FH1620208025781", firstName: "Test"}));
    console.log(await Test.create({_id: "609269995b2e888426d019ef"}))
    console.log(await Test.find());
    await Test.find().updateOne({lastName: 'Testerson'});
    console.log(await Test.find());
}

test();

while running, an error occurred
Exception has occurred: ValidationError: Test validation failed: _id: Cast to ObjectId failed for value "ejeLoP_FH1620208025781" at path "_id"

How to handle this case??

**Comment by IslandRhythms** [comment] 2021-05-07 16:08
The problem is that its not a valid _id string. It has to be either 12 byte binary string, or a 24 hex byte string.
`ejeLoP_FH1620208025781` is neither

**Comment by vkarpov15** [comment] 2021-05-12 17:27
The issue is due to `testSchema.add()`, we accidentally introduced a bug related to that in v5.12.7. We already fixed this with #10203, and the fix will be in v5.12.9 :+1:

**Closed by vkarpov15** 2021-05-12 17:27 UTC
Labels: can't reproduce, has repro script

**Comment by sojinsamuel** [comment] 2023-07-25 21:20
I am using mongoose in nextjs. i am also getting this similar error
```javascript
import { connectToDB } from "utils/database";
import Prompt from "app/models/prompt";

export const GET = async (req, { params }) => {
  try {
    await connectToDB();
    const prompt = await Prompt.findById(params.id).populate("creator"); // may be the prob lies here idk
    console.log("GET called", prompt); // never hits this line
    if (!prompt) return new Response("Prompt not found", { status: 404 });
    return new Response(JSON.stringify(prompt), { status: 200 });
  } catch (error) {
    console.error("GET failed:", error.message);
    return new Response("Failed to fetch the prompt :(", { status: 500 });
  }
};
```
I was trying to access the api endpoint but it always fails with a 500
```javascript
useEffect(() => {
    const getPromptDetails = async () => {
      const response = await fetch(`/api/prompt/${promptId}`);
      const data = await response.json();

      setPost({
        prompt: data.prompt,
        tag: data.tag,
      });
    };

    if (promptId) getPromptDetails();
  }, [promptId]);
 ```
Model:
```javascript
import { Schema, model, models } from "mongoose";

const PromptSchema = new Schema({
  creator: {
    type: Schema.Types.ObjectId,
    ref: "User",
  },
  prompt: {
    type: String,
    required: [true, "Prompt is required!"],
  },
  tag: {
    type: String,
    required: [true, "Tag is required!"],
  },
});

const Prompt = models.Prompt || model("Prompt", PromptSchema);
export default Prompt;
```

**Comment by vkarpov15** [comment] 2023-07-28 12:39
@sojinsamuel the string `64c03827f6ab24acffdbbd3c}` isn't something Mongoose can convert to an ObjectId. Notice the trailing curly brace.
