### ISSUE TITLE
http://plugins.mongoosejs.io is not reachable!

### ISSUE THREAD

**Issue by kumarldh** [Automattic/mongoose#5790] opened 2017-11-05 04:48 UTC
The URL http://plugins.mongoosejs.io is not reachable. I tried with https as well, no luck. Here are curl outputs
`[chetan@debian ams]$ curl -v http://plugins.mongoosejs.io`
`* Rebuilt URL to: http://plugins.mongoosejs.io/`
`*   Trying 54.175.148.120...`
`* TCP_NODELAY set`
`* connect to 54.175.148.120 port 80 failed: Connection refused`
`* Failed to connect to plugins.mongoosejs.io port 80: Connection refused`
`* Closing connection 0`
`curl: (7) Failed to connect to plugins.mongoosejs.io port 80: Connection refused`
`[chetan@debian ams]$ curl -v https://plugins.mongoosejs.io`
`* Rebuilt URL to: https://plugins.mongoosejs.io/`
`*   Trying 54.175.148.120...`
`* TCP_NODELAY set`
`* connect to 54.175.148.120 port 443 failed: Connection refused`
`* Failed to connect to plugins.mongoosejs.io port 443: Connection refused`
`* Closing connection 0`
`curl: (7) Failed to connect to plugins.mongoosejs.io port 443: Connection refused`

**Comment by vkarpov15** [comment] 2017-11-06 22:44
Duplicate of https://github.com/vkarpov15/mongooseplugins/issues/17

**Closed by vkarpov15** 2017-11-06 22:44 UTC
