### ISSUE TITLE
`mongoose` v6 (`MongoDB` v4) breaks `jest` tests

### ISSUE THREAD

**Issue by faminchik** [Automattic/mongoose#11064] opened 2021-12-09 21:53 UTC
After the migration to the 6th version of `mongoose`, my tests have started to fail.
It's because the 4th version of `MongoDB` is written in Typescript.

If I just import a random `mongoose` function (for instance, `disconnect`) in a test file and then trigger it, then there is the following error (below)

**Test file:**

``` ts
import { disconnect } from 'mongoose';

describe('should ***', () => {
    test('should ***', () => {
        disconnect();

        expect(1).toBeTruthy();
    });
});
```

The path: **node_modules\mongodb\src\bson.ts:1**

``` ts
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import type {
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/mongodb/src/bson.ts:8:12)
```

If go back to the latest 5th version (**v5.13.13**) of `mongoose`, then everything works fine. The reason is MongoDB v3 is written in JS only

The same behavior is reproduced if just create a small project from scratch with `mongoose` and jest `packages` only.

I don't know If I need to attach my `jest` and `babel` configs, since with the 5th version `mongoose` everything was fine as mentioned above.

All recommendations that I found didn't help me (like using `ts-jest` or [ECMAScript modules](https://jestjs.io/docs/ecmascript-modules) for `jest`).

If it's not related to `mongoose` or it's not an issue, then feel free to close it. But if there are some thoughts, please, share them.

____

tsconfig:

``` json
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "commonjs",
        "allowJs": true,
        "jsx": "react",
        "outDir": "dist/.tmp",
        "strict": true,
        "baseUrl": "./src/",
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "resolveJsonModule": true,
        "removeComments": true,
        "noImplicitReturns": true,
        "noUncheckedIndexedAccess": true,
        "noImplicitOverride": true,
        "skipLibCheck": true,
    },
    "include": ["src"],
    "exclude": ["node_modules"]
}
```

____

`mongoose`: **v6.1.1**
`node`: **v14.17.6**
`jest`: **v27.3.1**

**Comment by vkarpov15** [comment] 2021-12-12 02:47
Duplicate of #10844, see comments here: https://github.com/Automattic/mongoose/issues/10844#issuecomment-967297363 

In general, we strongly recommend using any testing framework other than Jest. [Read our docs on Jest for more info](https://mongoosejs.com/docs/jest.html).

**Closed by vkarpov15** 2021-12-12 02:47 UTC

**Comment by faminchik** [comment] 2021-12-13 22:06
@vkarpov15, thank you!
