### ISSUE TITLE
.populate() populates the same document as a reference instead of a new plain object

### ISSUE THREAD

**Issue by dciccale** [Automattic/mongoose#3851] opened 2016-02-03 21:19 UTC
I was hours fighting a bug, when finally I understood the issue.. let me explain (the example is pseudo-code)

Let's say I have a schema like this:
```js
Order = Schema({
  _id: // native,
  name: String,
  products: [{
    variant_id: Number,
    details: {type: ObjectId, ref: 'Product'}
  }]
});
Variants = Schema({
  _id: // native,
  variant_id: Number,
  title: String
});
Product = Schema({
  _id: // native,
  title: String,
  variants: [Variants],
  qty: Number
});
```

let's say I have this data in the db

product collection

```js
product = {
  _id: '56b2480cf69ebbde9cea46f9',
  title: 'Something',
  variants: [
    {variant_id: 1, title: 'A'},
    {variant_id: 2, title: 'B'}
  ]
}
```

order collection

```js
order = {
  name: 'whatever',
  products: [
    {variant_id: 1, details: '56b2480cf69ebbde9cea46f9', qty: 2},
    {variant_id: 2, details: '56b2480cf69ebbde9cea46f9', qty: 1}
  ]
}
```

now i do this

Order.findOne({name: 'whatever'}).populate('products.details').exec(e, order)...

now i have my order like this

```js
order = {
  name: 'whatever',
  products: [
    {
      variant_id: 1, 
      details: {
        title: 'Something',
        variants: [
          {variant_id: 1, title: 'A'},
          {variant_id: 2, title: 'B'}
        ]
      }, 
      qty: 2
    },
    {
      variant_id: 2, 
      details: {
        title: 'Something',
        variants: [
          {variant_id: 1, title: 'A'},
          {variant_id: 2, title: 'B'}
        ]
      }, 
      qty: 1
    }
  ]
}
```

now if I do this:

```js
order.products[0].details.title = 'UPDATED TITLE'

order.products[1].details.title === 'UPDATED TITLE' // true
```

so both populated products are the same reference. where I would expect them to be totally different plain objects.

Even when using `.lean()` those objects are the same reference.

**Comment by vkarpov15** [comment] 2016-02-04 20:21
Duplicate of #3258. Planning on adding support for an option to tweak this behavior in next release.

**Closed by vkarpov15** 2016-02-04 20:21 UTC
