### ISSUE TITLE
findOneAndUpdate() behavior when read preference is not 'primary'

### ISSUE THREAD

**Issue by kaspars** [Automattic/mongoose#2971] opened 2015-05-06 09:54 UTC
MyModel has read preference set to 'secondary', and I'd expect that only read-only queries will be targeting the secondary node from replica set. But apparently findOneAndUpdate() respects read preference as well.

code like this:
```
MyModel.findOneAndUpdate(query, obj, callback);
```

produces:
```
{ [MongoError: not master]
  name: 'MongoError',
  message: 'not master',
  note: 'from execCommand',
  ok: 0,
  errmsg: 'not master' }
```

I'm experiencing this after switching from mongoose 3.8.* to 4.0.2.

A quick workaround in my code:
```
MyModel.findOneAndUpdate(query, obj).read('primary').exec(callback);
```
but I'd prefer that findOneAndUpdate() is treated the same way as other write queries.

**Comment by vkarpov15** [comment] 2015-05-06 13:43
Duplicate of #2823 #2899 etc. etc. it's already fixed in master (3b16b4e87c9a0691f29c3363102ce2f5c0fa51ab) and will be fixed when 4.0.3 is released.

**Closed by vkarpov15** 2015-05-06 13:43 UTC
