### ISSUE TITLE
Randomly seeing high response time with findOne

### ISSUE THREAD

**Issue by inderpals** [Automattic/mongoose#4638] opened 2016-10-20 04:48 UTC
We have 2 node servers running. (Both process run on 2 core 4 GB RAM boxes)

Process 1 : Serves requests from client directly.
Process 2 : Is a consumer serving internal requests.

Number of queries/update per sec is almost similar in both the processes.

Sometimes we see a latency spike in Process 1 findOne queries. It goes as high as 100secs. And at the same time Process 2's findOne latency would be normal (4-10ms).

Mongo health looks fine during this latency spike period. Lock% pagefaults etc all seems fine.Plus we don't see any slow queries also running during the same time.

Process 1 does some other heavy network operation also along with mongoose queries. These heavy operation include queries to redis/couchbase + some rest api calls to facebook/google etc (we use request module to do these rest calls).
But we don't see a latency spike in these requests.
We have tried restart even that fails to bring down findOne's latency. Within a minute after restart latency will jump upto >60secs.

Weird thing is this problem gets auto corrected within 5-10mins. Latencies will come back to normal.

We have experimented with pool size ,tried increasing it to 10 but no luck so far.

Can someone please guide us in debugging this issue further. What could be the next possible set of experiment that we can do to figure out the root cause of this issue.
If you need any data from my side please let me know.

Node Version :- v0.10.29 Mongoose version :- 4.6.3

**Comment by vkarpov15** [comment] 2016-10-22 20:22
Pool size would be my first guess. Is process 1 only doing lightweight findOne queries or does it do some heavy aggregation queries on startup? Alao, how long does it take mongoose to connect?

**Comment by inderpals** [comment] 2016-10-23 05:17
All findOne queries are lightweight.
The other thing that we noticed is Process 1 gets stuck only when there is burst of request and will return to its normal state after 10-15 mins.

**Comment by vkarpov15** [comment] 2016-10-26 00:31
Hmm how exactly are you measuring your mongodb latency?

**Comment by djanowski** [comment] 2017-01-13 22:56
Another probable duplicate of #4513.

**Closed** 2017-01-18 23:37 UTC
Labels: help
