### ISSUE TITLE
When querying, selecting only `_id` causes schema defaults to be added to returned document

### ISSUE THREAD

**Issue by fiznool** [Automattic/mongoose#3412] opened 2015-09-26 11:07 UTC
```
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost/tests');

var TestSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  active: {
    type: Boolean,
    default: false
  }
});

var Model = mongoose.model('TestModel', TestSchema);

Model.create({ name: 'Test', active: true }, function(err, m) {
  var query = Model.findById(m._id);
  query.select({ _id: 1 });
  query.exec(function(err, m) {
    console.log(m);
  });
});
```

This yields

```
{ _id: 56067b6bfa01c1d1399b76cb, active: false }
```

Although I only asked for the `_id` field, it seems that the `active` field is being added to the returned document too. Notice I've set `active: true` in the created model, so the fact this is `false` isn't correct.

Selecting something other than `_id` works fine. E.g:

```
var query = Model.findById(m._id);
  query.select({ name: 1 });
  query.exec(function(err, m) {
    console.log(m);
  });
```

Yields:

```
{ _id: 56067b442204666739d89f0b, name: 'Test' }
```

**Comment by vkarpov15** [comment] 2015-10-05 13:39
This looks to be a duplicate of #3407, that fix also makes your script output the correct value. The fix is already in master (cf8c8da503f3d946b87a700a695c7da395870304) and will be released with 4.1.10 later today.

**Closed by vkarpov15** 2015-10-05 13:39 UTC
