### ISSUE TITLE
ts bug: toConstructor(): typeof Query<ResultType, DocType, THelpers, RawDocType>;

### ISSUE THREAD

**Issue by simllll** [Automattic/mongoose#12688] opened 2022-11-14 09:51 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.7.2

### Node.js version

16.x

### MongoDB server version

5.x

### Typescript version (if applicable)

4.8.4

### Description

somehow this fails now suddenly:
../../node_modules/mongoose/types/query.d.ts(619,34): error TS1144: '{' or ';' expected.
../../node_modules/mongoose/types/query.d.ts(619,45): error TS1005: '>' expected.
../../node_modules/mongoose/types/query.d.ts(619,77): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,19): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,41): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,50): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,73): error TS1005: '(' expected.
../../node_modules/mongoose/types/query.d.ts(622,114): error TS1109: Expression expected.
../../node_modules/mongoose/types/query.d.ts(622,138): error TS1005: '(' expected.

the change was made already some weeks ago, but the line is definitly wrong:

toConstructor(): typeof Query<ResultType, DocType, THelpers, RawDocType>;

Query is already a Class and therefore typeof should just get removed.

![image](https://user-images.githubusercontent.com/5757263/201628524-299a3116-57a7-47be-9307-5f3e9c64f08b.png)

change line 619 to 
`toConstructor(): Query<ResultType, DocType, THelpers, RawDocType>;`

fixes it

### Steps to Reproduce

just open the query.d.ts file in your favourite IDE :)

**Comment by suits-at** [comment] 2022-11-16 15:26
I also have the same problem, downgrading to 6.7.1 does help for me. I think it has to do with this commit: https://github.com/Automattic/mongoose/commit/86ca62894f5e5a528f924910acabc3d85483ba9c. So reverting to 6.7.1 does change this line back to `toConstructor(): typeof this;` instead of deleting `typeof`

**Comment by hasezoey** [comment] 2022-11-21 10:49
Possibly a duplicate of #12529

though i still dont understand why this error occurs, because i cannot reproduce it in any project and from what i can tell, the syntax is correct

---

@simllll did you already confirm the following things (if yes, could you also provide them?):
- `tsc --version` actually prints `4.8.4` (or higher)
- re-install `node_modules`
- look for `yarn why mongoose` / `npm ls mongoose` and see if the latest version is actually installed (and not duplicated)
- (in case typescript is not correct): `yarn why typescript` / `npm ls typescript`

**Comment by simllll** [comment] 2022-11-21 11:30
Hi @hasezoey, it's indeed strange... 

i was looking into it again , and tested different typescript versions.

I need to go deeper why it's happening on our side, as we actually have tsc 4.8.4 everywhere, but my result shows that it only happens with tsc < 4.7.

tsc 4.6.4: $ npx tsc-files --noEmit types/query.d.ts  FAILS
tsc 4.7.x: $ npx tsc-files --noEmit types/query.d.ts  WORKS
tsc 4.8.x: $ npx tsc-files --noEmit types/query.d.ts  WORKS
tsc 4.9.x: $ npx tsc-files --noEmit types/query.d.ts  WORKS

**Closed** 2022-11-23 18:07 UTC
Labels: typescript
