### ISSUE TITLE
Init Hook Not Firing 

### ISSUE THREAD

**Issue by alaboudi** [Automattic/mongoose#5623] opened 2017-09-05 14:35 UTC
I wanted to inquire whether the `init` hook actually fires when instantiating a model using `new Model()`. I am currently trying to use the pre('init') hook to validate the structure of my request that contains data that does not get saved in the database. But it seems like as though the pre('init') hook does not fire.

**hooks.js file**
```
// ......
function preInit(next) {
    let organization = this;

    // ensure that an organization has at least one admin
    let admins = _.filter(organization.users, {role: 'admin'});
    if (!admins.length) {
        let errMsg = 'An organization must have an administrator';
        return next(new Error(errMsg));
    }

    next();
}

module.exports = {preValidate, preInit};
```
**schema.js file**
`organizationSchema.pre('init', hooks.preInit);`

**Comment by koliaVasyliv** [comment] 2017-09-05 20:01
@alaboudi , hi, the init hook is fired after document is returned from mongodb but not when you are calling ``new Model()``;

**Comment by heisian** [comment] 2017-09-06 00:33
In my experience, the pre-`init` hook gets fired when one does:
```
const myModel = new Model({ ...});
await Model.save();

const myModelFetched = await Model.findById(myModel._id).exec();
// It is here that the pre-init hook is triggered
myModelFetched.someField = 'data';
await myModelFetched.save();

// Apologies for the ES6 syntax..
```

**Comment by varunjayaraman** [comment] 2017-09-11 01:32
yeah `init` here means when its fetched from the db.

**Comment by varunjayaraman** [comment] 2017-09-11 01:33
could you do the validation in a custom `validator` or a pre save or pre validate hook?

**Comment by heisian** [comment] 2017-09-11 17:20
@varunjayaraman in favor of wanting to keep the repo clean (and also being slightly but necessarily rude), I think this issue should be closed until the poster provides more information.

**Comment by alaboudi** [comment] 2017-09-11 17:40
I see. I had an exposed endpoint in which I was expecting to receive more information in the body than that is defined in the schema. I wanted to validate that the additional information prior to saving the data. I was hoping to use mongoose hooks to get this done but I am starting to think that I should be doing this as a middleware function rather than using the hooks

**Comment by heisian** [comment] 2017-09-11 17:49
@alaboudi can the issue be closed as this is not a bug or feature request? thanks

**Closed** 2017-09-12 01:30 UTC
Labels: needs clarification
