### ISSUE TITLE
BUG: Results of #save() do not match what is actually saved

### ISSUE THREAD

**Issue by joniba** [Automattic/mongoose#3658] opened 2015-12-09 09:45 UTC
Following is a function that shows the bug:

```javascript
var mongoose = require('mongoose');
var connection = mongoose.createConnection('mongodb://localhost:27017');

connection.once('open', function () {
  var schema = new mongoose.Schema({
    obj: [{}] //mongoose.Schema.Types.Mixed
  });

  var Model = connection.model('mtest', schema);
  var model = new Model({
    obj: [{ name: 'Original' }]
  });

  model.save(function (err, res) {
    console.log('result 1', res);

    Model.findOne({_id: res._id}, function (err, res) {
      res.obj[0].name = 'Modified';
      res.obj.push({ name: 'other' });
      //res.markModified('obj'); // using markModified does not help

      res.save(function (err, res) {
        console.log('result 2', res);
        connection.close();
        process.exit();
      });
    });
  })
});
```

The output of "result 2" shows "Modified" for the first item in "obj": obj: [ { name: 'Modified' }, { name: 'other' } ].
However, in the database the value of the first item is still "Original".

Note that this bug does not occur if not pushing a second item into the array.
Note also that markModified does resolve the issue.
Lastly, note that we use an array of empty objects types in the schema because in reality this use case deals with with schemas that inherit from each other, so no single schema can be used here.

**Comment by vkarpov15** [comment] 2015-12-09 15:24
`markModified('obj')` should work here but apparently doesn't. However, I can confirm that `markModified('obj.0');` works just fine in the above case, so you can use that as a workaround.

**Comment by vkarpov15** [comment] 2015-12-09 16:05
Yeah unfortunately there's no good fix for this issue, because mongoose can't pick up changes to mixed type fields automatically. Because of that, `markModified()` doesn't know there's anything other than a push. I'd recommend just doing:

```javascript
      res.set('obj.0.name', 'Modified');
      res.obj.push({ name: 'other' });

      res.save(function (err, res) {
        console.log('result 2', res);
        connection.close();
        process.exit();
      });
```

That works. Typically it's better to use `.set()` for mixed types and arrays, [fewer edge cases that way](http://mongoosejs.com/docs/faq.html)

**Closed by vkarpov15** 2015-12-09 16:05 UTC
