### ISSUE TITLE
Use of middleware with arrow functions (ES6)

### ISSUE THREAD

**Issue by abekim** [Automattic/mongoose#4816] opened 2016-12-18 02:49 UTC
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Many apologies if this has already been addressed in a separate thread; my GoogleFu has failed to produce any meaningful reference on this topic.

The `pre` middleware doesn't seem to work as expected due to lexical binding of the `this` variable when using [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) (ES6).

As described in the [middleware documentation](http://mongoosejs.com/docs/middleware.html), one references the document being processed using `this`. An example of a complex validation may look something like: 

```javascript
schema.pre('validate', function(next) {
  runComplexValidation(this.complexAttribute);
  // do other things
  next();
});
```

However, the same implementation using arrow functions doesn't work:

```javascript
schema.pre('validate', (next) => {
  runComplexValidation(this.complexAttribute); // this.complexAttribute doesn't exist; sadness!
  // do other things
  next();
});
```

Is there a plan to support ES6's arrow function syntax in the future? Perhaps an extension of the middleware function signature to accept a reference to the document object may be an easy stopgap solution? For example:

```javascript
// Unsure what a reasonable way to extend to parallel middlewares is...
schema.pre('validate', (next, doc) => {
  runComplexValidation(doc.complexAttribute); // Happiness!
  // do other things
  next();
});
```

Would love others' insights on this! Thanks in advance for any insight!

**Please mention your node.js, mongoose and MongoDB version.**

```
$ node -v; npm -v; mongo --version
v7.2.1
3.10.9
MongoDB shell version v3.4.0
git version: f4240c60f005be757399042dc12f6addbc3170c1
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```

**Comment by vkarpov15** [comment] 2016-12-19 01:50
Duplicate of numerous issues including #3619, #3695, #3333, etc. Follow issue #3379 for updates.

**Closed by vkarpov15** 2016-12-19 01:50 UTC
