### ISSUE TITLE
Auto remove empty object in condition

### ISSUE THREAD

**Issue by adostal** [Automattic/mongoose#13086] opened 2023-02-26 11:52 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

6.9.2

### Node.js version

19.0.1

### MongoDB server version

6

### Typescript version (if applicable)

4.9.5

### Description

I use casl.js in my project.
The conditions themselves are generated automatically from the @casl/mongoose library
The problem is that newer versions of mongoose remove the empty object that is sometimes part of the condition.
After updating mongoose from **6.7.5** to **6.9.2**, the empty object started to be removed.

If it would be possible to set this behavior in the mongoose configuration, that would be great.

### Steps to Reproduce

```typescript
// query for all people (conditions are from casl.js - sometimes with empty object)
const people = PeopleModel.find({$or: [
  {},
  {type: "xxx"},
  .... other conditions
]})
```

### Expected Behavior

In version 6.9.2 is finally condition without empty object {}:
```
condition: $or: [{"type": "xxx", ... other conditions}]
```

In version 6.7.5 is finally condition with empty object {}:
```
condition: $or: [{}, {"type": "xxx", ... other conditions}]
```

**Comment by vkarpov15** [comment] 2023-02-26 18:46
This looks like it is caused by https://github.com/Automattic/mongoose/pull/12898 . We merged this issue because we thought that `$or: [{}]` is likely indicative of a potential bug where `strictQuery` removed some fields. However, you're right, there are some valid use cases for this behavior. We'll revert #12898 in 6.10.1.

**Closed** 2023-02-28 15:41 UTC
Labels: confirmed-bug
