### ISSUE TITLE
Feature request: let mongoose default to global.Promise

### ISSUE THREAD

**Issue by kdekooter** [Automattic/mongoose#5687] opened 2017-10-03 15:46 UTC
With promises being a first class citizen on the latest node versions it would be nice if mongoose defaults to the native promise, instead of having to configure that explicitly.

**Comment by vkarpov15** [comment] 2017-10-04 23:32
Duplicate of https://github.com/Automattic/mongoose/issues/2917

**Closed by vkarpov15** 2017-10-04 23:32 UTC
