### ISSUE TITLE
InterSchemaType does not infer field with type: Array of ObjectId, String, etc

### ISSUE THREAD

**Issue by darwin403** [Automattic/mongoose#12206] opened 2022-08-03 04:21 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Mongoose version

^6.5.0

### Node.js version

16.13.1

### MongoDB server version

6.x

### Description

Schema field of type of **Array of Objects, String, etc.** does not return the expected Schema type.

### Steps to Reproduce

```js
const campaignSchema = new Schema(
  {
    managers: [
      {
        type: Schema.Types.ObjectId,
        trim: true,
        ref: "User",
      },
    ],
  },
  { timestamps: true }
);

type ICampaign = InferModelType<ICampaignSchema>;  

// returned type
//  {
//   managers: {
//        type?: Types.ObjectId | undefined;
//        trim?: unknown;
//        ref?: unknown;
//    }[];
// }
```
![Screenshot-from-2022-08-03-09-45-35](https://user-images.githubusercontent.com/65121170/182523175-666d3d65-537d-4f91-a52a-d81a6e17425f.png)

### Expected Behavior

```js
type ICampaign = InferModelType<ICampaignSchema>;  

// should return type
// {
//     managers: Types.ObjectId [];
// }
```

**Comment by IslandRhythms** [comment] 2022-08-08 18:56
Duplicate of #12205

**Closed by IslandRhythms** 2022-08-08 18:56 UTC
