### ISSUE TITLE
.toObject is not function with findOneAndUpdate -- Information for Others

### ISSUE THREAD

**Issue by ptariche** [Automattic/mongoose#7749] opened 2019-04-25 20:45 UTC
".toObject is not function" with findOneAndUpdate

#### Information for others debugging: 

https://github.com/Automattic/mongoose/pull/7736/files is a breaking change. 

**Resolution**: Set '{ useFindAndModify: false }' in options -- https://mongoosejs.com/docs/deprecations.html#-findandmodify.

This will resolve the issue.

#### Related

https://github.com/Automattic/mongoose/issues/7734
https://github.com/Automattic/mongoose/issues/7735

**Comment by Fonger** [comment] 2019-04-25 23:00
I can't reproduce the issue with the following script.
Can you provide a repro script?

```js
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

mongoose.set('debug', true);


const userSchema = new Schema({
  name: String
});

userSchema.methods.testFunc = function(){}
const User = mongoose.model('User', userSchema);

mongoose.connect('mongodb://localhost:27017/test-map').then(async () => {

  const newUser = new User({
    name: 'Fonger'
  });

  await newUser.save();

  const editUser = await User.findOneAndUpdate({name: 'Fonger'}, { name: 'Fonger2'}, { new: true });
  console.log(editUser.toObject());
  editUser.set('name', 'Fonger3');
  await editUser.save();
  console.log(editUser.toObject());
});
```

**Comment by ptariche** [comment] 2019-04-25 23:34
Last tested on mongoose": "^5.5.3". Let me write something up as a test and get back to you. We resolved the issue by setting  useFindAndModify: false with Node 10.15.3 and moving to 5.5.4

**Comment by Fonger** [comment] 2019-04-26 02:50
I’m assuming you’re using 5.5.3 to reproduce this bug.

The PR you mentioned is merged in 5.5.4 so it’s not a breaking change.

Instead, it fixed the breaking change in 5.5.3.

**Comment by kksrini89** [comment] 2019-04-26 05:20
> ".toObject is not function" with findOneAndUpdate
> 
> #### Information for others debugging:
> https://github.com/Automattic/mongoose/pull/7736/files is a breaking change.
> 
> **Resolution**: Set '{ useFindAndModify: false }' in options -- https://mongoosejs.com/docs/deprecations.html#-findandmodify.
> 
> This will resolve the issue.
> 
> #### Related
> #7734
> #7735

But I got the same issue with mongoose: "^5.0.11".

**Comment by vkarpov15** [comment] 2019-04-29 18:54
@kksrini89 v5.5.3 does match `^5.0.11`, so you may be running 5.5.3. Try explicitly upgrading to `"mongoose": "^5.5.4"`

**Closed by vkarpov15** 2019-04-29 18:54 UTC

**Comment by AkyunaAkish** [comment] 2019-12-18 16:32
I was having a similar issue getting the obj.toObject is not a function with findOneAndUpdate, in my case I was using a full document returned from mongoose to update. The full document contained properties I did not need during the update, so instead I had to just use the document._doc property.

```
    let Doc = await Models.User.findOne({
      _id: user._id
    })

    if (Doc._doc) {
      Doc = Doc._doc <------ This helped me in my case ---------
    }

    const mergedData = mergeDeepLeft(newValues, Doc) // mergeDeepLeft is from package: ramda/src/mergeDeepLeft

    const updatedTeam = await Models.User.findOneAndUpdate(
      { _id: user._id },
      mergedData,
      { new: true }
    )
```

I'm on version 5.8.1 of mongoose and 3.3.5 of the mongodb npm packages
