### ISSUE TITLE
ensureIndex is deprecated starting with MongoDB 3.0.0

### ISSUE THREAD

**Issue by Kuzmin** [Automattic/mongoose#3280] opened 2015-08-17 20:02 UTC
I tried searching the issues but I couldn't find anything about it, and I saw that the code still uses ensureIndex, so I thought I should give a heads up about this deprecation in MongoDB. :)

http://docs.mongodb.org/manual/reference/method/db.collection.ensureIndex/

**Comment by adamreisnz** [comment] 2017-08-16 20:39
I think this can just be replaced by `createIndex` from what it seems. Could probably be addressed in 4.x still as it wouldn't be a breaking change.

**Comment by vkarpov15** [comment] 2017-08-27 05:34
Yeah since `createIndex` is just an alias for `ensureIndex` (see [docs](https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/) ) we'll switch over in 4.x.

**Comment by djanowski** [comment] 2017-10-06 02:48
This breaks for us. Apparently `createIndex` is not just an alias for `ensureIndex`?

We get `Index with name: ... already exists with different options` even though nothing changed.

MongoDB version is 3.2.10 (Compose).

**Comment by adamreisnz** [comment] 2017-10-06 02:56
That's strange, because it is supposed to be:

https://docs.mongodb.com/manual/reference/method/db.collection.ensureIndex/

> db.collection.ensureIndex(keys, options)
> Deprecated since version 3.0.0: db.collection.ensureIndex() is now an alias for db.collection.createIndex().

**Comment by vkarpov15** [comment] 2017-10-07 01:17
@djanowski sorry for the trouble. Can you provide me some more information on how the indexes were created? And also open a separate issue?

As a workaround, you can [disable `autoIndex`](http://mongoosejs.com/docs/guide.html#autoIndex) and just rely on your indexes as they are right now.

**Comment by bazineta** [comment] 2017-10-07 17:51
In our case, we did see the same thing that @djanowski reports after the update, caused by a 'safe' option being set in the index options. See #3439. Since this shows up only in development for us, we just dropped the indices and allowed them to auto-create again.

However, this might be indicative of a more serious issue, if the commentary in this SE discussion about 3.7 refusing to restore if 'safe' is present is true:

https://stackoverflow.com/questions/31464332/in-a-mongodb-index-what-do-the-options-safe-and-force-mean

**Comment by vkarpov15** [comment] 2017-10-10 00:53
Considering that MongoDB 3.6 is not out yet, I doubt there's anything that's set in stone for 3.8, so I don't trust that comment re: 3.7. But please provide code samples to help us reproduce this :+1:

**Comment by bazineta** [comment] 2017-10-10 02:54
@vkarpov15 The indices in question all had `safe: null` set, placed there by by an autoindex using mongoose < #3439. I'm not sure how to repro on the levels we're at now, frankly.

**Comment by vkarpov15** [comment] 2017-10-14 15:13
I can confirm that the `safe` option isn't important for indexes, you can remove it. Sorry about the inconvenience.

**Comment by codeback** [comment] 2017-10-16 14:11
Hi @djanowski, 

I am facing with the same problem "Index with name: ... already exists with different options" and I have the MongoDB in Compose too (version 3.2.10).

My problem has started when I've upgraded Mongoose from 4.8.5 to 4.12.2. 

Thanks in advance

**Comment by vkarpov15** [comment] 2017-10-17 19:50
Please provide code samples @codeback

**Comment by codeback** [comment] 2017-10-19 13:59
Hi @vkarpov15, thank you for your response. 

Mongoose Options:
```
options: {
            autoIndex: false,
            auth: { authdb: 'admin' },
            user: '<user>'
            pass: '<password>',
            db: {
                safe: true
            },
            mongos: {
                ssl: true,
                sslValidate: true,
                sslCA: ca
            }
        }
```

Mongoose connection:
```
...
db = mongoose.createConnection(uri, options);
...
```
Model:
```
...
const ProviderSchema = new mongoose.Schema({
    _modifiedAt: { type: Date, default: Date.now },
    _createdAt: { type: Date, default: Date.now },
    _modifiedBy: { type: Schema.Types.ObjectId, ref: 'User'},
    _createdBy: { type: Schema.Types.ObjectId, ref: 'User'},
    kind: { type: String, enum: kindOptions, required: true },
    domain: { type: String, required: true, unique: true },
    ...
});

// Indexes
ProviderSchema.index({ kind: 1});
ProviderSchema.index({ domain: 1});

// Virtuals

// Validations

const Provider = db.model('Provider', ProviderSchema);
```

**Comment by Moeriki** [comment] 2017-10-24 15:47
I am also running into `IndexOptionsConflict `.

Looking at the code of `node-mongodb-driver` it is clear that it is not a simple alias.

**createIndex**

https://github.com/mongodb/node-mongodb-native/blob/3.0.0/lib/db.js#L1029

**ensureIndex**

https://github.com/mongodb/node-mongodb-native/blob/3.0.0/lib/db.js#L1113

**Comment by adamreisnz** [comment] 2017-10-24 19:14
@Moeriki I've raised an issue for that on their JIRA boards:

https://jira.mongodb.org/browse/NODE-1167

Wonder what they come back with, because this is clearly a conflict between the docs and the code. I would trust the docs thought, if they state `ensureIndex` is deprecated. It will probably be removed in a future version.

**Comment by rlidwka** [comment] 2017-10-25 15:12
It's worth pointing out that MongoDB driver still uses `ensureIndex` in various places.

Fun side effect: using mongodb's GridFS on a connection created by mongoose causes `ensureIndex() is deprecated in Mongoose >= 4.12.0` warning to appear because of [this code](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/gridfs/grid_store.js#L217-L231) inside mongodb driver.

**Comment by vkarpov15** [comment] 2017-10-30 18:24
You're right, we'll change back to `ensureIndex()` for now and undeprecate until I can figure out what's going on on the mongodb side. Sorry about the trouble, I mistakenly assumed the docs were accurate without actually verifying.

**Comment by adamreisnz** [comment] 2017-10-30 19:22
Goes to show how important it is to have accurate documentation, if a lot of people rely on your code :)

I wonder what they'll come back with at MongoDB.

**Closed** 2017-10-31 18:12 UTC
