### ISSUE TITLE
pre, post middleware are not executed on findByIdAndUpdate

### ISSUE THREAD

**Issue by skotchio** [Automattic/mongoose#964] opened 2012-06-15 18:32 UTC
Because a findAndUpdate method is presented to cut down the following code:

     Model.findById(_id, function (err, doc) {
          if (doc) {
              doc.field = 'value';
              doc.save(function (err) {
                     // do something;
              });
          }
     });

to this:

    Model
       .findByIdAndUpdate(_id, {$set: {field: 'value'}}, function (err, doc) {
            // do something 
        });

We need to use pre, post middleware exactly the same. At now pre, post middleware are not executed when I make findByIdAndUpdate.

**Comment by vkarpov15** [comment] 2015-01-02 15:59
The 3.9.x branch has support for pre and post hooks for `find` and `findOne` - should be easy to add support for `findOneAndUpdate` and `update`.

**Comment by theGlenn** [comment] 2015-01-06 11:04
Is this feature merged ?

**Comment by vkarpov15** [comment] 2015-01-06 17:02
So the `pre('findOneAndUpdate')` and `post('findOneAndUpdate')` hooks are in master, there isn't an update hook just yet.

**Comment by krzysztofantczak** [comment] 2015-02-17 08:47
So does it triggers pre-save after .update() now?

**Comment by vkarpov15** [comment] 2015-02-17 17:08
No. There is a separate `update()` hook for `Query.update()`. Save hooks are distinct from query hooks.

**Comment by karlstanton** [comment] 2015-02-18 03:27
@vkarpov15 Can you please link to the supporting documentation for the update hook? Any word on when `pre('findOneAndUpdate')` and `post('findOneAndUpdate')` will hit a release?

**Comment by vkarpov15** [comment] 2015-02-18 18:16
@karlstanton use 4.0.0-rc2, `npm install mongoose@unstable` :)

**Comment by neverfox** [comment] 2015-02-27 03:32
Hmm, I'm using 4.0.0-rc2, but my post save hook isn't firing after a `findOneAndUpdate`.

**Comment by neverfox** [comment] 2015-02-27 03:54
```javascript
'use strict';

var Promise  = require('bluebird');
var co       = require('co');
var mongoose = Promise.promisifyAll(require('mongoose'));

var counterSchema = new mongoose.Schema({
	total: {
		type:    Number,
		default: 0
	}
});

counterSchema.post('findOneAndUpdate', function (doc) {
	console.log(doc.total);
});

var Counter = mongoose.model('Counter', counterSchema);

co(function *() {
	yield mongoose.connectAsync(process.env.MONGODB_URI);
	console.log('Connected');
	let counter = yield Counter.createAsync({});
	console.log(`${counter.total}`);
	for (let i = 0; i < 10; i++) {
		yield Counter.findOneAndUpdateAsync({ _id: counter.id }, { $inc: { total: 1} });
	}
});
```

```
Connected
0
0
1
2
3
4
5
6
7
8
9
```
Seems like it's a step behind. What am I missing?

**Comment by neverfox** [comment] 2015-02-27 03:59
AH, the `new` flag default breaking change.

**Comment by syzer** [comment] 2015-02-27 06:41
@neverfox :)

**Comment by vkarpov15** [comment] 2015-02-27 20:16
Yeah @neverfox good catch. This change is [documented in the release notes](https://github.com/LearnBoost/mongoose/wiki/4.0-Release-Notes#backwards-breaking-changes) and you can see more discussion why this was changed in #2262.

The reason is that `new` is false by default in the mongodb node driver, the mongodb shell, the actual mongodb server, etc. and wrapper layers setting non-standard defaults makes life difficult for devs. My canonical example of a module that gets this horribly wrong is [gulp-uglify](https://www.npmjs.com/package/gulp-uglify), which overrides a bunch of uglify-js's defaults.

**Comment by CaptainStaplerz** [comment] 2015-05-04 05:38
I see that the issue is closed, but is the functionality in place in version 4.0.2 out is it just still in the unstable version? It doesn't seem to execute on findOneAndUpdate with Scema.pre('update') or Schema.pre('findOneAndUpdate') with the 4.0.2 version. Am I missing something that I have to pass to the function?

**Comment by vkarpov15** [comment] 2015-05-04 13:14
How are you declaring the pre hook @CaptainStaplerz ?

**Comment by honitus** [comment] 2015-05-04 18:30
Is findOneAndUpdate middleware available in 4.0.2? I upgraded from 3.8 to latest mongoose 4.0.2 to use this and the middlware Document.schema.post('findOneAndUpdate', function (doc) is not getting triggered like save() or remove()

**Comment by vkarpov15** [comment] 2015-05-04 18:49
@honitus show me your code

**Comment by honitus** [comment] 2015-05-04 19:13
@vkarpov15  - Thanks for quick response, here you go

// Updates an existing Blog in the DB, adds comment
exports.update = function(req, res) {

Blog.findOneAndUpdate(
     {"_id": req.body._id,},
      {"$push": {"comments": buildComment}},
     {safe: true, upsert: true}, function (err, workspace) {
      if (err) {
         return handleError(res, err);
       }
       return res.send(200);
      }
   );

}



/**
 * Broadcast updates to client when the model changes
 */

'use strict';

var Blog= require('./blog.model');

exports.register = function(socket) {
//SAVE WORKS
  Blog.schema.post('save', function (doc) {
    onSave(socket, doc);
  });

// IS NOT TRIGGERED :(
 Blog.schema.post('findOneAndUpdate', function (doc) {
    onComment(socket, doc);
  });

  Blog.schema.post('remove', function (doc) {
    onRemove(socket, doc);
  });
}

//SAVE WORKS when a new blog is created
function onSave(socket, doc, cb) {
  socket.emit('blog:save', doc);
}

// IS NOT TRIGGERED :(
function onComment(socket, doc, cb) {
  socket.emit('blog:findOneAndUpdate', doc);
}

function onRemove(socket, doc, cb) {
  socket.emit('blog:remove', doc);
}

**Comment by honitus** [comment] 2015-05-04 20:38
@vkarpov15  Thanks for reopening. Does this mean hook for findOneAndUpdate isn't there in 4.0.2 and you plan to include in 4.0.3.

**Comment by CaptainStaplerz** [comment] 2015-05-04 20:44
@vkarpov15 Here's the code where I declare the hooks:

...
var TodoSchema = new mongoose.Schema({
  name: {type: String, required: true},
  note: String,
  completed: {type: Boolean, default: false},
  updatedAt: {type: Date, default: Date.now},
  user: {
    type: mongoose.Schema.ObjectId,
    ref: 'Users'
  }
});
...
// Not executed
TodoSchema.pre('update', function() {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
});
// Not executed
TodoSchema.pre('findOneAndUpdate', function() {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
});

And here's where I call the update:
...
router.route('/:id')
.put(function(req, res, next) {
  TodoModel.findOneAndUpdate({_id: req.params.id, user: req.user.id}, req.body, {new: true}, function(err, post) {
    if(err) return next(err);
    if(post) {
      res.status(200).json(post);
    }
    else {
      next(newSystemError(errorCodes.TODO_NOT_FOUND, undefined, req.params.id));
    }
  });
});

**Comment by vkarpov15** [comment] 2015-05-05 19:59
As far as I know the `findOneAndUpdate()` hook should be in there, if it's not working that's a bug

@CaptainStaplerz try:

```javascript
TodoSchema.pre('update', function(next) {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
  next();
});
```

Also, is the `console.log` statement executing, or is it just the Date.now() part that's giving unexpected results?

**Comment by honitus** [comment] 2015-05-05 20:02
@vkarpov15 
I changed by source coding adding the changes you made in Add implementation #964 https://github.com/Automattic/mongoose/commit/e98ef98e857965c4b2ae3339fdd7eefd2a5a9913

It works like charm now. So I think the fix is not checked into main

**Comment by vkarpov15** [comment] 2015-05-05 20:11
@honitus are you sure you're using mongoose 4.0.2? That change is in fact committed to 4.0.0 and up.

**Comment by honitus** [comment] 2015-05-05 20:13
honitus$ npm view mongoose version
4.0.2

**Comment by vkarpov15** [comment] 2015-05-05 22:02
@honitus what you're doing incorrectly is that you're adding hooks to the schema **after** compiling your model. `Model.schema.pre('remove');` is not expected to work, see ["Compiling your first model" on the model docs](http://mongoosejs.com/docs/models.html). Attach the hooks to the schema first and then things should work - that's the only difference I see between your code and our tests.

**Comment by vkarpov15** [comment] 2015-05-05 22:08
@CaptainStaplerz the only way I can find to repro your code is with an empty update. The below code works

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh964');

var TodoSchema = new mongoose.Schema({
  name: {type: String, required: true},
  note: String,
  completed: {type: Boolean, default: false},
  updatedAt: {type: Date, default: Date.now},
  user: {
    type: mongoose.Schema.ObjectId,
    ref: 'Users'
  }
});
TodoSchema.pre('update', function() {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
});
TodoSchema.pre('findOneAndUpdate', function() {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
});

var Todo = mongoose.model('Todo', TodoSchema);

Todo.update({}, { note: "1" }, function(err) {
  if (err) {
    console.log(err);
  }
  console.log('Done');
  process.exit(0);
});
```

But once you make the update empty:

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh964');

var TodoSchema = new mongoose.Schema({
  name: {type: String, required: true},
  note: String,
  completed: {type: Boolean, default: false},
  updatedAt: {type: Date, default: Date.now},
  user: {
    type: mongoose.Schema.ObjectId,
    ref: 'Users'
  }
});
TodoSchema.pre('update', function() {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
});
TodoSchema.pre('findOneAndUpdate', function() {
  console.log('------------->>>>>> update updatedAt')
  this.updatedAt = Date.now();
});

var Todo = mongoose.model('Todo', TodoSchema);

Todo.update({}, { }, function(err) {
  if (err) {
    console.log(err);
  }
  console.log('Done');
  process.exit(0);
});
```

The pre update hook no longer executes. Is this consistent with what you're seeing?

**Comment by honitus** [comment] 2015-05-05 23:53
@vkarpov15 
Model.schema.pre('remove'); is one the stubs automatically created by angular full stack
I added implementation #964 e98ef98 
All I did is add one line below
this.schema.s.hooks.wrap('findOneAndUpdate', Query.base.findOneAndUpdate,
See Line 1526 in 4.0.2 - this.model.hooks.wrap('findOneAndUpdate', Query.base.findOneAndUpdate,

Replace Line 1526 with-  this.schema.s.hooks.wrap('findOneAndUpdate', Query.base.findOneAndUpdate,
and it works.

**Comment by vkarpov15** [comment] 2015-05-06 13:40
That's by design. Mongoose is not supposed to allow modifying the schema hooks after the model has been compiled (that is, the `mongoose.model()` call), which is why that no longer works.

**Comment by CaptainStaplerz** [comment] 2015-05-06 20:38
@vkarpov15 I managed to get the hook working now with the following, it must have been a stupid typo or something else:
```javascript
TodoSchema.pre('findOneAndUpdate', function(next) {
  console.log('------------->>>>>> update updatedAt: ', this.updatedAt);
  this.updatedAt = Date.now();
  next();
});
```
However 'this' doesn't seem to refer to the updated model (but it does in the 'save' hook?), thereby this.updatedAt refers to undefined.

How do I update the 'updatedAt' -field in the 'findOneAndUpdate' -hook?

**Comment by vkarpov15** [comment] 2015-05-06 22:24
I should add more docs clarifying this - the document that's being updated may not exist in memory when you call `findOneAndUpdate`, so the `this` object refers to the **query** rather than the **document** in [query middleware](http://mongoosejs.com/docs/middleware.html). Try `this.update({ $set: { updatedAt: Date.now() } });`

**Comment by aggied** [comment] 2015-05-07 06:43
@vkarpov15 I could not get `this.update({ $set: { updatedAt: Date.now() } });` to work, but I was able to successfully update the doc on the `findOneAndUpdate` hook with this: `this._update['$setOnInsert'].updatedAt=Date.now();`.

**Comment by vkarpov15** [comment] 2015-05-07 14:41
I would highly recommend not depending on tweaking internal state like that. I'm pretty surprised that you couldn't get `this.update()` to work - can you show me what your hook looks like?

**Comment by aggied** [comment] 2015-05-07 16:38
Sure! 

`````
tagSchema.pre('findOneAndUpdate',function(next){
  var self = this;

  //NOTE THAT 'this' in the findOneAndUpdate hook refers to the query, not the document
  //https://github.com/Automattic/mongoose/issues/964

  geoData.country.findOne({'_id':self._update['$setOnInsert'].countryCode}).select('_id name cca2 cca3 ccn3').lean().exec(function(err,country){
    if (err){throw err;}
    if (!country){throw 'no coutnry';}
    self._update['$setOnInsert'].country=country;
    next();
  });
});
`````

I could obviously handle this when I initialize the document elsewhere in my app, but it's nice to have it all contained right there in Mongoose. Welcome any thoughts!

**Comment by vkarpov15** [comment] 2015-05-07 20:38
Yeah I was confused and thought you were using `update`. The below script

```javascript
var mongoose = require('mongoose');
mongoose.set('debug', true);
var util = require('util');

mongoose.connect('mongodb://localhost:27017/gh964');

var TodoSchema = new mongoose.Schema({
  name: {type: String, required: true},
  note: String,
  completed: {type: Boolean, default: false},
  updatedAt: {type: Date, default: Date.now},
  user: {
    type: mongoose.Schema.ObjectId,
    ref: 'Users'
  }
});
TodoSchema.pre('findOneAndUpdate', function() {
  this.findOneAndUpdate({}, { updatedAt: Date.now() });
});

var Todo = mongoose.model('Todo', TodoSchema);

Todo.findOneAndUpdate({}, { note: "1" }, function(err) {
  if (err) {
    console.log(err);
  }
  console.log('Done');
  process.exit(0);
});
```

Works correctly and executes the desired query:

```
Mongoose: todos.findAndModify({}) [] { '$set': { note: '1', updatedAt: new Date("Thu, 07 May 2015 20:36:39 GMT") } } { new: false, upsert: false }
Done
```

So please use

```javascript
TodoSchema.pre('findOneAndUpdate', function() {
  this.findOneAndUpdate({}, { updatedAt: Date.now() });
});
```

Instead of manually manipulating mquery's internal state - that's usually a bad idea unless you really really know what you're doing.

**Closed by vkarpov15** 2015-05-07 20:38 UTC

**Comment by agjs** [comment] 2015-06-29 18:26
Is this working or not ? Only hook that works for me is 'save', rest is completely ignored. I'm running on 4.0.6. Thanks

**Comment by vkarpov15** [comment] 2015-06-29 20:15
@agjs provide code example please.

**Comment by agjs** [comment] 2015-06-29 20:21
UserController.prototype.updateAvatar = function (req, res) {
	return new Promise(function (resolve, reject) {
		CompanyDetails.update({
			_author: req.user._id
		}, {
			avatarPath: req.files.file
		}, function (error, updated) {
			if (error) {
				reject(error);
			} else {
				resolve(updated);
			}
		});
	}).then(function (resolved) {
		res.sendStatus(204).send(updated);
	}).catch(function (error) {
		next(error);
	})

};


CompanyAvatarSchema.pre('update', function (next) {
	console.log('pre save');
	let VirtualModel = this,
		parent = this.ownerDocument(),
		PATH = path.normalize('./public/images/uploads/avatars/' + parent._id);

	mkdirp(PATH, function (error) {
		if (error) {
			next(error);
		} else {
			fs.rename(VirtualModel.path, path.join(PATH, VirtualModel.name), function (error2) {
				if (error2) {
					next(error2);
				} else {
					next();
				}
			});
		}
	});

});

**Comment by agjs** [comment] 2015-06-29 21:07
I have another pre-hook on another model with model.create and pre-save and it works normally.

With update whatsoever, It simply doesn't see the hook, doesn't even console.log it. I tried findOneAndUpdate too etc, doesn't really work... Funny thing I've went through this entire thread and as I usually do, checked official documentation and you guys claim even there that it works.

**Comment by vkarpov15** [comment] 2015-06-30 00:18
What's the relationship between CompanyAvatarSchema and CompanyDetails in the above code?

**Comment by agjs** [comment] 2015-06-30 07:48
Company details have CompanyAvatar.schema as a subdocument 

```javascript
avatarPath: {
		type: [CompanyAvatar.schema],
		required: true
	}
```

**Comment by agjs** [comment] 2015-06-30 08:28
Also, its not only pre-hook but validation gets ignored completely as well.

**Comment by vkarpov15** [comment] 2015-06-30 15:33
You're calling `CompanyDetails.update()` but the pre hook is defined on a separate schema. Query middleware doesn't fire the nested schema's `pre('update')` atm.

Also, please provide a more thorough code example for your 'validation gets ignored completely' case as well.

**Comment by agjs** [comment] 2015-07-01 10:54
Here is my company avatar schema made for validation and pre-hooks for users who are updating their profile (avatar photo): 

```javascript
'use strict';

let mongoose = require('mongoose'),
	mkdirp = require('mkdirp'),
	fs = require('fs'),
	path = require('path'),
	Schema = mongoose.Schema;

let CompanyAvatarSchema = new Schema({
	name: String,
	width: Number,
	height: Number,
	size: Number,
	type: String
});


CompanyAvatarSchema.path('type').validate(function (type) {
	return /^image\//.test(type);
}, 'Image type not allowed!');

CompanyAvatarSchema.path('size').validate(function (size) {
	return size < 5;
}, 'Image too big!');



CompanyAvatarSchema.virtual('path').set(function (path) {
	return this._path = path;
}).get(function () {
	return this._path;
});


CompanyAvatarSchema.virtual('public_path').get(function () {
	var parent = this.ownerDocument();
	var PATH = path.normalize('images/uploads/avatars/' + parent._id);
	if (this.name) {
		return path.join(PATH, this.name);
	}
});

CompanyAvatarSchema.set('toJSON', {
	getters: true
});

CompanyAvatarSchema.pre('findOneAndUpdate', function (next) {
	console.log('pre save');
	let VirtualModel = this,
		parent = this.ownerDocument(),
		PATH = path.normalize('./public/images/uploads/avatars/' + parent._id);

	mkdirp(PATH, function (error) {
		if (error) {
			next(error);
		} else {
			fs.rename(VirtualModel.path, path.join(PATH, VirtualModel.name), function (error2) {
				if (error2) {
					next(error2);
				} else {
					next();
				}
			});
		}
	});

});


let runValidatorsPlugin = function (schema, options) {
	schema.pre('findOneAndUpdate', function (next) {
		this.options.runValidators = true;
		next();
	});
};

CompanyAvatarSchema.plugin(runValidatorsPlugin);

let CompanyAvatar = mongoose.model('CompanyAvatar', CompanyAvatarSchema);
module.exports = CompanyAvatar;
```

Here is the company_details schema where company_avatar is a subdocument :

```javascript
let CompanyDetailsSchema = new mongoose.Schema({
	_author: [{
		type: Schema.Types.ObjectId,
		ref: 'CompanyAccount'
	}],
	company_name: {
		type: String,
		es_indexed: true,
		es_boost: 2.0
	},
	contact_email: {
		type: String,
		es_indexed: true
	},
	website: {
		type: String,
		es_indexed: true
	},
	country: {
		type: String,
		es_indexed: true
	},
	industry: {
		type: String,
		es_indexed: true
	},
	address: {
		type: String,
		es_indexed: true
	},
	about: {
		type: String,
		es_indexed: true
	},
	avatarPath: {
		type: [CompanyAvatar.schema],

	}
});
```

And here is update profile controller and the avatarPath which should be validated / hooked before this update performs:

```javascript
UserController.prototype.updateAvatar = function (req, res, next) {
	let updates = {
		$set: {
			avatarPath: req.files.file
		}
	};
	return new Promise(function (resolve, reject) {
		CompanyDetails.findOneAndUpdate({
			_author: req.user._id
		}, updates, function (error) {
			if (error) {
				reject(error);
			} else {
				resolve('done');
			}
		});
	}).then(function () {
		res.sendStatus(204);
	}).catch(function (error) {
		next(error);
	});

};
```

**Comment by vkarpov15** [comment] 2015-07-09 13:42
The issue is that the pre('findOneAndUpdate') middleware is defined on a nested schema. Right now, mongoose only fires query middleware for top level schemas, so middlewares defined on `CompanyDetailsSchema` will get fired re: #3125

**Comment by w3hacker** [comment] 2015-09-12 07:10
+1

**Comment by willemmulder** [comment] 2015-11-06 07:20
@vkarpov15 I get that 

    TodoSchema.pre('findOneAndUpdate', function() {
      this.findOneAndUpdate({}, { updatedAt: Date.now() });
    });

works to set a property to a hard value, but how would I *read anc change* a property, e.g. hash a password?

    TodoSchema.pre('findOneAndUpdate', function() {
      this.findOneAndUpdate({}, { password: hashPassword(.....?....) });
    });

Any thoughts? This is a pretty common usecase, right? Or do people usually find() and then separate save() ?

**Comment by vkarpov15** [comment] 2015-11-06 18:21
```javascript
TodoSchema.pre('findOneAndUpdate', function() {
  this.findOneAndUpdate({}, { password: hashPassword(this.getUpdate().$set.password) });
});
```

That should work @willemmulder.

**Comment by willemmulder** [comment] 2015-11-06 20:15
@vkarpov15 perfect, thanks! I'll be trying that tonight. That should also work for `pre('update')` right?

**Comment by willemmulder** [comment] 2015-11-06 21:27
@vkarpov15 So I just tried it using 

    schema.pre('update', function(next) {
	this.update({}, { $set : { password: bcrypt.hashSync(this.getUpdate().$set.password) } });
	next();
    });

and if I console.log `this` I do get 

``` _update:
{ '$set':
    { password: '$2a$10$CjLYwXFtx0I94Ij0SImk0O32cyQwsShKnWh1248BpYsJLIHh7jb66',
        postalAddress: [Object],
        permissions: [Object],
        firstName: 'Willem',
        lastName: 'Mulder',
        email: '...@...',
        _id: 55ed4e8b6de4ff183c1f98e8 } },
```

which seems fine (and I even tried setting that property directly before) but in the end, it doesn't actually write the hashed value to the database, but simply the 'raw' value. Is there anything I could try?

**Comment by vkarpov15** [comment] 2015-11-07 18:23
That's strange. You can try enabling mongoose debug mode with `require('mongoose').set('debug', true);` and see what the query that's getting sent to the db is, that could shed some light.

**Comment by willemmulder** [comment] 2015-11-07 20:02
Thanks for the suggestion. Just did that:

I run this:

```
schema.pre('update', function(next) {
	this.update({}, { password: bcrypt.hashSync(this.getUpdate().$set.password) } );
	console.log(this.getUpdate());
	next();
});
```

which returns this for the console.log

```
{ '$set':
   { password: '$2a$10$I1oXet30Cl5RUcVMxm3GEOeTFOLFmPWaQvXbr6Z5368zbfpA8nFEK',
     postalAddress: { street: '', houseNumber: '', zipCode: '', city: '', country: '' },
     permissions: [ '' ],
     __v: 0,
     lastName: '',
     firstName: '',
     email: 'test@test.nl',
     _id: 563b0410bd07ce2030eda26d } }
```

and then this for the Mongoose debug

```
Mongoose: users.update({ _id: ObjectId("563b0410bd07ce2030eda26d") }) { '$set': { password: 'test', postalAddress: { street: '', houseNumber: '', zipCode: '', city: '', country: '' }, permissions: [ '\u001b[32m\'\'\u001b[39m' ], __v: 0, lastName: '', firstName: '', email: 'test@test.nl', _id: ObjectId("563b0410bd07ce2030eda26d") } } { overwrite: false, strict: true, multi: false, upsert: false, safe: true }
Mongoose: users.findOne({ _id: ObjectId("563b0410bd07ce2030eda26d") }) { fields: { password: 0 } }
```

Any clue?

**Comment by vkarpov15** [comment] 2015-11-07 21:54
Not sure, opened up a new issue to track.

**Comment by willemmulder** [comment] 2015-11-09 07:37
@vkarpov15 Thanks, will track the other issue.

**Comment by akoskm** [comment] 2016-04-01 10:52
@vkarpov15 I think the right way to set options for the ongoing query in pre hook would be something like:

```js
  finishSchema.pre('findOneAndUpdate', function (next) {
    this.setOptions({
      new: true,
      runValidators: true
    });
    this.update({}, {
      lastEdited: Date.now()
    });
    next();
  });
```

but the documentation, http://mongoosejs.com/docs/api.html#query_Query-setOptions doesn't mention any of those options. If this considered to be a hackish solutions, what would be more appropriate?

**Comment by vkarpov15** [comment] 2016-04-03 14:40
That's an issue with the docs, that code you describe looks like it should work at first glance

**Comment by vkarpov15** [comment] 2016-04-03 14:41
Can you open up a separate issue for that?

**Comment by akoskm** [comment] 2016-04-03 20:54
@vkarpov15 Yes, it does work. I think I wasn't clear enough.

`setOptions` applies `new` and `runValidators` correctly, I was merely asking if setting those options through `setOptions` should be preferred over `this.options`.

**Comment by vkarpov15** [comment] 2016-04-04 20:40
`setOptions()` is preferable IMO, but both should work. Or you could just do

```javascript
this.update({}, { lastEdited: Date.now() }, { new: true, runValidators: true });
```

**Comment by nlonguit** [comment] 2016-04-06 07:01
```
schema.pre('update', function(next) {
this.update({}, { $set : { password: bcrypt.hashSync(this.getUpdate().$set.password) } });
next();
});
```
This will update password on every update() call. So if i just change the value of other fields, i.e. name or age, then password will be updated also which is not correct!?

**Comment by akoskm** [comment] 2016-04-06 07:12
@nlonguit I guess it will. But you can access through `this` the fields that are going to be updated and you could do something like:

```
if (this._fields.password) { // <- I'm sure about this one, check in debugger the properties of this 
    this.update({}, { $set : { password: bcrypt.hashSync(this.getUpdate().$set.password) } });
}
```

**Comment by nlonguit** [comment] 2016-04-06 08:12
` if (this._update.$set.password) {
        this.update({},
            { $set:
                { password: bcrypt.hashSync(this.getUpdate().$set.password)}
            });
    }`

This code is working well for me. Thanks @akoskm

**Comment by mickyginger** [comment] 2016-04-06 21:49
I wonder if it would be possible to add a pre hook for findByIdAndUpdate as well. Would be nice to have both hooks available.

**Comment by vkarpov15** [comment] 2016-04-09 21:21
@mickyginger [we have hooks for `findOneAndUpdate`](http://mongoosejs.com/docs/middleware.html), and [`findByIdAndUpdate()` just calls `findOneAndUpdate()` under the hood](http://mongoosejs.com/docs/api.html#model_Model.findByIdAndUpdate)

**Comment by keegho** [comment] 2016-06-04 21:22
I did it this way and it is working: Just findById then save without updating any fields then use the findByIdAndUpdate method:

`dbModel.findById(barId, function (err, bar) {
        if (bar) {
            
            bar.save(function (err) {
                if (err) throw err;
            });
        }
    });
    dbModel.findByIdAndUpdate(barId, {$set:req.body}, function (err, bar) {
        if (err) throw err;
        res.send('Updated');
    });`

**Comment by zilions** [comment] 2016-06-09 22:40
I'm trying to set a property to have the length of an array.

```
schema.post('findOneAndUpdate', function(result) {
    console.log(result.comments.length);
    this.findOneAndUpdate({}, { totalNumberOfComments: result.comments.length });
});
```

The correct length is logged, although the query never sets totalNumberOfComments, and the field stays at 0 (since the schema references default: 0).

Is there something I'm doing wrong, or is this a bug?

**Comment by vkarpov15** [comment] 2016-06-11 20:00
@zilions `this.findOneAndUpdate({}, { totalNumberOfComments: result.comments.length }).exec();` need to actually execute the query :) Just be careful, you're gonna get an infinite recursion there because your post save hook will trigger another post save hook

**Comment by zilions** [comment] 2016-06-11 23:46
Ahhhh right! Then what would be the way around this? Just use 'update' instead of 'findOneAndUpdate' inside the hook to stop it running infinitely?

**Comment by vkarpov15** [comment] 2016-06-14 13:38
Because you're technically executing the same query - 

```javascript
schema.post('findOneAndUpdate', function(result) {
    this.update({}, {
        totalNumberOfComments: result.comments.length
    }).exec();
}));
```

is essentially the same as

```javascript
var query = Post.findOneAndUpdate({_id: fj394hri3hfj}, {$push: {comments: myNewComment}});
query.update({}, {
        totalNumberOfComments: result.comments.length
    }).exec();
query.findOneAndUpdate().exec();
```

If you want to create a new query from scratch, just do

```javascript
schema.post('findOneAndUpdate', function(result) {
    this.model.update({}, { // <--- `this.model` gives you access to the `Post` model
        totalNumberOfComments: result.comments.length
    }).exec();
}));
```

**Comment by luffy06** [comment] 2016-08-16 02:51
I am a student who is learning this. I want to add a pre hook when I use findOneById in order to hash my loginid.
Here is my code.
```
var mongoose = require('mongoose');
var bcrypt = require('bcryptjs');
var SALT_WORK_FACTOR = 10;

var userSchema = new mongoose.Schema({
  // user ID
  loginid: {
    type: String,
    unique: true
  },
  // user name
  name: String,
  // user password
  pass: String,
  // user role: student, teacher, specialist, leader, supervisor, other
  role: {
    type: String,
    default: 'student'
  },
  meta: {
    createAt: {
      type: Date,
      default: Date.now()
    }, 
    updateAt: {
      type: Date,
      default: Date.now()
    }
  }
});

userSchema.pre('save', function(next) {
  var user = this;

  // set updating time
  if (this.isNew) {
    this.meta.createAt = this.meta.updateAt = Date.now()
  }
  else {
    this.meta.updateAt = Date.now()
  }

  // use bcrypt to encrypt
  bcrypt.genSalt(SALT_WORK_FACTOR, function(err, salt) {
    if (err)
      return next(err);
    bcrypt.hash(user.pass, salt, function(err, hash) {
      if (err)
        return next(err);
      user.pass = hash;
    })
    bcrypt.hash(user.loginid, salt, function(err, hash) {
      if (err)
        return next(err)
      user.loginid = hash;
      next();
    })
  })
});

userSchema.pre('findOne', function(next) {
  var loginid = this.findOne().loginid;

  bcrypt.genSalt(SALT_WORK_FACTOR, function(err, salt) {
    if (err)
      return next(err);
    bcrypt.hash(loginid, salt, function(err, hash) {
      if (err)
        return next(err)
      loginid = hash;
      next();
    })
  })
})

// custom method
userSchema.methods = {
  // compare password
  comparePassword: function(pass, cb) {
    bcrypt.compare(pass, this.pass, function(err, isMatch) {
      if (err) 
        return cb(err);
      cb(null, isMatch);
    });
  },
  // update password
  updatePassword: function(pass, cb) {
    var user = this;

    bcrypt.genSalt(SALT_WORK_FACTOR, function(err, salt) {
      if (err)
        return cb(err);
      bcrypt.hash(pass, salt, function(err, hash) {
        if (err)
          return cb(err);
        user.pass = hash;
        cb(null);
      });
    });
  }
}

// statics method
userSchema.statics = {
  // use user's role level to sort order by cmp
  fetch: function(cmp, cb) {
    return this
      .find({})
      .sort({"role": cmp})
      .exec(cb)
  },
  findOneById: function(loginid, cb) {
    return this
      .findOne({"loginid": loginid})
      .exec(cb)
  },
  // use user's name to find user
  findByName: function(name, cb) {
    return this
      .findOne({"name": name})
      .exec(cb)
  }
}

module.exports = userSchema;y;
```
Thank you!

**Comment by moparlakci** [comment] 2016-09-13 20:06
just dont touch your pre save hook,

`router.put('/:id', jsonParser, function(req, res, next) {

  currentCollection.findByIdAndUpdate(req.params.id, req.body, function (err, item) {
    if (!item) {
        res.status(404);
        return res.json({'error': 'Item Not Found'}); // may never happen normally
    }
    if (err) {
        res.status(404);
        return res.json({'error': 'Server Error', 'trace': err});
    }
    item.save(); **// <=== this is were you save your data again :)** 
    res.status(200); 
    return res.json({'message': 'Saved successfully'});
  });
});`

**Comment by nicky-lenaers** [comment] 2016-11-28 19:26
I found that the order matters in which you define a model and define a ``pre`` hook. Allow me to demonstrate:

Does not work:
```
// Create Model
let model = Database.Connection.model(`UserModel`, this._schema, `users`);

// Attach Pre Hook
this._schema.pre(`findOneAndUpdate`, function(next) {
    console.log('pre update');
    return next();
});
```

Does work:
```
// Attach Pre Hook
this._schema.pre(`findOneAndUpdate`, function(next) {
    console.log('pre update');
    return next();
});

// Create Model
let model = Database.Connection.model(`UserModel`, this._schema, `users`);
```

Hope this helps anyone!

**Comment by albert-92** [comment] 2016-11-30 00:16
I just found out the same thing as @nicky-lenaers.

It works just fine with `'safe'`. `'delete'`. etc. if you define the hooks after the model is defined.

Is there a workaround do define a `'findOneAndUpdate'` hook after the model is defined?

**Comment by vkarpov15** [comment] 2016-12-03 04:31
@albert-92 no not at the moment

**Comment by marcusjwhelan** [comment] 2016-12-08 20:08
For anyone trying to get something that used to be like 

```javascript
SCHEMA.pre('validate', function(done) {
    // and here use something like 
    this.yourNestedElement 
    // to change a value or maybe create a hashed character    
    done();
});
```
This should work
```javascript
SCHEMA.pre('findOneAndUpdate', function(done){
    this._update.yourNestedElement
    done();
});
```

**Comment by johndeyrup** [comment] 2016-12-21 15:15
I can't get post hooks to update the document in the collection. 

`module.exports = function (mongoose) {
    var mySchema = mongoose.Schema({
        id: { type: Number, index: { unique: true } },
        field1: { type: String },
        field2: { type: String}
    }, {
        collection: "mySchema",
        versionKey: false
    });

    mySchema.post('findOneAndUpdate', function (result) {
        this.model.update({}, {
            field2: 'New Value'
        }).exec();
    });
    return mySchema;
};
`

`mySchema.findOneAndUpdate({id: 1}, {field1: 'test'}, {new: true});`

Returns { id:1, field1: 'test' ) but should be {id: 1, field1: 'test', field2:'New Value'}
Not sure what I am doing wrong

**Comment by marcusjwhelan** [comment] 2016-12-21 16:25
I think it might be that you are trying to update the model with an element that already exists on the model. Or possibly that you are selecting it wrong. Try printing out "this" in your mySchema.post. Also you don't seem to have a done() or next() in your post. I'm not very knowledgable on the subject but I know printing out this will at least give you an idea of what you are dealing with.

**Comment by johndeyrup** [comment] 2016-12-21 16:30
Isn't the point of update to change an existing document in your model?

this is a query object

You don't need done or next in post hooks as far as I understand.

**Comment by marcusjwhelan** [comment] 2016-12-21 17:09
Well you have this.model.update which is the schema not the model of the object. I think.. Which means you would have to use 

```javascript
mySchema.post('findOneAndUpdate', function (result) {
    this.model.update({}, {
        $set: { field2: 'New Value'}
    }).exec();
});
return mySchema;
```

In my example above I used this._update because that was the update object that needed to be used off of this.

**Comment by johndeyrup** [comment] 2016-12-21 17:15
I have tried using $set. It still doesn't change my document in the collection.

**Comment by kanyaparamita** [comment] 2017-01-09 11:24
gabisa ya nih?

**Comment by jcyh0120** [comment] 2017-09-07 09:41
Where can I find the all available pre and post hooks?

**Comment by vkarpov15** [comment] 2017-09-16 00:18
Middleware docs http://mongoosejs.com/docs/middleware.html

**Comment by syzer** [comment] 2018-08-17 13:13
+1
