### ISSUE TITLE
Casting null to object

### ISSUE THREAD

**Issue by realjay007** [Automattic/mongoose#7372] opened 2018-12-26 13:57 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug, I think.

**What is the current behavior?**
Document properties defined as an object in schema but set to null, cast to boolean true.

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
const mongoose = require("mongoose");

const MONGODB_URI = "mongodb://127.0.0.1:27017/test";

async function run() {
	await mongoose.connect(MONGODB_URI);

	const Schema = mongoose.Schema({
		name: String,
		obj_or_null: {
			a: String,
			b: String
		}
	});
	const Model = mongoose.model("User", Schema);

	// Clear existing records
	await Model.deleteMany();

	let user = new Model({
		name: "John Doe",
		obj_or_null: {
			a: "hello",
			b: "world"
		}
	});

	await user.save();

	user = await Model.findOne({name: "John Doe"}).exec();
	user.obj_or_null = null;
	await user.save();

	user = await Model.findOne({name: "John Doe"}).exec();
	let obj_or_null = user.obj_or_null;
        // Logs null
	console.log(obj_or_null);
        // Logs true instead of false
	console.log(Boolean(obj_or_null));

        // For reference
        let a = null;
        // Logs null
	console.log(a);
        // Logs false
	console.log(Boolean(a));
}

run().catch(err => console.log(err))

```

**What is the expected behavior?**
Casting null to boolean returns false in normal javascript. I tried the mongodb library directly and null casted directly to false. 

**Please mention your node.js, mongoose and MongoDB version.**
Nodejs: 10.14
Mongoose: 5.4
Mongodb: 4.0

**Comment by vkarpov15** [comment] 2019-01-03 17:34
This is a duplicate of #5369 and #5310. `obj_or_null` is actually an object because of how Mongoose change tracking works - you can't do `Object.defineProperty()` on `null`. Use [`toObject()`](https://mongoosejs.com/docs/api.html#document_Document-toObject) before checking:

```javascript
console.log(Boolean(obj_or_null.toObject())); // false
console.log(obj_or_null.toObject() == null); // true
```

In a future release we'll add an `isEmpty()` helper to help with this, so you can do `obj_or_null.isEmpty()` or `obj_or_null.isNull()`

**Closed** 2019-01-03 17:35 UTC
