### ISSUE TITLE
When adding pre-populated objects onto a model instance array property, they get converted to ObjectID's

### ISSUE THREAD

**Issue by adamreisnz** [Automattic/mongoose#3575] opened 2015-11-14 21:44 UTC
I've noticed what seems to be a discrepancy in the way Mongoose handles pre-populated values.
Consider the following simple example schema:

``` javascript
var FooSchema = new Schema({
  bar: {
    type: Schema.Types.ObjectId,
    ref: 'Bar'
  },
  bars: [{
    type: Schema.Types.ObjectId,
    ref: 'Bar'
  }]
});
```

Now  suppose we get some Bar objects and we create a new Foo:

``` javascript
//Assume these variables are Bar model instances with the following properties:
var bar1 = {id: 1, name: 'BarOne'};
var bar2 = {id: 2, name: 'BarTwo'};
var bar3 = {id: 3, name: 'BarThree'};

//Prepare data for a new Foo instance:
var fooData = {
  bar: bar1,
  bars: [bar2, bar3]
};

//Create new Foo instance
Foo.create(fooData).then(function(foo) {
  //...
});
```

After creation, the foo instance looks like this:

``` javascript
{
  bar: {
    id: 1,
    name: 'BarOne'
  },
  bars: [2, 3]
}
```

What has happened, is that Mongoose recognised that `bar1` was a `Bar` instance, so it left it on the `foo` instance as a populated property. However, it has un-populated the array of `bars` and flattened them to just ID's, even though they were also pre-populated.

Why the inconsistency?

I would expect the foo instance to either un-populate all properties, or keep them all populated, if the data is available, e.g.:

``` javascript
{
  bar: 1,
  bars: [2, 3]
}
```

or

``` javascript
{
  bar: {
    id: 1,
    name: 'BarOne'
  },
  bars: [{
    id: 2,
    name: 'BarTwo'
  }, {
    id: 3,
    name: 'BarThree'
  }]
}
```

Any way I can force this behaviour one way or another for both object refs and arrays of object refs?

**Comment by vkarpov15** [comment] 2015-11-16 17:19
Fix will be in 4.2.6 later today. The issue [is that it's tricky to support the general case of setting an array element to a populated value](https://github.com/Automattic/mongoose/issues/1530#issuecomment-59545311), because what happens with a partially-populated array? With this fix, it should work fine if you overwrite the entire array:

```javascript
var barSchema = new mongoose.Schema({ name: String });

var Bar = mongoose.model('Bar', barSchema);

var fooSchema = new mongoose.Schema({
  bar: {
    type: Schema.Types.ObjectId,
    ref: 'Bar'
  },
  bars: [{
    type: Schema.Types.ObjectId,
    ref: 'Bar'
  }]
});

var Foo = mongoose.model('Foo', fooSchema);

Bar.create([{ name: 'bar1' }, { name: 'bar2' }, { name: 'bar3' }], function(error, docs) {
  assert.ifError(error);
  assert.equal(docs.length, 3);
  var foo = new Foo({ bar: docs[0], bars: [docs[1], docs[2]] });
  console.log(foo);
  process.exit(0);
});
```

**Comment by adambuczynski** [comment] 2015-11-17 03:40
Can confirm that this is working now in 4.2.6.

**Comment by robertleeplummerjr** [comment] 2015-12-16 17:32
bump

**Comment by adambuczynski** [comment] 2015-12-16 17:52
Why is this being bumped? It has already been fixed in 4.2.6.

**Comment by vkarpov15** [comment] 2015-12-16 17:52
@robertleeplummerjr this issue has been fixed. If you have a similar issue, please post relevant code samples and instructions on how to reproduce, preferably in a separate issue.

**Comment by robertleeplummerjr** [comment] 2015-12-16 18:16
I bumped it because there was an unanswered question that I simply was
curious about.

On Wed, Dec 16, 2015 at 1:07 PM, Valeri Karpov <notifications@github.com>
wrote:

> @robertleeplummerjr <https://github.com/robertleeplummerjr> this issue
> has been fixed. If you have a similar issue, please post relevant code
> samples and instructions on how to reproduce, preferably in a separate
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/mongoose/issues/3575#issuecomment-165193411>
> .
>



-- 
Robert Plummer

**Comment by vkarpov15** [comment] 2015-12-16 18:29
Which question?

**Comment by robertleeplummerjr** [comment] 2015-12-16 18:49
I miss-read it now looking back.  My bad.

**Comment by robertleeplummerjr** [comment] 2015-12-16 18:50
The "question": https://github.com/Automattic/mongoose/issues/3575#issuecomment-165193371

**Comment by vkarpov15** [comment] 2015-12-16 19:11
No worries :beers:

**Comment by adambuczynski** [comment] 2015-12-16 19:57
:beers:

**Comment by emmanuelbuah** [comment] 2016-12-21 00:30
This doesn't seem to work if the array ref schema is the base type using discriminator. 

`
var shapeSchema = new mongoose.Schema({discriminatorKey: 'kind'});

var Shape = mongoose.model('Shape', shapeSchema);

var Circle = Shape.discriminator('Circle', new mongoose.Schema({
 radius: { type: Number }
},{discriminatorKey: 'kind'}))


var Square = Shape.discriminator('Square', new mongoose.Schema({
 sides: { type: Number }
},{discriminatorKey: 'kind'}))

var FooSchema = new Schema({
  bar: {
    type: Schema.Types.ObjectId,
    ref: 'Shape'
  },
  bars: [{
    type: Schema.Types.ObjectId,
    ref: 'Shape'
  }]
});

var Foo = mongoose.model('Foo', fooSchema);

var test = new Foo({ });
test.bars = [{ kind: Cirle , _id: ObjectId(..) } , { kind: Cirle , _id: ObjectId(..) } ];
//test.bar[0] is objectid rather than circle object
test.save()
//test.bar[0] is objectid rather than circle object

`

**Closed** 2016-12-24 21:37 UTC
