### ISSUE TITLE
How to set a reasonable poolsize?

### ISSUE THREAD

**Issue by zwb-ict** [Automattic/mongoose#3351] opened 2015-09-07 10:08 UTC
I enable keepalive with mongo, now I have doubts about how to set poolsize reasonablly, I searched google, but not found a good answer, would you please give me a hand? Thank you.

**Comment by vkarpov15** [comment] 2015-09-08 14:00
Duplicate of #3350

**Closed by vkarpov15** 2015-09-08 14:00 UTC
