### ISSUE TITLE
Mongoose returns a value that is defined in the schema but doesn't actually exist in the db document

### ISSUE THREAD

**Issue by KingDGrizzle** [Automattic/mongoose#5990] opened 2018-01-12 14:43 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Mongoose returns a document with data that isn't in the document but is in the schema.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Have a schema like 
```js
const schema = new Schema({
	object: {
		otherObject1: {
			valid: true,
		},
	},
});
```
- Create a document using the schema
- Update the schema by adding a new object, kinda like
```js
const schema = new Schema({
	object: {
		otherObject1: {
			valid: true,
		},
		otherObject2: {
			valid: true,
		},
	},
});
```
- Fetch the document that was created before

**What is the expected behavior?**
The returned document wouldn't add the `otherObject2` to itself and it would just be null / undefined if you would check for it. In the current state, it adds itself without caring.

**Please mention your node.js, mongoose and MongoDB version.**
Node.js v8.9.1
Mongoose: 4.13.9 (I'm pending some internal changes before switching to 5.0)
MongoDB 3.6

**Comment by varunjayaraman** [comment] 2018-01-15 20:35
I'm not able to reproduce this. Here's a repro script where if you uncomment out the relevant parts in the 2nd time you run the script, it gives you back an object that meets your expected behavior:

```javascript
const mongoose = require('mongoose');
mongoose.Promise = global.Promise;

const GITHUB_ISSUE = `gh-5990`;
const connectionString = `mongodb://localhost:27017/${GITHUB_ISSUE}`;

run().catch(error => console.error(error.stack));

async function run() {
  await mongoose.connect(connectionString);

  const schema = new mongoose.Schema({
    object1: { name: String },
    // uncomment in 2nd pass
    // object2: { name: String }
  });

  const Model = mongoose.model('Model', schema);

  // run in first pass
  await createObj(Model);

  // run in 2nd pass
  // console.log(await findObj(Model));
  
}

function findObj(Model) {
  return Model.findOne({ object1: { name: 'testobject1' } })
}

function createObj(Model) {
  return Model.create({ object1: { name: 'testobject1' } });
}
```

Here's the final log output after the 2nd pass where i commented out `createObj` and uncommented out the 2nd pass stuff:

```
{ _id: 5a5d0fa6a6c0f8440bb7a05d,
  __v: 0,
  object1: { name: 'testobject1' } }
```

**Comment by KingDGrizzle** [comment] 2018-01-16 08:02
Hmm. That's very weird.. I was just able to reproduce this in with mongoose 4.13.19
![image](http://wait-it.works.wtf/vlag/2018/01/v5p8d6.png)

And yes, although its an eval, I did do the same in a migration script and it outputted the same results.. [Here's](https://github.com/GilbertGobbels/GAwesomeBot/tree/indev-4.0.2/Database) the GitHub folder which contains our database configurations. The schema that can change is the serverConfigSchema, which bases off some `commands.js` values. Simple test would be to comment out a whole command from there, start the database, make a document, stop it, uncomment and restart and refetch.

**Comment by vkarpov15** [comment] 2018-01-17 19:27
This is a duplicate of #5310, etc. Mongoose adds `doc.otherObject2 = {}` for change tracking, because trying to use getters/setters on top of a null value leads to some truly baffling behavior in JS as described [here](https://github.com/Automattic/mongoose/issues/5310#issuecomment-307666824). The empty object won't get saved or put in `JSON.stringify()` output as long as you use [`minimize: true` in your schema](http://mongoosejs.com/docs/guide.html#minimize)

**Closed by vkarpov15** 2018-01-17 19:27 UTC
Labels: can't reproduce
