### ISSUE TITLE
LeanDocument Type doesn't include _id or id

### ISSUE THREAD

**Issue by noseworthy** [Automattic/mongoose#11761] opened 2022-05-03 16:49 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I believe that the types defined here are incorrect:
https://github.com/Automattic/mongoose/blob/c22152c5a95c5ce9ed688d96b37b05c7df6be1ec/types/index.d.ts#L2261-L2267
This says that `LeanDocuments` (that is documents returned from `.toObject()` or when using the `lean` option don't have the `_id` or `id` fields. I don't think this is correct.

This issue only presented itself in version 6.3.2 and wasn't present in 6.3.1

**If the current behavior is a bug, please provide the steps to reproduce.**

```typescript
import mongoose from 'mongoose'

async function test() {
  const thingSchema = new mongoose.Schema({
    name: mongoose.Schema.Types.String,
  });

  const ThingModel = mongoose.model('Thing', thingSchema);

  // TypeScript will complain here that `_id` doesn't exist
  const { _id, ...thing1 } = (await ThingModel.create({name: 'Thing 1'})).toObject();

  // if I ignore the above warning and this log happens, _id is a valid ObjectId.
  console.log({_id, thing1});
}

```

**What is the expected behavior?**

`_id` and `id` are present on LeanDocuments (I think...)
**What are the versions of Node.js, Mongoose and MongoDB you are using? Note that "latest" is not a version.**

Node.js: v16.15.0
TypeScript: v4.6.2
mongoose: v6.3.2

**Comment by Uzlopak** [comment] 2022-05-03 16:55
I think, that id is not on a lean document if you did not define id in the schema explicitly, as id is actually a virtual field. 

@taxilian

**Comment by Uzlopak** [comment] 2022-05-03 16:56
I guess you can avoid the bug for now, by explicitly defining _id: Schema.Types.ObjectId in your Schema.

**Comment by noseworthy** [comment] 2022-05-03 17:37
Yeah, I'm just `@ts-ignore`-ing the few errors we're getting for now. However, I don't feel like we should be required to define `_id` in the schema. The POJO that we get back has the `_id` on it regardless of the schema definition. I think the TypeScript type should reflect that.

That said, I don't have super deep understanding of the inner workings of all this and I could be missing something. 🤷‍♂️

It's why I raised a bug rather than open an MR. Didn't feel comfortable mucking about on this one, haha. Thanks for taking a look at it! 😁

**Comment by taxilian** [comment] 2022-05-03 20:07
This is one of those things which *could* be fixed, but there are a *lot* of potential issues that it can cause; I would strongly suggest that you just define _id yourself in your schema. It's a simple one-time fix and it removes a *lot* of complexity in the typescript

**Comment by Uzlopak** [comment] 2022-05-03 20:36
This is a clear regression. This is comparable to when Apple had antenna issues with their iphones, if you hold the IPhones in your hand and they basically said, that it is the consumers fault, because the consumer hold the iPhone "wrong"... 

This is not acceptable.

@mohammad0-0ahmad 
We need to fix this. Any idea how we can fix that in a timely manner?

**Comment by mohammad0-0ahmad** [comment] 2022-05-03 22:31
I've tested the code snippet that is provided by @noseworthy, but I couldn't reproduce TS warning because the returned value is "any".
![Capture](https://user-images.githubusercontent.com/50488054/166582590-d7373d5d-8726-48b2-8d3e-ef90089057ad.PNG)

**Comment by taxilian** [comment] 2022-05-03 23:09
Sorry, I'm looking more closely at this and there are several things that don't make sense.

First, the assumption stated in the issue is incorrect: "This says that LeanDocuments (that is documents returned from .toObject() or when using the lean option don't have the _id or id fields." -- that's actually exactly opposite. The reference to _id is in a double negative -- it's telling it to omit any fields from Document *except* those ones.

I'm not claiming that there is no issue here because clearly someone is seeing an issue, but I can't reproduce it either because -- like @mohammad0-0ahmad says -- the type here is `any`. If someone can show a unit test reproducing the issue I'd be happy to take a look at it, but the problem is absolutely *not* what is postulated in the issue description because that code was there before I meddled.

**Comment by mohammad0-0ahmad** [comment] 2022-05-03 23:11
The regression has appeared after merging this commit [e4b007b3fb2f6a92a4e33579f3757b8964613b1f](https://github.com/Automattic/mongoose/commit/e4b007b3fb2f6a92a4e33579f3757b8964)
@vkarpov15 might take a look before opening a PR to solve this issue.

**Comment by mohammad0-0ahmad** [comment] 2022-05-03 23:15
@taxilian  I think he forgot to provide schema type as generic in the code snippet as I said above.
![Capture](https://user-images.githubusercontent.com/50488054/166587950-cab152e9-5a0c-4bf9-aa48-5c89e8e3689c.PNG)

**Comment by taxilian** [comment] 2022-05-04 04:53
I very very strongly recommend against making it add _id in that case. it's up to you, but in the long run it's going to add a nontrivial amount of complexity which far exceeds the problems that it solves.

The benefit *is not* worth the cost.

**Comment by Uzlopak** [comment] 2022-05-04 05:00
I respectfully disagree. We dont break user space without making a major release.  Now we force devs to patch their schemas or write ts-ignore. Also it would mean that the typings do not represent the javascript reality.

@mohammad0-0ahmad  Would the autotyping PR fix this implicitly?

**Comment by ghost91-** [comment] 2022-05-04 08:02
Not sure if this is strictly related, but the change to the types here also broke some stuff for us. In particular making the return type of `toObject` always the `LeanDocument<T>` breaks stuff for us, since we are using a generic type as `T`.

The most confusing thing is that this is now actually inconsistent between `.lean<T>()` ans `.toObject<T>()`, because the former actually resolves to `T` (when the query is awaited), but the latter resolves to `LeanDocument<T>`.

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 08:53
Hello @taxilian !
I've created PR to solve this issue, and it's fixed so far. To be honest, there are  a lot to do to improve types, but It just a quick fix.
I've deleted some unnecessary types "I think so" that you have created in your latest PR, I guess it would be great if you review the changes in the mentioned PR.

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 08:53
> Not sure if this is strictly related, but the change to the types here also broke some stuff for us. In particular making the return type of `toObject` always the `LeanDocument<T>` breaks stuff for us, since we are using a generic type ourselves for `T`, and that doesn't match up with our types now anymore.
> 
> The most confusing thing is that this is now actually inconsistent between `.lean<T>()` ans `.toObject<T>()`, because the former actually resolves to `T` (when the query is awaited), but the latter resolves to `LeanDocument<T>`.
Hi @ghost91- !
Thanks for your comment, Can you please provide code snippet ?

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 08:57
> I respectfully disagree. We dont break user space without making a major release.  Now we force devs to patch their schemas or write ts-ignore. Also it would mean that the typings do not represent the javascript reality.
> 
> @mohammad0-0ahmad  Would the autotyping PR fix this implicitly?

I've created new PR instead.😉

**Comment by ghost91-** [comment] 2022-05-04 09:32
> Hi @ghost91- ! Thanks for your comment, Can you please provide code snippet ?

This is a dumbed down example of what we are doing:
```ts
class GenericRepository<T extends { id: string }> {
  constructor(private readonly GenericModel: Model<T>) {}

  public async create(t: T): Promise<T> {
    const document = new this.GenericModel(t);
    await document.save();
    return document.toObject<T>(); // worked in 6.3.1, broken in 6.3.2, as it returns `LeanDocument<T>` instead of `T` now, which might not be compatible with `T`
  }

  public async update(t: T): Promise<T | null> {
    const document = await this.GenericModel.findByIdAndUpdate({ id: t.id }, t).lean<T | null>(); // still OK in 6.3.2
    return document;
  }
}
```

The underlying problem is that TypeScript doesn't know that `T` does not have any properties that are omitted by `LeanDocument`. Unfortunately it's not possible in TypeScript to create a constraint to `T` so that it can _not_ have any of these properties (due the nature of the structural type system).

I realize that the new way may actually be a little more correct (not sure what would happen at runtime if a schema defined properties that clash with things added by `Document`). But it's weird that the typing works differently for `lean` and `toObject`. The old way was a handy way for us to get what we need, but I suppose we could work around the new way with a simple type assertion. But in that case, I think it should work the same for both `lean` and `toObject`.

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 10:08
> > Hi @ghost91- ! Thanks for your comment, Can you please provide code snippet ?
> 
> This is a dumbed down example of what we are doing:
> 
> ```ts
> class GenericRepository<T extends { id: string }> {
>   constructor(private readonly GenericModel: Model<T>) {}
> 
>   public async create(t: T): Promise<T> {
>     const document = new this.GenericModel(t);
>     await document.save();
>     return document.toObject<T>(); // worked in 6.3.1, broken in 6.3.2, as it returns `LeanDocument<T>` instead of `T` now, which might not be compatible with `T`
>   }
> 
>   public async update(t: T): Promise<T | null> {
>     const document = await this.GenericModel.findOneAndUpdate({ id: t.id }, t).lean<T | null>(); // still OK in 6.3.2
>     return document;
>   }
> }
> ```
> 
> The underlying problem is that TypeScript doesn't know that `T` does not have any properties that are omitted by `LeanDocument`. Unfortunately it's not possible in TypeScript to create a constraint to `T` so that it can _not_ have any of these properties (due the nature of the structural type system).
> 
> I realize that the new way may actually be a little more correct (not sure what would happen at runtime if a schema defined properties that clash with things added by `Document`). But it's weird that the typing works differently for `lean` and `toObject`. The old way was a handy way for us to get what we need, but I suppose we could work around the new way with a simple type assertion. But in that case, I think it should work the same for both `lean` and `toObject`.

After merging mentioned PR, you will be able to do like following:
```
  class GenericRepository<T extends { id: string }> {
    constructor(private readonly GenericModel: Model<T>) {}

    public async create(t: T): Promise<LeanDocument<T>> { // Wrap T with LeanDocument
      const document = new this.GenericModel(t);
      await document.save();
      return document.toObject<T>(); // worked in 6.3.1, broken in 6.3.2, as it returns `LeanDocument<T>` instead of `T` now, which might not be compatible with `T`
    }

    public async update(t: T): Promise<T | null> {
      const document = await this.GenericModel.findOneAndUpdate({ id: t.id }, t).lean<T | null>(); // still OK in 6.3.2
      return document;
    }
  }
```
What do you think about that?

**Comment by ghost91-** [comment] 2022-05-04 10:55
The point is that we _want_ to return `Promise<T>`, not `Promise<LeanDocument<T>>`, since we know that there will be no conflicting properties. If that requires a type assertion, that's probably acceptable, but I still think `lean` and `toObject` should work the same in that regard, and right now, they don't. They basically fulfill the same purpose, so I really think they should provide the same interface (on a type level).

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 11:22
@ghost91- !
Yes, you have right, sorry I didn't read the lean line because it's working.
I will take a look and try to fix it in the same PR.

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 11:29
@ghost91- 
According to the docs, lean() and toObject() does not return same type.
Take a look:
https://mongoosejs.com/docs/api.html#document_Document-toObject
https://mongoosejs.com/docs/api.html#query_Query-lean
@Uzlopak  @vkarpov15 can check my comment and correct it if I am wrong.

**Comment by noseworthy** [comment] 2022-05-04 12:48
Woah, this blew up over night. Thanks for looking at it folks and sorry for the incomplete and misleading issue description. You're right, I was missing the schema type generic and totally misread that `LeanDocument` type definition. It was at the end of a sprint planning day and I was sort of spent 😅

**Comment by taxilian** [comment] 2022-05-04 17:06
oh please please please don't use that PR (#11767) -- that undoes literally days of work. If this is that big of a concern then I will find a way to fix it. That PR oversimplifies to the point that you fix this one issue and create lots and lots of other ones.

Let me take a look at this and fix it the right way, not by just undoing a bunch of needed things

**Comment by taxilian** [comment] 2022-05-04 17:12
At this point I'm not sure I 100% understand the things people are trying to do -- if you can give me a couple of tests which fail right now and should not fail I will make them work *without* completely neutering the improvements that I made. Let's please not throw the baby out with the bathwater.

It's very possible -- and quite easy -- to have types which are actually useful and help you locate code which is going to be problematic. It frustrates me that we're so determined to have code work which seemed intuitive because of weird assumptions that we're willing to throw out usefulness as well, but if it's that important then let's fix it -- but let's fix it, not just say "well, that improvement made things harder so forget it".

If these are things which are important then let's get tests around them to make sure they don't break and let's fix them.

**Comment by taxilian** [comment] 2022-05-04 17:16
> Hello @taxilian !
> I've created PR to solve this issue, and it's fixed so far. To be honest, there are a lot to do to improve types, but It just a quick fix.

Sorry, responding in a more reasoned way now =] If we have to do this as a "quick fix" I understand.

> I've deleted some unnecessary types "I think so" that you have created in your latest PR, I guess it would be great if you review the changes in the mentioned PR.

Those are 100% not unnecessary types. They are *very* necessary to cover some very specific cases while still allowing useful types. I'm happy to discuss specifics, though not sure if this is the most useful place to do so -- are you on the mongoose slack? Just let me know when/how you want to discuss.

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 17:28
> > Hello @taxilian !
> > I've created PR to solve this issue, and it's fixed so far. To be honest, there are a lot to do to improve types, but It just a quick fix.
> 
> Sorry, responding in a more reasoned way now =] If we have to do this as a "quick fix" I understand.
> 
> > I've deleted some unnecessary types "I think so" that you have created in your latest PR, I guess it would be great if you review the changes in the mentioned PR.
> 
> Those are 100% not unnecessary types. They are _very_ necessary to cover some very specific cases while still allowing useful types. I'm happy to discuss specifics, though not sure if this is the most useful place to do so -- are you on the mongoose slack? Just let me know when/how you want to discuss.

I am not on the mongoose slack.

**Comment by taxilian** [comment] 2022-05-04 17:31
> Maybe we should really do it the strict TDD was and collect typings tests, and then implement the typings.

I've been trying to do that with all my changes -- working on a fix for this doing that method. That's one reason that I'm concerned that the largest change in the proposed PR involves removing 40 lines of unit test code which would no longer work....

**Comment by simllll** [comment] 2022-05-04 17:32
Not quite sure if it is the same, but 6.3.2 causes also a lot of troulbes on our side. toObject() seems to not match the plain type anymore?

e.g.
```
error TS2345: Argument of type 'Omit<_LeanDocument<any>, "$getAllSubdocs" | "$ignore" | "$isDefault" | "$isDeleted" | "$getPopulatedDocs" | "$isEmpty" | "$isValid" | "$locals" | "$markValid" | ... 44 more ... | "$isSingleNested">' is not assignable to parameter of type '_LeanDocument<IDBOrganization>'.
  Type 'Omit<_LeanDocument<any>, "$getAllSubdocs" | "$ignore" | "$isDefault" | "$isDeleted" | "$getPopulatedDocs" | "$isEmpty" | "$isValid" | "$locals" | "$markValid" | ... 44 more ... | "$isSingleNested">' is missing the following properties from type '_LeanDocument<IDBOrganization>': _id, name, searchName, createdAt, and 51 more.
```
or
`TS2740: Type 'Omit_LeanDocument , "save" | "validate" | "remove" | "populate" | "$getAllSubdocs" | "$ignore" | "$isDefault" | "$isDeleted" | "$getPopulatedDocs" | "$isEmpty" | ... 43 more ... | "$isSingleNested">' is missing the following properties from type 'IWebUpload': _id, _user, type, typeid, and 3 more.`

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 17:36
> > Maybe we should really do it the strict TDD was and collect typings tests, and then implement the typings.
> 
> I've been trying to do that with all my changes -- working on a fix for this doing that method. That's one reason that I'm concerned that the largest change in the proposed PR involves removing 40 lines of unit test code which would no longer work....

They are working if I keep them, but there are some types that are used in these tests and doesn't use internally.
Please check out the PR and double check what I said by undo the latest commit.

We can discuss that further in the mentioned PR instead of here.

**Comment by taxilian** [comment] 2022-05-04 17:42
Moving discussion there =]

**Comment by taxilian** [comment] 2022-05-04 17:43
@simllll is there any way you can make a short example showing the problem? I'm happy to take a look at it but I'm not following your explanation. If you can give me a snippet I can put in a unit test we can a) address it and b) make sure it doesn't come back.

**Comment by simllll** [comment] 2022-05-04 17:47
@taxilian Nothing special actually, what we do is for example something like this:

MyModel:
```ts
interface IDBMyModel extends Document {
	_id: string;
	someprop: string;
}

const MyModel: Model<IDBMyModel> = model<IDBMyModel>(
	'MyModel',
	new Schema({
	someprop: { type: String }
        })
)
```
and this one causes already erros with 6.3.2:
```ts
interface IWebUpload {
	_id: string;
	someprop: string;
}
function async a(): Promise<IWebUpload> {
const model = new MyModel({someprop: 'asdf'});
await model.save();
return model.toObject();
}
```

**Comment by taxilian** [comment] 2022-05-04 18:17
> @taxilian Nothing special actually, what we do is for example something like this:
> 
> MyModel:
> 
> ```ts
> interface IDBMyModel extends Document {
> 	_id: string;
> 	someprop: string;
> }
> 
> const MyModel: Model<IDBMyModel> = model<IDBMyModel>(
> 	'MyModel',
> 	new Schema({
> 	someprop: { type: String }
>         })
> )
> ```
> 
> and this one causes already erros with 6.3.2:
> 
> ```ts
> interface IWebUpload {
> 	_id: string;
> 	someprop: string;
> }
> function async a(): Promise<IWebUpload> {
> const model = new MyModel({someprop: 'asdf'});
> await model.save();
> return model.toObject(); <-- errors
> }
> ```

I can look at this -- and will because I want to prevent regressions -- but part of the issue is that you're using what I would call an anti-pattern -- don't have your interface extend Document. Instead, do this:

```typescript
interface MyModel {
	_id: string;
	someprop: string;
}
type IDBMyModel = HydratedDocument<MyModel>;

const myModelSchema = new Schema<MyModel>({someProp: String});
const MyModel = model('MyModel', myModelSchema);\
```

You'll find your types all work better that way.  ... that said, let me see if I can repro your issue in my PR branch

**Comment by taxilian** [comment] 2022-05-04 18:20
@simllll also just to verify -- you realize your types are wrong for _id? The default type of _id is ObjectId, not string, so if you use that you're going to have inaccurate types unless you define _id as a string in your schema

**Comment by taxilian** [comment] 2022-05-04 18:27
@simllll I see what is causing the issue, and it's a frustrating one because there isn't a good fix for it. Here is the problem:

* Because you're extending Document in your base interface there is no way to get the interface which describes just your document vs what your document would look like without mongoose
* Because of how types work, the only way for .toObject to reference that type and try to figure out what it should be is to use `this` as part of the return type, which is what was used before 6.3.2 -- however, the reason it was changed is because in a lot of the tests I ran it very easily created circular dependencies on the types when I did that.
* The workaround is to pass the type into toObject -- i.e. change it to `return model.toObject<IWebUpload>`

Because of this breaking change it perhaps should have gone into a 6.4 release instead of a patch release :-/

The problem is that while this has a minor but annoying workaround the problems caused by the other way don't have any workaround that I could discover.

That said, if you just restructure so that you aren't extending Document (which is a really bad idea for lots of reasons anyway) then you won't have the issue and everything will Just Work (tm) =]

**Comment by simllll** [comment] 2022-05-04 18:34
> @simllll also just to verify -- you realize your types are wrong for _id? The default type of _id is ObjectId, not string, so if you use that you're going to have inaccurate types unless you define _id as a string in your schema

Yeah I just was wirting the example directly inside the comment box, I actually you some more sophiticated typescript type we call "TypeObjectId<>" that is a generic so we can distingiush differnet object ids from each other.


Regarding the extends Document, I will look into it right now and see if it's an easy fix.

**Comment by taxilian** [comment] 2022-05-04 19:15
if not then just providing the type to the `.toObject` will be. I'm also happy to help figure out better ways to structure typescript stuff in general if you need -- I actually enjoy that sort of thing (probably a neurological disorder) and can be found on the mongoose slack server.

**Comment by vkarpov15** [comment] 2022-05-04 21:00
Still reviewing, but quick comment that this is related to https://github.com/Automattic/mongoose/issues/11118

**Comment by simllll** [comment] 2022-05-04 21:49
For me I think I sorted it out by removing all the `extends Document` and adding some magic with _id conversion. The mentioned pr of @vkarpov15 was also something I experienced, a toObject() is missing the _id field.

Hopefully all this effort has also some positive effects like typescript performance? 🫣👍

**Comment by mohammad0-0ahmad** [comment] 2022-05-04 21:54
> Still reviewing, but quick comment that this is related to #11118
![Untitled](https://user-images.githubusercontent.com/50488054/166831930-3559af6e-4a9a-462d-bbf9-df4351f0ccc4.png)

already covered in https://github.com/Automattic/mongoose/pull/11767

**Closed** 2022-05-05 00:46 UTC
Labels: typescript

**Comment by Uzlopak** [comment] 2022-05-05 09:14
I went to sleep, woke up and saw the notifications and I thought: "Oh I hope the devs did not get frustrated that one and not the other PR was merged". First of all I thank you both, @taxilian  and @mohammad0-0ahmad and others . I know that it could been frustrating but I think that you both had a respectful and valuable discussion why doing this or that. 

And yeah, it is kind of pedantic/neurological disorder to type complex code :). I have that too. I always try to make the typings strict as possible and correct as possible. People love and hate it :dagger:

Anyway. I think that we have to rethink the whole typings. I actually also dont understand why we have LeanDocument in the first place as it should be a POJO, which shape is based on the projection and if the lean flag or function was set. So I actually wonder if the following would make sense:

The first thing is to get the automatic typing from mohammad0 getting properly reviewed and merged. I invite you, @taxilian  to also review it. I will probably also review it and try and some test cases. 

But actually what should happen is, that when we create a query e.g. findOne, it should return Document<T> if not lean option was set to true or lean() was called and it should return T, were T is in both cases the resulting type of the potential fields/projection setting.

**Comment by taxilian** [comment] 2022-05-05 14:54
Agreed -- and while LeanDocument did originate with me I'm not so prideful that I can't see the limitations =] (I mean, it's a close thing, but still :-P)

Which PR is the "automatic typings"? I'd love to review it. I really feel like there is an "ideal" solution out there but that we haven't found it yet, so maybe that's it ;-)

I keep finding myself wondering if there is a way to make an alternate usage pattern for mongoose where you literally just pass around POJOs and then instead of "hydrating" documents you can either use them with "operate on this object" type functions or else with a backwards-compatibility style Proxy... but a) that is *so* far outside of this discussion that I should be shot for bringing it up and b) I'm well aware of just how much work that can end up being.

Sorry for my impatience yesterday and thanks to all who contributed; I think the fix (mine) which was merged is the safest short term solution, but likely not the best long term solution so definitely want to keep involved with the discussions. I have two different jobs where I rely on all of this =]
