### ISSUE TITLE
Mongoose validation fails when removing and updating simultaneously on array

### ISSUE THREAD

**Issue by neverfox** [Automattic/mongoose#2344] opened 2014-10-05 01:54 UTC
I have a schema that involves a nest of arrays, with the final array storing objects that have a required field. When I try to update the whole top-level document (fund) such that I'm removing some of the objects in the bottom level array (holdings) while also changing the value of `allocation` on some of the objects I'm keeping, it fails the `required` validation. However, if I do it in two stages (either deleting the unwanted objects first with a save, then changing the others with a save; or vice versa), it works fine.

Here is the schema (simplified for clarity):

```
holdingSchema = new Schema
  instrument_id:
    type: Schema.ObjectId
    required: true
    ref: 'Instrument'
  allocation:
    type: Number
    required: true

positionSchema = new Schema
  holdings: [holdingSchema]

fundSchema = new Schema
  positions: [positionSchema]
```

For example, I have 11 items in holdings. I remove 3 and change the allocation value of another. I then set and save the whole fund document via JSON. This leads to a validation error. If I don't change the allocation value of any remaining items, all goes smoothly.

~~I can *add* and *change* in the same operation. I can *add* and *remove* in the same operation. I can even *add*, *change* and *remove* in the same operation. I just cannot *remove* and *change* (no add) in the same operation.~~ See below.

Is this a known limitation, forcing me to build a two-stage process or is there something wrong?

Mongoose 3.8.16

**Comment by Oted** [comment] 2015-01-08 17:29
Im experiencing a similar issue. 

We have a large collection of products in our database, and initially we didn't have any validation on fields. The validation was added at a later stage and thus resulting in invalid products in the collection.

We did a script to fetch and fix these products and many of the invalid fields where fields inside nested arrays. When we tried to remove the invalid objects from the array and saving, the validation complained on non existent indexes : 
```javascript
Could not repair 53f7daa184ba27130053cac8 { [ValidationError: Validation failed]
  message: 'Validation failed',
  name: 'ValidationError',
  errors:
   { 'merchants.0.stock.-1.sizes.0.price.currency':
      { [ValidatorError: Currency is required.]
        message: 'Currency is required.',
        name: 'ValidatorError',
        path: 'price.currency',
        type: 'required',
        value: undefined } },
  key: 'undefined.0.undefined.0.undefined.0.undefined' }
```

Obviously this index (-1) does not exist, and when logging the product before the validation error is thrown. It looks ok. The bug can be avoided by doing

```javascript
product.validate(function(err) {console.log(err)})
```

And then saving.

**Comment by jessedpate** [comment] 2015-03-05 18:40
Is there any movement on this issue? It doesn't happen regularly on our production app, but it causes client facing errors we have to address manually whenever it comes up.

**Comment by vkarpov15** [comment] 2015-03-06 16:28
Well I haven't been able to reproduce it. Would be helpful if somebody provided me a standalone example or a test case that reproduces the issue.

**Comment by S0c5** [comment] 2015-04-14 18:42
Hi guys I present the same problem. 

I have a model User this is the schema
```JavaScript
'use strict'

var states = anabeljs.model('states');
var genres = anabeljs.model('genres');

var Schema = mgs.Schema;

var userSchema = new Schema({
    email: {
        type: String,
        required: true,
        unique: true
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    },
    followers: [
        {
            type: mgs.Schema.ObjectId,
            ref: 'user'
        }
    ],
    following: [
        {
            type: mgs.Schema.ObjectId,
            ref: 'user'
        }
    ]
});

userSchema.path('email').validate(function(email, cb) {
    // Make sure the email address is not already registered
    var UserModel = mgs.model('user');

    UserModel.find({'email': email.toLowerCase()}, function (err, users) {
        cb(err || users.length === 0);
    });
}, 'Email is already registered');

userSchema.path('userName').validate(function(userName, cb) {
    // Make sure the email address is not already registered
    var UserModel = mgs.model('user');

    UserModel.find({'userName': userName.toLowerCase()}, function (err, users) {
        cb(err || users.length === 0);
    });
}, 'userName is already registered');


module.exports = mgs.model('user', userSchema);

```

make two users: A and B.

and I have the next code on the controller: 

```JavaScript
User.findOne({_id: req.params.id}, function(err, user){
                if(err) return res.mongoError(err);
                if(!user) return res.notFound('user');

                if(user.followers.indexOf(req.user._id) === -1) user.followers.push(req.user._id);
                if(req.user.following.indexOf(user._id) === -1) req.user.following.push(user._id);

                req.user.save(function(err){
                    console.log('before 1')
                    console.log(err)
                    if(err) return res.mongoError(err);

                    user.save(function(err){ // Here Crash For validations
                        console.log('before 2')
                        console.log(err);
                        if(err) return res.mongoError(err);

                        res.ok(user.toJSON());
                    });
                })
            });
```


when the B user will be saved, this return a validation erros. (email already registered, and Username), but this message why? if I want to update an item.

**Comment by vkarpov15** [comment] 2015-04-14 20:33
Can you confirm which version of mongoose you're using @S0c5?

**Comment by S0c5** [comment] 2015-04-15 18:23
My version is 3.8. @vkarpov15

**Comment by vkarpov15** [comment] 2015-07-16 16:26
@S0c5 sorry for taking a long time to get back to you. This doesn't look like it has anything to do with the original issue. Re: email, I'm not sure why your validation is failing, but your userName validation is failing because you don't have a `userName` path in your schema, so that validator is guaranteed to always fail.

I'm gonna close this, re-open if this is still an issue.

**Closed by vkarpov15** 2015-07-16 16:26 UTC

**Comment by dmurkerNuorder** [comment] 2015-10-01 23:15
I work on the same team as Jesse Pate above, and we're seeing this issue in Mongoose 3.8.35.  Was this issue fixed in 4.x?  (updating is on our roadmap, but not imminently so.)

Just to recap, given the following schemata:

PrimarySchema = {
   _id: ObjectId
   subDocs: [subDocSchema]
}

subDocSchema = {
  _id: ObjectId,
  tertiaryDocs: [tertiaryDocSchema]
}

tertiaryDocSchema: {
   _id: ObjectId,
   value: Number, Required
}

and an original doc that looks like this (psuedocode):
primary = {
  _id: <primaryDocId>,
  subDocs: [
    {
      _id: subDocId1,
      tertiaryDocs: [
        {
          _id: <tertDocId1>
          value: 1
        },
        {
          _id: <tertDocId2>
          value: 2
        }
      ]
    }
  ]
}

the following model call should throw an error as described in the first post:
model.update({_id: <primaryDocId>}, {$set: {
  _id: <primaryDocId>,
  subDocs: [
    {
      _id: subDocId1,
      tertiaryDocs: [
        {
          _id: <tertDocId1>
          value: 6
        }
      ]
    }
  ]
}

**Comment by vkarpov15** [comment] 2015-10-02 17:02
@dmurkerNuorder why should that call throw an error? Looks perfectly valid to me.

**Comment by jessedpate** [comment] 2015-10-02 17:04
I believe when Daniel says it should throw an error, he means that it
(likely) will throw an error that should not actually happen.

**Comment by vkarpov15** [comment] 2015-10-02 17:17
No exception thrown in the below script

```javascript
'use strict';

var assert = require('assert');

var mongoose = require('mongoose');
var ObjectId = mongoose.Schema.Types.ObjectId;
mongoose.set('debug', true);
mongoose.connect('mongodb://localhost:27017/gh2344');

var tertiaryDocSchema = new mongoose.Schema({
   _id: ObjectId,
   value: { type: Number, required: true }
});

var subDocSchema = new mongoose.Schema({
  _id: ObjectId,
  tertiaryDocs: [tertiaryDocSchema]
});

var PrimarySchema = new mongoose.Schema({
   _id: ObjectId,
   subDocs: [subDocSchema]
});

var Primary = mongoose.model('gh2344', PrimarySchema);

var update = {
  $set: {
      _id: '000000000000000000000001',
      subDocs: [
      {
        _id: '000000000000000000000001',
        tertiaryDocs: [
          {
            _id: '000000000000000000000001',
            value: 6
          }
        ]
      }
    ]
  }
};

Primary.update({ _id: '000000000000000000000001' }, update, function(error) {
  assert.ifError(error);
  process.exit(0);
});
```
